import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W5B: Recipe[] = [
  {
    id: "home-braised-beancurd-with-black-fungus-and-konnyaku",
    name: "Braised Beancurd with Black Fungus and Konnyaku",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Tofu"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Tofu and vegetables into pieces; lightly brown Tofu in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Tofu is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "木耳芋絲燴豆腐",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-beef-brisket-and-fruits-in-plum-and-soyb",
    name: "Braised Beef Brisket and Fruits in Plum and Soybean Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Beef steak", "Beef brisket"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Beef steak and Beef brisket into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "果香梅子炆牛腩",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-beef-brisket-and-turnip-with-oyster-sauc",
    name: "Braised Beef Brisket and Turnip with Oyster Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Beef steak", "Beef brisket"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Beef steak and Beef brisket into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "蘿蔔牛腩",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-beef-brisket-with-radish",
    name: "Braised Beef Brisket with Radish",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Beef steak", "Beef brisket"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Beef steak and Beef brisket into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "蘿蔔炆牛腩",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-beef-ribs-in-teriyaki-sauce",
    name: "Braised Beef Ribs in Teriyaki Sauce",
    cuisine: "Japanese",
    time: 45,
    servings: 3,
    need: ["Beef steak"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Beef steak and vegetables into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "燒汁牛肋條",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-broccoli-with-oyster-sauce",
    name: "Braised Broccoli with Oyster Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Broccoli"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Broccoli and vegetables into pieces; lightly brown Broccoli in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Broccoli is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "蠔油燴西蘭花",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-chicken-legs-with-oyster-sauce",
    name: "Braised Chicken Legs with Oyster Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Chicken thighs and vegetables into pieces; lightly brown Chicken thighs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Chicken thighs is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "滷雞腿",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-chicken-wings-with-red-braising-sauce",
    name: "Braised Chicken Wings with Red Braising Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken wings", "Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Chicken wings and Chicken thighs into pieces; lightly brown Chicken wings in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Chicken wings is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "紅燒雞翼",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-chicken-with-chestnut-and-mushroom",
    name: "Braised Chicken with Chestnut and Mushroom",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs", "Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Chicken thighs and Mushroom into pieces; lightly brown Chicken thighs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Chicken thighs is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "冬菇栗子炆雞",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-chicken-with-port-and-soy-sauce",
    name: "Braised Chicken with Port and Soy Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Chicken thighs and vegetables into pieces; lightly brown Chicken thighs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Chicken thighs is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "砵酒頭抽煀雞",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-chicken-with-vegetables",
    name: "Braised Chicken with Vegetables",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Chicken thighs and vegetables into pieces; lightly brown Chicken thighs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Chicken thighs is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "紅炆雞塊",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-chicken-with-yam-in-coconut-milk",
    name: "Braised Chicken with Yam in Coconut Milk",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Chicken thighs and vegetables into pieces; lightly brown Chicken thighs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Chicken thighs is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "椰香淮山炆雞",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-duck-with-chu-hou-sauce",
    name: "Braised Duck with Chu Hou Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs", "Pak choi"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Chicken thighs and Pak choi into pieces; lightly brown Chicken thighs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Chicken thighs is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "農家柱侯鴨",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-e-fu-noodles-with-double-mushrooms",
    name: "Braised E Fu Noodles with Double Mushrooms",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Mushroom", "Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Mushroom and Noodles into pieces; lightly brown Mushroom in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Mushroom is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "雙菇乾燒伊麵",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-egg-noodles-with-oyster-sauce",
    name: "Braised Egg Noodles with Oyster Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Eggs", "Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Eggs and Noodles into pieces; lightly brown Eggs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Eggs is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "蠔皇燴麵",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-eggplant-minced-pork-and-glass-noodle-wi",
    name: "Braised Eggplant Minced Pork and Glass Noodle with Seafood Xo Sauce in Casserole",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork", "Eggs", "Eggplant", "Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Ground pork and Eggs into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "海皇XO醬茄子肉碎粉絲煲",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-fish-maw-with-sea-cucumber-and-mushroom",
    name: "Braised Fish Maw with Sea Cucumber and Mushroom",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["White fish", "Cucumber", "Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut White fish and Cucumber into pieces; lightly brown White fish in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until White fish is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "蠔皇香菇花膠燜海參",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-fried-tofu-with-chicken-and-shrimp-roe",
    name: "Braised Fried Tofu with Chicken and Shrimp Roe",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs", "Shrimp"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Chicken thighs and Shrimp into pieces; lightly brown Chicken thighs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Chicken thighs is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "雞柳蝦籽鍋塌豆腐",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-lamb-brisket-and-bean-curd-sheets-with-c",
    name: "Braised Lamb Brisket and Bean Curd Sheets with Chu Hou Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Beef steak"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Beef steak and vegetables into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "柱侯羊腩炆枝竹",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-meatballs-with-tomato-sauce-and-coke",
    name: "Braised Meatballs with Tomato Sauce and Coke",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Tomato and vegetables into pieces; lightly brown Tomato in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Tomato is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "可樂茄汁燴肉丸",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-minced-pork-with-oyster-sauce-on-rice",
    name: "Braised Minced Pork with Oyster Sauce on Rice",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Ground pork and Cooked rice into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "蠔油肉燥飯",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-mushroom-with-abalone-and-fish-maw",
    name: "Braised Mushroom with Abalone and Fish Maw",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["White fish", "Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut White fish and Mushroom into pieces; lightly brown White fish in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until White fish is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "鮑魚花膠燜冬菇",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-oysters-with-local-street-style-fish-bal",
    name: "Braised Oysters with Local Street Style Fish Ball Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["White fish"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut White fish and vegetables into pieces; lightly brown White fish in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until White fish is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "醬燒生蠔",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-pork-belly-with-oyster-sauce-dong-po-por",
    name: "Braised Pork Belly with Oyster Sauce Dong Po Pork",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Ground pork and vegetables into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "東坡肉",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-pork-knuckle-with-peanut-and-dried-oyste",
    name: "Braised Pork Knuckle with Peanut and Dried Oyster",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Ground pork and vegetables into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "花生蠔豉炆豬手",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-pork-knuckle-with-peanuts-in-secret-sauc",
    name: "Braised Pork Knuckle with Peanuts in Secret Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Ground pork and vegetables into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "秘製醬汁花生燜豬手",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-pork-knuckle-with-preserved-sweet-prune",
    name: "Braised Pork Knuckle with Preserved Sweet Prune",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Ground pork and vegetables into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "話梅炆豬手",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-pork-meatballs-chinese-lions-head",
    name: "Braised Pork Meatballs Chinese Lions Head",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Ground pork and vegetables into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "鴻運當頭",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-pork-noodles-with-scallops-and-miscellan",
    name: "Braised Pork Noodles with Scallops and Miscellaneous Mushrooms",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork", "Mushroom", "Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Ground pork and Mushroom into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "瑤柱雜菌肉絲炆伊麵",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-pork-trotter-with-oyster-sauce",
    name: "Braised Pork Trotter with Oyster Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Ground pork and vegetables into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "滷花生豬手",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-pork-with-preserved-vegetable",
    name: "Braised Pork with Preserved Vegetable",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Ground pork and vegetables into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "梅菜扣肉",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-premium-abalone-with-shrimp-egg-and-sea",
    name: "Braised Premium Abalone with Shrimp Egg and Sea Cucumber",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Shrimp", "White fish", "Cucumber"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Shrimp and White fish into pieces; lightly brown Shrimp in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Shrimp is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "蝦籽鮑魚燴海參",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-rice-vermicelli-with-pickled-leaf-mustar",
    name: "Braised Rice Vermicelli with Pickled Leaf Mustard and Shredded Beef",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Beef steak", "Pickled mustard", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Beef steak and Pickled mustard into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "酸菜牛柳絲炆米",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-scallops-in-tri-colour-quinoa-and-chicke",
    name: "Braised Scallops in Tri Colour Quinoa and Chicken Broth",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Chicken thighs briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "三色藜麥雞湯浸帶子",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-braised-sea-cucumber-and-fish-maw-with-oyster-sa",
    name: "Braised Sea Cucumber and Fish Maw with Oyster Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["White fish", "Cucumber"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut White fish and Cucumber into pieces; lightly brown White fish in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until White fish is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "三鮮燴海參花膠",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-sea-cucumber-with-mushrooms-and-cordycep",
    name: "Braised Sea Cucumber with Mushrooms and Cordyceps Flowers in Oyster Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Cucumber", "Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Cucumber and Mushroom into pieces; lightly brown Cucumber in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Cucumber is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "蠔皇蟲草花燴花菇海參",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-seafood-and-seasonal-vegetables-in-seafo",
    name: "Braised Seafood and Seasonal Vegetables in Seafood Xo Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Eggs and Tomato into pieces; lightly brown Eggs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Eggs is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "海皇XO醬海鮮燴時蔬",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-seafood-and-winter-melon-with-tofu",
    name: "Braised Seafood and Winter Melon with Tofu",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Tofu", "Winter melon"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Tofu and Winter melon into pieces; lightly brown Tofu in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Tofu is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "冬瓜海鮮燴豆腐",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-spare-ribs-and-winter-melon-in-oyster-sa",
    name: "Braised Spare Ribs and Winter Melon in Oyster Sauce with Dried Scallop",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Spare ribs", "Winter melon"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Spare ribs and Winter melon into pieces; lightly brown Spare ribs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Spare ribs is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "瑤柱蠔油肉排燜冬瓜",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-spicy-garlic-pumpkin",
    name: "Braised Spicy Garlic Pumpkin",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["White fish", "Pumpkin"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut White fish and Pumpkin into pieces; lightly brown White fish in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until White fish is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "魚香燴南瓜",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-tofu-with-stewed-mushroom-and-vegetarian",
    name: "Braised Tofu with Stewed Mushroom and Vegetarian Meat",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Tofu", "Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Tofu and Mushroom into pieces; lightly brown Tofu in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Tofu is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "紅燒冬菇素肉扒豆腐",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-tomato-and-lamb-shank",
    name: "Braised Tomato and Lamb Shank",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Tomato and vegetables into pieces; lightly brown Tomato in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Tomato is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "番茄時蔬燉羊膝",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-turnip-and-chicken",
    name: "Braised Turnip and Chicken",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Chicken thighs and vegetables into pieces; lightly brown Chicken thighs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Chicken thighs is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "蘿蔔燴雞肉",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-vegetables-with-vegetarian-oyster-sauce",
    name: "Braised Vegetables with Vegetarian Oyster Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Eggs and Tomato into pieces; lightly brown Eggs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Eggs is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "羅漢上素",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-broccoli-with-mixed-mushrooms-in-abalone-sauce",
    name: "Broccoli with Mixed Mushrooms in Abalone Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Broccoli", "Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Broccoli and Mushroom; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Broccoli and cook until just cooked.",
      "Add Mushroom, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "鮑汁雜菌扒西蘭花",
      steps: [
        "準備鮑汁雜菌扒西蘭花材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-brown-braised-eggplant",
    name: "Brown Braised Eggplant",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Eggs", "Eggplant"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Eggs and Eggplant into pieces; lightly brown Eggs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Eggs is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "紅燒茄子",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-brown-rice-with-yuzu-and-salmon",
    name: "Brown Rice with Yuzu and Salmon",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Salmon", "White fish", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Salmon and White fish plus Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Salmon and cook until just cooked.",
      "Add White fish and Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "柚子三文魚糙米飯",
      steps: [
        "準備柚子三文魚糙米飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-butter-and-oyster-sauce-flavoured-king-oyster-mu",
    name: "Butter and Oyster Sauce Flavoured King Oyster Mushrooms",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Mushroom and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Mushroom and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "醬香牛油杏鮑菇",
      steps: [
        "準備醬香牛油杏鮑菇材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-butterfly-shrimps-in-tomato-sauce",
    name: "Butterfly Shrimps in Tomato Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Shrimp and Tomato; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add Tomato, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "咕嚕蝦球",
      steps: [
        "準備咕嚕蝦球材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-cabbage-rolls-in-soup",
    name: "Cabbage Rolls in Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Cabbage"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Cabbage briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "cabbage-rolls-in-soup",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
]
