import type { Recipe } from "@/lib/recipes"

/**
 * Cuisine expansion w6b — title-matched exclusive sources only.
 * Materials (groups/amounts) synced from each dish sourceUrl.
 */
export const MORE_W6B: Recipe[] = [
  {
    id: "home-nasi-goreng",
    name: "Nasi goreng",
    cuisine: "Indonesian",
    time: 30,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/nasi-goreng-indonesian-fried-rice/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Chicken thighs", role: "core", group: "main", amount: 8, unit: "oz", note: "sliced or cut into small ½-inch/1cm chunks" },
      { name: "Cornstarch", role: "staple", group: "marinade", amount: 1, unit: "tsp" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 3, unit: "tbsp", note: "plus more for frying eggs and shallots" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "diced; about ⅔ cup" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, unit: "clove" },
      { name: "Shrimp", role: "core", group: "main", amount: 1, unit: "tbsp", note: "see notes" },
      { name: "Ketchup", role: "core", group: "main", amount: 1, unit: "tbsp" },
      { name: "Cooked rice", role: "core", group: "main", amount: 4, unit: "cup" },
      { name: "White pepper", role: "staple", group: "main", amount: 0.125, unit: "tsp" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 1 },
      { name: "Salt", role: "staple", group: "main", amount: 0.5, unit: "tsp", note: "optional, or to taste" },
      { name: "Shallot", role: "core", group: "main", amount: 0.33, unit: "cup", note: "thinly sliced and fried until crispy, or use pre-fried shallots; see notes" },
      { name: "Eggs", role: "core", group: "main" },
      { name: "Tomato", role: "core", group: "main" },
      { name: "Cucumber", role: "core", group: "main" },
    ],
    need: ["Chicken thighs","Shrimp","Ketchup","Cooked rice","Shallot","Eggs","Tomato","Cucumber"],
    optional: ["Cornstarch","Soy sauce","Cooking oil","Onion","Garlic","White pepper","Spring onion","Salt"],
    steps: [
      "In a medium bowl, combine the chicken pieces, cornstarch, water, and soy sauce. Marinate for 20-30 minutes while you prepare the rest of the ingredients.",
      "Reduce the heat to medium. Add 1 tablespoon of oil, along with the onions and garlic. For a spicier dish, you can also add the Thai chilies at this point (alternatively, add them at the end with the scallions). Stir-fry for 1 minute, or just until the onions are translucent. Next, add the shrimp paste and ketchup. Increase the heat to high and fry the mixture for 20 seconds, or until fragrant.",
      "Next, add the chicken and its juices to the rice and continue to stir-fry for another minute or until the chicken is heated through. Stir in the scallions and the chopped Thai chilies (if you didn’t add them earlier). Taste for seasoning, and add salt if needed.",
      "Plate the rice, and top with fried shallots, a fried egg, and the sliced tomato and cucumber. The eggs can be served sunny side up or over-easy, depending on your preference but the egg is traditionally cooked so the yolk is still runny. Serve!",
    ],
    zh: {
      name: "印尼炒飯",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-char-kway-teow",
    name: "Char kway teow",
    cuisine: "Malaysian",
    time: 25,
    servings: 2,
    sourceUrl: "https://thewoksoflife.com/char-kway-teow/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Wide rice noodles", role: "core", group: "main", amount: 8, unit: "oz", note: "225g dried or 450g fresh" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 2, unit: "tsp" },
      { name: "Fish sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Shrimp", role: "core", group: "main", amount: 1, unit: "tsp" },
      { name: "Oyster sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "White pepper", role: "staple", group: "main", amount: 0.125, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 3, unit: "tbsp", note: "divided" },
      { name: "Chinese sausage", role: "core", group: "main", amount: 2, note: "about 115g, sliced ⅛ inch thick" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, unit: "clove", note: "sliced" },
      { name: "White fish", role: "core", group: "main", amount: 4, unit: "oz", note: "115g" },
      { name: "Shaoxing wine", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "optional" },
      { name: "Eggs", role: "core", group: "main", amount: 1, note: "lightly beaten" },
      { name: "Bean sprouts", role: "core", group: "main", amount: 6, unit: "oz", note: "170g" },
    ],
    need: ["Wide rice noodles","Shrimp","Chinese sausage","White fish","Eggs","Bean sprouts"],
    optional: ["Soy sauce","Fish sauce","Oyster sauce","White pepper","Sugar","Cooking oil","Garlic","Shaoxing wine"],
    steps: [
      "Soak the dried noodles in warm water for 30 to 45 minutes. Transfer to a colander and let the excess water drain. If you have fresh rice noodles, cut them into 1½-inch wide strips, and set them aside. You can even try making your own rice noodles at home using Judy’s recipe for Homemade Rice Noodles.",
      "Add the 2 cloves of sliced garlic, the shrimp, and the fish tofu. Continue stir-frying for another 20 seconds.",
      "Next, add the garlic chives. Gently mix the noodles (to minimize breakage) while spreading them around the perimeter of the wok to get that wok hay sear from the superheated sides of the wok. Because of the hot wok and the oil, the rice noodles shouldn’t stick.",
      "Next add the mung bean sprouts and gently mix everything together for 1 minute.",
      "If your Char Kway Teow looks dry, sprinkle 2 tablespoons of water over the noodles while stir-frying. You can also add a bit more vegetable oil if you like. Serve your Char Kway teow with chlli garlic paste or homemade chili oil on the side.",
    ],
    zh: {
      name: "炒粿條",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-hainanese-chicken-rice",
    name: "Hainanese chicken rice",
    cuisine: "Singaporean",
    time: 90,
    servings: 6,
    sourceUrl: "https://thewoksoflife.com/hainanese-chicken-rice/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Chicken thighs", role: "core", group: "main", amount: 1, note: "3-3½ pounds/1.5kg, preferably buddhist-style with head and feet on, or organic" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tbsp" },
      { name: "Ginger", role: "staple", group: "main", amount: 4 },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 2 },
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tsp", note: "such as vegetable, canola, or avocado oil" },
      { name: "Garlic", role: "staple", group: "main", amount: 4, unit: "clove", note: "minced" },
      { name: "Cooked rice", role: "core", group: "main", amount: 3, unit: "cup", note: "preferably jasmine rice, washed and drained" },
      { name: "Chicken stock", role: "staple", group: "main", note: "from cooking the chicken" },
      { name: "Sugar", role: "staple", group: "main", amount: 1.25, unit: "oz", note: "2 sizable chunks, or substitute 2.5 tbsp granulated sugar" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "cup" },
      { name: "Dried chili", role: "core", group: "main", amount: 3, note: "choose a chili with medium spice level; we used holland chilies" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Lime", role: "core", group: "main", amount: 1, unit: "tbsp", note: "1 tbsp/15ml = the juice of 1/2 lime" },
    ],
    need: ["Chicken thighs","Cooked rice","Dried chili","Lime"],
    optional: ["Salt","Ginger","Spring onion","Cooking oil","Garlic","Chicken stock","Sugar","Soy sauce","Sesame oil"],
    steps: [
      "Wash the chicken clean and remember to set aside the piece of chicken fat from the cavity. Transfer the chicken to a plate and pat dry with a paper towel. Lightly rub the chicken with the salt. This will give the chicken skin a nice sheen. Set it aside.",
      "When the timer (for the chicken) is almost up, prepare a large ice bath. To check if the chicken is done, stick a toothpick into the thickest part of the thigh until it touches the bone; if the juices run clear, it’s cooked through. Carefully lift the chicken out of the pot, drain the water from the cavity and lower it into the ice bath. Take care not to break the skin. After 15 minutes in the ice bath, the chicken should be cooled completely, drain and cover with clear plastic until ready to cut and serve.",
      "If you don’t have a rice cooker, transfer the toasted rice to a medium/large pot. Add 4 cups of chicken stock and the salt, giving it a quick stir. Soak the rice for 20 minutes. Then cover the pot and bring to a boil. Once it boils, immediately turn down the heat to the lowest setting. Let the rice simmer and cook (covered) for 15 minutes, until the liquid has absorbed into the rice, and it is tender.",
      "Grind the chilies, ginger, and garlic in a food processor until finely chopped. You will probably have to scrape down the sides of the food processor 1-2 times to ensure everything is ground up evenly. Add the sesame oil, salt, sugar, lime juice, and vinegar to the food processor. Pulse 2-3 times to combine. You can also do this in a mortar and pestle.",
      "Transfer to a small bowl and add chicken broth (what you used to boil the chicken) 1 tablespoon at a time until a saucy consistency is achieved. This is really about your preference too; if you like a thicker paste, add less broth.",
    ],
    zh: {
      name: "海南雞飯",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-coconut-rice-sea",
    name: "Coconut rice",
    cuisine: "Malaysian",
    time: 25,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/quick-easy-coconut-rice/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Cooked rice", role: "core", group: "main", amount: 2, unit: "cup" },
      { name: "Coconut milk", role: "core", group: "main", amount: 13.5, unit: "oz" },
      { name: "Sugar", role: "staple", group: "main", amount: 2, unit: "tsp" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Bread", role: "core", group: "main", amount: 0.25, unit: "cup", note: "toasted in a dry pan until lightly golden; optional" },
    ],
    need: ["Cooked rice","Coconut milk","Bread"],
    optional: ["Sugar","Salt"],
    steps: [
      "Prep ingredients as listed for Coconut rice.",
      "Cook following the linked The Woks of Life method until proteins reach a safe temperature (poultry/mince 74°C / 165°F).",
      "Taste, adjust seasoning, and serve.",
    ],
    zh: {
      name: "椰漿飯",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-curry-mee",
    name: "Curry mee",
    cuisine: "Malaysian",
    time: 45,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/curry-mee/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tbsp" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "minced" },
      { name: "Garlic", role: "staple", group: "main", amount: 3, unit: "clove", note: "minced" },
      { name: "Ginger", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "minced" },
      { name: "Lemon", role: "core", group: "main", amount: 1, unit: "tbsp", note: "minced" },
      { name: "Curry powder", role: "staple", group: "main", amount: 1, unit: "tbsp" },
      { name: "Chicken thighs", role: "core", group: "main", amount: 0.5, unit: "lb", note: "thinly sliced" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 0.5, unit: "tsp" },
      { name: "Coconut milk", role: "core", group: "main", amount: 13.5, unit: "oz", note: "400 ml" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 4, unit: "cup", note: "950 ml" },
      { name: "Fish sauce", role: "staple", group: "sauce", amount: 3, unit: "tbsp", note: "optional for vegetarians" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Eggs", role: "core", group: "main", amount: 8, unit: "oz", note: "225g" },
      { name: "Salt", role: "staple", group: "main", note: "to taste" },
      { name: "Bean sprouts", role: "core", group: "main", amount: 2, note: "washed and trimmed" },
      { name: "Cilantro", role: "core", group: "garnish", note: "for garnish" },
      { name: "Lime", role: "core", group: "main", amount: 1, note: "cut into wedges" },
    ],
    need: ["Lemon","Chicken thighs","Coconut milk","Eggs","Bean sprouts","Cilantro","Lime"],
    optional: ["Cooking oil","Onion","Garlic","Ginger","Curry powder","Turmeric","Chicken stock","Fish sauce","Sugar","Salt"],
    steps: [
      "Heat the oil in a pot over medium high heat and add the onion, garlic, ginger, and lemongrass. Cook for about 6 minutes, until softened and fragrant. Stir in the red curry paste.",
      "Turn the heat up to high and add the chicken. Stir-fry until the chicken turns opaque. Add the curry powder, turmeric, coconut milk, chicken stock, fish sauce, and sugar. Bring to a boil and simmer for 10 minutes.",
      "Meanwhile, cook the noodles according to package directions. Divide into 3 soup bowls and set aside.",
      "Taste the soup and season with salt to taste. Divide the soup among your bowls of noodles, and garnish with raw bean sprouts, cilantro, and a squeeze of lime.",
    ],
    zh: {
      name: "咖喱麵",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-chicken-satay-woks",
    name: "Chicken satay",
    cuisine: "Malaysian",
    time: 40,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/chicken-satay-with-peanut-sauce/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Chicken thighs", role: "core", group: "main", amount: 1.5, unit: "lb", note: "680g, cut into chunks" },
      { name: "Coconut milk", role: "core", group: "main", amount: 1, unit: "cup", note: "60 ml" },
      { name: "Fish sauce", role: "staple", group: "sauce", amount: 2, unit: "tsp" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 2, unit: "tsp" },
      { name: "Curry powder", role: "staple", group: "main", amount: 2, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Lime", role: "core", group: "main", amount: 1, unit: "tbsp" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tbsp" },
      { name: "Butter", role: "core", group: "main", amount: 1, unit: "cup" },
      { name: "Garlic", role: "staple", group: "main", amount: 1, unit: "clove", note: "minced" },
      { name: "Ginger", role: "staple", group: "main", amount: 1, unit: "tsp", note: "minced or grated" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 1, unit: "tsp" },
    ],
    need: ["Chicken thighs","Coconut milk","Lime","Butter"],
    optional: ["Fish sauce","Soy sauce","Curry powder","Sugar","Cooking oil","Garlic","Ginger","Sesame oil"],
    steps: [
      "Before you get started, if you’re using bamboo skewers, soak them in a bowl of water for at least an hour––this prevents them from burning during the cooking process!",
      "While the chicken is marinating, prepare the sauce by combining the peanut butter, hot water, lime juice, garlic, ginger, soy sauce, fish sauce, and sesame oil. If you want it saltier, you can add more soy sauce or fish sauce.",
      "You can cook the skewers on the grill, but we cooked them in a skillet set over medium-high with 2 tablespoons of oil. Make sure to let your skillet preheat first, and when you add the chicken, turn down the heat to medium or medium-low if it’s browning too fast. Cook the chicken evenly for about 10-12 minutes, turning it until golden on all sides. Because the chicken is irregularly-sized on the skewers, take care to make sure it’s cooked through.",
      "Serve with the peanut sauce. Enjoy!",
    ],
    zh: {
      name: "沙爹雞串",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-ayam-kecap",
    name: "Ayam kecap",
    cuisine: "Indonesian",
    time: 45,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/ayam-kecap-indonesian-braised-chicken/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Chicken thighs", role: "core", group: "main", amount: 2.5, unit: "lb" },
      { name: "Salt", role: "staple", group: "main", amount: 0.5, unit: "tsp" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "such as canola, vegetable, or avocado oil" },
      { name: "Ginger", role: "staple", group: "main", amount: 0.5, unit: "tsp", note: "finely minced or grated" },
      { name: "Garlic", role: "staple", group: "main", amount: 3, unit: "clove", note: "chopped" },
      { name: "Shallot", role: "core", group: "main", amount: 1, unit: "cup", note: "finely diced" },
      { name: "Dried chili", role: "core", group: "main", amount: 3, note: "optional" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 2.25, unit: "cup" },
      { name: "Ground coriander", role: "staple", group: "main", amount: 0.75, unit: "tsp" },
      { name: "Lime", role: "core", group: "main", amount: 3 },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 2, unit: "tbsp" },
      { name: "White pepper", role: "staple", group: "main", amount: 0.5, unit: "tsp" },
    ],
    need: ["Chicken thighs","Shallot","Dried chili","Lime"],
    optional: ["Salt","Cooking oil","Ginger","Garlic","Chicken stock","Ground coriander","Soy sauce","White pepper"],
    steps: [
      "In a large bowl, add the chicken legs, and sprinkle them with the salt. Rub the salt in evenly, and let sit for at least 10 minutes. Heat a medium pot over medium-high heat, and add the oil. Sear the chicken legs until lightly browned on all sides. Remove the chicken to a plate.",
      "Add the ginger, garlic, shallot/onion, and dried red chili peppers (if using). Cook until caramelized and fragrant.",
      "Next, add the chicken stock and stir to deglaze the bottom of the pot. Add galangal powder, coriander powder, cloves, lime leaves, kecap manis, soy sauce, tamarind paste (if using) and the pepper. Stir to combine.",
      "Bring the mixture to a simmer, and add the seared chicken and any juices back to the pot. Cook uncovered for 25 minutes, turning the chicken every 5 to 10 minutes for even cooking. Skim off any foam that may emerge at the surface.",
      "Turn the heat up slightly and continue to cook off the liquid until the sauce thickens enough to coat a spoon. Taste for seasoning and add additional salt only if needed. Serve with rice and a stir-fried vegetable on the side.",
    ],
    zh: {
      name: "印尼豉油雞",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-laksa",
    name: "Laksa",
    cuisine: "Malaysian",
    time: 35,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/laksa_69012",
    sourceName: "BBC Food",
    materials: [
      { name: "Cooking oil", role: "staple", group: "main", amount: 75, unit: "ml", note: "/2.5fl oz vegetable oil" },
      { name: "Onion", role: "staple", group: "main", amount: 150, unit: "g", note: "/5.5oz , roughly chopped" },
      { name: "Ginger", role: "staple", group: "main", amount: 4, note: "cm/1.5in fresh root , peeled and roughly chopped" },
      { name: "Garlic", role: "staple", group: "main", amount: 4, note: "cloves" },
      { name: "Dried chili", role: "core", group: "main", amount: 8, note: "chillies, soaked in hot water for 30 minutes and drained" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 1, unit: "tbsp", note: "ground" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 1, unit: "tbsp", note: "ground" },
      { name: "Ground coriander", role: "staple", group: "main", amount: 1.5, unit: "tbsp" },
      { name: "Shrimp", role: "core", group: "main", amount: 12, unit: "g", note: "/0.5oz  paste" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 800, unit: "ml", note: "/1.5 pints" },
      { name: "Coconut milk", role: "core", group: "main", amount: 400, unit: "ml", note: "/14fl oz" },
      { name: "Sugar", role: "staple", group: "main", amount: 35, unit: "g", note: "/1.25oz caramelized palm  or dark brown sugar, plus extra to taste if needed" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "sea , plus extra to taste if needed" },
      { name: "Lemon", role: "core", group: "main", amount: 1, note: "grass stalk, cut in half then pounded lightly with a pestle to bruise" },
      { name: "Tofu", role: "core", group: "main", amount: 24, note: "deep-fried  puffs, cut in half" },
      { name: "Eggs", role: "core", group: "main", amount: 3, note: "free-range" },
      { name: "Beans", role: "core", group: "main", amount: 100, unit: "g", note: "/3.5oz prouts" },
      { name: "Green beans", role: "core", group: "main", amount: 60, unit: "g", note: "/2.25oz , cut into 5cm/2in lengths" },
    ],
    need: ["Dried chili","Shrimp","Coconut milk","Lemon","Tofu","Eggs","Beans","Green beans"],
    optional: ["Cooking oil","Onion","Ginger","Garlic","Cumin","Turmeric","Ground coriander","Chicken stock","Sugar","Salt"],
    steps: [
      "To make the spice paste, blend all of the ingredients in a food processor to a fine purée.",
      "Turn off the heat, remove the laksa leaves and lemongrass and adjust the salt and sugar to taste. Add the tofu puffs to the broth for 10 minutes so that they soak up the flavours.",
      "Fill another saucepan with water and bring to the boil. Blanch the following in boiling water one after the other – beansprouts for 10 seconds, green beans for 3 minutes and prawns for 90 seconds. Refresh the beansprouts and beans in cold water immediately after taking them out of the boiling water, then drain. Remember to allow the water to come back up to the boil before blanching the next ingredient.",
      "Finally, blanch the egg noodles for 10 seconds and drain well before distributing between six bowls.",
      "Divide the beansprouts, green beans and prawns evenly between the bowls. Pour the broth into each of the bowls, evenly dividing the tofu puffs between each serving. Place a boiled egg half on top of each bowl and finish with the sliced laksa leaves.",
    ],
    zh: {
      name: "叻沙",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-prawn-laksa",
    name: "Prawn laksa",
    cuisine: "Malaysian",
    time: 30,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/prawn_laksa_96549",
    sourceName: "BBC Food",
    materials: [
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "vegetable oil" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "finely chopped" },
      { name: "Garlic", role: "staple", group: "main", amount: 3, note: "cloves, crushed" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "light brown soft" },
      { name: "Fish sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Lime", role: "core", group: "main", amount: 1, note: "finely grated zest and juice" },
      { name: "Coconut milk", role: "core", group: "main", amount: 400, unit: "ml", note: "tin" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 100, unit: "ml", note: "/3.5fl oz fresh , gluten-free if required" },
      { name: "Spinach", role: "core", group: "main", amount: 85, unit: "g", note: "/3oz  baby  leaves" },
      { name: "Shrimp", role: "core", group: "main", amount: 200, unit: "g", note: "/7oz raw king prawns, shelled with the tails on (if desired)" },
      { name: "Cooked rice", role: "core", group: "main", amount: 100, unit: "g", note: "/3.5oz wide flat rice noodles or rice vermicelli" },
      { name: "Salt", role: "staple", group: "main", note: "and freshly ground black pepper" },
      { name: "Cilantro", role: "core", group: "garnish", amount: 2, unit: "tbsp", note: "chopped fresh coriander leaves" },
    ],
    need: ["Lime","Coconut milk","Spinach","Shrimp","Cooked rice","Cilantro"],
    optional: ["Cooking oil","Onion","Garlic","Sugar","Fish sauce","Chicken stock","Salt"],
    steps: [
      "Heat the oil in a large saucepan over a medium heat. Add the onion and fry for 5 minutes, stirring regularly. Reduce the heat, add the laksa paste and cook over a low heat for 5 minutes, until fragrant.",
      "Add the coconut milk and stock and boil for 2 minutes, then reduce to a simmer for 10–12 minutes.",
      "Meanwhile, cook the rice noodles according to packet instructions.",
      "Divide the laksa between two bowls. Top with the noodles, red onion, coriander and chilli. Serve immediately, with lime wedges for squeezing over.",
    ],
    zh: {
      name: "蝦叻沙",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-nasi-goreng",
    name: "Nasi goreng with lime",
    cuisine: "Indonesian",
    time: 25,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/nasi_goreng_with_lime_87031",
    sourceName: "BBC Food",
    materials: [
      { name: "Garlic", role: "staple", group: "main", amount: 3, note: "cloves, crushed" },
      { name: "White pepper", role: "staple", group: "main", amount: 1, unit: "tsp", note: "crushed corns" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "granulated" },
      { name: "Fish sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp", note: "Thai" },
      { name: "Lime", role: "core", group: "main", amount: 1, note: "juice only" },
      { name: "Chicken thighs", role: "core", group: "main", amount: 500, unit: "g", note: "/1lb 2oz skinned boneless , each cut into 2.5cm/1in strips" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "vegetable oil" },
      { name: "Shallot", role: "core", group: "main", amount: 50, unit: "g", note: "/2oz s, roughly chopped" },
      { name: "Salt", role: "staple", group: "main", amount: 25, unit: "g", note: "/1oz roasted ed peanuts" },
      { name: "Cooked rice", role: "core", group: "main", amount: 300, unit: "g", note: "/10.5oz long-grain rice" },
      { name: "Eggs", role: "core", group: "main", amount: 2, note: "free-range" },
      { name: "Tomato paste", role: "staple", group: "sauce", amount: 1, unit: "tbsp", note: "tomato purée" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp", note: "light" },
      { name: "Cucumber", role: "core", group: "main", amount: 5, note: "cm/2in piece , cut into quarters lengthways, sliced" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 8, note: "s, trimmed, thinly sliced on the diagonal" },
    ],
    need: ["Lime","Chicken thighs","Shallot","Cooked rice","Eggs","Cucumber"],
    optional: ["Garlic","White pepper","Sugar","Fish sauce","Cooking oil","Salt","Tomato paste","Soy sauce","Spring onion"],
    steps: [
      "For the barbecued chicken, mix the crushed garlic, crushed white peppercorns, sugar, fish sauce and lime juice together in a bowl. Add the chicken pieces and place in the fridge to marinate for at least 2 hours or overnight.",
      "For the nasi goreng, cook the rice in boiling, salted water for 12-15 minutes, or according to packet instructions, until just tender. Drain, rinse well with boiling hot water from the kettle, and drain well again.",
      "When the egg rolls are cold, slice them into thin strips.",
      "Add the soy sauce, cucumber and most of the spring onions and mix together well.",
      "To serve, spoon the nasi goreng onto a large warmed platter. Sprinkle over the remaining spring onions and allow people to help themselves.",
    ],
    zh: {
      name: "青檸印尼炒飯",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-beef-rendang",
    name: "Beef rendang",
    cuisine: "Indonesian",
    time: 120,
    servings: 6,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/beefrendang_78767",
    sourceName: "BBC Food",
    materials: [
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "roughly chopped" },
      { name: "Ginger", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "chopped fresh" },
      { name: "Garlic", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "chopped" },
      { name: "Lemon", role: "core", group: "main", amount: 1, note: "grass stalk, tough outer layer removed and roughly chopped" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 1, unit: "tsp" },
      { name: "Dried chili", role: "core", group: "main", amount: 6, note: "long red dried chillies, soaked in water and roughly chopped" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "sunflower oil" },
      { name: "Cardamom", role: "core", group: "main", amount: 6, note: "pods" },
      { name: "Beef steak", role: "core", group: "main", amount: 650, unit: "g", note: "/1lb 7oz braising steak, cut into 2cm/1inch cubes" },
      { name: "Lime", role: "core", group: "main", amount: 4, note: "makrut  leaves" },
      { name: "Coconut milk", role: "core", group: "main", amount: 400, unit: "ml", note: "/14fl oz" },
      { name: "Cilantro", role: "core", group: "garnish", note: "coriander sprigs to garnish" },
      { name: "Cooked rice", role: "core", group: "main", amount: 250, unit: "g", note: "/9oz basmati rice" },
      { name: "Salt", role: "staple", group: "main", note: "sea" },
      { name: "Shallot", role: "core", group: "main", note: "deep-fried s" },
    ],
    need: ["Lemon","Dried chili","Cardamom","Beef steak","Lime","Coconut milk","Cilantro","Cooked rice","Shallot"],
    optional: ["Onion","Ginger","Garlic","Turmeric","Cooking oil","Salt"],
    steps: [
      "For the rendang paste, place the onion, ginger, galangal, garlic, lemongrass, turmeric and chillies into a food processor. Blend to form a smooth purée.",
      "Season with salt, stir well then reduce to a simmer.",
      "Add the rice and fry until the grains begin to turn an opaque white.",
      "Keep warm until everything else is ready. You can hold rice like this for up to half an hour.",
      "To serve, mix the herbs into the rice and divide between four warmed serving dishes. Next spoon on the rendang, finish with a few sprigs of coriander and serve immediately, garnished with the deep-fried shallots and chilli.",
    ],
    zh: {
      name: "仁當牛肉",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-mee-goreng",
    name: "Tofu mee goreng",
    cuisine: "Malaysian",
    time: 25,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/tofu_mee_goreng_25209",
    sourceName: "BBC Food",
    materials: [
      { name: "Pak choi", role: "core", group: "main", amount: 2 },
      { name: "Cornstarch", role: "staple", group: "marinade", amount: 2, unit: "tbsp", note: "cornflour" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 4, unit: "tbsp", note: "sunflower oil" },
      { name: "Tofu", role: "core", group: "main", amount: 140, unit: "g", note: "/5oz extra firm , drained well" },
      { name: "Onion", role: "staple", group: "main", amount: 0.5, note: "cut into thin wedges" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, note: "cloves, thinly sliced" },
      { name: "Broccoli", role: "core", group: "main", amount: 100, unit: "g", note: "/3.5oz Tenderstem , stems sliced and heads halved if large, or ordinary brocc…" },
      { name: "Bell pepper", role: "core", group: "main", amount: 1, note: "red pepper, seeds removed, thinly sliced" },
      { name: "Carrots", role: "core", group: "main", amount: 1, note: "carrot, peeled and thinly sliced on the diagonal" },
      { name: "Eggs", role: "core", group: "main", amount: 300, unit: "g", note: "/9oz ready-cooked vegan noodles, such as no-egg medium noodles or rice noodles" },
    ],
    need: ["Pak choi","Tofu","Broccoli","Bell pepper","Carrots","Eggs"],
    optional: ["Cornstarch","Cooking oil","Onion","Garlic"],
    steps: [
      "Trim the pak choi and cut into roughly 3cm/1¼ in slices. Separate the white part from the leaves and set aside. Sprinkle the cornflour over a large plate. Cut the tofu into 8–10 thin slices. Dust the tofu lightly on both sides with the cornflour.",
      "Heat the oil in a large frying pan and fry the tofu for 1–1½ minutes on each side, or until crisp and lightly browned, turning carefully. Transfer to a plate lined with kitchen paper.",
      "Add the onion to the pan and cook over a medium-high heat for 6–8 minutes, or until lightly browned. Add the garlic and cook for a few seconds more. Lift out of the pan with a slotted spoon or spatula and drain on kitchen paper.",
      "Add the broccoli, red pepper, carrot and white part of the pak choi to the frying pan and stir-fry for 5 minutes. Add the noodles and green part of the pak choi and cook for 2 minutes more, or until the noodles are hot and the leaves have wilted.",
      "Stir the ketjap manis and half a teaspoon of chilli paste into the pan, add the tofu, onion and garlic and cook for 1–2 minutes more, stirring and tossing all the ingredients until hot. Add extra chilli to taste, scatter with the cashew nuts and serve.",
    ],
    zh: {
      name: "豆腐馬來炒麵",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-sambal-tofu",
    name: "Sticky sambal tofu",
    cuisine: "Malaysian",
    time: 25,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/sticky_sambal_tofu_and_85375",
    sourceName: "BBC Food",
    materials: [
      { name: "Tofu", role: "core", group: "main", amount: 600, unit: "g", note: "/1lb 5oz extra firm , torn into bite sized pieces" },
      { name: "Sugar", role: "staple", group: "main", amount: 4, unit: "tbsp", note: "brown" },
      { name: "Lime", role: "core", group: "main", amount: 0.5, note: "juice only" },
      { name: "Noodles", role: "core", group: "main", amount: 4, note: "portions (approx. 320g/11.5oz)  of choice" },
      { name: "Butter", role: "core", group: "main", amount: 4, unit: "tbsp", note: "peanut  (any type)" },
      { name: "Cabbage", role: "core", group: "main", amount: 0.25, note: "white , finely shredded" },
      { name: "Spinach", role: "core", group: "main", amount: 40, unit: "g", note: "/1.5oz fresh , thinly sliced" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 1, unit: "tbsp" },
      { name: "Salt", role: "staple", group: "main" },
    ],
    need: ["Tofu","Lime","Noodles","Butter","Cabbage","Spinach"],
    optional: ["Sugar","Sesame oil","Salt"],
    steps: [
      "To make the tofu, preheat the oven to 200C/180C Fan/Gas 6.",
      "Mix the rest of the noodle ingredients together in a large bowl. Add a splash of water as needed until you have a smooth, pourable sauce.",
      "Add the remaining tofu ingredients and 4 tablespoons water to a bowl and stir well to create the sambal sauce.",
      "Pour over the sambal sauce (it should sizzle immediately) and cook for 30 seconds to 1 minute, stirring continuously so it doesn’t burn, until it reduces to a sticky sauce. Remove from the heat.",
      "To serve, divide the noodles evenly between 4 bowls then top with the tofu, greens and a lime wedge.",
    ],
    zh: {
      name: "參巴豆腐",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-quick-chicken-laksa",
    name: "Quick chicken laksa",
    cuisine: "Malaysian",
    time: 25,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/quick_chicken_laksa_27176",
    sourceName: "BBC Food",
    materials: [
      { name: "Eggs", role: "core", group: "main", amount: 2, note: "free-range" },
      { name: "Noodles", role: "core", group: "main", amount: 200, unit: "g", note: "/7oz dried vermicelli" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "vegetable oil" },
      { name: "Curry powder", role: "staple", group: "main", amount: 3, unit: "tbsp", note: "shop-bought red curry paste or laksa paste" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 200, unit: "ml", note: "/7fl oz" },
      { name: "Coconut milk", role: "core", group: "main", amount: 400, unit: "ml", note: "tin" },
      { name: "Fish sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp", note: "light brown" },
      { name: "Chicken breast", role: "core", group: "main", amount: 1, note: "(or 2 small chicken breasts)" },
      { name: "Cucumber", role: "core", group: "main", amount: 0.25, note: "cut into very thin matchsticks" },
      { name: "Cilantro", role: "core", group: "garnish", note: "handful chopped fresh coriander leaves" },
      { name: "Lime", role: "core", group: "main", amount: 1, note: "cut into wedges, to serve" },
    ],
    need: ["Eggs","Noodles","Coconut milk","Chicken breast","Cucumber","Cilantro","Lime"],
    optional: ["Cooking oil","Curry powder","Chicken stock","Fish sauce","Sugar"],
    steps: [
      "Bring a large saucepan of water to the boil. Cook the eggs for 6 minutes. Transfer the eggs to a bowl of cold water and set aside until needed.",
      "Add the chicken breast to the pan, place the lid back on and lower the heat to medium. Cook for 10–12 minutes or until the chicken is cooked through.",
      "Carefully transfer the chicken to a plate. Keep the soup warm over a low heat. Leave the chicken to cool, then use your hands or forks to shred the chicken into chunks.",
      "Divide the drained vermicelli between two bowls and top with the shredded chicken. Ladle the soup into each bowl until the vermicelli is just covered. Peel the eggs, cut each in half and add to the bowls. Garnish with the cucumber, mint, coriander and chilli and serve with the lime wedges.",
    ],
    zh: {
      name: "快手雞叻沙",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-pineapple-shrimp-fried-rice",
    name: "Pineapple shrimp fried rice",
    cuisine: "Thai",
    time: 25,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/pineapple-fried-rice/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Shrimp", role: "core", group: "main", amount: 8, unit: "oz", note: "225g, peeled, deveined, rinsed, and pat dry" },
      { name: "Onion", role: "staple", group: "main", amount: 1, unit: "cup", note: "150g, diced" },
      { name: "Carrots", role: "core", group: "main", amount: 1, unit: "cup", note: "75g, diced" },
      { name: "Ham", role: "core", group: "main", amount: 4, unit: "oz", note: "or Chinese sausage; 115g, finely diced" },
      { name: "Cooked rice", role: "core", group: "main", amount: 6, unit: "cup", note: "about 900g" },
      { name: "Snow peas", role: "core", group: "main", amount: 2, unit: "cup", note: "100g" },
      { name: "Pineapple", role: "core", group: "main", amount: 1, unit: "cup", note: "diced into 1/2-inch pieces" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 1, note: "chopped" },
      { name: "Eggs", role: "core", group: "main", amount: 2, note: "beaten" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp", note: "more to taste" },
      { name: "Shaoxing wine", role: "staple", group: "main", amount: 1, unit: "tsp", note: "plus 1 tablespoon, divided" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 4, unit: "tbsp", note: "divided" },
      { name: "Fish sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp", note: "or Thai thin soy sauce" },
      { name: "White pepper", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 1.5, unit: "tsp" },
    ],
    need: ["Shrimp","Carrots","Ham","Cooked rice","Snow peas","Pineapple","Eggs"],
    optional: ["Onion","Spring onion","Salt","Shaoxing wine","Cooking oil","Fish sauce","Soy sauce","White pepper","Sesame oil"],
    steps: [
      "First, prepare the shrimp, onion, carrot, ham/Chinese sausage, rice, peas, pineapple, and scallions. If using fresh pineapple, remember to trim away the pineapple core. If using canned pineapple, rinse away any syrup and pat dry with a clean kitchen towel.",
      "Heat another 1 tablespoon of oil over medium heat. Cook the shrimp until they turn pink, about 1 minute. Remove from the wok and set aside.",
      "Stir-fry everything together well, and add in the peas, 1 tablespoon fish sauce, 1 tablespoon light soy sauce, ½ teaspoon ground white pepper, 1 teaspoon sesame oil, the scrambled egg, and the cooked shrimp. Stir-fry everything together for a few minutes.",
      "Finally, add the pineapple and scallions. Mix everything again for a minute or two. To crisp and warm the rice through, you can use your wok spatula to spread the rice in a single layer around the surface area of the wok, making use of all the heat and letting any excess liquid evaporate.",
      "Salt to taste, and serve immediately!",
    ],
    zh: {
      name: "菠蘿蝦炒飯",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  }
]
