import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W5D: Recipe[] = [
  {
    id: "home-diced-berkshire-pork-with-peach-in-sweetened-vin",
    name: "Diced Berkshire Pork with Peach in Sweetened Vinegar Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Ground pork"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Ground pork and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "一口蜜桃醋香黑豚肉",
      steps: [
        "準備一口蜜桃醋香黑豚肉材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-dong-po-pork-dumplings",
    name: "Dong Po Pork Dumplings",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Ground pork"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Ground pork and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "東坡肉餃子",
      steps: [
        "準備東坡肉餃子材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-double-boiled-winter-melon-soup-with-morels",
    name: "Double Boiled Winter Melon Soup with Morels",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Winter melon"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Winter melon briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "羊肚菌迷你冬瓜盅",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-double-mushroom-and-chicken-rice",
    name: "Double Mushroom and Chicken Rice",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs", "Mushroom", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and Mushroom plus Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add Mushroom and Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "雙菇雞肉炊飯",
      steps: [
        "準備雙菇雞肉炊飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-drumstick-rice-bake-rice-cooker-version",
    name: "Drumstick Rice Bake Rice Cooker Version",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Chicken thighs", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and Cooked rice with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "飯煲焗雞髀紫薯飯",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-anhydrous-japanese-chicken-curry",
    name: "Anhydrous Japanese Chicken Curry",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "無水咖喱鍋",
      steps: [
        "準備無水咖喱鍋日本材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-avocado-pesto-pasta",
    name: "Avocado Pesto Pasta",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Avocado", "Pasta"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Olive oil", "Cheddar", "Onion"],
    steps: [
      "Boil pasta in salted water until al dente; reserve ½ cup pasta water.",
      "Meanwhile sauté garlic/onion and Avocado in olive oil until just cooked.",
      "Toss pasta with the pan sauce and a splash of pasta water; adjust salt and finish with pepper or cheese if using.",
    ],
    zh: {
      name: "牛油果青醬意粉",
      steps: [
        "意粉盐水煮至 al dente，留半杯麵水。",
        "另鑊用橄欖油炒蒜洋蔥及主料至熟。",
        "拌入意粉和少許麵水調味，可加芝士或黑胡椒。",
      ],
    },
  },
  {
    id: "home-beef-bourguignon",
    name: "Beef Bourguignon",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Beef steak"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Beef steak and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "紅酒燉牛肉",
      steps: [
        "準備紅酒燉牛肉材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-beef-bourguignon-using-vermicular-oven-pot-2",
    name: "Beef Bourguignon Using Vermicular Oven Pot 2",
    cuisine: "Chinese",
    time: 40,
    servings: 2,
    need: ["Beef steak"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Heat oven to 200°C. Toss Beef steak and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "法式紅酒燉牛肉",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-beetroot-and-mikan-salad",
    name: "Beetroot and Mikan Salad",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Prep Eggs and Tomato; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "蜜柑紅菜頭沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-beyond-beef-rice-in-claypot",
    name: "Beyond Beef Rice in Claypot",
    cuisine: "Hong Kong",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Eggs", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Beef steak and Eggs plus Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Eggs and Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "窩蛋未來牛肉煲仔飯",
      steps: [
        "準備窩蛋未來牛肉煲仔飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-black-squid-ink-paella-with-scallop-and-oyster",
    name: "Black Squid Ink Paella with Scallop and Oyster",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Squid"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Squid and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Squid and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "墨汁意大利飯",
      steps: [
        "準備墨汁意大利飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-braised-abalone-with-mushroom-and-goose-feet",
    name: "Braised Abalone with Mushroom and Goose Feet",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["White fish", "Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut White fish and Mushroom into pieces; lightly brown White fish in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until White fish is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "鮑魚花菇炆鵝掌",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-beef-cheeks-in-red-wine",
    name: "Braised Beef Cheeks in Red Wine",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Beef steak", "Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Beef steak and Noodles into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "紅酒燉牛面頰",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-oxtail-in-red-wine",
    name: "Braised Oxtail in Red Wine",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Beef steak"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Beef steak and vegetables into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "紅酒燉牛尾",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-cauliflower-rice-with-crab-meat-and-onsen-tamago",
    name: "Cauliflower Rice with Crab Meat and Onsen Tamago",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Cauliflower", "Cabbage", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Eggs and Cauliflower plus Cabbage; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Cauliflower and Cabbage, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "黑松露忌廉蟹肉椰菜花飯配",
      steps: [
        "準備黑松露忌廉蟹肉椰菜花飯配溫泉蛋材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-cherry-tomato-confit",
    name: "Cherry Tomato Confit",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Tomato and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Tomato and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "油封車厘茄",
      steps: [
        "準備油封車厘茄認真地烹調每一粒蕃茄材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-chestnut-chicken-rice-using-japanese-donabe",
    name: "Chestnut Chicken Rice Using Japanese Donabe",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "粟子雞肉炊飯",
      steps: [
        "準備🌰粟子雞肉炊飯暖笠笠又簡單 土鍋煮飯示範材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-chestnut-mushroom-rice",
    name: "Chestnut Mushroom Rice",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Mushroom", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Mushroom and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Mushroom and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "栗子野菌炊飯",
      steps: [
        "準備栗子野菌炊飯日本材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-chicken-and-chorizo-paella",
    name: "Chicken and Chorizo Paella",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "西班牙辣肉腸雞肉飯",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-chicken-and-mushroom-clay-pot-rice-using-ih-indu",
    name: "Chicken and Mushroom Clay Pot Rice Using Ih Induction Cooker and Cast Iron Pot",
    cuisine: "Hong Kong",
    time: 20,
    servings: 2,
    need: ["Chicken thighs", "Mushroom", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and Mushroom plus Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add Mushroom and Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "金黃飯焦",
      steps: [
        "準備金黃飯焦北菇滑雞煲仔飯 用電磁爐及鑄鐵鍋 都可做到完美飯焦？材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-chicken-consomme",
    name: "Chicken Consomme",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Chicken thighs briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "法式澄清雞湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-chicken-teriyaki-don",
    name: "Chicken Teriyaki Don",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "照燒雞扒丼飯",
      steps: [
        "準備照燒雞扒丼飯放工快靚正食譜材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-chicken-tsukune",
    name: "Chicken Tsukune",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "日式免治雞肉軟骨串",
      steps: [
        "準備日式免治雞肉軟骨串材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-chiuchow-pickled-oysters",
    name: "Chiuchow Pickled Oysters",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Eggs and Tomato; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Tomato, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "潮汕生醃蠔",
      steps: [
        "準備潮汕生醃蠔自家改良日式風味 網絡熱爆食法材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-clams-with-chorizo-and-tomatoes",
    name: "Clams with Chorizo and Tomatoes",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Clams", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Clams briefly if it is meat; rinse. Cut Tomato into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "西班牙辣肉腸番茄煮蜆",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-clear-tomato-cold-soup-with-okra",
    name: "Clear Tomato Cold Soup with Okra",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Tomato", "Green beans"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Tomato briefly if it is meat; rinse. Cut Green beans into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "濃縮番茄凍清湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-congee-seafood-steam-pot",
    name: "Congee Seafood Steam Pot",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Arrange Rice with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "粥底海鮮蒸氣鍋",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-cream-of-cauliflower-soup",
    name: "Cream of Cauliflower Soup",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Cauliflower", "Cabbage"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Cauliflower briefly if it is meat; rinse. Cut Cabbage into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "椰菜花忌廉湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-creamy-corn-soup",
    name: "Creamy Corn Soup",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Corn"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Corn briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "特濃粟米忌廉湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-creamy-mentaiko-pasta",
    name: "Creamy Mentaiko Pasta",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Pasta"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Olive oil", "Cheddar", "Onion"],
    steps: [
      "Boil pasta in salted water until al dente; reserve ½ cup pasta water.",
      "Meanwhile sauté garlic/onion and Pasta in olive oil until just cooked.",
      "Toss pasta with the pan sauce and a splash of pasta water; adjust salt and finish with pepper or cheese if using.",
    ],
    zh: {
      name: "明太子忌廉意粉",
      steps: [
        "意粉盐水煮至 al dente，留半杯麵水。",
        "另鑊用橄欖油炒蒜洋蔥及主料至熟。",
        "拌入意粉和少許麵水調味，可加芝士或黑胡椒。",
      ],
    },
  },
  {
    id: "home-diced-beef-tenderloin-with-black-pepper-and-pota",
    name: "Diced Beef Tenderloin with Black Pepper and Potato",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Potato", "Bell pepper"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Beef steak and Potato plus Bell pepper; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Potato and Bell pepper, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "黑椒薯仔牛柳粒",
      steps: [
        "準備黑椒薯仔牛柳粒大排檔必點菜式在家做材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-fish-en-papillote-with-fresh-herbs-and-lime",
    name: "Fish En Papillote with Fresh Herbs and Lime",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["White fish", "Lime"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep White fish and Lime; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add White fish and cook until just cooked.",
      "Add Lime, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "法式紙包魚",
      steps: [
        "準備法式紙包魚材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-fortune-chicken-with-mushrooms",
    name: "Fortune Chicken with Mushrooms",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Chicken thighs", "Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and Mushroom with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "松茸野菌富貴雞",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-french-crepe-with-ham-cheese-egg",
    name: "French Crepe with Ham Cheese Egg",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Ham", "Eggs", "Tortilla"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Ham and Eggs plus Tortilla; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ham and cook until just cooked.",
      "Add Eggs and Tortilla, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "法式鹹可麗餅",
      steps: [
        "準備法式鹹可麗餅材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-french-onion-soup",
    name: "French Onion Soup",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Tofu", "Pak choi"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Tofu briefly if it is meat; rinse. Cut Pak choi into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "法式洋蔥湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-french-pot-roast-chicken",
    name: "French Pot Roast Chicken",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "法式田園焗雞",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-french-roast-three-yellow-chicken",
    name: "French Roast Three Yellow Chicken",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "法式焗三黃雞",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-fried-rice-with-eel",
    name: "Fried Rice with Eel",
    cuisine: "Japanese",
    time: 15,
    servings: 2,
    need: ["White fish", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Loosen cold cooked rice; beat 2 eggs if eggs are in the dish. Dice other mix-ins small.",
      "Scramble eggs in a hot oiled pan; push aside or remove. Stir-fry aromatics and proteins until cooked.",
      "Add rice and 1–2 tbsp soy sauce; toss on high heat until hot and lightly toasted. Finish with spring onion.",
    ],
    zh: {
      name: "日式鰻魚炒飯",
      steps: [
        "隔夜飯撥散；如用蛋可先打散。配料切細。",
        "熱鑊炒蛋盛起；爆香蒜薑及蛋白質炒熟。",
        "下飯加 1 至 2 湯匙生抽大火炒香，撒蔥起鑊。",
      ],
    },
  },
  {
    id: "home-furano-country-style-bake-chicken",
    name: "Furano Country Style Bake Chicken",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "富良野田園焗雞",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-golden-beet-soup",
    name: "Golden Beet Soup",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Tofu", "Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Tofu briefly if it is meat; rinse. Cut Mushroom into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "金菜頭濃湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-grilled-flatfish-claypot-rice",
    name: "Grilled Flatfish Claypot Rice",
    cuisine: "Hong Kong",
    time: 20,
    servings: 2,
    need: ["White fish", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep White fish and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add White fish and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "炙燒左口魚煲仔飯",
      steps: [
        "準備炙燒左口魚煲仔飯左口魚Fans必學 日本長谷園土鍋示範材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-hokkaido-horsehair-crab-clay-pot-rice",
    name: "Hokkaido Horsehair Crab Clay Pot Rice",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Cooked rice and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Cooked rice and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "北海道毛蟹鍋飯",
      steps: [
        "準備北海道毛蟹鍋飯在家也可吃毛蟹鍋飯 長谷園土鍋示範材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-homemade-fettuccine-in-tomato-sauce-with-pan-sea",
    name: "Homemade Fettuccine in Tomato Sauce with Pan Seared Chicken Breast",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Chicken thighs", "Tomato", "Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Pat Chicken breast dry; season with salt and white pepper. Slice Chicken thighs if using as a side.",
      "Pan-fry in a lightly oiled skillet over medium heat until browned and cooked until cooked through (74°C / 165°F).",
      "Deglaze with a splash of soy sauce or serve with a quick ginger-spring-onion drizzle.",
    ],
    zh: {
      name: "自家製鮮茄醬闊條麵配煎嫩雞胸",
      steps: [
        "主料抹乾，加鹽白胡椒；配菜切片。",
        "中火少油煎至上色并熟透。",
        "可淋少許生抽或以薑蔥油提味。",
      ],
    },
  },
  {
    id: "home-homemade-golden-pasta",
    name: "Homemade Golden Pasta",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Pasta"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Olive oil", "Cheddar", "Onion"],
    steps: [
      "Boil pasta in salted water until al dente; reserve ½ cup pasta water.",
      "Meanwhile sauté garlic/onion and Pasta in olive oil until just cooked.",
      "Toss pasta with the pan sauce and a splash of pasta water; adjust salt and finish with pepper or cheese if using.",
    ],
    zh: {
      name: "手製意大利麵",
      steps: [
        "意粉盐水煮至 al dente，留半杯麵水。",
        "另鑊用橄欖油炒蒜洋蔥及主料至熟。",
        "拌入意粉和少許麵水調味，可加芝士或黑胡椒。",
      ],
    },
  },
  {
    id: "home-homemade-tomato-pasta-sauce",
    name: "Homemade Tomato Pasta Sauce",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Tomato", "Pasta"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Olive oil", "Cheddar", "Onion"],
    steps: [
      "Boil pasta in salted water until al dente; reserve ½ cup pasta water.",
      "Meanwhile sauté garlic/onion and Tomato in olive oil until just cooked.",
      "Toss pasta with the pan sauce and a splash of pasta water; adjust salt and finish with pepper or cheese if using.",
    ],
    zh: {
      name: "手工香草蕃茄意粉醬",
      steps: [
        "意粉盐水煮至 al dente，留半杯麵水。",
        "另鑊用橄欖油炒蒜洋蔥及主料至熟。",
        "拌入意粉和少許麵水調味，可加芝士或黑胡椒。",
      ],
    },
  },
  {
    id: "home-homemade-tomato-sauce",
    name: "Homemade Tomato Sauce",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Tomato and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Tomato and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "自家製番茄醬",
      steps: [
        "準備自家製番茄醬日本材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-homemde-tempura-bowl-rice",
    name: "Homemde Tempura Bowl Rice",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Cooked rice and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Cooked rice and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "自家製天丼",
      steps: [
        "準備自家製天丼在家都可以做出合格的天婦羅？材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-honey-lime-salad-oil",
    name: "Honey Lime Salad Oil",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Lime"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Prep Lime and vegetables; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "青金桔沙律油",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-italian-caprese-salad",
    name: "Italian Caprese Salad",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Prep Eggs and Tomato; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "意大利三色沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
]
