import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W4A: Recipe[] = [
  {
    id: "home-old-cucumber-pork-soup",
    name: "Old cucumber pork soup",
    cuisine: "Cantonese",
    time: 55,
    servings: 4,
    need: ["Pork chops", "Cucumber"],
    optional: ["Ginger", "Salt", "White pepper", "Dried mushrooms", "Cooking oil", "Glass noodles", "Cabbage", "Spring onion", "Cilantro"],
    steps: [
      "Cut 400 g pork chops into large pieces; peel and thick-slice 2 cucumbers (old-cucumber stand-in). Soak a few dried mushrooms if using.",
      "Blanch pork 2 minutes in boiling water; rinse. Add pork, cucumber, ginger slices, and mushrooms to a pot with about 1.5 L water.",
      "Simmer uncovered 40–45 minutes until pork is tender. Season with salt and white pepper; skim foam before serving.",
    ],
    zh: {
      name: "老黃瓜排骨湯",
      steps: [
        "豬扒約 400 克切大件；兩條青瓜去皮厚切（代替老黃瓜）。乾冬菇可先浸軟。",
        "豬件焯水 2 分鐘過冷河。豬、青瓜、薑片和冬菇加水約 1.5 升。",
        "慢火煮 40 至 45 分鐘至豬軟，加鹽和白胡椒，撇沫即可。",
      ],
    },
  },
  {
    id: "home-watercress-pork-rib",
    name: "Watercress pork rib soup",
    cuisine: "Cantonese",
    time: 50,
    servings: 4,
    need: ["Pork chops", "Ginger"],
    optional: ["Salt", "White pepper", "Soy sauce"],
    steps: [
      "Cut 500 g spare ribs into pieces; blanch 2 minutes and rinse. Wash 200 g spinach (watercress stand-in).",
      "Simmer ribs with ginger and dried mushrooms in about 1.5 L water for 35–40 minutes until meat is tender.",
      "Add spinach for the last 2–3 minutes until wilted. Season with salt and white pepper.",
    ],
    zh: {
      name: "西洋菜排骨湯",
      steps: [
        "排骨約 500 克切件焯水 2 分鐘過冷河。菠菜約 200 克洗净（代替西洋菜）。",
        "排骨加薑和乾冬菇，加水約 1.5 升煮 35 至 40 分鐘至軟。",
        "最後 2 至 3 分鐘下菠菜至軟，加鹽和白胡椒調味。",
      ],
    },
  },
  {
    id: "home-tomato-brisket-soup",
    name: "Tomato beef brisket soup",
    cuisine: "Hong Kong",
    time: 90,
    servings: 4,
    need: ["Beef brisket", "Tomato", "Potato"],
    optional: ["Onion", "Carrots", "Celery", "Salt", "Sugar", "White pepper", "Beef steak", "Cornstarch", "Baking soda", "Cooking oil", "Oyster sauce", "Soy sauce", "Sesame oil", "Ginger", "Garlic", "Shallot", "Spring onion", "Ketchup", "Shaoxing wine"],
    steps: [
      "Cut 600 g beef brisket into 4 cm chunks; blanch 3 minutes and rinse. Chop 3 tomatoes, 1 potato, and onion/carrot if using.",
      "Brown brisket lightly, then add tomato and onion; cook until saucy. Cover with about 1.5 L water.",
      "Simmer 70–80 minutes until brisket is tender. Add potato (and carrot/celery) for the last 20 minutes. Season with salt, a pinch of sugar, and white pepper.",
    ],
    zh: {
      name: "番茄牛腩湯",
      steps: [
        "牛腩約 600 克切 4 厘米件，焯水 3 分鐘過冷河。三個番茄、一個薯仔切件，有洋蔥紅蘿蔔亦可。",
        "牛腩略煎香，下番茄洋蔥炒至出汁，加水約 1.5 升。",
        "炆 70 至 80 分鐘至軟；最後 20 分鐘下薯仔（可加紅蘿蔔芹菜），加鹽、少許糖和白胡椒。",
      ],
    },
  },
  {
    id: "home-soy-egg-tofu-braise",
    name: "Soy-braised eggs with tofu",
    cuisine: "Chinese",
    time: 35,
    servings: 3,
    need: ["Eggs", "Tofu", "Soy sauce"],
    optional: ["Sugar", "Garlic", "Spring onion", "Sesame oil", "White pepper", "Cooking oil", "Chicken stock", "Oyster sauce", "Salt", "Carrots", "Shaoxing wine", "Cornstarch"],
    steps: [
      "Hard-boil 4 eggs 8–9 minutes; cool and peel. Cut 300 g tofu into thick slabs.",
      "Mix 3 tbsp soy sauce, 1 tbsp sugar if using, minced garlic, and 1 cup water. Arrange tofu in a pan; nestle eggs alongside.",
      "Pour sauce over, simmer covered 12–15 minutes, turning eggs once so they take color. Finish with spring onion and sesame oil.",
    ],
    zh: {
      name: "滷蛋炆豆腐",
      steps: [
        "四隻蛋煮 8 至 9 分鐘放涼去殼。豆腐約 300 克切厚件。",
        "三湯匙生抽、一湯匙糖（可用）、蒜蓉和一杯水拌勻。鍋中鋪豆腐，蛋放旁邊。",
        "倒入醬汁加蓋炆 12 至 15 分鐘，中途翻蛋上色；撒蔥花滴麻油。",
      ],
    },
  },
  {
    id: "home-lotus-corn-clear-soup",
    name: "Lotus root corn soup",
    cuisine: "Cantonese",
    time: 50,
    servings: 4,
    need: ["Lotus root", "Corn", "Pork chops"],
    optional: ["Ginger", "Carrots", "Salt", "Dried mushrooms", "Chicken stock", "Oyster sauce", "Sugar", "White pepper", "Cooking oil", "Garlic", "Spring onion", "Shaoxing wine", "Cornstarch"],
    steps: [
      "Peel and slice 300 g lotus root; cut 1 corn cob into rounds (or use 1 cup corn kernels). Cut 300 g pork chops into pieces; blanch and rinse.",
      "Add pork, lotus, corn, ginger, and carrot/mushrooms if using to a pot with about 1.5 L water.",
      "Simmer 40–45 minutes until lotus is tender. Season with salt.",
    ],
    zh: {
      name: "蓮藕玉米湯",
      steps: [
        "蓮藕約 300 克去皮切片；一條玉米切段（或一杯玉米粒）。豬扒約 300 克切件焯水過冷河。",
        "豬、蓮藕、玉米、薑，可加紅蘿蔔或乾冬菇，加水約 1.5 升。",
        "煮 40 至 45 分鐘至蓮藕軟，加鹽調味。",
      ],
    },
  },
  {
    id: "home-winter-melon-rib-soup",
    name: "Winter melon spare rib soup",
    cuisine: "Cantonese",
    time: 50,
    servings: 4,
    need: ["Winter melon", "Spare ribs"],
    optional: ["Ginger", "Salt", "Dried mushrooms", "White pepper", "Spring onion"],
    steps: [
      "Cut 500 g spare ribs into pieces; blanch 2 minutes and rinse. Peel and cube 500 g winter melon.",
      "Simmer ribs with ginger and dried mushrooms in about 1.5 L water for 25 minutes.",
      "Add winter melon; cook 20 more minutes until soft. Season with salt and white pepper; top with spring onion.",
    ],
    zh: {
      name: "冬瓜排骨湯",
      steps: [
        "排骨約 500 克切件焯水 2 分鐘過冷河。冬瓜約 500 克去皮切塊。",
        "排骨加薑和乾冬菇，加水約 1.5 升煮 25 分鐘。",
        "下冬瓜再煮 20 分鐘至軟，加鹽和白胡椒，撒蔥花。",
      ],
    },
  },
  {
    id: "home-creamy-pumpkin-soup",
    name: "Creamy pumpkin soup",
    cuisine: "Western",
    time: 35,
    servings: 3,
    need: ["Pumpkin", "Onion", "Milk"],
    optional: ["Butter", "Garlic", "Salt", "White pepper", "Bread", "Chicken stock"],
    steps: [
      "Cube 500 g pumpkin; chop 1 onion. Soften onion and garlic in butter or oil 4–5 minutes.",
      "Add pumpkin and about 3 cups water; simmer 18–20 minutes until soft. Mash or blend until smooth.",
      "Stir in 1/2 cup milk; warm without boiling. Season with salt and white pepper; serve with bread if you like.",
    ],
    zh: {
      name: "南瓜濃湯",
      steps: [
        "南瓜約 500 克切塊；一個洋蔥切碎。牛油或油炒軟洋蔥蒜蓉 4 至 5 分鐘。",
        "下南瓜加水約三杯，煮 18 至 20 分鐘至軟，壓蓉或攪拌至滑。",
        "加入半杯牛奶溫熱勿滾，加鹽和白胡椒，可配麵包。",
      ],
    },
  },
  {
    id: "home-apple-pork-bone-soup",
    name: "Apple pork bone soup",
    cuisine: "Cantonese",
    time: 55,
    servings: 4,
    need: ["Ginger", "Cabbage", "Spring onion", "Cilantro"],
    optional: ["Cooking oil", "Salt", "White pepper"],
    steps: [
      "Cut 400 g pork chops into pieces; blanch and rinse. Core and quarter 2 apples; chunk 1 carrot.",
      "Add pork, apple, carrot, ginger, and corn/mushrooms if using with about 1.5 L water.",
      "Simmer 40–45 minutes. Season lightly with salt (apples add sweetness).",
    ],
    zh: {
      name: "蘋果豬骨湯",
      steps: [
        "豬扒約 400 克切件焯水過冷河。兩個蘋果去核切四；一條紅蘿蔔切塊。",
        "豬、蘋果、紅蘿蔔、薑，可加玉米或乾冬菇，加水約 1.5 升。",
        "煮 40 至 45 分鐘，略加鹽（蘋果帶甜）。",
      ],
    },
  },
  {
    id: "home-carrot-potato-brisket",
    name: "Carrot potato brisket stew",
    cuisine: "Chinese",
    time: 85,
    servings: 4,
    need: ["Beef brisket", "Carrots", "Potato"],
    optional: ["Onion", "Soy sauce", "Ginger", "Garlic", "Sugar", "Salt"],
    steps: [
      "Cut 600 g beef brisket into chunks; blanch and rinse. Cube 2 carrots and 2 potatoes.",
      "Brown brisket with ginger/garlic; add 2 tbsp soy sauce, onion if using, and about 1.2 L water.",
      "Simmer 60 minutes; add carrot and potato, cook 20 more minutes until tender. Adjust salt and a pinch of sugar.",
    ],
    zh: {
      name: "紅蘿蔔薯仔炆牛腩",
      steps: [
        "牛腩約 600 克切件焯水過冷河。兩條紅蘿蔔、兩個薯仔切塊。",
        "牛腩加薑蒜略炒，下兩湯匙生抽、洋蔥（可用）和水約 1.2 升。",
        "炆 60 分鐘；下紅蘿蔔薯仔再 20 分鐘至軟，調鹽和少許糖。",
      ],
    },
  },
  {
    id: "home-dried-mushroom-chicken-soup",
    name: "Dried mushroom chicken soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Mushroom", "Berries", "Chicken breast", "Ginger", "Spring onion"],
    optional: ["Cooking oil", "Shaoxing wine", "Salt"],
    steps: [
      "Soak 8–10 dried mushrooms until soft; squeeze and slice. Cut 500 g chicken thighs into pieces; blanch briefly.",
      "Add chicken, mushrooms, ginger, and a splash of Shaoxing wine if using with about 1.2 L water.",
      "Simmer 30–35 minutes until chicken reaches 74°C / 165°F. Season with salt and white pepper; finish with spring onion.",
    ],
    zh: {
      name: "冬菇雞湯",
      steps: [
        "乾冬菇 8 至 10 朵浸軟擠乾切片。雞脾約 500 克切件略焯。",
        "雞、冬菇、薑，可加少許料酒，加水約 1.2 升。",
        "煮 30 至 35 分鐘至雞全熟（74°C），加鹽和白胡椒，撒蔥花。",
      ],
    },
  },
  {
    id: "home-tofu-skin-rib-soup",
    name: "Tofu skin spare rib soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Spare ribs", "Tofu skin"],
    optional: ["Ginger", "Salt", "Dried mushrooms", "White pepper"],
    steps: [
      "Cut 400 g spare ribs into pieces; blanch and rinse. Soak 50–80 g tofu skin until pliable; cut into strips.",
      "Simmer ribs with ginger and mushrooms in about 1.2 L water for 30 minutes.",
      "Add tofu skin; cook 8–10 more minutes. Season with salt and white pepper.",
    ],
    zh: {
      name: "腐竹排骨湯",
      steps: [
        "排骨約 400 克切件焯水過冷河。腐竹約 50 至 80 克浸軟切段。",
        "排骨加薑和冬菇，加水約 1.2 升煮 30 分鐘。",
        "下腐竹再煮 8 至 10 分鐘，加鹽和白胡椒。",
      ],
    },
  },
  {
    id: "home-bitter-melon-rib-soup",
    name: "Bitter melon spare rib soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Bitter melon", "Spare ribs"],
    optional: ["Ginger", "Salt", "White pepper", "Dried mushrooms"],
    steps: [
      "Halve bitter melon, scrape seeds, and thick-slice. Cut 400 g spare ribs into pieces; blanch and rinse.",
      "Simmer ribs with ginger for 25 minutes in about 1.2 L water.",
      "Add bitter melon (and mushrooms if using); cook 15 minutes. Season with salt and white pepper.",
    ],
    zh: {
      name: "涼瓜排骨湯",
      steps: [
        "涼瓜剖開去瓤厚切。排骨約 400 克切件焯水過冷河。",
        "排骨加薑加水約 1.2 升煮 25 分鐘。",
        "下涼瓜（可加冬菇）再煮 15 分鐘，加鹽和白胡椒。",
      ],
    },
  },
  {
    id: "home-soy-braised-wings",
    name: "Soy-braised chicken wings",
    cuisine: "Chinese",
    time: 40,
    servings: 3,
    need: ["Chicken wings", "Soy sauce", "Sugar"],
    optional: ["Garlic", "Ginger", "Spring onion", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Pat dry 800 g chicken wings. Mix 4 tbsp soy sauce, 2 tbsp sugar, minced garlic/ginger, and a splash of Shaoxing wine if using.",
      "Brown wings in a little oil 4–5 minutes. Pour in marinade plus 1/2 cup water.",
      "Simmer covered 20–25 minutes, turning once, until wings reach 74°C / 165°F and sauce turns glossy. Finish with spring onion and sesame oil.",
    ],
    zh: {
      name: "豉油雞翼",
      steps: [
        "雞翼約 800 克抹乾。四湯匙生抽、兩湯匙糖、蒜薑蓉，可加少許料酒拌勻。",
        "少油將雞翼煎香 4 至 5 分鐘，倒入醬汁和半杯水。",
        "加蓋炆 20 至 25 分鐘至全熟（74°C）汁濃，撒蔥花滴麻油。",
      ],
    },
  },
  {
    id: "home-cabbage-meatball-soup",
    name: "Cabbage pork meatball soup",
    cuisine: "Chinese",
    time: 35,
    servings: 3,
    need: ["Ground pork", "Cabbage", "Eggs"],
    optional: ["Ginger", "Spring onion", "Soy sauce", "Salt", "Cornstarch", "White pepper", "Cooking oil", "Glass noodles", "Cilantro"],
    steps: [
      "Mix 300 g ground pork with 1 egg, minced ginger, 1 tsp soy sauce, cornstarch, and white pepper; shape into small meatballs.",
      "Bring about 1.2 L water to a simmer; gently drop in meatballs and cook 8–10 minutes until pork reaches 74°C / 165°F.",
      "Add shredded cabbage; simmer 5 more minutes. Season with salt; top with spring onion.",
    ],
    zh: {
      name: "白菜貢丸湯",
      steps: [
        "免治豬肉約 300 克加一隻蛋、薑蓉、一茶匙生抽、生粉和白胡椒，搓成小丸。",
        "水約 1.2 升燒開，輕輕下肉丸煮 8 至 10 分鐘至全熟（74°C）。",
        "下椰菜絲再煮 5 分鐘，加鹽，撒蔥花。",
      ],
    },
  },
  {
    id: "home-celery-pork-bone-soup",
    name: "Celery pork bone soup",
    cuisine: "Cantonese",
    time: 50,
    servings: 3,
    need: ["Ginger", "Cabbage", "Spring onion", "Cilantro"],
    optional: ["Cooking oil", "Salt", "White pepper"],
    steps: [
      "Cut 400 g pork chops into pieces; blanch and rinse. Cut 3 celery stalks and 1 carrot into chunks.",
      "Simmer pork with ginger in about 1.3 L water for 30 minutes.",
      "Add celery, carrot, and corn if using; cook 15–18 minutes. Season with salt and white pepper.",
    ],
    zh: {
      name: "西芹豬骨湯",
      steps: [
        "豬扒約 400 克切件焯水過冷河。三條西芹和一條紅蘿蔔切段。",
        "豬加薑加水約 1.3 升煮 30 分鐘。",
        "下西芹、紅蘿蔔（可加玉米）再煮 15 至 18 分鐘，加鹽和白胡椒。",
      ],
    },
  },
  {
    id: "home-silken-clam-soup",
    name: "Silken tofu clam soup",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Clams", "Silken tofu"],
    optional: ["Ginger", "Spring onion", "Salt", "White pepper", "Sesame oil"],
    steps: [
      "Soak and scrub 400 g clams; discard any open ones that do not close. Cube 300 g silken tofu.",
      "Bring about 3 cups water with ginger to a boil; add clams and cover 4–6 minutes until shells open (discard unopened).",
      "Gently add tofu; warm 2 minutes. Season lightly with salt and white pepper; finish with spring onion and sesame oil.",
    ],
    zh: {
      name: "蜆肉豆腐湯",
      steps: [
        "蜆約 400 克浸洗乾淨，不閉口的棄掉。嫩豆腐約 300 克切塊。",
        "薑片加水約三杯燒開，下蜆加蓋 4 至 6 分鐘至開殼（不開棄掉）。",
        "輕輕下豆腐溫 2 分鐘，略加鹽和白胡椒，撒蔥花滴麻油。",
      ],
    },
  },
  {
    id: "home-glass-noodle-brisket-soup",
    name: "Glass noodle beef brisket soup",
    cuisine: "Asian",
    time: 80,
    servings: 3,
    need: ["Beef brisket", "Glass noodles"],
    optional: ["Onion", "Ginger", "Soy sauce", "Spring onion", "Salt", "White pepper", "Tomato", "Sesame oil", "Vinegar", "Shrimp", "Cooking oil", "Eggs"],
    steps: [
      "Cut 500 g beef brisket into chunks; blanch and rinse. Soak glass noodles in warm water until pliable.",
      "Simmer brisket with ginger and onion in about 1.3 L water for 60–70 minutes until tender; season with soy sauce or salt.",
      "Add drained glass noodles for 2–3 minutes until clear and soft. Finish with spring onion and white pepper.",
    ],
    zh: {
      name: "粉絲牛腩湯",
      steps: [
        "牛腩約 500 克切件焯水過冷河。粉絲用溫水浸軟。",
        "牛腩加薑洋蔥加水約 1.3 升炆 60 至 70 分鐘至軟，加生抽或鹽調味。",
        "下瀝乾粉絲煮 2 至 3 分鐘至透，撒蔥花和白胡椒。",
      ],
    },
  },
  {
    id: "home-winter-melon-chicken-soup",
    name: "Winter melon chicken soup",
    cuisine: "Cantonese",
    time: 40,
    servings: 3,
    need: ["Winter melon", "Salmon", "Shrimp", "Eggs"],
    optional: ["Chicken stock", "Salt", "Sugar", "White pepper", "Olive oil", "Sesame oil", "Cornstarch"],
    steps: [
      "Cube 400 g winter melon; cut 400 g chicken thighs into pieces and blanch briefly.",
      "Simmer chicken with ginger and mushrooms in about 1.2 L water for 20 minutes until chicken reaches 74°C / 165°F.",
      "Add winter melon; cook 15 more minutes until soft. Season with salt and white pepper; top with spring onion.",
    ],
    zh: {
      name: "冬瓜雞湯",
      steps: [
        "冬瓜約 400 克切塊；雞脾約 400 克切件略焯。",
        "雞加薑和冬菇加水約 1.2 升煮 20 分鐘至全熟（74°C）。",
        "下冬瓜再煮 15 分鐘至軟，加鹽和白胡椒，撒蔥花。",
      ],
    },
  },
  {
    id: "home-lotus-pork-braise",
    name: "Lotus root braised pork",
    cuisine: "Chinese",
    time: 55,
    servings: 3,
    need: ["Pork chops", "Lotus root", "Soy sauce"],
    optional: ["Ginger", "Garlic", "Sugar", "Shaoxing wine", "Spring onion", "Chicken stock", "Oyster sauce", "Salt", "White pepper", "Cooking oil", "Cornstarch"],
    steps: [
      "Cut 400 g pork chops into chunks; peel and slice 300 g lotus root into thick coins.",
      "Brown pork with ginger/garlic; add 3 tbsp soy sauce, a pinch of sugar, Shaoxing wine if using, and 1 cup water.",
      "Add lotus; simmer covered 30–35 minutes until pork is tender and lotus soft. Reduce sauce; finish with spring onion.",
    ],
    zh: {
      name: "蓮藕炆豬肉",
      steps: [
        "豬扒約 400 克切件；蓮藕約 300 克去皮厚片。",
        "豬加薑蒜炒香，下三湯匙生抽、少許糖、料酒（可用）和一杯水。",
        "下蓮藕加蓋炆 30 至 35 分鐘至軟，收汁撒蔥花。",
      ],
    },
  },
  {
    id: "home-miso-pumpkin-braise",
    name: "Miso braised pumpkin",
    cuisine: "Japanese",
    time: 30,
    servings: 2,
    need: ["Pumpkin", "Miso"],
    optional: ["Sugar", "Soy sauce", "Sesame oil", "Sesame seeds", "Spring onion"],
    steps: [
      "Cube 400 g pumpkin (leave skin on if tender). Soften briefly in a pan with a little oil.",
      "Mix 1.5 tbsp miso with 1 cup water, 1 tsp sugar, and a splash of soy sauce if using; pour over pumpkin.",
      "Simmer covered 15–18 minutes until soft and glaze thickens. Finish with sesame oil, seeds, and spring onion.",
    ],
    zh: {
      name: "味噌炆南瓜",
      steps: [
        "南瓜約 400 克切塊（皮嫩可留）。少油略炒。",
        "一湯匙半味噌加一杯水、一茶匙糖，可加少許生抽，倒入鍋中。",
        "加蓋炆 15 至 18 分鐘至軟汁濃，滴麻油撒芝麻蔥花。",
      ],
    },
  },
  {
    id: "home-doenjang-beef-soup",
    name: "Doenjang beef soup",
    cuisine: "Korean",
    time: 40,
    servings: 3,
    need: ["Beef steak", "Doenjang", "Zucchini"],
    optional: ["Onion", "Garlic", "Tofu", "Spring onion", "Salt"],
    steps: [
      "Slice 250 g beef steak thinly; cube zucchini and tofu if using. Soften onion/garlic in a pot.",
      "Dissolve 2 tbsp doenjang in about 4 cups water; add to pot and bring to a simmer.",
      "Add beef and zucchini (and tofu); cook 8–10 minutes until beef is just cooked. Adjust salt; top with spring onion.",
    ],
    zh: {
      name: "大醬牛肉湯",
      steps: [
        "牛扒約 250 克切薄片；翠玉瓜切塊，可加豆腐。鍋中炒軟洋蔥蒜蓉。",
        "兩湯匙大醬溶於約四杯水，倒入鍋中燒開。",
        "下牛肉和翠玉瓜（可加豆腐）煮 8 至 10 分鐘至剛熟，調鹽撒蔥花。",
      ],
    },
  },
  {
    id: "home-coconut-pumpkin-soup",
    name: "Coconut pumpkin soup",
    cuisine: "Thai",
    time: 30,
    servings: 3,
    need: ["Pumpkin", "Coconut milk"],
    optional: ["Onion", "Garlic", "Lemongrass", "Salt", "Sugar", "Chili oil", "Butter", "Chicken stock", "White pepper"],
    steps: [
      "Cube 450 g pumpkin; chop onion/garlic if using. Soften aromatics 3–4 minutes; add a bruised lemongrass stalk if available.",
      "Add pumpkin and 1 cup water; simmer 15 minutes until soft. Mash lightly.",
      "Stir in 1 cup coconut milk; warm 3–4 minutes. Season with salt and a pinch of sugar; drizzle chili oil if you like.",
    ],
    zh: {
      name: "椰香南瓜湯",
      steps: [
        "南瓜約 450 克切塊；可炒香洋蔥蒜蓉，有香茅可拍鬆同煮。",
        "下南瓜和一杯水煮 15 分鐘至軟，略壓蓉。",
        "加入一杯椰漿溫 3 至 4 分鐘，加鹽和少許糖，可滴辣椒油。",
      ],
    },
  },
  {
    id: "home-ginger-chicken-clear-soup",
    name: "Ginger chicken clear soup",
    cuisine: "Cantonese",
    time: 40,
    servings: 3,
    need: ["Chicken thighs", "Ginger"],
    optional: ["Salt", "Shaoxing wine", "Spring onion", "White pepper", "Dried mushrooms", "Garlic", "Cooking oil", "Shallot", "Chicken stock", "Soy sauce", "Oyster sauce", "Cornstarch"],
    steps: [
      "Cut 500 g chicken thighs into pieces; smash a thick thumb of ginger. Blanch chicken briefly.",
      "Simmer chicken, ginger, and mushrooms if using in about 1.2 L water with a splash of Shaoxing wine for 30 minutes until chicken reaches 74°C / 165°F.",
      "Season with salt and white pepper; finish with spring onion.",
    ],
    zh: {
      name: "薑片雞湯",
      steps: [
        "雞脾約 500 克切件；厚薑拍鬆。雞略焯。",
        "雞、薑，可加冬菇，加水約 1.2 升和少許料酒煮 30 分鐘至全熟（74°C）。",
        "加鹽和白胡椒，撒蔥花。",
      ],
    },
  },
  {
    id: "home-sweet-potato-pork-soup",
    name: "Sweet potato pork soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Sweet potato", "Pork chops"],
    optional: ["Ginger", "Corn", "Salt", "White pepper", "Cooking oil", "Glass noodles", "Cabbage", "Spring onion", "Cilantro"],
    steps: [
      "Peel and chunk 2 sweet potatoes; cut 350 g pork chops into pieces and blanch.",
      "Simmer pork with ginger in about 1.3 L water for 25 minutes.",
      "Add sweet potato and corn if using; cook 15–18 minutes until soft. Season with salt and white pepper.",
    ],
    zh: {
      name: "番薯豬骨湯",
      steps: [
        "兩個番薯去皮切塊；豬扒約 350 克切件焯水。",
        "豬加薑加水約 1.3 升煮 25 分鐘。",
        "下番薯（可加玉米）再煮 15 至 18 分鐘至軟，加鹽和白胡椒。",
      ],
    },
  },
  {
    id: "home-nori-tofu-clear-soup",
    name: "Nori tofu clear soup",
    cuisine: "Japanese",
    time: 15,
    servings: 2,
    need: ["Nori", "Tofu"],
    optional: ["Miso", "Spring onion", "Sesame oil", "Salt", "White pepper", "Chicken stock", "Cooking oil", "Eggs", "Mushroom", "Cabbage", "Cilantro"],
    steps: [
      "Cut 250 g tofu into small cubes; tear 1 sheet nori into strips.",
      "Bring about 3 cups water to a simmer; add tofu 3 minutes. Optional: whisk in 1 tbsp miso off heat.",
      "Add nori for 30 seconds; season lightly with salt/white pepper if not using miso. Finish with spring onion and sesame oil.",
    ],
    zh: {
      name: "紫菜豆腐湯",
      steps: [
        "豆腐約 250 克切小塊；一張紫菜撕絲。",
        "水約三杯燒開，下豆腐煮 3 分鐘；可離火拌入一湯匙味噌。",
        "下紫菜 30 秒；若無味噌略加鹽白胡椒，撒蔥花滴麻油。",
      ],
    },
  },
  {
    id: "home-fermented-tofu-braised-pork",
    name: "Fermented tofu braised pork",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Pork chops", "Fermented tofu"],
    optional: ["Garlic", "Ginger", "Sugar", "Soy sauce", "Spring onion", "Cornstarch", "Silken tofu", "Cooking oil", "Chicken stock", "Oyster sauce", "Sesame oil", "Salt", "Carrots", "Shaoxing wine"],
    steps: [
      "Cut 400 g pork chops into bite-size pieces. Mash 2 cubes fermented tofu with 1 tsp sugar, minced garlic, and a splash of water into a paste.",
      "Brown pork 4–5 minutes; stir in fermented-tofu paste and 1/2 cup water.",
      "Simmer covered 25–30 minutes until pork is tender. Optional: thicken with a little cornstarch slurry; finish with spring onion.",
    ],
    zh: {
      name: "腐乳炆豬肉",
      steps: [
        "豬扒約 400 克切件。兩件腐乳加一茶匙糖、蒜蓉和少許水壓成醬。",
        "豬件炒香 4 至 5 分鐘，下腐乳醬和半杯水。",
        "加蓋炆 25 至 30 分鐘至軟；可勾芡，撒蔥花。",
      ],
    },
  },
  {
    id: "home-black-bean-rib-soup",
    name: "Fermented black bean spare rib soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Fermented black beans", "Orange", "Spare ribs", "Spring onion", "Garlic", "Ginger"],
    optional: ["Cornstarch", "White pepper", "Cooking oil", "Salt", "Sugar", "Soy sauce", "Oyster sauce", "Shaoxing wine", "Sesame oil"],
    steps: [
      "Cut 450 g spare ribs into pieces; blanch and rinse. Rinse 1 tbsp fermented black beans; crush lightly with garlic.",
      "Simmer ribs with ginger in about 1.2 L water for 30 minutes.",
      "Add black beans; cook 10 more minutes. Season carefully with salt (beans are salty) and white pepper; top with spring onion.",
    ],
    zh: {
      name: "豆豉排骨湯",
      steps: [
        "排骨約 450 克切件焯水過冷河。一湯匙豆豉過水，加蒜略壓。",
        "排骨加薑加水約 1.2 升煮 30 分鐘。",
        "下豆豉再煮 10 分鐘；豆豉偏鹹，小心加鹽，撒白胡椒蔥花。",
      ],
    },
  },
  {
    id: "home-onion-beef-clear-soup",
    name: "Onion beef clear soup",
    cuisine: "Chinese",
    time: 35,
    servings: 2,
    need: ["Beef steak", "Onion"],
    optional: ["Baking soda", "Cornstarch", "Cooking oil", "Oyster sauce", "Soy sauce", "Ketchup", "Sugar", "Sesame oil"],
    steps: [
      "Slice 250 g beef steak thinly against the grain; toss with a drop of soy sauce if using. Slice 1 large onion.",
      "Simmer onion and ginger in about 4 cups water for 15 minutes until sweet.",
      "Add beef slices; cook 1–2 minutes until just browned. Season with salt and white pepper; finish with spring onion.",
    ],
    zh: {
      name: "洋蔥牛肉清湯",
      steps: [
        "牛扒約 250 克逆紋切薄，可滴生抽。一個大洋蔥切片。",
        "洋蔥薑片加水約四杯煮 15 分鐘至甜。",
        "下牛肉片煮 1 至 2 分鐘至剛熟，加鹽和白胡椒，撒蔥花。",
      ],
    },
  },
  {
    id: "home-zucchini-pork-soup",
    name: "Zucchini pork soup",
    cuisine: "Chinese",
    time: 30,
    servings: 2,
    need: ["Zucchini", "Ground pork"],
    optional: ["Ginger", "Salt", "White pepper", "Spring onion", "Soy sauce", "Cornstarch", "Cooking oil", "Glass noodles", "Cabbage", "Cilantro"],
    steps: [
      "Mix 200 g ground pork with a pinch of salt, cornstarch, and white pepper; shape small meatballs. Slice 2 zucchini.",
      "Bring about 4 cups water with ginger to a simmer; cook meatballs 8–10 minutes until pork reaches 74°C / 165°F.",
      "Add zucchini; cook 4–5 minutes until tender. Season with salt; top with spring onion.",
    ],
    zh: {
      name: "翠玉瓜肉丸湯",
      steps: [
        "免治豬肉約 200 克加少許鹽、生粉和白胡椒搓小丸。兩條翠玉瓜切片。",
        "薑片加水約四杯燒開，下肉丸煮 8 至 10 分鐘至全熟（74°C）。",
        "下翠玉瓜煮 4 至 5 分鐘至軟，加鹽撒蔥花。",
      ],
    },
  },
  {
    id: "home-corn-chicken-wing-soup",
    name: "Corn chicken wing soup",
    cuisine: "Cantonese",
    time: 40,
    servings: 3,
    need: ["Chicken breast", "Carrots", "Corn", "Eggs", "Cilantro"],
    optional: ["Cornstarch", "Salt", "White pepper", "Sesame oil"],
    steps: [
      "Separate 600 g chicken wings at joints; blanch briefly. Cut 1–2 corn cobs into rounds (or use 1.5 cups kernels).",
      "Simmer wings with ginger, corn, and carrot/mushrooms if using in about 1.3 L water for 30 minutes until wings reach 74°C / 165°F.",
      "Season with salt and white pepper.",
    ],
    zh: {
      name: "玉米雞翼湯",
      steps: [
        "雞翼約 600 克斬件略焯。一至兩條玉米切段（或一杯半玉米粒）。",
        "雞翼加薑、玉米，可加紅蘿蔔或冬菇，加水約 1.3 升煮 30 分鐘至全熟（74°C）。",
        "加鹽和白胡椒調味。",
      ],
    },
  },
]
