import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W5J: Recipe[] = [
  {
    id: "home-potato-salad",
    name: "Potato Salad",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Potato", "Onion", "Bacon", "Spring onion"],
    optional: [],
    steps: [
      "Prep Potato and vegetables; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "醒胃薯仔沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-shrimp-braise",
    name: "Shrimp Braise",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Shrimp", "Napa cabbage", "Cheddar", "Cream"],
    optional: ["Cornstarch"],
    steps: [
      "Cut Shrimp and vegetables into pieces; lightly brown Shrimp in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Shrimp is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "芝士大蝦炆娃娃菜",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-white-fish-congee",
    name: "White Fish Congee",
    cuisine: "Cantonese",
    time: 35,
    servings: 2,
    need: ["Rice", "White fish", "Lettuce", "Ginger", "Spring onion"],
    optional: [],
    steps: [
      "Rinse ½ cup rice; simmer with about 1.2 L water 30–35 minutes, stirring occasionally until creamy.",
      "Add sliced White fish in the last 8–10 minutes until just cooked.",
      "Season with salt, white pepper, and sesame oil; top with spring onion.",
    ],
    zh: {
      name: "生菜魚腩粥",
      steps: [
        "半杯米洗净，加水约 1.2 升煮 30 至 35 分鐘至绵密。",
        "最後 8 至 10 分鐘下切片主料煮熟。",
        "加鹽白胡椒麻油，撒蔥。",
      ],
    },
  },
  {
    id: "home-bell-pepper-stirfry",
    name: "Bell Pepper Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Bell pepper", "Apple", "Eggs"],
    optional: ["Chicken stock", "Oyster sauce", "Cornstarch"],
    steps: [
      "Prep Bell pepper and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Bell pepper and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "青椒蘋果炒雞丁",
      steps: [
        "準備青椒蘋果炒雞丁材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-eggs-steam",
    name: "Eggs Steam",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Eggs", "Spinach", "Spring onion"],
    optional: ["Shaoxing wine"],
    steps: [
      "Arrange Eggs with Spinach on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "花蟹菠菜蒸水蛋",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-lotus-root-stirfry-knorr",
    name: "Lotus Root Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Garlic", "Lotus root", "Dried chili", "Spring onion", "Corn"],
    optional: ["Sesame seeds", "White pepper", "Soy sauce", "Sugar", "Shaoxing wine"],
    steps: [
      "Prep Lotus root and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Lotus root and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "欖菜風沙雞配蓮藕",
      steps: [
        "準備欖菜風沙雞配蓮藕材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-salmon-stirfry",
    name: "Salmon Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Salmon", "Chinese yam", "Okra", "Garlic", "Spring onion"],
    optional: ["Chicken stock", "White pepper", "Paprika"],
    steps: [
      "Prep Salmon and White fish plus Green beans; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Salmon and cook until just cooked.",
      "Add White fish and Green beans, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "秋葵炒三文魚鮮淮山",
      steps: [
        "準備秋葵炒三文魚鮮淮山材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-ground-pork-braise",
    name: "Ground Pork Braise",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Spare ribs", "Daikon", "Garlic", "Ginger", "Shallot", "Spring onion"],
    optional: [],
    steps: [
      "Cut Ground pork and vegetables into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "白蘿蔔炆豬軟骨",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-ground-pork-panfry",
    name: "Ground Pork Panfry",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Pork chops", "Ginger", "Mozzarella"],
    optional: ["Sesame seeds", "Chicken stock", "Sugar", "Soy sauce", "Mirin", "Cornstarch"],
    steps: [
      "Pat Ground pork dry; season with salt and white pepper. Slice Pork chops if using as a side.",
      "Pan-fry in a lightly oiled skillet over medium heat until browned and cooked until cooked through (74°C / 165°F).",
      "Deglaze with a splash of soy sauce or serve with a quick ginger-spring-onion drizzle.",
    ],
    zh: {
      name: "香煎照燒芝麻豬扒",
      steps: [
        "主料抹乾，加鹽白胡椒；配菜切片。",
        "中火少油煎至上色并熟透。",
        "可淋少許生抽或以薑蔥油提味。",
      ],
    },
  },
  {
    id: "home-shrimp-pasta-knorr",
    name: "Shrimp Pasta",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Shrimp", "Pasta", "Tomato", "Garlic", "Shallot", "Thai basil"],
    optional: [],
    steps: [
      "Boil pasta in salted water until al dente; reserve ½ cup pasta water.",
      "Meanwhile sauté garlic/onion and Shrimp in olive oil until just cooked.",
      "Toss pasta with the pan sauce and a splash of pasta water; adjust salt and finish with pepper or cheese if using.",
    ],
    zh: {
      name: "蒜香番茄大蝦煮意粉",
      steps: [
        "意粉盐水煮至 al dente，留半杯麵水。",
        "另鑊用橄欖油炒蒜洋蔥及主料至熟。",
        "拌入意粉和少許麵水調味，可加芝士或黑胡椒。",
      ],
    },
  },
  {
    id: "home-kimchi-braise",
    name: "Kimchi Braise",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Cabbage", "Rice cakes", "Kimchi", "Carrots"],
    optional: [],
    steps: [
      "Cut Kimchi and Rice cakes into pieces; lightly brown Kimchi in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Kimchi is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "泡菜年糕炆雞",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-drunken-chicken-hot-pot",
    name: "Drunken Chicken Hot Pot",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Soy sauce", "Garlic", "Cooking oil", "Onion", "Spring onion", "Oyster sauce", "Ginger", "Salt", "White pepper", "Sugar", "Sesame oil", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "醉雞火鍋",
      steps: [
        "準備醉雞火鍋材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-drunken-chicken-roll",
    name: "Drunken Chicken Roll",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Soy sauce", "Garlic", "Cooking oil", "Onion", "Spring onion", "Oyster sauce", "Ginger", "Salt", "White pepper", "Sugar", "Sesame oil", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "醉雞捲",
      steps: [
        "準備醉雞捲材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-drunken-chicken-with-herbs-hotpot",
    name: "Drunken Chicken with Herbs Hotpot",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chinese yam", "Garlic"],
    optional: ["Soy sauce", "Sesame oil", "Chili oil"],
    steps: [
      "Blanch Chicken thighs briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "藥膳醉雞湯底",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-duck-crystal-wrap",
    name: "Duck Crystal Wrap",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Duck", "Lettuce", "Water chestnuts", "Dried mushrooms", "Pineapple", "Shallot", "Spring onion", "Cilantro", "Ginger", "Mozzarella", "Rice", "Hoisin sauce"],
    optional: ["Oyster sauce", "Chicken stock", "Cornstarch"],
    steps: [
      "Prep Lettuce and Tortilla; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Lettuce and cook until just cooked.",
      "Add Tortilla, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "鴨鬆生菜包",
      steps: [
        "準備鴨鬆生菜包材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-dumplings-with-fine-shrimp-sauce",
    name: "Dumplings with Fine Shrimp Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Rice", "Eggs", "Shrimp paste"],
    optional: ["Sesame oil", "Sugar", "Salt", "Soy sauce"],
    steps: [
      "Prep Shrimp and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蝦醬鹹肉粽",
      steps: [
        "準備蝦醬鹹肉粽材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-easy-omurice-recipe-omelette-wrapped-rice",
    name: "Easy Omurice Recipe Omelette Wrapped Rice",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Onion", "Carrots", "Cooked rice", "Spring onion", "Eggs", "Gochujang"],
    optional: ["Salt"],
    steps: [
      "Prep Eggs and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "簡易蛋包飯食譜",
      steps: [
        "準備簡易蛋包飯食譜材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-egg-in-a-hole-with-xo-sauce",
    name: "Egg in a Hole with Xo Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Bread", "Eggs", "Butter", "XO sauce"],
    optional: [],
    steps: [
      "Prep Eggs and Bread; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Bread, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "XO醬蛋多士",
      steps: [
        "準備XO醬蛋多士材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-enoki-mushroom-pork-rolls-in-teriyaki-sauce",
    name: "Enoki Mushroom Pork Rolls in Teriyaki Sauce",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Enoki", "Chicken wings"],
    optional: [],
    steps: [
      "Prep Ground pork and Mushroom; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add Mushroom, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "燒汁金菇豬肉卷",
      steps: [
        "準備燒汁金菇豬肉卷材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-extra-thick-satay-hot-pot",
    name: "Extra Thick Satay Hot Pot",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Tomato"],
    optional: ["Soy sauce", "Garlic", "Cooking oil", "Onion", "Spring onion", "Oyster sauce", "Ginger", "Salt", "White pepper", "Sugar", "Sesame oil", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Eggs and Tomato; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Tomato, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "特濃沙爹火鍋",
      steps: [
        "準備特濃沙爹火鍋材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-fettuccine-and-beef-in-guilin-chilli-sauce",
    name: "Fettuccine and Beef in Guilin Chilli Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Noodles", "Bell pepper", "Garlic", "Gochujang", "Mozzarella"],
    optional: ["Sesame oil", "Oyster sauce", "Cornstarch", "Sugar"],
    steps: [
      "Prep Beef steak and Noodles; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Noodles, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "辣味牛柳闊條麵",
      steps: [
        "準備辣味牛柳闊條麵材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-vegetables-in-chicken-soup",
    name: "Vegetables in Chicken Soup",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs"],
    optional: ["Chicken stock", "White pepper", "Salt", "Ginger", "Cooking oil", "Soy sauce", "Garlic", "Spring onion", "Sugar", "Sesame oil"],
    steps: [
      "Blanch Chicken thighs briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "蔬菜總匯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-anhydrous-vegetable-pot",
    name: "Anhydrous Vegetable Pot",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Onion", "Carrots", "Lotus root"],
    optional: ["Salt", "White pepper"],
    steps: [
      "Prep Eggs and Tomato; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Tomato, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "無水野菜鍋",
      steps: [
        "準備無水野菜鍋將蔬菜甜味完全帶出的烹調方法材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-artisan-bread-with-sharp-healsio-oven",
    name: "Artisan Bread with Sharp Healsio Oven",
    cuisine: "Chinese",
    time: 40,
    servings: 2,
    need: ["Flour"],
    optional: ["Salt", "Honey"],
    steps: [
      "Heat oven to 200°C. Toss Noodles and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "水波爐裸烤歐式麵包",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-authentic-bolognese-sauce",
    name: "Authentic Bolognese Sauce",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Beef steak", "Onion", "Carrots", "Celery", "Tomato", "Cardamom"],
    optional: ["Tomato paste", "Ketchup"],
    steps: [
      "Boil pasta in salted water until al dente; reserve ½ cup pasta water.",
      "Meanwhile sauté garlic/onion and Tomato in olive oil until just cooked.",
      "Toss pasta with the pan sauce and a splash of pasta water; adjust salt and finish with pepper or cheese if using.",
    ],
    zh: {
      name: "意式番茄肉醬",
      steps: [
        "意粉盐水煮至 al dente，留半杯麵水。",
        "另鑊用橄欖油炒蒜洋蔥及主料至熟。",
        "拌入意粉和少許麵水調味，可加芝士或黑胡椒。",
      ],
    },
  },
  {
    id: "home-avocado-mango-kale-roll",
    name: "Avocado Mango Kale Roll",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Avocado", "Mango", "Carrots", "Cucumber", "Quinoa"],
    optional: [],
    steps: [
      "Prep Avocado and Mango; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Avocado and cook until just cooked.",
      "Add Mango, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "牛油果香芒羽衣甘藍卷",
      steps: [
        "準備牛油果香芒羽衣甘藍卷材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-bake-japanese-sweat-potatoes",
    name: "Bake Japanese Sweat Potatoes",
    cuisine: "Japanese",
    time: 40,
    servings: 2,
    need: ["Potato"],
    optional: ["Garlic", "Cooking oil", "Salt", "Honey", "Soy sauce", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Heat oven to 200°C. Toss Potato and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "烤Donki蕃薯",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-baked-bbq-baby-back-ribs",
    name: "Baked Bbq Baby Back Ribs",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Bell pepper", "Garlic"],
    optional: ["Sugar", "Salt", "White pepper", "Cumin"],
    steps: [
      "Heat oven to 200°C. Toss Eggs and Tomato with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "醬燒豬仔骨",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-baked-camembert-with-honey-pistachio-and-thyme",
    name: "Baked Camembert with Honey Pistachio and Thyme",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Cheddar", "Garlic"],
    optional: ["Honey"],
    steps: [
      "Heat oven to 200°C. Toss Noodles and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "🧀焗金文畢芝士 + 開心果碎碎",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-baked-hazelnut-chocolate-dumpling",
    name: "Baked Hazelnut Chocolate Dumpling",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Flour", "Butter", "Eggs"],
    optional: ["Sugar", "Salt"],
    steps: [
      "Heat oven to 200°C. Toss Eggs and Tomato with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "伯爵茶榛子朱古力角仔",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-balsamic-vinegar-pearls",
    name: "Balsamic Vinegar Pearls",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Tomato"],
    optional: ["Soy sauce", "Garlic", "Cooking oil", "Onion", "Spring onion", "Oyster sauce", "Ginger", "Salt", "White pepper", "Sugar", "Sesame oil", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Eggs and Tomato; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Tomato, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "黑醋珍珠",
      steps: [
        "準備黑醋珍珠材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-ginger-steamed-chicken",
    name: "Ginger Steamed Chicken",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Dried mushrooms", "Ginger", "Spring onion", "Dried chili"],
    optional: ["Sugar", "Salt", "Cornstarch"],
    steps: [
      "Arrange Chicken thighs with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through (poultry/mince to 74°C / 165°F).",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "薑米蒸雞",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟（肉類至 74°C / 165°F）。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-cucumber-with-chicken",
    name: "Cucumber with Chicken",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Cucumber", "Garlic"],
    optional: ["Chili oil", "Sesame oil", "Shaoxing wine", "Sugar", "White pepper", "Cornstarch"],
    steps: [
      "Prep Chicken thighs and Cucumber; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add Cucumber, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "青瓜炒雞柳",
      steps: [
        "準備青瓜炒雞柳材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-rice-cake-in-chicken-and-cabbage-soup",
    name: "Rice Cake in Chicken and Cabbage Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Rice cakes", "Dried mushrooms", "Spring onion", "Ginger", "Mozzarella", "Rice"],
    optional: ["Chicken stock", "Salt", "White pepper", "Olive oil"],
    steps: [
      "Blanch Chicken thighs briefly if it is meat; rinse. Cut Cabbage into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "上湯年糕",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-home-style-rice-cake-with-vegetables-pork",
    name: "Home Style Rice Cake with Vegetables & Pork",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Rice cakes", "Dried mushrooms", "Spring onion", "Ginger", "Garlic"],
    optional: ["Chicken stock", "Salt", "Shaoxing wine", "White pepper", "Cornstarch", "Sugar"],
    steps: [
      "Prep Ground pork and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "素菜肉丝炒年糕",
      steps: [
        "準備素菜肉丝炒年糕材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-monk-fruit-lotus-root-soup",
    name: "Monk Fruit Lotus Root Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Lotus root"],
    optional: [],
    steps: [
      "Blanch Lotus root briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "羅漢果蓮藕湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-stir-fried-crab-with-ginger-and-green-onion-hong",
    name: "Stir-fried Crab with Ginger and Green Onion Hong Kong Style",
    cuisine: "Hong Kong",
    time: 20,
    servings: 2,
    need: ["Spring onion", "Ginger", "Garlic", "Dried chili", "Mozzarella"],
    optional: ["Cornstarch", "Oyster sauce", "Chicken stock"],
    steps: [
      "Prep Tofu and Pak choi; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Tofu and cook until just cooked.",
      "Add Pak choi, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "薑蔥炒蟹",
      steps: [
        "準備薑蔥炒蟹材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-clams-in-thai-basil-sauce",
    name: "Clams in Thai Basil Sauce",
    cuisine: "Thai",
    time: 20,
    servings: 2,
    need: ["Clams", "Thai basil", "Garlic", "Mozzarella"],
    optional: ["Oyster sauce", "Chicken stock", "Cornstarch", "White pepper"],
    steps: [
      "Prep Clams and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Clams and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "九層塔炒蜆",
      steps: [
        "準備九層塔炒蜆材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-chilled-tofu-with-uni-beauty-and-healthy-recipe",
    name: "Chilled Tofu with Uni",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Silken tofu", "Salmon", "Bean sprouts", "Mustard"],
    optional: [],
    steps: [
      "Cook or blanch Tofu and vegetables as needed; cool under cold water.",
      "Mix a dressing of soy sauce, vinegar, sesame oil, and minced garlic.",
      "Toss and chill 10 minutes; garnish with spring onion or sesame seeds.",
    ],
    zh: {
      name: "海膽冷豆腐",
      steps: [
        "材料焯熟过冷河。",
        "用生抽、醋、麻油、蒜蓉调汁。",
        "拌匀冷藏 10 分鐘，可撒蔥或芝麻。",
      ],
    },
  },
  {
    id: "home-star-fruit-with-lean-pork-soup",
    name: "Star Fruit with Lean Pork Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ginger"],
    optional: ["Salt"],
    steps: [
      "Blanch Ground pork briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "楊桃燉瘦肉湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-chrysanthemum-saute-chicken",
    name: "Chrysanthemum Saute Chicken",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs", "Spring onion", "Ginger", "Rice", "Mozzarella"],
    optional: ["Sesame oil", "Chicken stock", "Cornstarch", "White pepper"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "菊花雞絲",
      steps: [
        "準備菊花雞絲材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-seafood-mix-in-xo-sauce",
    name: "Seafood Mix in XO Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Squid", "Onion", "Bell pepper", "Garlic", "XO sauce", "Mozzarella"],
    optional: ["Chicken stock", "Cornstarch"],
    steps: [
      "Prep Eggs and Tomato; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Tomato, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "XO醬炒雙鮮",
      steps: [
        "準備XO醬炒雙鮮材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-butterfly-prawns",
    name: "Butterfly Prawns",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Spring onion", "Garlic", "Eggs", "Rice", "Mozzarella"],
    optional: ["Cornstarch", "Chicken stock", "Salt", "White pepper"],
    steps: [
      "Prep Shrimp and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "鳳尾蝦",
      steps: [
        "準備鳳尾蝦材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-pomelo-shrimp",
    name: "Pomelo Shrimp",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Thai basil", "Dried chili", "Garlic", "Lime", "Mozzarella"],
    optional: ["Shaoxing wine", "Sugar", "Fish sauce"],
    steps: [
      "Prep Shrimp and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "柚子蝦球",
      steps: [
        "準備柚子蝦球材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-basic-pot-stickers",
    name: "Basic Pot Stickers",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Ground pork", "Flour"],
    optional: ["Shaoxing wine", "Sesame oil", "Cornstarch", "Salt", "White pepper"],
    steps: [
      "Prep Ground pork and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "韭菜豬肉鍋貼",
      steps: [
        "準備韭菜豬肉鍋貼材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-taiwanese-seafood-congee",
    name: "Taiwanese Seafood Congee",
    cuisine: "Taiwanese",
    time: 35,
    servings: 2,
    need: ["Oats", "Shrimp", "Gai lan", "Beans"],
    optional: ["Shaoxing wine", "White pepper", "Salt"],
    steps: [
      "Rinse ½ cup rice; simmer with about 1.2 L water 30–35 minutes, stirring occasionally until creamy.",
      "Add sliced Rice in the last 8–10 minutes until just cooked.",
      "Season with salt, white pepper, and sesame oil; top with spring onion.",
    ],
    zh: {
      name: "台式海鮮燕麥粥",
      steps: [
        "半杯米洗净，加水约 1.2 升煮 30 至 35 分鐘至绵密。",
        "最後 8 至 10 分鐘下切片主料煮熟。",
        "加鹽白胡椒麻油，撒蔥。",
      ],
    },
  },
  {
    id: "home-cordyceps-fig-soup",
    name: "Cordyceps Fig Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Spare ribs", "Ginger", "Mozzarella"],
    optional: ["Salt"],
    steps: [
      "Blanch Tofu briefly if it is meat; rinse. Cut Mushroom into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "蟲草花無花果湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-ginseng-gorgon-ribs-soup",
    name: "Ginseng Gorgon Ribs Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Spare ribs", "Chinese yam", "Ginger", "Mozzarella"],
    optional: ["Salt"],
    steps: [
      "Blanch Ground pork briefly if it is meat; rinse. Cut Spare ribs into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "花旗參芡實排骨湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-ginseng-lingzhi-lean-pork-soup",
    name: "Ginseng Lingzhi Lean Pork Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ginger", "Mozzarella"],
    optional: ["Salt"],
    steps: [
      "Blanch Ground pork briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "花旗參靈芝瘦肉湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-cordyceps-sweet-corn-soup",
    name: "Cordyceps Sweet Corn Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Corn", "Spare ribs", "Mozzarella"],
    optional: ["Salt"],
    steps: [
      "Blanch Corn briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "滋肺蟲草花玉米脊骨湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
]
