import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W4B: Recipe[] = [
  {
    id: "home-winter-melon-stirfry",
    name: "Winter melon stir-fry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Winter melon", "Garlic"],
    optional: ["Dried mushrooms", "Oyster sauce", "Salt", "Cornstarch", "Spring onion", "Shrimp", "Eggs", "Chicken stock", "Sugar", "White pepper", "Olive oil", "Sesame oil"],
    steps: [
      "Peel and thin-slice 400 g winter melon; soak and slice dried mushrooms if using.",
      "Stir-fry garlic until fragrant; add winter melon and mushrooms. Cook 6–8 minutes, adding a splash of water if dry.",
      "Season with oyster sauce or salt; optional cornstarch slurry to gloss. Finish with spring onion.",
    ],
    zh: {
      name: "清炒冬瓜",
      steps: [
        "冬瓜約 400 克去皮薄片；乾冬菇可浸軟切片。",
        "爆香蒜蓉，下冬瓜和冬菇炒 6 至 8 分鐘，乾可加水少許。",
        "加蠔油或鹽調味；可勾芡，撒蔥花。",
      ],
    },
  },
  {
    id: "home-pumpkin-rice",
    name: "Pumpkin rice",
    cuisine: "Chinese",
    time: 40,
    servings: 3,
    need: ["Pumpkin", "Rice"],
    optional: ["Chinese sausage", "Salt", "Spring onion", "Dried mushrooms"],
    steps: [
      "Cube 300 g pumpkin; rinse 1.5 cups rice. Slice Chinese sausage or soak mushrooms if using.",
      "Combine rice, pumpkin, sausage/mushrooms, and a pinch of salt with water to the usual rice line in a pot or cooker.",
      "Cook as for steamed rice (about 25–30 minutes). Fluff and top with spring onion.",
    ],
    zh: {
      name: "南瓜飯",
      steps: [
        "南瓜約 300 克切塊；米約一杯半洗净。可切臘腸或浸冬菇。",
        "米、南瓜、臘腸或冬菇加少許鹽，按平常水量下煲或飯鍋。",
        "蒸煮約 25 至 30 分鐘至熟，拌匀撒蔥花。",
      ],
    },
  },
  {
    id: "home-eggplant-pumpkin-stir",
    name: "Eggplant pumpkin stir-fry",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Eggplant", "Pumpkin"],
    optional: ["Garlic", "Soy sauce", "Sugar", "Salt", "Chili oil", "Spring onion"],
    steps: [
      "Cube 1 eggplant and 300 g pumpkin. Soften pumpkin first with a splash of water, covered 6–8 minutes.",
      "Add eggplant and garlic; cook 6–8 more minutes until both are tender, stirring often.",
      "Season with soy sauce, pinch of sugar or salt; optional chili oil and spring onion.",
    ],
    zh: {
      name: "茄子炒南瓜",
      steps: [
        "一條茄子和南瓜約 300 克切塊。南瓜先加水加蓋焖 6 至 8 分鐘。",
        "下茄子和蒜蓉再炒 6 至 8 分鐘至軟，常翻動。",
        "加生抽、少許糖或鹽，可滴辣椒油撒蔥花。",
      ],
    },
  },
  {
    id: "home-lotus-root-stirfry",
    name: "Stir-fried lotus root",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Lotus root", "Mushroom", "Bell pepper", "Ginger", "Garlic", "Spring onion"],
    optional: ["Chicken stock", "Oyster sauce", "Salt", "Sugar", "White pepper", "Cooking oil", "Shaoxing wine", "Cornstarch"],
    steps: [
      "Peel and thin-slice 300 g lotus root; soak in water briefly then drain. Julienne 1 carrot.",
      "Stir-fry garlic if using, then lotus and carrot on high heat 4–5 minutes until crisp-tender.",
      "Season with soy sauce, a splash of vinegar, pinch of sugar, and sesame oil.",
    ],
    zh: {
      name: "清炒蓮藕",
      steps: [
        "蓮藕約 300 克去皮薄片，略泡水瀝乾。一條紅蘿蔔切絲。",
        "可爆香蒜蓉，大火炒蓮藕紅蘿蔔 4 至 5 分鐘至爽脆。",
        "加生抽、少許醋、少許糖和麻油調味。",
      ],
    },
  },
  {
    id: "home-bitter-melon-egg",
    name: "Bitter melon with egg",
    cuisine: "Cantonese",
    time: 18,
    servings: 2,
    need: ["Beef steak", "Bitter melon", "Garlic", "Beans"],
    optional: ["Salt", "Baking soda", "Cooking oil", "Shaoxing wine", "Sugar", "Soy sauce", "Sesame oil", "White pepper", "Cornstarch", "Oyster sauce"],
    steps: [
      "Halve bitter melon, scrape seeds, thin-slice; toss with salt 5 minutes, rinse and pat dry. Beat 3 eggs.",
      "Stir-fry bitter melon with garlic 2–3 minutes until slightly softened; push aside.",
      "Pour in eggs; scramble gently until just set, then toss with melon. Season with soy sauce or salt and white pepper.",
    ],
    zh: {
      name: "涼瓜炒蛋",
      steps: [
        "涼瓜剖開去瓤薄片，撒鹽 5 分鐘沖淨抹乾。打散三隻蛋。",
        "蒜蓉炒涼瓜 2 至 3 分鐘至略軟，撥到一邊。",
        "倒入蛋液慢炒至凝固，再與涼瓜拌匀，加生抽或鹽和白胡椒。",
      ],
    },
  },
  {
    id: "home-pumpkin-garlic-stir",
    name: "Garlic pumpkin stir-fry",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Pumpkin", "Garlic"],
    optional: ["Soy sauce", "Sugar", "Salt", "Sesame oil", "Spring onion"],
    steps: [
      "Cube 400 g pumpkin into 2 cm pieces. Mince 3 garlic cloves.",
      "Stir-fry garlic briefly; add pumpkin and a splash of water. Cover 8–10 minutes until soft, stirring once.",
      "Season with soy sauce, a pinch of sugar or salt; finish with sesame oil and spring onion.",
    ],
    zh: {
      name: "蒜香炒南瓜",
      steps: [
        "南瓜約 400 克切 2 厘米塊。三瓣蒜切蓉。",
        "略爆蒜蓉，下南瓜和少許水，加蓋 8 至 10 分鐘至軟，中途拌一次。",
        "加生抽、少許糖或鹽，滴麻油撒蔥花。",
      ],
    },
  },
  {
    id: "home-pak-choi-dried-mushroom",
    name: "Pak choi with dried mushrooms",
    cuisine: "Cantonese",
    time: 18,
    servings: 2,
    need: ["Mushroom"],
    optional: [],
    steps: [
      "Soak 6–8 dried mushrooms until soft; squeeze and slice. Cut pak choi into lengths.",
      "Stir-fry garlic if using; add mushrooms 2 minutes, then pak choi with a splash of water 2–3 minutes.",
      "Season with oyster sauce or soy sauce and a pinch of sugar; optional light slurry.",
    ],
    zh: {
      name: "冬菇炒白菜",
      steps: [
        "乾冬菇 6 至 8 朵浸軟擠乾切片。白菜切段。",
        "可爆香蒜蓉，炒冬菇 2 分鐘，下白菜加水炒 2 至 3 分鐘。",
        "加蠔油或生抽和少許糖；可薄芡。",
      ],
    },
  },
  {
    id: "home-green-bean-pork",
    name: "Green beans with minced pork",
    cuisine: "Sichuan",
    time: 25,
    servings: 2,
    need: ["Ground pork", "Ginger", "Green beans", "Garlic", "Bell pepper", "Dried chili"],
    optional: ["Shaoxing wine", "Soy sauce", "Sugar", "Cornstarch", "Cooking oil", "Sesame oil", "White pepper", "Salt"],
    steps: [
      "Trim 300 g green beans; cut into 5 cm lengths. Mix 200 g ground pork with a little cornstarch and soy sauce.",
      "Stir-fry pork until browned and cooked through (74°C / 165°F); remove. Blister beans in the pan 5–6 minutes.",
      "Return pork with garlic, soy sauce, chili oil, and a pinch of sugar; toss 1 minute.",
    ],
    zh: {
      name: "肉碎炒四季豆",
      steps: [
        "四季豆約 300 克切 5 厘米段。免治豬肉約 200 克加少許生粉生抽。",
        "炒香豬肉至全熟（74°C）盛起；四季豆乾煸 5 至 6 分鐘。",
        "回肉碎加蒜蓉、生抽、辣椒油和少許糖，快炒 1 分鐘。",
      ],
    },
  },
  {
    id: "home-winter-melon-pork-stir",
    name: "Winter melon pork stir-fry",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Spare ribs", "Ginger", "Winter melon", "Cilantro"],
    optional: ["Salt", "White pepper", "Soy sauce"],
    steps: [
      "Slice 250 g pork chops thinly; toss with soy sauce and cornstarch. Cube 350 g winter melon.",
      "Stir-fry pork 2–3 minutes until just cooked; remove. Soften garlic/ginger; add winter melon with a splash of water, cover 6–8 minutes.",
      "Return pork with oyster sauce; toss 30 seconds and serve.",
    ],
    zh: {
      name: "冬瓜炒豬肉",
      steps: [
        "豬扒約 250 克切薄片，加生抽生粉。冬瓜約 350 克切塊。",
        "炒豬肉 2 至 3 分鐘盛起；爆香蒜薑，下冬瓜加水加蓋 6 至 8 分鐘。",
        "回豬肉加蠔油快炒 30 秒上碟。",
      ],
    },
  },
  {
    id: "home-lotus-carrot-stirfry",
    name: "Lotus root and carrot stir-fry",
    cuisine: "Chinese",
    time: 18,
    servings: 2,
    need: ["Lotus root", "Mushroom", "Bell pepper", "Ginger", "Garlic", "Spring onion"],
    optional: ["Chicken stock", "Oyster sauce", "Salt", "Sugar", "White pepper", "Cooking oil", "Shaoxing wine", "Cornstarch"],
    steps: [
      "Thin-slice 250 g lotus root; julienne 1 carrot and 1 bell pepper.",
      "Stir-fry garlic if using; add vegetables on high heat 4–5 minutes until crisp-tender.",
      "Season with soy sauce, pinch of sugar, and sesame oil.",
    ],
    zh: {
      name: "蓮藕紅蘿蔔炒彩椒",
      steps: [
        "蓮藕約 250 克薄片；一條紅蘿蔔和一個燈籠椒切絲。",
        "可爆香蒜蓉，大火快炒蔬菜 4 至 5 分鐘至爽。",
        "加生抽、少許糖和麻油調味。",
      ],
    },
  },
  {
    id: "home-bitter-melon-pork",
    name: "Bitter melon pork stir-fry",
    cuisine: "Cantonese",
    time: 22,
    servings: 2,
    need: ["Pork chops", "Ginger", "Bitter melon"],
    optional: ["Salt"],
    steps: [
      "Slice 250 g pork thinly; toss with soy sauce and cornstarch. Seed and slice bitter melon; blanch 1 minute, drain.",
      "Stir-fry pork until just cooked; remove. Soften garlic and rinsed black beans if using; toss bitter melon 2 minutes.",
      "Return pork with a pinch of sugar and splash of water; toss 30 seconds.",
    ],
    zh: {
      name: "涼瓜炒豬肉",
      steps: [
        "豬扒約 250 克切薄，加生抽生粉。涼瓜去瓤切片焯 1 分鐘瀝乾。",
        "炒豬肉至剛熟盛起；爆香蒜蓉和洗淨豆豉（可用），炒涼瓜 2 分鐘。",
        "回豬肉加少許糖和水快炒 30 秒。",
      ],
    },
  },
  {
    id: "home-water-spinach-beef",
    name: "Water spinach beef",
    cuisine: "Cantonese",
    time: 18,
    servings: 2,
    need: ["Water spinach"],
    optional: [],
    steps: [
      "Slice 200 g beef steak thinly; toss with soy sauce and cornstarch. Wash 250 g water spinach.",
      "Stir-fry beef on high heat 1–2 minutes until just browned; remove. Soften garlic; toss water spinach 1 minute.",
      "Return beef with oyster sauce and a pinch of sugar; toss 20 seconds.",
    ],
    zh: {
      name: "通菜炒牛肉",
      steps: [
        "牛扒約 200 克切薄，加生抽生粉。通菜約 250 克洗净。",
        "大火快炒牛肉 1 至 2 分鐘盛起；爆香蒜蓉炒通菜 1 分鐘。",
        "回牛肉加蠔油和少許糖，快炒 20 秒。",
      ],
    },
  },
  {
    id: "home-pineapple-sweet-sour-veg",
    name: "Pineapple sweet and sour vegetables",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Pineapple", "Bell pepper", "Onion"],
    optional: ["Carrots", "Cucumber", "Ketchup", "Vinegar", "Sugar", "Salt", "Cornstarch", "Cooking oil", "Ginger", "Soy sauce"],
    steps: [
      "Cube 1 cup pineapple; chunk bell pepper, onion, and carrot/cucumber if using.",
      "Stir-fry vegetables 3–4 minutes until crisp-tender; add pineapple for 1 minute.",
      "Mix 2 tbsp ketchup, 1 tbsp vinegar, 1 tsp sugar, and a splash of water; pour in and toss. Optional cornstarch slurry to thicken.",
    ],
    zh: {
      name: "菠蘿咕噜蔬菜",
      steps: [
        "菠蘿約一杯切塊；燈籠椒、洋蔥切件，可加紅蘿蔔青瓜。",
        "炒蔬菜 3 至 4 分鐘至爽，下菠蘿 1 分鐘。",
        "兩湯匙茄汁、一湯匙醋、一茶匙糖和少許水倒入快炒；可勾芡。",
      ],
    },
  },
  {
    id: "home-tofu-skin-veg-stir",
    name: "Tofu skin vegetable stir-fry",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Tofu skin", "Pak choi"],
    optional: ["Garlic", "Carrots", "Soy sauce", "Sesame oil", "Salt"],
    steps: [
      "Soak 80 g tofu skin until soft; cut into strips. Chop pak choi and carrot if using.",
      "Stir-fry garlic; add carrot then pak choi 2–3 minutes. Add tofu skin and a splash of water.",
      "Season with soy sauce or salt; finish with sesame oil.",
    ],
    zh: {
      name: "腐皮炒蔬菜",
      steps: [
        "腐皮約 80 克浸軟切絲。白菜切段，可加紅蘿蔔。",
        "爆香蒜蓉，先炒紅蘿蔔再下白菜 2 至 3 分鐘，下腐皮和少許水。",
        "加生抽或鹽，滴麻油。",
      ],
    },
  },
  {
    id: "home-dried-mushroom-greens",
    name: "Dried mushroom greens",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Dried mushrooms", "Choi sum"],
    optional: ["Garlic", "Oyster sauce", "Soy sauce", "Sugar", "Cornstarch", "Salt"],
    steps: [
      "Soak 8 dried mushrooms until soft; squeeze and slice. Cut choi sum into lengths.",
      "Stir-fry garlic; add mushrooms 2 minutes, then choi sum with a splash of water 2–3 minutes.",
      "Season with oyster sauce or soy sauce and a pinch of sugar; optional light slurry.",
    ],
    zh: {
      name: "冬菇菜心",
      steps: [
        "乾冬菇 8 朵浸軟擠乾切片。菜心切段。",
        "爆香蒜蓉，炒冬菇 2 分鐘，下菜心加水炒 2 至 3 分鐘。",
        "加蠔油或生抽和少許糖；可薄芡。",
      ],
    },
  },
  {
    id: "home-sesame-green-beans",
    name: "Sesame green beans",
    cuisine: "Japanese",
    time: 15,
    servings: 2,
    need: ["Green beans", "Sesame seeds"],
    optional: ["Soy sauce", "Sesame oil", "Sugar", "Salt", "Garlic", "Cooking oil", "Shaoxing wine", "Oyster sauce", "Cornstarch"],
    steps: [
      "Trim 300 g green beans; boil or steam 4–5 minutes until bright and tender-crisp; drain and cool slightly.",
      "Toast 1 tbsp sesame seeds; crush lightly. Mix with 1 tbsp soy sauce, 1/2 tsp sugar, and sesame oil if using.",
      "Toss beans in the sesame dressing; serve warm or room temperature.",
    ],
    zh: {
      name: "芝麻四季豆",
      steps: [
        "四季豆約 300 克切去頭尾，焯或蒸 4 至 5 分鐘至爽綠，瀝乾稍涼。",
        "一湯匙芝麻略炒壓碎，加一湯匙生抽、半茶匙糖，可加麻油。",
        "拌匀四季豆，可熱食或涼食。",
      ],
    },
  },
  {
    id: "home-thai-basil-green-beans",
    name: "Thai basil green beans",
    cuisine: "Thai",
    time: 18,
    servings: 2,
    need: ["Green beans", "Thai basil"],
    optional: ["Garlic", "Soy sauce", "Sugar", "Chili oil", "Onion", "Cooking oil", "Shaoxing wine", "Oyster sauce", "Salt", "Cornstarch"],
    steps: [
      "Trim 300 g green beans into 5 cm pieces. Pick a handful of Thai basil leaves.",
      "Stir-fry garlic and onion if using; add beans with a splash of water 5–6 minutes until tender-crisp.",
      "Season with soy sauce, pinch of sugar, and chili oil; toss in Thai basil off heat.",
    ],
    zh: {
      name: "九層塔四季豆",
      steps: [
        "四季豆約 300 克切 5 厘米段。摘一把九層塔葉。",
        "可炒香蒜蓉洋蔥，下四季豆加水炒 5 至 6 分鐘至爽。",
        "加生抽、少許糖和辣椒油，離火拌入九層塔。",
      ],
    },
  },
  {
    id: "home-lemongrass-veg-stir",
    name: "Lemongrass vegetable stir-fry",
    cuisine: "Vietnamese",
    time: 18,
    servings: 2,
    need: ["Lemongrass", "Zucchini", "Bell pepper"],
    optional: ["Garlic", "Onion", "Soy sauce", "Sugar", "Salt", "Chili oil"],
    steps: [
      "Mince the tender white part of 2 lemongrass stalks. Slice zucchini and bell pepper; slice onion if using.",
      "Stir-fry lemongrass and garlic until fragrant 30–40 seconds; add vegetables 4–5 minutes.",
      "Season with soy sauce, pinch of sugar or salt; optional chili oil.",
    ],
    zh: {
      name: "香茅炒時蔬",
      steps: [
        "兩支香茅取嫩白部切蓉。翠玉瓜和燈籠椒切片，可加洋蔥。",
        "爆香香茅蒜蓉約 30 至 40 秒，下蔬菜炒 4 至 5 分鐘。",
        "加生抽、少許糖或鹽，可滴辣椒油。",
      ],
    },
  },
  {
    id: "home-peanut-cabbage-salad",
    name: "Peanut cabbage salad",
    cuisine: "Asian",
    time: 15,
    servings: 2,
    need: ["Cabbage", "Peanuts"],
    optional: ["Carrots", "Cucumber", "Soy sauce", "Vinegar", "Sugar", "Sesame oil", "Salt"],
    steps: [
      "Shred 1/4 cabbage and carrot/cucumber if using. Roughly crush 1/3 cup roasted peanuts.",
      "Mix 1 tbsp soy sauce, 1 tbsp vinegar, 1 tsp sugar, and sesame oil into a dressing.",
      "Toss vegetables with dressing and peanuts just before serving.",
    ],
    zh: {
      name: "花生拌椰菜",
      steps: [
        "四分一椰菜切絲，可加紅蘿蔔青瓜。三分一杯花生略壓碎。",
        "一湯匙生抽、一湯匙醋、一茶匙糖和麻油拌成汁。",
        "上桌前將蔬菜、醬汁和花生拌匀。",
      ],
    },
  },  {
    id: "home-winter-melon-shrimp",
    name: "Winter melon shrimp",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Winter melon", "Shrimp"],
    optional: ["Garlic", "Ginger", "Salt", "Cornstarch", "White pepper", "Spring onion", "Eggs", "Chicken stock", "Sugar", "Olive oil", "Sesame oil"],
    steps: [
      "Cube 350 g winter melon; peel and devein 200 g shrimp, toss with cornstarch and white pepper.",
      "Stir-fry shrimp 1–2 minutes until pink; remove. Soften garlic/ginger; add winter melon with splash of water, cover 6–8 minutes.",
      "Return shrimp; toss 30 seconds. Season with salt; finish with spring onion.",
    ],
    zh: {
      name: "冬瓜炒蝦仁",
      steps: [
        "冬瓜約 350 克切塊；蝦約 200 克去殼腸，加生粉白胡椒。",
        "炒蝦 1 至 2 分鐘至變色盛起；爆香蒜薑，下冬瓜加水加蓋 6 至 8 分鐘。",
        "回蝦快炒 30 秒，加鹽撒蔥花。",
      ],
    },
  },
  {
    id: "home-lotus-beef-stir",
    name: "Lotus root beef stir-fry",
    cuisine: "Chinese",
    time: 22,
    servings: 2,
    need: ["Lotus root", "Mushroom", "Bell pepper", "Ginger", "Garlic", "Spring onion"],
    optional: ["Chicken stock", "Oyster sauce", "Salt", "Sugar", "White pepper", "Cooking oil", "Shaoxing wine", "Cornstarch"],
    steps: [
      "Slice 200 g beef thinly; toss with soy sauce and cornstarch. Thin-slice 250 g lotus root; soak briefly and drain.",
      "Stir-fry beef 1–2 minutes until just browned; remove. Stir-fry lotus 3–4 minutes until crisp-tender.",
      "Return beef with oyster sauce and a pinch of sugar; toss 30 seconds.",
    ],
    zh: {
      name: "蓮藕炒牛肉",
      steps: [
        "牛扒約 200 克切薄，加生抽生粉。蓮藕約 250 克薄片略泡瀝乾。",
        "炒牛肉 1 至 2 分鐘盛起；炒蓮藕 3 至 4 分鐘至爽。",
        "回牛肉加蠔油和少許糖快炒 30 秒。",
      ],
    },
  },
  {
    id: "home-bitter-melon-tofu",
    name: "Bitter melon tofu",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Bitter melon", "Tofu"],
    optional: ["Garlic", "Fermented black beans", "Soy sauce", "Sugar", "Salt", "Beef steak", "Baking soda", "Cooking oil", "Beans", "Shaoxing wine", "Sesame oil", "White pepper", "Cornstarch", "Oyster sauce"],
    steps: [
      "Seed and slice bitter melon; blanch 1 minute. Cube 300 g tofu; pan-sear until lightly golden.",
      "Soft garlic and rinsed black beans if using; toss bitter melon 2 minutes.",
      "Add tofu with soy sauce and a pinch of sugar; gently toss 1 minute.",
    ],
    zh: {
      name: "涼瓜豆腐",
      steps: [
        "涼瓜去瓤切片焯 1 分鐘。豆腐約 300 克切塊略煎至微金。",
        "爆香蒜蓉和洗淨豆豉（可用），炒涼瓜 2 分鐘。",
        "下豆腐加生抽和少許糖，輕輕拌 1 分鐘。",
      ],
    },
  },
  {
    id: "home-water-spinach-chili-garlic",
    name: "Chili garlic water spinach",
    cuisine: "Sichuan",
    time: 12,
    servings: 2,
    need: ["Water spinach", "Garlic", "Chili oil"],
    optional: ["Salt", "Soy sauce", "Sesame oil"],
    steps: [
      "Wash 300 g water spinach; mince 4 garlic cloves.",
      "Heat oil; fry garlic 15 seconds, then chili oil until fragrant.",
      "Add water spinach; toss 1–2 minutes until wilted. Season with salt or soy sauce; optional sesame oil.",
    ],
    zh: {
      name: "椒蒜通菜",
      steps: [
        "通菜約 300 克洗净；四瓣蒜切蓉。",
        "熱油爆蒜 15 秒，再下辣椒油炒香。",
        "下通菜快炒 1 至 2 分鐘至軟，加鹽或生抽，可滴麻油。",
      ],
    },
  },
  {
    id: "home-green-bean-black-bean",
    name: "Green beans with black bean sauce",
    cuisine: "Cantonese",
    time: 18,
    servings: 2,
    need: ["Green beans", "Onion", "Garlic", "Pork chops"],
    optional: ["White pepper", "Cooking oil", "Shaoxing wine", "Soy sauce", "Oyster sauce", "Sugar", "Salt", "Cornstarch"],
    steps: [
      "Trim 300 g green beans; cut into 5 cm pieces. Rinse 1 tbsp fermented black beans; crush with garlic.",
      "Stir-fry beans on medium-high 5–6 minutes until blistered; add a splash of water if needed.",
      "Add black-bean garlic paste, soy sauce, and a pinch of sugar; toss 1 minute. Optional chili oil.",
    ],
    zh: {
      name: "豆豉四季豆",
      steps: [
        "四季豆約 300 克切 5 厘米段。一湯匙豆豉過水，加蒜壓蓉。",
        "中大火炒四季豆 5 至 6 分鐘至起皺，乾可加水。",
        "下豆豉蒜蓉、生抽和少許糖快炒 1 分鐘，可滴辣椒油。",
      ],
    },
  },
  {
    id: "home-zucchini-pork-stir",
    name: "Zucchini pork stir-fry",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Zucchini", "Pork chops"],
    optional: ["Garlic", "Soy sauce", "Oyster sauce", "Cornstarch", "Salt"],
    steps: [
      "Slice 250 g pork thinly; toss with soy sauce and cornstarch. Slice 2 zucchini into half-moons.",
      "Stir-fry pork until just cooked; remove. Soften garlic; toss zucchini 3–4 minutes.",
      "Return pork with oyster sauce; toss 30 seconds.",
    ],
    zh: {
      name: "翠玉瓜炒豬肉",
      steps: [
        "豬扒約 250 克切薄，加生抽生粉。兩條翠玉瓜切半圓片。",
        "炒豬肉至剛熟盛起；爆香蒜蓉炒翠玉瓜 3 至 4 分鐘。",
        "回豬肉加蠔油快炒 30 秒。",
      ],
    },
  },
  {
    id: "home-sweet-potato-stirfry",
    name: "Sweet potato stir-fry",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Sweet potato", "Bell pepper"],
    optional: ["Onion", "Garlic", "Soy sauce", "Sugar", "Salt", "Sesame oil"],
    steps: [
      "Peel and thin-slice 1 large sweet potato; slice bell pepper and onion if using.",
      "Stir-fry sweet potato with a splash of water, covered 6–8 minutes until softening; add peppers and onion.",
      "Cook uncovered 3–4 minutes; season with soy sauce, pinch of sugar, and sesame oil.",
    ],
    zh: {
      name: "清炒番薯",
      steps: [
        "一個大番薯去皮薄片；燈籠椒切片，可加洋蔥。",
        "番薯加水加蓋炒 6 至 8 分鐘至軟，下椒和洋蔥。",
        "開蓋再炒 3 至 4 分鐘，加生抽、少許糖和麻油。",
      ],
    },
  },
  {
    id: "home-corn-carrot-stirfry",
    name: "Corn and carrot stir-fry",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Corn", "Carrots"],
    optional: ["Butter", "Salt", "Sugar", "Spring onion", "White pepper"],
    steps: [
      "Use 1.5 cups corn kernels; dice 1 carrot small.",
      "Melt butter or heat oil; stir-fry carrot 3 minutes, then corn 3–4 minutes until hot.",
      "Season with salt, pinch of sugar, and white pepper; finish with spring onion.",
    ],
    zh: {
      name: "玉米炒紅蘿蔔",
      steps: [
        "玉米粒約一杯半；一條紅蘿蔔切小粒。",
        "牛油或油先炒紅蘿蔔 3 分鐘，下玉米再 3 至 4 分鐘至熱。",
        "加鹽、少許糖和白胡椒，撒蔥花。",
      ],
    },
  },
  {
    id: "home-cauliflower-sesame",
    name: "Sesame cauliflower stir-fry",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Cauliflower", "Sesame seeds"],
    optional: ["Garlic", "Soy sauce", "Sesame oil", "Salt", "Sugar"],
    steps: [
      "Cut 400 g cauliflower into small florets. Toast 1 tbsp sesame seeds; set aside.",
      "Stir-fry garlic if using; add cauliflower with a splash of water, cover 6–8 minutes until tender-crisp.",
      "Season with soy sauce, pinch of sugar or salt, sesame oil, and toasted sesame seeds.",
    ],
    zh: {
      name: "芝麻炒椰菜花",
      steps: [
        "椰菜花約 400 克切小朵。一湯匙芝麻略炒盛起。",
        "可爆香蒜蓉，下椰菜花加水加蓋 6 至 8 分鐘至爽軟。",
        "加生抽、少許糖或鹽、麻油和炒香芝麻。",
      ],
    },
  },
  {
    id: "home-spinach-peanut-toss",
    name: "Spinach peanut toss",
    cuisine: "Asian",
    time: 12,
    servings: 2,
    need: ["Spinach", "Peanuts"],
    optional: ["Garlic", "Soy sauce", "Sesame oil", "Salt", "Vinegar"],
    steps: [
      "Blanch 300 g spinach 30–45 seconds; squeeze dry and chop. Crush 1/4 cup peanuts.",
      "Mix soy sauce, sesame oil, optional vinegar and minced garlic into a light dressing.",
      "Toss spinach with dressing and peanuts; serve cool or room temperature.",
    ],
    zh: {
      name: "花生拌菠菜",
      steps: [
        "菠菜約 300 克焯 30 至 45 秒，擠乾切段。四分一杯花生壓碎。",
        "生抽麻油，可加醋和蒜蓉拌成汁。",
        "菠菜、醬汁和花生拌匀，涼食。",
      ],
    },
  },
]
