import type { Recipe } from "@/lib/recipes"

/**
 * Cuisine expansion w6cd — title-matched exclusive sources only.
 * Materials (groups/amounts) synced from each dish sourceUrl.
 */
export const MORE_W6CD: Recipe[] = [
  {
    id: "home-katsudon",
    name: "Katsudon",
    cuisine: "Japanese",
    time: 40,
    servings: 2,
    sourceUrl: "https://thewoksoflife.com/katsudon/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Salt", role: "staple", group: "main" },
      { name: "Flour", role: "staple", group: "main", note: "for dusting" },
      { name: "Eggs", role: "core", group: "main", amount: 1 },
      { name: "Cooking oil", role: "staple", group: "main", note: "for frying" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 1, unit: "cup" },
      { name: "Sugar", role: "staple", group: "main", amount: 2, unit: "tsp" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Mirin", role: "staple", group: "sauce", amount: 2, unit: "tsp" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "thinly sliced" },
      { name: "Cooked rice", role: "core", group: "main", amount: 2 },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 1, note: "chopped" },
    ],
    need: ["Eggs","Cooked rice"],
    optional: ["Salt","Flour","Cooking oil","Chicken stock","Sugar","Soy sauce","Mirin","Onion","Spring onion"],
    steps: [
      "Season the pounded pork chops with salt and pepper, and dust with a light, even coating of flour. In one shallow bowl, beat the egg. Put the panko into another shallow bowl.",
      "Add thin, even layer of oil to a cast iron pan or skillet over medium heat. The oil is ready when you throw a panko breadcrumb into the oil and it sizzles. Dip the pork into the egg to coat. Transfer the pork to the panko and press it evenly into the meat to get a good coating.",
      "Carefully lay the pork chops in the hot oil and cook for 5-6 minutes on one side, until golden brown. Flip and cook the other side for another 5-6 minutes. Drain on a plate lined with a paper towel.",
      "While the pork is resting, add the stock, sugar, soy sauce, and Mirin to a small bowl. In another bowl, lightly beat 2 eggs. Add a tablespoon of oil to a pan over medium heat, and add the sliced onion. Fry the onions until they’re translucent and slightly caramelized.",
      "Pour the stock mixture over the onions. Slice your tonkatsu into pieces and place on top of the onions. Drizzle the egg over everything. Cook over medium low heat until the egg is just set. Serve over bowls of steamed rice, and garnish with scallions.",
    ],
    zh: {
      name: "豬排丼",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-chicken-katsu-curry-rice",
    name: "Chicken katsu curry rice",
    cuisine: "Japanese",
    time: 50,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/chicken-katsu-curry-rice/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tbsp" },
      { name: "Onion", role: "staple", group: "main", amount: 10, unit: "oz", note: "about 2 small to medium onions, halved and cut into 1-inch/2.5cm pieces" },
      { name: "Garlic", role: "staple", group: "main", amount: 1, unit: "clove", note: "minced" },
      { name: "Tomato paste", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Curry powder", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "such as madras curry powder" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Potato", role: "core", group: "main", amount: 8, unit: "oz", note: "cut into 3/4 inch or 2 cm cubes; about 1 medium or 2 small potatoes" },
      { name: "Carrots", role: "core", group: "main", amount: 8, unit: "oz", note: "cut into 3/4 inch or 2 cm triangular pieces; about 3 medium carrots" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 2, unit: "cup" },
      { name: "Cornstarch", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "mixed onto a slurry with 1 tablespoon water" },
      { name: "Butter", role: "core", group: "main", amount: 1, unit: "tbsp" },
      { name: "Chicken breast", role: "core", group: "main", amount: 2, unit: "lb" },
      { name: "Flour", role: "staple", group: "main", amount: 2, unit: "tbsp" },
      { name: "Eggs", role: "core", group: "main", amount: 1 },
      { name: "Cooked rice", role: "core", group: "main", amount: 6, unit: "cup", note: "such as koshihikari" },
    ],
    need: ["Potato","Carrots","Butter","Chicken breast","Eggs","Cooked rice"],
    optional: ["Cooking oil","Onion","Garlic","Tomato paste","Curry powder","Salt","Sugar","Chicken stock","Cornstarch","Flour"],
    steps: [
      "Heat a Dutch oven or other medium to large pot over medium heat. Add the 1 tablespoon oil and the onion, and cook until the onions begin to turn translucent and the edges begin to brown, about 2-3 minutes.",
      "Stir in the potatoes, carrots, and chicken stock. Bring to a simmer, cover, and cook until the potatoes and carrots are tender, about 20-25 minutes.",
      "You’ll need to cook the chicken in a couple batches. Carefully lay the chicken in the hot oil and cook for 6 minutes on one side, until golden brown. Flip and cook the other side for another 5-6 minutes. Transfer to a plate and repeat with the remaining chicken, adding oil to the pan as needed.",
      "Stir the cornstarch with the water to make a slurry, and add it to the curry sauce. Stir until the sauce is thickened, then stir in the butter. Taste for seasoning and add additional salt to taste if needed.",
      "Slice the chicken, and place over the steamed rice. Ladle the curry sauce on the side. Enjoy!",
    ],
    zh: {
      name: "炸雞咖喱飯",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-tempura-donburi",
    name: "Tempura donburi",
    cuisine: "Japanese",
    time: 45,
    servings: 2,
    sourceUrl: "https://thewoksoflife.com/tempura-donburi-shrimp-vegetable/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Dashi", role: "staple", group: "main", amount: 3, unit: "cup", note: "homemade or made with instant dashi granules" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 2, unit: "tbsp" },
      { name: "Mirin", role: "staple", group: "sauce", amount: 2, unit: "tbsp" },
      { name: "Cooked rice", role: "core", group: "main", amount: 4, unit: "cup" },
      { name: "Sweet potato", role: "core", group: "main", amount: 1, note: "peeled and sliced into thin rounds" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "sliced into 1/2-inch rounds" },
      { name: "Broccoli", role: "core", group: "main", amount: 2, note: "torn into small individual florets" },
      { name: "Mushroom", role: "core", group: "main", amount: 2, unit: "cup", note: "broken up into individual pieces" },
      { name: "Shrimp", role: "core", group: "main", amount: 12, note: "peeled and deveined, with the tail on" },
      { name: "Cooking oil", role: "staple", group: "main", note: "or canola/peanut oil, for frying" },
      { name: "Flour", role: "staple", group: "main", amount: 1.25, unit: "cup" },
      { name: "Eggs", role: "core", group: "main", amount: 2 },
    ],
    need: ["Cooked rice","Sweet potato","Broccoli","Mushroom","Shrimp","Eggs"],
    optional: ["Dashi","Soy sauce","Mirin","Onion","Cooking oil","Flour"],
    steps: [
      "First, prepare the dipping sauce by combining dashi stock, soy sauce, and mirin. We used instant dashi, but if you want to make it yourself, we have detailed instructions in our Miso Soup recipe . At this point, you can also cook the rice you’ll serve with the tempura.",
      "Score the shrimp with a sharp knife so that they can lay flat (you can do this lightly if you don’t mind them retaining some of their curved shape). Refrigerate the shrimp until you’re ready to fry.",
      "To fry, swirl one piece of vegetable or shrimp in the batter (for the shrimp, hold it by the tail), and lower it gently into the batter. Fry everything in batches of 3-4 items for 45-90 seconds, turning each item 3-4 times. When the vegetables are lightly golden and the shrimp are lightly golden, orange, and floating, it’s ready to be transferred to the wire rack.",
      "Adjust the heat as needed between batches as you add cold food to the oil. The oil should be hot enough that it doesn’t take too long to cook the tempura, but not so hot that the food immediately turns golden when it hits the oil.",
      "To assemble the tempura donburi bowls, spoon a base of steamed rice into each bowl. Top with with vegetables and a few shrimp per bowl. Serve with the dipping sauce, grated daikon (optional), and perhaps a bowl of miso soup!",
    ],
    zh: {
      name: "天婦羅丼",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-tan-tan-ramen",
    name: "Tan tan ramen",
    cuisine: "Japanese",
    time: 35,
    servings: 2,
    sourceUrl: "https://thewoksoflife.com/tan-tan-ramen/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Ground pork", role: "core", group: "main", amount: 8, unit: "oz", note: "can substitute any other ground meat" },
      { name: "Mirin", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Ginger", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "minced" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "or any other neutral oil" },
      { name: "Doubanjiang", role: "core", group: "main", amount: 1, unit: "tbsp", note: "Sichuan doubanjiang" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, unit: "clove", note: "minced" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 2, unit: "tbsp" },
      { name: "Cooked rice", role: "core", group: "main", amount: 1, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Chili oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "preferably homemade" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 2, unit: "cup" },
      { name: "Milk", role: "core", group: "main", amount: 2, unit: "cup" },
      { name: "Lettuce", role: "core", group: "main", amount: 2, note: "such as spinach, baby bok choy, or yu choy, trimmed and washed" },
      { name: "Noodles", role: "core", group: "main", amount: 10, unit: "oz", note: "such as Myojo medium-thick wavy ramen noodles" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 2, note: "chopped" },
    ],
    need: ["Ground pork","Doubanjiang","Cooked rice","Milk","Lettuce","Noodles"],
    optional: ["Mirin","Ginger","Cooking oil","Garlic","Soy sauce","Sugar","Chili oil","Chicken stock","Spring onion"],
    steps: [
      "Combine the ground pork with the mirin and minced ginger. Set aside for 15 minutes to marinate.",
      "Combine the chicken stock and oat milk in a pot, and bring to a simmer. Cover to keep warm. (Do not let this mixture go above a low simmer. If it boils, the milk may split, causing it to curdle.) Also bring a large pot of water to a boil for the leafy greens and the noodles.",
      "To the pot of boiling water, add the green vegetables and blanch for 30 seconds to 1 minute. Remove from the water, drain, and set aside. Bring the water to a rolling boil again, and add the noodles, cooking them according to package directions until they’re just cooked through and still chewy.",
      "Add half of the sesame paste mixture to each bowl, followed by the hot simmering stock/milk mixture. Stir to combine. Divide the cooked noodles between the two bowls, and top with the cooked pork, blanched veggies, and chopped scallions. If you like yours extra spicy, you can add a bit more chili oil on top.",
    ],
    zh: {
      name: "擔擔拉麵",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-miso-fish",
    name: "Miso fish",
    cuisine: "Japanese",
    time: 25,
    servings: 2,
    sourceUrl: "https://thewoksoflife.com/miso-fish/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "White fish", role: "core", group: "main", amount: 6, unit: "oz", note: "or other firm, white fish" },
      { name: "Miso", role: "core", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Mirin", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tsp" },
    ],
    need: ["White fish","Miso"],
    optional: ["Mirin","Sesame oil","Cooking oil"],
    steps: [
      "Make sure your fish is thawed. You can put it in the refrigerator the night before. The morning you want to eat the fish, whisk together the miso, mirin, and sesame oil.",
      "Using a paring knife make a few large hash marks in the fish so the marinade can penetrate. Swish the fillets in the marinade until fully coated. Cover and marinate in the refrigerator for at least 2 hours.",
      "Heat a skillet over medium-high heat for 3-4 minutes. Add the neutral oil and the fish (it should lightly sizzle). If it’s sizzling intensely, reduce the heat.",
      "Cook the fish for 4 minutes. Once you get a golden burnish on one side, flip, and reduce the heat to medium/medium-low if needed to ensure that the marinade doesn’t burn. A little bit of dark caramelization around the edges is okay, but the goal is to avoid burning the miso.",
      "Cook for another 2 to 2.5 minutes. The middle should be just cooked and still a little juicy if you gently peek inside the fillet with a fork or chopstick. Serve with a grain and some veggies for an easy lunch or dinner!",
    ],
    zh: {
      name: "味噌烤魚",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-okonomiyaki",
    name: "Okonomiyaki",
    cuisine: "Japanese",
    time: 35,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/easy_okonomiyaki_78828",
    sourceName: "BBC Food",
    materials: [
      { name: "Ketchup", role: "core", group: "main", amount: 1.5, unit: "tbsp", note: "tomato" },
      { name: "Honey", role: "staple", group: "main", amount: 2, unit: "tsp", note: "runny" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "dark" },
      { name: "Eggs", role: "core", group: "main", amount: 3, note: "free-range" },
      { name: "Flour", role: "staple", group: "main", amount: 3, unit: "tbsp", note: "plain" },
      { name: "Salt", role: "staple", group: "main", amount: 0.5, unit: "tsp", note: "sea" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 0.5, unit: "tsp", note: "toasted" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 2, note: "s, thinly sliced" },
      { name: "Cabbage", role: "core", group: "main", amount: 275, unit: "g", note: "/9.75oz white , shredded" },
      { name: "Cooking oil", role: "staple", group: "main", note: "sunflower oil" },
    ],
    need: ["Ketchup","Eggs","Cabbage"],
    optional: ["Honey","Soy sauce","Flour","Salt","Sesame oil","Spring onion","Cooking oil"],
    steps: [
      "For the okonomiyaki sauce, whisk together the tomato ketchup, Worcestershire sauce, honey and dark soy sauce in a small bowl until combined. Set aside.",
      "Fold the spring onions and cabbage into the batter until everything is well coated.",
      "Spoon some of the cabbage mixture into the pan into pancake shapes that are about the size of your palm. Press down with the back of the spoon and fry until golden-brown on each side, flipping halfway. Transfer the pancakes to the kitchen paper to drain.",
      "Fry in batches until you’ve run out of mixture – you should get about eight pancakes.",
      "Serve the pancakes drizzled with the okonomiyaki sauce.",
    ],
    zh: {
      name: "大阪燒",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-okonomiyaki-classic",
    name: "Okonomiyaki classic",
    cuisine: "Japanese",
    time: 40,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/okonomiyaki_26987",
    sourceName: "BBC Food",
    materials: [
      { name: "Flour", role: "staple", group: "main", amount: 100, unit: "g", note: "/3.5oz plain" },
      { name: "Cabbage", role: "core", group: "main", amount: 0.75, note: "sweetheart , thinly shredded (approximately 150g/5.5oz)" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 2, note: "s, thinly sliced" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "vegetable oil" },
      { name: "Ketchup", role: "core", group: "main", amount: 1, unit: "tbsp", note: "tomato" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 2, unit: "tsp" },
    ],
    need: ["Cabbage","Ketchup"],
    optional: ["Flour","Spring onion","Cooking oil","Soy sauce"],
    steps: [
      "Grind the linseeds with a pestle and mortar, or pop them in a sandwich bag and bash with a rolling pin. In a small bowl, mix 1 tablespoon linseeds with 5 tablespoons water. Set aside until there is no visible water and the mixture appears thickened and slightly gelatinous.",
      "Heat the oil in a large frying pan until shimmering hot. Add the cabbage mixture and push into an even layer, pressing down with a spatula to compact it.",
      "Meanwhile, mix together the tomato ketchup and soy sauce in a small bowl.",
      "To serve, slide the pancake onto a plate, drizzle with the ketchup sauce and sprinkle with nutritional yeast and the reserved spring onions.",
    ],
    zh: {
      name: "經典大阪燒",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-ramen-noodles",
    name: "Ramen noodles bowl",
    cuisine: "Japanese",
    time: 25,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/ramen_noodles_with_87615",
    sourceName: "BBC Food",
    materials: [
      { name: "Noodles", role: "core", group: "main", amount: 1, note: "packet instant ramen" },
      { name: "Pak choi", role: "core", group: "main", amount: 1, note: "cut in half or quarters, depending on size" },
      { name: "Chicken breast", role: "core", group: "main", amount: 1, note: "cooked" },
      { name: "Butter", role: "core", group: "main", amount: 2, unit: "tbsp", note: "crunchy peanut" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "light" },
      { name: "Honey", role: "staple", group: "main", amount: 1, unit: "tsp", note: "runny" },
      { name: "Dried chili", role: "core", group: "main", note: "red chilli flakes (optional)" },
    ],
    need: ["Noodles","Pak choi","Chicken breast","Butter","Dried chili"],
    optional: ["Soy sauce","Honey"],
    steps: [
      "Cook the ramen noodles according to packet instructions, using the flavour sachet. In the last 2 minutes of cooking, add the pak choi pieces to gently blanch.",
      "While the noodles are cooking, reheat the chicken in a dry pan over a medium-low heat, if desired, until piping hot throughout. Remove the chicken from the pan and thickly slice, then set aside.",
      "To make the peanut sauce, combine the peanut butter, sriracha, soy sauce and honey in a small bowl. Add 2–3 tablespoons ice-cold water to loosen the sauce and reach a drizzling consistency.",
      "When the noodles are cooked, transfer to a bowl (with or without the stock, depending on whether you want brothy noodles) and add the blanched pak choi and sliced chicken pieces. Generously spoon over the peanut sauce and finish with a sprinkling of chilli flakes, if using.",
    ],
    zh: {
      name: "拉麵碗",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-beef-udon-woks",
    name: "Beef udon",
    cuisine: "Japanese",
    time: 30,
    servings: 2,
    sourceUrl: "https://thewoksoflife.com/beef-udon/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Dashi", role: "staple", group: "main", amount: 1.5, unit: "tbsp", note: "if not using prepared dashi stock" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tbsp" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "thinly sliced" },
      { name: "Beef steak", role: "core", group: "main", amount: 8, unit: "oz", note: "fatty beef chuck or ribeye for hot pot/shabu shabu" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Mirin", role: "staple", group: "sauce", amount: 2, unit: "tbsp", note: "divided" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp", note: "divided" },
      { name: "Oyster sauce", role: "staple", group: "sauce", amount: 1, unit: "tsp" },
      { name: "Udon", role: "core", group: "main", amount: 14, unit: "oz", note: "or 7 ounces dried udon noodles" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 2, note: "finely chopped" },
    ],
    need: ["Beef steak","Udon"],
    optional: ["Dashi","Cooking oil","Onion","Sugar","Mirin","Soy sauce","Oyster sauce","Spring onion"],
    steps: [
      "Prepare your dashi stock by bringing 4 cups of water to a simmer in a medium pot and adding the dashi powder. Keep covered at a low simmer. If using prepared dashi stock, you may need to add salt to taste. Bring a separate pot of water to a boil for the noodles.",
      "Heat the neutral oil in a large skillet over medium high heat, and cook the sliced onions for about 8 minutes, stirring often. Add the beef and sugar, and cook until the beef is slightly browned. Add 1 tablespoon mirin, ½ tablespoon soy sauce, the oyster sauce, and ½ cup of the dashi stock. Bring to a simmer, and cook for about 10 minutes to reduce the stock to a thin sauce.",
      "Meanwhile, to the remaining dashi stock in the pot, add the remaining 1 tablespoon mirin and ½ tablespoon soy sauce. Add the noodles to the boiling water, and cook according to package instructions. Divide the noodles and dashi stock amongst 2 bowls. Top each bowl with half of the beef mixture and scallions. Serve immediately.",
    ],
    zh: {
      name: "牛肉烏冬",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-japchae-woks",
    name: "Japchae",
    cuisine: "Korean",
    time: 40,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/japchae/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Beef steak", role: "core", group: "main", amount: 6, unit: "oz", note: "170g, cut into thin strips" },
      { name: "Garlic", role: "staple", group: "main", amount: 3, unit: "clove", note: "minced, divided" },
      { name: "Sugar", role: "staple", group: "main", amount: 6, unit: "tsp", note: "24g, divided" },
      { name: "White pepper", role: "staple", group: "main", amount: 0.75, unit: "tsp", note: "divided" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 4.5, unit: "tbsp", note: "67 ml, divided &#8211; can substitute tamari or gluten-free soy sauce" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 1, unit: "tsp", note: "plus 2 tablespoons, divided" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "sliced thinly" },
      { name: "Carrots", role: "core", group: "main", amount: 2, note: "julienned" },
      { name: "Mushroom", role: "core", group: "main", amount: 4, note: "cut into thin strips" },
      { name: "Bell pepper", role: "core", group: "main", amount: 1, note: "cut into thin strips" },
      { name: "Spinach", role: "core", group: "main", amount: 4, unit: "oz", note: "115g, about 3 large handfuls" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 3, note: "cut into 3-inch sections and thinly sliced" },
      { name: "Glass noodles", role: "core", group: "main", amount: 10, unit: "oz" },
      { name: "Cooking oil", role: "staple", group: "main" },
      { name: "Sesame seeds", role: "staple", group: "garnish", amount: 1, unit: "tbsp" },
    ],
    need: ["Beef steak","Carrots","Mushroom","Bell pepper","Spinach","Glass noodles"],
    optional: ["Garlic","Sugar","White pepper","Soy sauce","Sesame oil","Onion","Spring onion","Cooking oil","Sesame seeds"],
    steps: [
      "Mix the beef together with 1 clove of the garlic, 1 teaspoon sugar, ¼ teaspoon ground black pepper, 1 tablespoon soy sauce, and 1 teaspoon of sesame oil.",
      "Prepare the vegetables, and set aside. Cook the noodles for 7 minutes in a large pot of boiling water. Strain and cut with scissors so that they’re a little shorter. Add 1 tablespoon sesame oil, 1 tablespoon soy sauce, and 2 teaspoons sugar to the noodles. Toss thoroughly.",
      "Heat up a skillet over medium high heat. Stir-fry the onion and carrot with 1 tablespoon of vegetable oil until tender, but still a little crunchy. Transfer to a large mixing bowl. Add another tablespoon of oil to the pan, and add the mushrooms. Cook until caramelized, and transfer to the mixing bowl along with the onion and carrot. Add another tablespoon of oil to the pan, and cook the red peppers until tender. Add in the spinach, scallions, and the remaining garlic. Cook the entire mixture until the scallions and spinach are wilted. Transfer to the mixing bowl with the other vegetables.",
      "Turn up your heat to high, and add the beef to the pan. Stir-fry for a couple minutes until the beef is no longer pink. Transfer the noodles and the beef to the mixing bowl, along with the sesame seeds.",
      "Add 3 teaspoons sugar, ½ teaspoon ground black pepper, 2 1/2 tablespoons soy sauce, and 1 tablespoon of sesame oil to the mixing bowl full of ingredients. Toss to combine all the ingredients together, and serve.",
    ],
    zh: {
      name: "雜菜粉絲",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-kimchi-noodle-soup-woks",
    name: "Kimchi noodle soup",
    cuisine: "Korean",
    time: 30,
    servings: 2,
    sourceUrl: "https://thewoksoflife.com/kimchi-noodle-soup/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "such as vegetable, canola, or avocado oil" },
      { name: "Pork chops", role: "core", group: "main", amount: 8, unit: "oz", note: "thinly sliced" },
      { name: "Mushroom", role: "core", group: "main", amount: 5, unit: "oz" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "thinly sliced" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, unit: "clove", note: "chopped" },
      { name: "Cabbage", role: "core", group: "main", amount: 1, unit: "cup", note: "roughly chopped" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Gochujang", role: "core", group: "sauce", amount: 1, unit: "tbsp", note: "Korean fermented pepper paste" },
      { name: "Dashi", role: "staple", group: "main", amount: 2, unit: "cup", note: "I use instant dashi granules" },
      { name: "Chicken thighs", role: "core", group: "main", amount: 2, unit: "tsp", note: "mixed with 2 cups/475ml hot water; or prepared chicken stock" },
      { name: "Beef steak", role: "core", group: "main", amount: 1, unit: "tsp", note: "mixed with 2 cups/475ml hot water" },
      { name: "Kimchi", role: "core", group: "main", amount: 0.25, unit: "cup" },
      { name: "Gochugaru", role: "core", group: "main", amount: 2, unit: "tbsp", note: "Korean chili flakes" },
      { name: "Fish sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 0.25, unit: "tsp" },
      { name: "Noodles", role: "core", group: "main", amount: 12, unit: "oz" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 1, note: "chopped" },
    ],
    need: ["Pork chops","Mushroom","Cabbage","Gochujang","Chicken thighs","Beef steak","Kimchi","Gochugaru","Noodles"],
    optional: ["Cooking oil","Onion","Garlic","Sugar","Dashi","Fish sauce","Sesame oil","Spring onion"],
    steps: [
      "Heat a wok or wide soup pot over high heat until very hot. Add the oil, followed by the pork belly, and stir-fry for 2 minutes (or until lightly browned and caramelized).",
      "Add the mushrooms, and stir-fry for 2 minutes. Then add the onion, garlic, kimchi, and sugar, and cook for 3 minutes. Finally, add the gochujang and cook for another minute. Remove this mixture to a plate, and set aside.",
      "To the wok or pot, add the dashi stock, chicken stock, beef bouillon paste and water, and kimchi juice. Mix well to deglaze the surface of the pan and ensure the bouillon paste is completely dissolved. Bring to a boil. Stir in the gochugaru, fish sauce, and sesame oil, reduce the heat to low, and cover.",
      "Meanwhile, bring a large pot of water to a boil for the noodles. Cook the noodles according to package instructions, and divide between 3-4 bowls. Cover with the broth, and top with the kimchi, pork belly, and mushroom mixture. Garnish with chopped scallions, and enjoy!",
    ],
    zh: {
      name: "泡菜湯麵",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-oi-muchim",
    name: "Oi muchim",
    cuisine: "Korean",
    time: 15,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/oi-muchim-korean-cucumber-salad/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Cucumber", role: "core", group: "main", amount: 14, unit: "oz", note: "about 1 large or 3 small" },
      { name: "Onion", role: "staple", group: "main", amount: 1, unit: "cup", note: "white or yellow onion; thinly sliced or roughly chopped" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 1, note: "chopped" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, unit: "clove", note: "minced" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Gochugaru", role: "core", group: "main", amount: 2, unit: "tsp", note: "Korean chili flakes" },
      { name: "Sesame seeds", role: "staple", group: "garnish", amount: 2, unit: "tsp" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 2, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Fish sauce", role: "staple", group: "sauce", amount: 1, unit: "tsp" },
      { name: "Cooked rice", role: "core", group: "main", amount: 1, unit: "tsp" },
      { name: "Carrots", role: "core", group: "main", amount: 1, note: "thinly sliced and julienned" },
    ],
    need: ["Cucumber","Gochugaru","Cooked rice","Carrots"],
    optional: ["Onion","Salt","Spring onion","Garlic","Soy sauce","Sesame seeds","Sesame oil","Sugar","Fish sauce"],
    steps: [
      "Cut the cucumber in half lengthwise, and then cut each half lengthwise again, so you have 4 long pieces. Cut the cucumber on a diagonal, rotating the pieces as you cut to get roughly triangular pieces. Add the onion and salt, and set aside for 20 minutes to allow the cucumber and onion to release excess water.",
      "In a large bowl, add the scallion, garlic, soy sauce, gochugaru, sesame seeds, sesame oil, sugar, fish sauce, and rice vinegar. Mix well.",
      "Pour off the liquid from the cucumber and onion, then add them to the seasoning mixture along with the carrot. Toss and serve.",
    ],
    zh: {
      name: "韓式凉拌青瓜",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-kimchi-jjigae",
    name: "Kimchi jjigae",
    cuisine: "Korean",
    time: 35,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/korean_kimchi_jjigae_27026",
    sourceName: "BBC Food",
    materials: [
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "vegetable oil" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "finely diced" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 1, note: "(green part), thinly sliced, reserve a little for garnish" },
      { name: "Garlic", role: "staple", group: "main", amount: 3, note: "cloves, finely diced" },
      { name: "Kimchi", role: "core", group: "main", amount: 200, unit: "g", note: "/7oz vegan , chopped, plus 2 tbsp of the brine (‘kimchi juice’)" },
      { name: "Gochujang", role: "core", group: "sauce", amount: 1, unit: "tbsp", note: "paste" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tsp" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 2, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Salt", role: "staple", group: "main", amount: 0.5, unit: "tsp" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 300, unit: "ml", note: "/10fl oz vegetable stock" },
      { name: "Tofu", role: "core", group: "main", amount: 400, unit: "g", note: "/14oz extra firm , pressed and cut into slices about 1cm thick" },
      { name: "Sesame seeds", role: "staple", group: "garnish" },
      { name: "Cooked rice", role: "core", group: "main" },
    ],
    need: ["Kimchi","Gochujang","Tofu","Cooked rice"],
    optional: ["Cooking oil","Onion","Spring onion","Garlic","Soy sauce","Sesame oil","Sugar","Salt","Chicken stock","Sesame seeds"],
    steps: [
      "Heat the vegetable oil in a large pan and cook the onion and spring onion for 5 minutes (hold back a little uncooked spring onion for the garnish.).",
      "Stir in the gochujang paste, soy sauce, sesame oil, sugar and salt. Mix well.",
      "Add the tofu slices to the stew and simmer for an additional 5-10 minutes, or until the tofu is heated through.",
      "Taste the stew and adjust the seasoning, adding more salt if needed.",
      "Garnish with sesame seeds, sesame oil and the reserved chopped spring onions. Serve hot with rice.",
    ],
    zh: {
      name: "泡菜鍋",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-pork-kimchi-stew",
    name: "Pork and kimchi stew",
    cuisine: "Korean",
    time: 40,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/pork_and_kimchi_stew_09539",
    sourceName: "BBC Food",
    materials: [
      { name: "Pork chops", role: "core", group: "main", amount: 750, unit: "g", note: "/1lb 10oz diced pork (shoulder or leg)" },
      { name: "Gochujang", role: "core", group: "sauce", amount: 2, unit: "tbsp", note: "(Korean fermented chilli paste)" },
      { name: "Mushroom", role: "core", group: "main", amount: 10, unit: "g", note: "/0.33oz dried shiitake s" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "vegetable oil" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "thickly sliced" },
      { name: "Carrots", role: "core", group: "main", amount: 1, note: "carrot, peeled and cut into chunks" },
      { name: "Kimchi", role: "core", group: "main", amount: 200, unit: "g", note: "/7oz" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Spring onion", role: "staple", group: "garnish", note: "bunch s, roughly sliced (including the green parts)" },
      { name: "Salt", role: "staple", group: "main", note: "and freshly ground black pepper" },
      { name: "Cooked rice", role: "core", group: "main", note: "steamed rice" },
      { name: "Cilantro", role: "core", group: "garnish", note: "bunch coriander, leaves separated" },
      { name: "Sesame seeds", role: "staple", group: "garnish", amount: 1, unit: "tsp" },
      { name: "Gochugaru", role: "core", group: "main", note: "pinch  (Korean red chilli powder), or other chilli flakes" },
    ],
    need: ["Pork chops","Gochujang","Mushroom","Carrots","Kimchi","Cooked rice","Cilantro","Gochugaru"],
    optional: ["Cooking oil","Onion","Soy sauce","Spring onion","Salt","Sesame seeds"],
    steps: [
      "Put the pork in a bowl and season with salt and pepper. Add the gochujang and stir until the pork is completely coated. Leave to marinate for 30 minutes–1 hour.",
      "Heat the vegetable oil in a large saucepan or flameproof casserole. Add the onion, carrot and turnips and fry over a high heat, stirring regularly, until starting to brown. Add the pork and fry until browned all over.",
      "Remove the lid and simmer until the sauce has reduced.",
      "Add the spring onions and simmer until they start to soften. Serve the stew over steamed rice, garnished with coriander leaves, a sprinkling of sesame seeds and a few chilli flakes.",
    ],
    zh: {
      name: "豬肉泡菜湯",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-bibimbap-sesame",
    name: "Bibimbap with sesame",
    cuisine: "Korean",
    time: 40,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/bibimbap_with_sesame_78959",
    sourceName: "BBC Food",
    materials: [
      { name: "Cooked rice", role: "core", group: "main", amount: 120, unit: "g", note: "/4.5oz brown basmati rice" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 2, unit: "tsp", note: "toasted" },
      { name: "Eggs", role: "core", group: "main", amount: 2, note: "free-range" },
      { name: "Cucumber", role: "core", group: "main", amount: 0.25, note: "peeled and roughly chopped" },
      { name: "Kimchi", role: "core", group: "main", amount: 100, unit: "g", note: "/3.5oz" },
      { name: "Sesame seeds", role: "staple", group: "garnish", amount: 1, unit: "tsp", note: "toasted , to garnish" },
      { name: "Carrots", role: "core", group: "main", amount: 1, note: "carrot, peeled and cut into thin matchsticks" },
      { name: "Sugar", role: "staple", group: "main", amount: 0.25, unit: "tsp", note: "caster" },
      { name: "Salt", role: "staple", group: "main", amount: 0.25, unit: "tsp", note: "sea" },
      { name: "Gochujang", role: "core", group: "sauce", amount: 2, unit: "tbsp", note: "(Korean fermented chilli paste)" },
      { name: "Honey", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "runny" },
      { name: "Garlic", role: "staple", group: "main", amount: 1, note: "clove, finely chopped" },
      { name: "Spinach", role: "core", group: "main", amount: 200, unit: "g", note: "/7oz baby  leaves" },
      { name: "Beans", role: "core", group: "main", amount: 100, unit: "g", note: "/3.5oz prouts" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
    ],
    need: ["Cooked rice","Eggs","Cucumber","Kimchi","Carrots","Gochujang","Spinach","Beans"],
    optional: ["Sesame oil","Sesame seeds","Sugar","Salt","Honey","Garlic","Soy sauce"],
    steps: [
      "Cook the rice in boiling water for 20 minutes until tender and then drain.",
      "To make the chilli sauce, whisk together all the ingredients until smooth in a small bowl.",
      "Just before serving, heat the sesame oil in a frying pan and fry the eggs, sunny side-up. Remove the pickled carrot from the bowl and pat dry on kitchen paper.",
      "Divide the rice between two shallow bowls. Add the sesame spinach, cucumber, carrot pickle and kimchi. Top each bowl with a fried egg, a drizzle of chilli sauce and a sprinkling of toasted sesame seeds.",
    ],
    zh: {
      name: "芝麻拌飯",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-beef-bulgogi",
    name: "Beef bulgogi",
    cuisine: "Korean",
    time: 30,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/beef_bulgogi_88615",
    sourceName: "BBC Food",
    materials: [
      { name: "Beef steak", role: "core", group: "main", amount: 300, unit: "g", note: "/10.5–14oz rib-eye steak" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 2, note: "s, each chopped into 2–3 pieces" },
      { name: "Lettuce", role: "core", group: "main", amount: 2, note: "Little Gem s, halved lengthways" },
      { name: "Sesame seeds", role: "staple", group: "garnish", amount: 1, unit: "tbsp", note: "toasted" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 4, unit: "tbsp", note: "light" },
      { name: "Sugar", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "soft brown" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, note: "cloves" },
      { name: "Ginger", role: "staple", group: "main", amount: 25, unit: "g", note: "/1oz fresh root , peeled and chopped" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 1, unit: "tbsp" },
      { name: "Salt", role: "staple", group: "main", note: "pinch  and pepper" },
      { name: "Gochujang", role: "core", group: "sauce", amount: 2, unit: "tbsp", note: "(Korean fermented chilli paste)" },
      { name: "Miso", role: "core", group: "sauce", amount: 1, unit: "tbsp", note: "paste" },
      { name: "Honey", role: "staple", group: "main", amount: 1, unit: "tbsp" },
    ],
    need: ["Beef steak","Lettuce","Gochujang","Miso"],
    optional: ["Spring onion","Sesame seeds","Soy sauce","Sugar","Garlic","Ginger","Sesame oil","Salt","Honey"],
    steps: [
      "Slice the steak as thinly as possible into long, wide pieces and then bash well with the side of a knife, cleaver or meat mallet to flatten.",
      "To make the marinade, blitz all of the ingredients together in a food processor. Pour over the steak and massage into the meat. Cover with cling film or leave in a sealed food container in the fridge overnight.",
      "Mix all of the ssamjang ingredients together in a ramekin or small bowl.",
      "Preheat a griddle or frying pan over a high heat or prepare the coals for a barbecue. Once the pan or barbecue is smoking hot, place the marinated meat, piece by piece, on top of the hot grill or pan and sear until nicely charred. Turn once and sear the other side. Char the spring onion and lettuces on the grill too. Scatter over the sesame seeds and serve with the ssamjang on the side.",
    ],
    zh: {
      name: "韓式烤肉",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-japchae",
    name: "Japchae BBC",
    cuisine: "Korean",
    time: 35,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/japchae_09863",
    sourceName: "BBC Food",
    materials: [
      { name: "Noodles", role: "core", group: "main", amount: 150, unit: "g", note: "/5.5oz dried Korean sweet potato vermicelli  (dangmyeon)" },
      { name: "Onion", role: "staple", group: "main", amount: 0.5, note: "finely sliced" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, note: "cloves, finely sliced" },
      { name: "Bell pepper", role: "core", group: "main", amount: 0.5, note: "red pepper, finely sliced" },
      { name: "Carrots", role: "core", group: "main", amount: 1, note: "carrot, peeled and cut into fine matchsticks" },
      { name: "Mushroom", role: "core", group: "main", amount: 4, note: "shiitake s, soaked in warm water and sliced" },
      { name: "Spinach", role: "core", group: "main", amount: 2, note: "handfuls fresh" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "vegetable or sunflower oil" },
      { name: "Sesame seeds", role: "staple", group: "garnish", note: "toasted, to garnish" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1.5, unit: "tbsp", note: "light" },
      { name: "Sugar", role: "staple", group: "main", amount: 0.5, unit: "tsp" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 1, unit: "tsp" },
    ],
    need: ["Noodles","Bell pepper","Carrots","Mushroom","Spinach"],
    optional: ["Onion","Garlic","Cooking oil","Sesame seeds","Soy sauce","Sugar","Sesame oil"],
    steps: [
      "Place the vermicelli in a large bowl and pour boiling water over the noodles. Leave to soak for about 6–8 minutes, or until softened and chewy. Drain and rinse under cold water.",
      "To make the sauce, mix all of the ingredients together in a small bowl.",
      "Once the noodles are added to the wok, stir-fry for a further minute or so, folding all the vegetables evenly through the noodles. Now pour the sauce into the wok and bring to a vigorous boil over a high heat.",
      "Stir the sauce into the noodles for 2–3 minutes, until all of the sauce has been absorbed by the noodles. Garnish with the toasted sesame seeds and serve.",
    ],
    zh: {
      name: "韓式雜菜粉絲",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-chinese-rice-cake-soup",
    name: "Chinese rice cake soup",
    cuisine: "Chinese",
    time: 35,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/chinese-rice-cake-soup/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Chicken thighs", role: "core", group: "main", amount: 8, unit: "oz", note: "cut into small, thin strips" },
      { name: "Shaoxing wine", role: "staple", group: "main", amount: 2, unit: "tsp" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "White pepper", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Cornstarch", role: "staple", group: "marinade", amount: 2, unit: "tsp" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 4, unit: "tbsp", note: "divided" },
      { name: "Ginger", role: "staple", group: "main", amount: 4, note: "julienned" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 3, note: "thinly sliced on an angle, white and green parts separated" },
      { name: "Carrots", role: "core", group: "main", amount: 1, note: "thinly sliced" },
      { name: "Cabbage", role: "core", group: "main", amount: 1.25, unit: "lb", note: "stems cut into ½-inch pieces and leaves cut into 1-inch pieces" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 4, unit: "cup" },
      { name: "Cooked rice", role: "core", group: "main", amount: 1, unit: "lb", note: "oval-shaped slices preferred" },
    ],
    need: ["Chicken thighs","Carrots","Cabbage","Cooked rice"],
    optional: ["Shaoxing wine","Soy sauce","Sesame oil","White pepper","Cornstarch","Cooking oil","Ginger","Spring onion","Chicken stock"],
    steps: [
      "Combine the pork (or chicken) with the Shaoxing wine, light soy sauce, sesame oil, white pepper, cornstarch, and water. Marinate for 15 to 20 minutes.",
      "Reduce the heat to medium, and add 2 more tablespoons oil to the wok, along with the ginger and the white parts of the scallions. Cook for 1 minute and add the carrots. Cook for another minute and add the napa cabbage. Stir fry everything together for a few minutes until the napa cabbage leaves are wilted.",
      "Add salt to taste, ½ teaspoon white pepper, 1 teaspoon sesame oil, and 1 tablespoon light soy sauce.",
      "Stir in the cooked pork, and sprinkle the rice cakes over the surface of the soup, along with green parts of the scallions. The rice cakes should be resting on top of the soup so they don’t sink into it and stick to the bottom of the wok/pot. Cover and cook for another minute, or as long as it takes to cook the rice cakes through (please see the Recipe Notes if you are using dried rice cakes). Salt to taste again and serve!",
    ],
    zh: {
      name: "年糕湯",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-jajangmyeon-woks",
    name: "Jajangmyeon",
    cuisine: "Korean",
    time: 40,
    servings: 2,
    sourceUrl: "https://thewoksoflife.com/korean-black-bean-noodles-jajangmyeon/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Cooking oil", role: "staple", group: "main", amount: 3, unit: "tbsp", note: "divided" },
      { name: "Pork chops", role: "core", group: "main", amount: 0.5, unit: "lb", note: "225g, cut into small cubes" },
      { name: "Onion", role: "staple", group: "main", amount: 2, note: "diced" },
      { name: "Zucchini", role: "core", group: "main", amount: 1, note: "cut into ¼-inch cubes" },
      { name: "Potato", role: "core", group: "main", amount: 2, note: "peeled and cut into ¼-inch cubes" },
      { name: "Noodles", role: "core", group: "main" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Cucumber", role: "core", group: "main", amount: 1, note: "cut into thin matchsticks for garnish" },
    ],
    need: ["Pork chops","Zucchini","Potato","Noodles","Cucumber"],
    optional: ["Cooking oil","Onion","Sesame oil"],
    steps: [
      "Heat 1 tablespoon of oil in a wok or pan over high heat. Stir fry the pork belly until it’s golden brown and crisped. The secret is high heat and minimal stirring! If there is a significant amount of pork fat pooling in the pan, you can drain that off.",
      "Clear a space in the center of the wok or pan, and the remaining 2 tablespoons of oil. Add the Korean black bean paste (chunjang) and let it fry in the center of the pan in the oil for one minute. Now stir everything together.",
      "After 10 minutes, check to make sure that the potato is cooked through. Once it’s fully cooked, add the potato starch slurry, and stir until thick and glossy. Finish off with the sesame oil.",
      "Serve with the noodles, and garnish with the cucumber. On the side, serve with that signature pickled radish and chopped onion.",
    ],
    zh: {
      name: "炸醬麵",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  }
]
