import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W4C: Recipe[] = [
  {
    id: "home-salt-pepper-squid",
    name: "Salt and pepper squid",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Squid", "White pepper", "Salt", "Eggs"],
    optional: ["Garlic", "Spring onion", "Chili oil", "Cornstarch", "Flour", "Dried chili", "Cooking oil", "Shaoxing wine", "Baking soda"],
    steps: [
      "Clean 400 g squid; score lightly and cut into rings or bite pieces. Pat dry; toss with cornstarch/flour if using.",
      "Pan-fry in hot oil 2–3 minutes until opaque and lightly crisp; drain briefly.",
      "Toss with salt, white pepper, minced garlic, spring onion, and chili oil if using over high heat 20–30 seconds.",
    ],
    zh: {
      name: "椒鹽鮮魷",
      steps: [
        "鮮魷約 400 克清理，輕劃刀切圈或件。抹乾，可拍生粉或麵粉。",
        "熱油煎或炸 2 至 3 分鐘至熟透微脆，瀝油。",
        "大火與鹽、白胡椒、蒜蓉、蔥花和辣椒油（可用）快炒 20 至 30 秒。",
      ],
    },
  },
  {
    id: "home-clams-black-bean",
    name: "Clams with black bean sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Clams", "Fermented black beans"],
    optional: ["Garlic", "Ginger", "Spring onion", "Chili oil", "Soy sauce", "Sugar", "Cooking oil", "Oyster sauce", "White pepper", "Sesame oil", "Cornstarch"],
    steps: [
      "Soak and scrub 500 g clams; discard any that stay open. Rinse 1.5 tbsp fermented black beans; crush with garlic.",
      "Stir-fry black-bean garlic paste with ginger until fragrant; add clams and a splash of water.",
      "Cover 4–6 minutes until shells open (discard unopened). Toss with spring onion and optional chili oil.",
    ],
    zh: {
      name: "豆豉炒蜆",
      steps: [
        "蜆約 500 克浸洗乾淨，不閉口棄掉。一湯匙半豆豉過水，加蒜壓蓉。",
        "爆香豆豉蒜蓉和薑，下蜆和少許水。",
        "加蓋 4 至 6 分鐘至開殼（不開棄掉），拌蔥花，可滴辣椒油。",
      ],
    },
  },
  {
    id: "home-garlic-steamed-shrimp-home",
    name: "Steamed garlic shrimp (scallop-style)",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Garlic"],
    optional: ["Spring onion", "Soy sauce", "Sesame oil", "Salt", "White pepper", "Glass noodles", "Sugar", "Ginger", "Cooking oil", "Cornstarch"],
    steps: [
      "Peel and devein 300 g shrimp (scallop stand-in); arrange in a heatproof dish. Optional: soak a nest of glass noodles and lay under shrimp.",
      "Mix minced garlic with a pinch of salt, soy sauce, and sesame oil; spoon over shrimp.",
      "Steam 6–8 minutes until shrimp are opaque. Finish with spring onion and white pepper.",
    ],
    zh: {
      name: "蒜蓉蒸蝦（帶子風）",
      steps: [
        "蝦約 300 克去殼腸（代替帶子）排入碟；可於底鋪浸軟粉絲。",
        "蒜蓉加少許鹽、生抽和麻油拌匀，舖在蝦上。",
        "蒸 6 至 8 分鐘至蝦熟透，撒蔥花和白胡椒。",
      ],
    },
  },
  {
    id: "home-lemon-tuna-pasta",
    name: "Lemon tuna pasta",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Pasta", "Canned tuna", "Lemon"],
    optional: ["Garlic", "Olive oil", "Salt", "White pepper", "Spring onion", "Cheddar"],
    steps: [
      "Boil 180 g pasta until al dente; reserve 1/2 cup pasta water, drain.",
      "Warm garlic in olive oil; add drained canned tuna and zest/juice of 1/2 lemon.",
      "Toss with pasta, a splash of pasta water, salt, and white pepper. Optional cheese or spring onion.",
    ],
    zh: {
      name: "檸檬吞拿魚意粉",
      steps: [
        "意粉約 180 克煮至彈牙，留半杯麵水瀝乾。",
        "橄欖油炒香蒜蓉，下瀝乾吞拿魚和半個檸檬皮汁。",
        "拌入意粉和少許麵水，加鹽白胡椒；可加芝士或蔥花。",
      ],
    },
  },
  {
    id: "home-salt-pepper-shrimp",
    name: "Salt and pepper shrimp",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "White pepper", "Salt"],
    optional: ["Garlic", "Spring onion", "Chili oil", "Cornstarch", "Cooking oil"],
    steps: [
      "Pat dry 350 g shrimp (shell-on OK); toss lightly with cornstarch if using.",
      "Pan-fry in hot oil 2–3 minutes per side until pink and cooked through.",
      "Toss with salt, white pepper, garlic, spring onion, and chili oil 20–30 seconds.",
    ],
    zh: {
      name: "椒鹽蝦",
      steps: [
        "蝦約 350 克抹乾（可連殼），可薄拍生粉。",
        "熱油每面煎 2 至 3 分鐘至變色熟透。",
        "與鹽、白胡椒、蒜蓉、蔥花和辣椒油快炒 20 至 30 秒。",
      ],
    },
  },
  {
    id: "home-squid-ginger-scallion",
    name: "Ginger scallion squid",
    cuisine: "Cantonese",
    time: 18,
    servings: 2,
    need: ["Squid", "Ginger", "Spring onion"],
    optional: ["Garlic", "Soy sauce", "Sesame oil", "Salt", "Shaoxing wine", "Cooking oil"],
    steps: [
      "Clean and slice 400 g squid into rings. Julienne ginger and spring onion.",
      "Stir-fry ginger and garlic on high heat 20 seconds; add squid and a splash of Shaoxing wine if using.",
      "Cook 2–3 minutes until opaque; toss with spring onion, soy sauce or salt, and sesame oil.",
    ],
    zh: {
      name: "薑蔥炒鮮魷",
      steps: [
        "鮮魷約 400 克清理切圈。薑和蔥切絲。",
        "大火爆香薑蒜 20 秒，下鮮魷，可加少許料酒。",
        "炒 2 至 3 分鐘至熟透，拌蔥絲、生抽或鹽和麻油。",
      ],
    },
  },
  {
    id: "home-clams-garlic-wine",
    name: "Garlic wine clams",
    cuisine: "Western",
    time: 18,
    servings: 2,
    need: ["Clams", "Garlic"],
    optional: ["Shaoxing wine", "Butter", "Spring onion", "Lemon", "Salt", "Bread", "Olive oil"],
    steps: [
      "Soak and scrub 500 g clams. Soften minced garlic in butter or olive oil.",
      "Add clams and 1/4 cup Shaoxing wine (or water); cover 4–6 minutes until open.",
      "Discard unopened clams; finish with spring onion and lemon juice. Serve with bread if you like.",
    ],
    zh: {
      name: "蒜香酒煮蜆",
      steps: [
        "蜆約 500 克浸洗乾淨。牛油或橄欖油炒香蒜蓉。",
        "下蜆和四分一杯料酒（或水），加蓋 4 至 6 分鐘至開殼。",
        "不開殼棄掉；撒蔥花擠檸檬汁，可配麵包。",
      ],
    },
  },
  {
    id: "home-steamed-fish-tofu",
    name: "Steamed fish with tofu",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["White fish", "Tofu", "Carrots"],
    optional: ["Ginger", "Spring onion", "Soy sauce", "Sesame oil", "Salt", "White pepper", "Cornstarch", "Flour", "Shaoxing wine", "Oyster sauce", "Cooking oil", "Garlic"],
    steps: [
      "Cut 300 g white fish into pieces; cube 250 g tofu. Layer tofu in a dish; top with fish and ginger shreds.",
      "Steam 10–12 minutes until fish flakes easily.",
      "Drizzle soy sauce and sesame oil; top with spring onion. Season with salt/white pepper if needed.",
    ],
    zh: {
      name: "豆腐蒸魚",
      steps: [
        "白魚約 300 克切件；豆腐約 250 克切塊。碟底鋪豆腐，放魚和薑絲。",
        "蒸 10 至 12 分鐘至魚肉易散。",
        "淋生抽麻油，撒蔥花；可略加鹽白胡椒。",
      ],
    },
  },
  {
    id: "home-shrimp-glass-noodles",
    name: "Shrimp glass noodle stir-fry",
    cuisine: "Asian",
    time: 25,
    servings: 2,
    need: ["Shrimp", "Glass noodles"],
    optional: ["Garlic", "Carrots", "Bean sprouts", "Soy sauce", "Sesame oil", "Spring onion"],
    steps: [
      "Soak glass noodles until pliable; drain. Peel 250 g shrimp.",
      "Stir-fry garlic; cook shrimp 1–2 minutes until pink. Add carrot and noodles with soy sauce and a splash of water.",
      "Toss 2–3 minutes; finish with bean sprouts, spring onion, and sesame oil.",
    ],
    zh: {
      name: "蝦仁炒粉絲",
      steps: [
        "粉絲浸軟瀝乾。蝦約 250 克去殼。",
        "爆香蒜蓉，炒蝦 1 至 2 分鐘至變色；下紅蘿蔔和粉絲加生抽少許水。",
        "炒 2 至 3 分鐘，拌芽菜蔥花和麻油。",
      ],
    },
  },
  {
    id: "home-squid-satay",
    name: "Satay squid",
    cuisine: "Hong Kong",
    time: 20,
    servings: 2,
    need: ["Squid", "Satay sauce"],
    optional: ["Onion", "Garlic", "Soy sauce", "Chili oil", "Spring onion"],
    steps: [
      "Clean and cut 400 g squid into bite pieces. Mix 2–3 tbsp satay sauce with a splash of soy sauce and water.",
      "Stir-fry onion/garlic if using; add squid 2 minutes until just opaque.",
      "Pour in satay mixture; toss 1–2 minutes until coated. Finish with chili oil and spring onion.",
    ],
    zh: {
      name: "沙爹鮮魷",
      steps: [
        "鮮魷約 400 克清理切件。兩至三湯匙沙爹醬加少許生抽和水拌匀。",
        "可炒香洋蔥蒜蓉，下鮮魷炒 2 分鐘至剛熟。",
        "倒入沙爹醬拌 1 至 2 分鐘，可滴辣椒油撒蔥花。",
      ],
    },
  },
  {
    id: "home-clam-udon-soup",
    name: "Clam udon soup",
    cuisine: "Japanese",
    time: 25,
    servings: 2,
    need: ["Clams", "Udon"],
    optional: ["Ginger", "Spring onion", "Soy sauce", "Miso", "Salt", "Nori"],
    steps: [
      "Soak and scrub 400 g clams. Cook udon per pack; drain.",
      "Simmer ginger in about 3 cups water; add clams, cover until open (4–6 minutes). Season with soy sauce or 1 tbsp miso.",
      "Add udon to bowls; ladle clam broth over. Top with spring onion and nori if using.",
    ],
    zh: {
      name: "蜆肉烏冬湯",
      steps: [
        "蜆約 400 克浸洗乾淨。烏冬按包裝煮熟瀝乾。",
        "薑片加水約三杯，下蜆加蓋 4 至 6 分鐘至開殼；加生抽或一湯匙味噌調味。",
        "烏冬入碗，淋蜆湯，撒蔥花，可加紫菜。",
      ],
    },
  },
  {
    id: "home-salt-pepper-fish",
    name: "Salt and pepper fish",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["White fish", "White pepper", "Salt", "Eggs"],
    optional: ["Garlic", "Spring onion", "Chili oil", "Cornstarch", "Flour", "Ginger", "Cooking oil", "Shaoxing wine", "Five-spice powder"],
    steps: [
      "Cut 350 g white fish into bite pieces; pat dry and dust with cornstarch/flour if using.",
      "Pan-fry in oil 3–4 minutes per side until cooked through and lightly crisp.",
      "Toss briefly with salt, white pepper, garlic, spring onion, and chili oil.",
    ],
    zh: {
      name: "椒鹽魚塊",
      steps: [
        "白魚約 350 克切件抹乾，可拍生粉或麵粉。",
        "熱油每面煎 3 至 4 分鐘至熟透微脆。",
        "與鹽、白胡椒、蒜蓉、蔥花和辣椒油略拌。",
      ],
    },
  },
  {
    id: "home-shrimp-thai-basil-home",
    name: "Thai basil shrimp",
    cuisine: "Thai",
    time: 18,
    servings: 2,
    need: ["Shrimp", "Thai basil", "Broccoli", "Eggs"],
    optional: ["Garlic", "Onion", "Soy sauce", "Sugar", "Chili oil", "Cooked rice", "Cooking oil", "Shaoxing wine", "Sesame oil", "Salt", "White pepper"],
    steps: [
      "Peel 300 g shrimp. Mince garlic; slice onion if using. Pick Thai basil leaves.",
      "Stir-fry garlic/onion; add shrimp 2–3 minutes until pink.",
      "Season with soy sauce, pinch of sugar, and chili oil; toss in basil off heat. Serve over rice.",
    ],
    zh: {
      name: "九層塔炒蝦",
      steps: [
        "蝦約 300 克去殼。蒜切蓉，可加洋蔥。摘九層塔葉。",
        "炒香蒜洋蔥，下蝦炒 2 至 3 分鐘至變色。",
        "加生抽、少許糖和辣椒油，離火拌九層塔，伴飯。",
      ],
    },
  },
  {
    id: "home-lemongrass-shrimp",
    name: "Lemongrass shrimp",
    cuisine: "Vietnamese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Lemongrass"],
    optional: ["Garlic", "Onion", "Soy sauce", "Sugar", "Chili oil", "Salt"],
    steps: [
      "Mince the tender white part of 2 lemongrass stalks. Peel 300 g shrimp.",
      "Stir-fry lemongrass and garlic until fragrant; add shrimp and onion if using.",
      "Cook 3–4 minutes until shrimp are opaque. Season with soy sauce, pinch of sugar, and chili oil.",
    ],
    zh: {
      name: "香茅蝦",
      steps: [
        "兩支香茅取嫩白部切蓉。蝦約 300 克去殼。",
        "爆香香茅蒜蓉，下蝦和洋蔥（可用）。",
        "炒 3 至 4 分鐘至熟，加生抽、少許糖和辣椒油。",
      ],
    },
  },
  {
    id: "home-miso-butter-salmon",
    name: "Miso butter salmon",
    cuisine: "Japanese",
    time: 25,
    servings: 2,
    need: ["Salmon", "Miso", "Butter"],
    optional: ["Sugar", "Soy sauce", "Lemon", "Sesame seeds", "Cooked rice"],
    steps: [
      "Pat dry 2 salmon fillets. Mix 1.5 tbsp miso with 1 tsp sugar, 1 tsp butter, and a splash of soy sauce.",
      "Pan-sear salmon skin-side down 4 minutes; flip and cook 3–4 more minutes until opaque.",
      "Brush with miso butter for the last minute; finish with lemon and sesame seeds. Serve with rice.",
    ],
    zh: {
      name: "味噌牛油三文魚",
      steps: [
        "兩件三文魚抹乾。一湯匙半味噌加一茶匙糖、一茶匙牛油和少許生抽拌匀。",
        "皮向下煎 4 分鐘，翻面再 3 至 4 分鐘至熟。",
        "最後一分鐘塗味噌牛油，擠檸檬撒芝麻，伴飯。",
      ],
    },
  },
  {
    id: "home-clam-tomato-pasta",
    name: "Clam tomato pasta",
    cuisine: "Western",
    time: 30,
    servings: 2,
    need: ["Clams", "Pasta", "Tomato"],
    optional: ["Garlic", "Onion", "Olive oil", "Salt", "Chili oil", "Spring onion", "Chicken stock", "White pepper"],
    steps: [
      "Boil 180 g pasta until al dente. Scrub 400 g clams. Chop 2 tomatoes.",
      "Soften garlic/onion in olive oil; add tomato and cook 5 minutes until saucy. Add clams; cover until open.",
      "Toss drained pasta with clam tomato sauce; season with salt and chili oil. Top with spring onion.",
    ],
    zh: {
      name: "蕃茄蜆意粉",
      steps: [
        "意粉約 180 克煮至彈牙。蜆約 400 克洗净。兩個番茄切碎。",
        "橄欖油炒香蒜洋蔥，下番茄煮 5 分鐘；下蜆加蓋至開殼。",
        "拌入意粉，加鹽和辣椒油，撒蔥花。",
      ],
    },
  },
  {
    id: "home-squid-rice-bowl",
    name: "Soy squid rice bowl",
    cuisine: "Asian",
    time: 20,
    servings: 2,
    need: ["Squid", "Cooked rice", "Soy sauce"],
    optional: ["Garlic", "Ginger", "Spring onion", "Sesame oil", "Sugar", "Eggs"],
    steps: [
      "Slice 350 g squid into rings. Mix 2 tbsp soy sauce, pinch of sugar, and sesame oil.",
      "Stir-fry garlic/ginger; cook squid 2–3 minutes until opaque; add sauce.",
      "Serve over hot cooked rice; optional fried egg and spring onion on top.",
    ],
    zh: {
      name: "豉油鮮魷飯",
      steps: [
        "鮮魷約 350 克切圈。兩湯匙生抽加少許糖和麻油拌匀。",
        "爆香蒜薑，炒鮮魷 2 至 3 分鐘至熟，下醬汁。",
        "淋在熱飯上；可加煎蛋和蔥花。",
      ],
    },
  },
  {
    id: "home-shrimp-lotus-stir",
    name: "Shrimp lotus root stir-fry",
    cuisine: "Chinese",
    time: 22,
    servings: 2,
    need: ["Shrimp", "Lotus root"],
    optional: ["Garlic", "Carrots", "Soy sauce", "Sesame oil", "Salt", "Cornstarch", "Chicken stock", "Oyster sauce", "Sugar", "White pepper", "Cooking oil", "Ginger", "Spring onion", "Shaoxing wine"],
    steps: [
      "Peel 250 g shrimp; toss with cornstarch. Thin-slice 250 g lotus root; soak briefly and drain.",
      "Stir-fry shrimp until pink; remove. Stir-fry lotus (and carrot) 3–4 minutes until crisp-tender.",
      "Return shrimp with soy sauce and sesame oil; toss 30 seconds.",
    ],
    zh: {
      name: "蝦仁炒蓮藕",
      steps: [
        "蝦約 250 克去殼加生粉。蓮藕約 250 克薄片略泡瀝乾。",
        "炒蝦至變色盛起；炒蓮藕（可加紅蘿蔔）3 至 4 分鐘至爽。",
        "回蝦加生抽麻油快炒 30 秒。",
      ],
    },
  },
  {
    id: "home-white-fish-curry",
    name: "White fish coconut curry",
    cuisine: "Thai",
    time: 30,
    servings: 2,
    need: ["White fish", "Coconut milk", "Curry powder"],
    optional: ["Onion", "Garlic", "Zucchini", "Salt", "Sugar", "Cooked rice", "Lemongrass", "Cooking oil", "Ginger", "Cilantro"],
    steps: [
      "Cut 350 g white fish into chunks. Soften onion/garlic; stir in 1–2 tsp curry powder until fragrant.",
      "Add 1 cup coconut milk and a splash of water (lemongrass if using); simmer 5 minutes. Add zucchini if using.",
      "Nestle fish in; simmer gently 6–8 minutes until fish flakes. Season with salt and pinch of sugar. Serve with rice.",
    ],
    zh: {
      name: "椰汁咖喱魚",
      steps: [
        "白魚約 350 克切件。炒軟洋蔥蒜蓉，下 1 至 2 茶匙咖喱粉炒香。",
        "加一杯椰漿和少許水（可加香茅）煮 5 分鐘；可下翠玉瓜。",
        "放入魚輕煮 6 至 8 分鐘至熟，加鹽和少許糖，伴飯。",
      ],
    },
  },
  {
    id: "home-tuna-nori-rice",
    name: "Tuna nori rice bowl",
    cuisine: "Japanese",
    time: 15,
    servings: 2,
    need: ["Canned tuna", "Cooked rice", "Nori"],
    optional: ["Soy sauce", "Mayonnaise", "Sesame seeds", "Spring onion", "Cucumber"],
    steps: [
      "Flake 1 can tuna; mix with 1 tbsp mayonnaise or a splash of soy sauce.",
      "Warm 2 bowls of cooked rice; tear nori into strips.",
      "Top rice with tuna, nori, sesame seeds, spring onion, and sliced cucumber if using.",
    ],
    zh: {
      name: "吞拿魚紫菜飯",
      steps: [
        "一罐吞拿魚壓碎，加一湯匙蛋黃醬或少許生抽拌匀。",
        "兩碗熱飯；紫菜撕絲。",
        "飯上放吞拿魚、紫菜、芝麻蔥花，可加青瓜片。",
      ],
    },
  },
  {
    id: "home-steamed-clams-ginger",
    name: "Ginger steamed clams",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Clams", "Ginger"],
    optional: ["Spring onion", "Soy sauce", "Sesame oil", "Shaoxing wine", "Salt"],
    steps: [
      "Soak and scrub 500 g clams. Julienne a thumb of ginger.",
      "Place clams in a heatproof dish with ginger and a splash of Shaoxing wine if using.",
      "Steam 6–8 minutes until open; discard unopened. Drizzle soy sauce and sesame oil; top with spring onion.",
    ],
    zh: {
      name: "薑絲蒸蜆",
      steps: [
        "蜆約 500 克浸洗乾淨。薑切絲。",
        "蜆與薑絲放入碟，可加少許料酒。",
        "蒸 6 至 8 分鐘至開殼，不開棄掉；淋生抽麻油撒蔥花。",
      ],
    },
  },
  {
    id: "home-squid-black-bean",
    name: "Black bean squid",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Squid", "Fermented black beans"],
    optional: ["Garlic", "Ginger", "Bell pepper", "Soy sauce", "Sugar", "Chili oil", "Beef steak", "Baking soda", "Cornstarch", "Cooking oil", "Oyster sauce", "Shaoxing wine", "Chicken stock", "Sesame oil", "White pepper", "Onion", "Snow peas"],
    steps: [
      "Clean and cut 400 g squid. Rinse 1 tbsp black beans; crush with garlic.",
      "Stir-fry black-bean paste and ginger; add squid and bell pepper if using.",
      "Cook 3–4 minutes until squid is opaque. Season with soy sauce, pinch of sugar, and chili oil.",
    ],
    zh: {
      name: "豆豉鮮魷",
      steps: [
        "鮮魷約 400 克清理切件。一湯匙豆豉過水加蒜壓蓉。",
        "爆香豆豉薑蓉，下鮮魷和燈籠椒（可用）。",
        "炒 3 至 4 分鐘至熟，加生抽、少許糖和辣椒油。",
      ],
    },
  },
  {
    id: "home-salmon-miso-bowl",
    name: "Salmon miso soup bowl",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Salmon", "Miso", "Tofu"],
    optional: ["Nori", "Spring onion", "Sesame seeds", "Cooked rice", "Chicken stock", "Eggs"],
    steps: [
      "Cut 200 g salmon into bite pieces; cube 150 g tofu.",
      "Simmer salmon and tofu in about 3 cups water 5–6 minutes until salmon is opaque.",
      "Off heat, whisk in 1.5 tbsp miso. Serve over rice if you like; top with nori, spring onion, and sesame seeds.",
    ],
    zh: {
      name: "三文魚味噌湯飯",
      steps: [
        "三文魚約 200 克切件；豆腐約 150 克切塊。",
        "魚和豆腐加水約三杯煮 5 至 6 分鐘至魚熟。",
        "離火拌入一湯匙半味噌；可配飯，撒紫菜蔥花芝麻。",
      ],
    },
  },
  {
    id: "home-shrimp-corn-stir",
    name: "Shrimp corn stir-fry",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Shrimp", "Corn"],
    optional: ["Eggs", "Garlic", "Salt", "White pepper", "Spring onion", "Butter"],
    steps: [
      "Peel 250 g shrimp; use 1.5 cups corn kernels. Optional: beat 1 egg.",
      "Stir-fry garlic; cook shrimp 1–2 minutes until pink. Add corn (and butter) 2–3 minutes.",
      "Optional: scramble in egg. Season with salt and white pepper; finish with spring onion.",
    ],
    zh: {
      name: "蝦仁炒玉米",
      steps: [
        "蝦約 250 克去殼；玉米粒約一杯半。可打一隻蛋。",
        "爆香蒜蓉，炒蝦 1 至 2 分鐘，下玉米（可加牛油）2 至 3 分鐘。",
        "可倒入蛋液快炒；加鹽白胡椒撒蔥花。",
      ],
    },
  },
  {
    id: "home-fish-tomato-stew",
    name: "Tomato fish stew",
    cuisine: "Chinese",
    time: 30,
    servings: 2,
    need: ["White fish", "Tomato"],
    optional: ["Onion", "Garlic", "Ginger", "Salt", "Sugar", "White pepper", "Spring onion"],
    steps: [
      "Cut 350 g white fish into pieces. Chop 3 tomatoes and onion if using.",
      "Soften onion/garlic/ginger; add tomato and cook 8 minutes until saucy with a splash of water.",
      "Nestle fish in; simmer covered 8–10 minutes until fish flakes. Season with salt, pinch of sugar, and white pepper; top with spring onion.",
    ],
    zh: {
      name: "番茄炆魚",
      steps: [
        "白魚約 350 克切件。三個番茄切碎，可加洋蔥。",
        "炒軟洋蔥蒜薑，下番茄加水煮 8 分鐘至出汁。",
        "放入魚加蓋煮 8 至 10 分鐘至熟，加鹽、少許糖和白胡椒，撒蔥花。",
      ],
    },
  },
]
