import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W4F: Recipe[] = [
  {
    id: "home-falafel-bowl",
    name: "Falafel-style bean bowl",
    cuisine: "Western",
    time: 30,
    servings: 2,
    need: ["Beans", "Flour", "Cooked rice"],
    optional: ["Garlic", "Onion", "Cucumber", "Tomato", "Yogurt", "Lemon", "Salt", "Lettuce"],
    steps: [
      "Mash 1 can drained beans with minced garlic, grated onion, salt, and 2–3 tbsp flour until moldable; shape small patties.",
      "Pan-fry patties 3–4 minutes per side until crisp and hot through.",
      "Serve over rice or lettuce with cucumber, tomato, and yogurt lemon sauce if using.",
    ],
    zh: {
      name: "法拉費風豆餅碗",
      steps: [
        "一罐瀝乾豆子壓蓉，加蒜蓉、洋蔥茸、鹽和兩至三湯匙麵粉搓成小餅。",
        "每面煎 3 至 4 分鐘至脆熱。",
        "配飯或生菜，加青瓜番茄，可淋乳酪檸檬醬。",
      ],
    },
  },
  {
    id: "home-quesadilla-clearout",
    name: "Fridge-clear quesadilla",
    cuisine: "Western",
    time: 15,
    servings: 1,
    need: ["Tortilla", "Cheddar", "Cooked leftovers"],
    optional: ["Onion", "Bell pepper", "Tomato", "Sour cream", "Salt"],
    steps: [
      "Warm 1–2 tortillas. Scatter grated cheddar and chopped leftovers (onion/pepper/tomato OK) on half.",
      "Fold and cook in a dry pan 2–3 minutes per side until cheese melts and tortilla crisps. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Slice into wedges; serve with sour cream if you like.",
    ],
    zh: {
      name: "清冰箱起司餅",
      steps: [
        "暖一至兩張餅皮。半邊撒切達芝士和切碎剩菜（可加洋蔥椒番茄）。",
        "對摺乾鑊每面烙 2 至 3 分鐘至芝士熔餅脆。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "切角，可配酸忌廉。",
      ],
    },
  },
  {
    id: "home-shoyu-ramen-home",
    name: "Shoyu ramen home-style",
    cuisine: "Japanese",
    time: 20,
    servings: 1,
    need: ["Instant noodles", "Soy sauce", "Eggs"],
    optional: ["Spring onion", "Nori", "Spinach", "Sesame oil", "Garlic", "Cooked leftovers"],
    steps: [
      "Boil instant noodles; discard or lighten the seasoning packet. Soft-boil 1 egg 7 minutes; peel.",
      "Make broth with about 2 cups water, 1–1.5 tbsp soy sauce, minced garlic, and sesame oil if using.",
      "Add noodles, spinach if using, leftover slices, halved egg, spring onion, and nori.",
    ],
    zh: {
      name: "家常醬油拉麵",
      steps: [
        "即食麵煮熟，調味包可棄或少用。蛋煮 7 分鐘放涼去殼。",
        "約兩杯水加一至一湯匙半生抽、蒜蓉，可滴麻油成湯。",
        "下面、菠菜（可用）、剩菜片、半隻蛋、蔥花和紫菜。",
      ],
    },
  },
  {
    id: "home-satay-chicken-pan",
    name: "Pan satay chicken",
    cuisine: "Asian",
    time: 25,
    servings: 2,
    need: ["Chicken thighs", "Satay sauce", "Coconut milk", "Curry powder"],
    optional: ["Onion", "Garlic", "Soy sauce", "Cooked rice", "Cucumber", "Chili oil", "Sugar", "Cooking oil", "Ginger", "Sesame oil"],
    steps: [
      "Cut 400 g chicken thighs into strips. Mix 3 tbsp satay sauce with a splash of soy sauce and water.",
      "Stir-fry onion/garlic; add chicken 6–8 minutes until cooked through (74°C / 165°F).",
      "Pour in satay mixture; toss 2 minutes until coated. Serve with rice and cucumber; optional chili oil.",
    ],
    zh: {
      name: "沙爹雞扒條",
      steps: [
        "雞脾約 400 克切條。三湯匙沙爹醬加少許生抽和水拌匀。",
        "炒香洋蔥蒜蓉，下雞炒 6 至 8 分鐘至全熟（74°C）。",
        "倒入沙爹醬拌 2 分鐘；伴飯和青瓜，可滴辣椒油。",
      ],
    },
  },
  {
    id: "home-thai-basil-pork-mince",
    name: "Thai basil pork mince",
    cuisine: "Thai",
    time: 18,
    servings: 2,
    need: ["Ground pork", "Thai basil"],
    optional: ["Garlic", "Onion", "Soy sauce", "Sugar", "Chili oil", "Cooked rice", "Eggs", "Cooking oil", "Dried chili", "Oyster sauce"],
    steps: [
      "Mince 3 garlic cloves; slice onion if using. Pick a big handful of Thai basil.",
      "Stir-fry garlic/onion; add 300 g ground pork and cook 5–7 minutes until pork reaches 74°C / 165°F.",
      "Season with soy sauce, pinch of sugar, and chili oil; toss in basil off heat. Serve over rice with optional fried egg.",
    ],
    zh: {
      name: "九層塔炒免治豬",
      steps: [
        "三瓣蒜切蓉，可加洋蔥。摘一大把九層塔。",
        "炒香蒜洋蔥，下免治豬肉約 300 克炒 5 至 7 分鐘至全熟（74°C）。",
        "加生抽、少許糖和辣椒油，離火拌九層塔；伴飯可加煎蛋。",
      ],
    },
  },
  {
    id: "home-lemongrass-pork-bowl",
    name: "Lemongrass pork bowl",
    cuisine: "Vietnamese",
    time: 25,
    servings: 2,
    need: ["Pork chops", "Lemongrass", "Cooked rice"],
    optional: ["Garlic", "Soy sauce", "Sugar", "Cucumber", "Lettuce", "Chili oil"],
    steps: [
      "Mince tender lemongrass and garlic. Slice 300 g pork chops thinly; toss with lemongrass, garlic, soy sauce, and pinch of sugar 10 minutes.",
      "Stir-fry pork 4–5 minutes until cooked through.",
      "Serve over rice with cucumber, lettuce, and chili oil if using.",
    ],
    zh: {
      name: "香茅豬肉飯",
      steps: [
        "香茅嫩部與蒜切蓉。豬扒約 300 克切薄，加香茅蒜蓉、生抽和少許糖醃 10 分鐘。",
        "炒豬肉 4 至 5 分鐘至熟。",
        "蓋飯上，配青瓜生菜，可滴辣椒油。",
      ],
    },
  },
  {
    id: "home-gochujang-chicken-bowl",
    name: "Gochujang chicken bowl",
    cuisine: "Korean",
    time: 25,
    servings: 2,
    need: ["Chicken thighs", "Gochujang", "Cooked rice"],
    optional: ["Garlic", "Soy sauce", "Sugar", "Sesame oil", "Sesame seeds", "Spring onion", "Cucumber"],
    steps: [
      "Cut 400 g chicken thighs into bite pieces. Mix 1.5 tbsp gochujang with 1 tbsp soy sauce, 1 tsp sugar, garlic, and sesame oil.",
      "Marinate chicken 10 minutes; pan-fry 8–10 minutes until chicken reaches 74°C / 165°F and glaze sticky.",
      "Serve over rice; top with sesame seeds, spring onion, and cucumber.",
    ],
    zh: {
      name: "韓式辣椒醬雞飯",
      steps: [
        "雞脾約 400 克切件。一湯匙半韓式辣椒醬加一湯匙生抽、一茶匙糖、蒜蓉和麻油拌匀。",
        "醃 10 分鐘，煎炒 8 至 10 分鐘至全熟（74°C）醬汁黏稠。",
        "蓋飯上，撒芝麻蔥花，配青瓜。",
      ],
    },
  },
  {
    id: "home-miso-butter-pasta",
    name: "Miso butter pasta",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Pasta", "Miso", "Butter"],
    optional: ["Garlic", "Spring onion", "Soy sauce", "Sesame seeds", "Nori"],
    steps: [
      "Boil 180 g pasta until al dente; reserve 1/2 cup pasta water.",
      "Melt 1 tbsp butter with minced garlic if using; whisk in 1.5 tbsp miso and pasta water until smooth.",
      "Toss pasta in the sauce; optional splash of soy sauce. Top with spring onion, sesame seeds, and nori.",
    ],
    zh: {
      name: "味噌牛油意粉",
      steps: [
        "意粉約 180 克煮至彈牙，留半杯麵水。",
        "一湯匙牛油融化，可加蒜蓉，拌入一湯匙半味噌和麵水至滑。",
        "拌入意粉，可加少許生抽；撒蔥花芝麻紫菜。",
      ],
    },
  },
  {
    id: "home-nori-butter-onigiri",
    name: "Nori butter onigiri",
    cuisine: "Japanese",
    time: 15,
    servings: 2,
    need: ["Cooked rice", "Nori", "Butter"],
    optional: ["Salt", "Soy sauce", "Sesame seeds", "Canned tuna"],
    steps: [
      "Season warm cooked rice lightly with salt. Optional: mix in flaked tuna.",
      "Shape into triangles or balls with wet hands; wrap with nori strips.",
      "Warm a little butter in a pan; sear onigiri 1–2 minutes per side until lightly toasted. Optional soy brush.",
    ],
    zh: {
      name: "紫菜牛油飯糰",
      steps: [
        "熱飯略加鹽；可拌吞拿魚碎。",
        "濕手捏成三角或圓形，包紫菜。",
        "少許牛油鑊中每面烙 1 至 2 分鐘至微焦；可掃生抽。",
      ],
    },
  },
  {
    id: "home-udon-curry-home",
    name: "Home curry udon",
    cuisine: "Japanese",
    time: 25,
    servings: 2,
    need: ["Udon", "Curry powder", "Onion"],
    optional: ["Chicken thighs", "Carrots", "Potato", "Soy sauce", "Spring onion"],
    steps: [
      "Cook udon; drain. Slice onion; cube optional chicken, carrot, and potato.",
      "Soften onion; stir in 1–2 tsp curry powder. Add veggies/chicken and about 2.5 cups water; simmer until chicken reaches 74°C / 165°F if using (12–15 minutes).",
      "Season with soy sauce; pour over udon. Top with spring onion.",
    ],
    zh: {
      name: "家常咖喱烏冬",
      steps: [
        "烏冬煮熟瀝乾。洋蔥切片；可加雞、紅蘿蔔薯仔切塊。",
        "炒軟洋蔥，下 1 至 2 茶匙咖喱粉；下菜和雞加水約兩杯半，有雞則煮至全熟（74°C）約 12 至 15 分鐘。",
        "加生抽淋在烏冬上，撒蔥花。",
      ],
    },
  },
  {
    id: "home-peanut-satay-tofu",
    name: "Peanut satay tofu",
    cuisine: "Asian",
    time: 20,
    servings: 2,
    need: ["Tofu", "Satay sauce"],
    optional: ["Peanut butter", "Soy sauce", "Garlic", "Cucumber", "Cooked rice", "Chili oil"],
    steps: [
      "Cube 300 g tofu; pan-sear until golden on most sides.",
      "Mix 2 tbsp satay sauce with optional peanut butter, soy sauce, and a splash of water; pour over tofu.",
      "Simmer 2–3 minutes until coated. Serve with rice and cucumber; optional chili oil.",
    ],
    zh: {
      name: "沙爹花生豆腐",
      steps: [
        "豆腐約 300 克切塊，煎至多面金黃。",
        "兩湯匙沙爹醬可加花生醬、生抽和少許水，倒入鍋中。",
        "炆 2 至 3 分鐘至裹醬；伴飯青瓜，可滴辣椒油。",
      ],
    },
  },
  {
    id: "home-doenjang-veg-stew",
    name: "Doenjang vegetable stew",
    cuisine: "Korean",
    time: 25,
    servings: 2,
    need: ["Doenjang", "Zucchini", "Tofu"],
    optional: ["Onion", "Garlic", "Mushroom", "Potato", "Spring onion", "Salt"],
    steps: [
      "Cube zucchini, tofu, and optional potato/mushroom. Soften onion/garlic in a pot.",
      "Dissolve 2 tbsp doenjang in about 3.5 cups water; add vegetables and tofu.",
      "Simmer 12–15 minutes until soft. Adjust salt; top with spring onion.",
    ],
    zh: {
      name: "大醬蔬菜鍋",
      steps: [
        "翠玉瓜、豆腐切塊，可加薯仔蘑菇。炒軟洋蔥蒜蓉。",
        "兩湯匙大醬溶於約三杯半水，下蔬菜豆腐。",
        "煮 12 至 15 分鐘至軟，調鹽撒蔥花。",
      ],
    },
  },
  {
    id: "home-kimchi-quesadilla",
    name: "Kimchi cheese quesadilla",
    cuisine: "Korean",
    time: 12,
    servings: 1,
    need: ["Kimchi", "Tortilla", "Cheddar"],
    optional: ["Spring onion", "Sesame oil", "Cooked leftovers"],
    steps: [
      "Chop 1/2 cup kimchi; squeeze lightly. Warm tortilla; add cheddar, kimchi, optional leftover bits and spring onion.",
      "Fold and cook 2–3 minutes per side until cheese melts.",
      "Optional brush of sesame oil on the outside for aroma. Slice and serve.",
    ],
    zh: {
      name: "泡菜芝士餅",
      steps: [
        "半杯泡菜切碎略擠乾。暖餅皮，放芝士、泡菜，可加剩菜和蔥花。",
        "對摺每面烙 2 至 3 分鐘至芝士熔。",
        "外皮可薄掃麻油增香，切件。",
      ],
    },
  },
  {
    id: "home-viet-lemongrass-bowl",
    name: "Vietnamese-style lemongrass bowl",
    cuisine: "Vietnamese",
    time: 25,
    servings: 2,
    need: ["Chicken thighs", "Lemongrass", "Cooked rice"],
    optional: ["Garlic", "Soy sauce", "Sugar", "Cucumber", "Lettuce", "Carrots", "Chili oil"],
    steps: [
      "Mince lemongrass and garlic. Cut 350 g chicken into strips; toss with lemongrass, garlic, soy sauce, and sugar 10 minutes.",
      "Stir-fry until chicken reaches 74°C / 165°F (6–8 minutes).",
      "Serve over rice with cucumber, lettuce, carrot, and chili oil if using.",
    ],
    zh: {
      name: "越式香茅雞飯",
      steps: [
        "香茅蒜蓉切碎。雞脾約 350 克切條，加香茅蒜、生抽和糖醃 10 分鐘。",
        "炒至全熟（74°C）約 6 至 8 分鐘。",
        "蓋飯上，配青瓜生菜紅蘿蔔，可滴辣椒油。",
      ],
    },
  },
  {
    id: "home-thai-coconut-noodles",
    name: "Thai coconut noodle bowl",
    cuisine: "Thai",
    time: 25,
    servings: 2,
    need: ["Noodles", "Coconut milk", "Shrimp", "Curry powder"],
    optional: ["Lemongrass", "Garlic", "Thai basil", "Salt", "Sugar", "Chili oil", "Zucchini", "Dried chili", "Shallot", "Ginger", "Cilantro", "Cooking oil", "Chicken stock"],
    steps: [
      "Cook noodles; drain. Soften garlic and bruised lemongrass if using; add 1 cup coconut milk and 1 cup water.",
      "Simmer 5 minutes; add 200 g shrimp (and zucchini) until shrimp are pink 3–4 minutes.",
      "Season with salt and pinch of sugar; add noodles and Thai basil. Optional chili oil.",
    ],
    zh: {
      name: "泰式椰香麵",
      steps: [
        "麵煮熟瀝乾。炒香蒜蓉，可加拍鬆香茅；下一杯椰漿和一杯水。",
        "煮 5 分鐘，下蝦約 200 克（可加翠玉瓜）煮 3 至 4 分鐘至變色。",
        "加鹽和少許糖，下面和九層塔，可滴辣椒油。",
      ],
    },
  },
  {
    id: "home-japchae-home",
    name: "Japchae home-style",
    cuisine: "Korean",
    time: 30,
    servings: 2,
    need: ["Glass noodles", "Spinach", "Carrots"],
    optional: ["Beef steak", "Onion", "Soy sauce", "Sugar", "Sesame oil", "Sesame seeds", "Garlic", "White pepper", "Spring onion", "Cooking oil"],
    steps: [
      "Soak glass noodles until pliable; boil 2–3 minutes, drain, and toss with sesame oil. Blanch spinach; squeeze dry. Julienne carrot and onion.",
      "Stir-fry optional sliced beef until just cooked; stir-fry vegetables separately.",
      "Toss noodles with soy sauce, pinch of sugar, garlic, veg, and beef. Finish with sesame seeds.",
    ],
    zh: {
      name: "家常雜菜粉絲",
      steps: [
        "粉絲浸軟煮 2 至 3 分鐘瀝乾，拌麻油。菠菜焯水擠乾。紅蘿蔔洋蔥切絲。",
        "可炒牛肉至剛熟；蔬菜分開快炒。",
        "粉絲加生抽、少許糖、蒜蓉、蔬菜和牛肉拌匀，撒芝麻。",
      ],
    },
  },
  {
    id: "home-shrimp-taco-wrap",
    name: "Shrimp taco wraps",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Tortilla", "Cabbage"],
    optional: ["Lemon", "Sour cream", "Chili oil", "Onion", "Salt", "Garlic", "Tomato"],
    steps: [
      "Peel 300 g shrimp; toss with salt, garlic, and chili oil if using. Shred cabbage; warm tortillas.",
      "Stir-fry shrimp 3–4 minutes until pink and opaque.",
      "Fill tortillas with cabbage, shrimp, tomato/onion if using, lemon juice, and sour cream.",
    ],
    zh: {
      name: "蝦肉墨西哥卷",
      steps: [
        "蝦約 300 克去殼，加鹽、蒜蓉，可加辣椒油。椰菜切絲；暖熱餅皮。",
        "炒蝦 3 至 4 分鐘至變色熟透。",
        "餅皮包椰菜、蝦、番茄洋蔥（可用），擠檸檬加酸忌廉。",
      ],
    },
  },
  {
    id: "home-coconut-shrimp-curry",
    name: "Coconut shrimp curry",
    cuisine: "Thai",
    time: 25,
    servings: 2,
    need: ["Shrimp", "Coconut milk", "Curry powder"],
    optional: ["Onion", "Garlic", "Zucchini", "Salt", "Sugar", "Cooked rice", "Thai basil", "Cooking oil", "Ginger", "Cilantro"],
    steps: [
      "Peel 300 g shrimp. Soften onion/garlic; stir in 1–2 tsp curry powder until fragrant.",
      "Add 1 cup coconut milk and a splash of water; simmer 3 minutes. Add zucchini if using.",
      "Add shrimp; cook 3–4 minutes until pink. Season with salt and pinch of sugar; toss Thai basil. Serve with rice.",
    ],
    zh: {
      name: "椰汁咖喱蝦",
      steps: [
        "蝦約 300 克去殼。炒軟洋蔥蒜蓉，下 1 至 2 茶匙咖喱粉炒香。",
        "加一杯椰漿和少許水煮 3 分鐘；可下翠玉瓜。",
        "下蝦煮 3 至 4 分鐘至變色，加鹽和少許糖，拌九層塔伴飯。",
      ],
    },
  },
  {
    id: "home-sesame-noodle-salad",
    name: "Cold sesame noodle salad",
    cuisine: "Asian",
    time: 20,
    servings: 2,
    need: ["Noodles", "Sesame seeds", "Soy sauce"],
    optional: ["Peanut butter", "Cucumber", "Carrots", "Sesame oil", "Vinegar", "Sugar", "Spring onion"],
    steps: [
      "Cook noodles; rinse under cold water and drain. Toast sesame seeds.",
      "Mix 2 tbsp soy sauce, 1 tbsp peanut butter or sesame oil, 1 tsp vinegar, and pinch of sugar with a splash of water into a dressing.",
      "Toss noodles with dressing, julienned cucumber/carrot, sesame seeds, and spring onion. Serve cold.",
    ],
    zh: {
      name: "芝麻涼麵沙律",
      steps: [
        "麵煮熟過冷河瀝乾。芝麻略炒。",
        "兩湯匙生抽、一湯匙花生醬或麻油、一茶匙醋、少許糖和少許水拌成汁。",
        "麵拌醬汁、青瓜紅蘿蔔絲、芝麻蔥花，凍食。",
      ],
    },
  },
  {
    id: "home-hummus-style-bowl",
    name: "Hummus-style bean bowl",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Beans", "Lemon", "Garlic"],
    optional: ["Olive oil", "Yogurt", "Cucumber", "Tomato", "Bread", "Salt", "Sesame seeds", "Cooked rice"],
    steps: [
      "Blend or mash 1 can drained beans with minced garlic, juice of 1/2 lemon, salt, and olive oil or yogurt until creamy.",
      "Warm bread or cooked rice as the base.",
      "Spoon bean mash over; top with cucumber, tomato, and sesame seeds.",
    ],
    zh: {
      name: "鷹嘴豆泥風豆蓉碗",
      steps: [
        "一罐瀝乾豆子壓蓉或攪拌，加蒜蓉、半個檸檬汁、鹽和橄欖油或乳酪至滑。",
        "暖熱麵包或米飯作底。",
        "鋪上豆蓉，加青瓜番茄和芝麻。",
      ],
    },
  },
]
