import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W3L: Recipe[] = [
  {
    id: "home-kung-pao-cauliflower",
    name: "Vegetarian kung pao cauliflower",
    cuisine: "Sichuan",
    time: 25,
    servings: 2,
    need: ["Cauliflower", "Peanuts", "Bell pepper"],
    optional: ["Garlic", "Ginger", "Soy sauce", "Chili oil", "Sugar", "Vinegar", "Cornstarch", "Shallot", "Cooking oil", "Salt", "Shaoxing wine", "White pepper", "Oyster sauce"],
    steps: [
      "Blanch cauliflower florets 2 minutes; drain well.",
      "Stir-fry with garlic, ginger, and bell pepper; add soy sauce, vinegar, sugar, and chili oil.",
      "Toss with peanuts 1 minute. (No meat.)",
    ],
    zh: {
      name: "素宮保菜花",
      steps: [
        "菜花焯 2 分鐘瀝乾。",
        "炒蒜薑燈籠椒，加生抽醋糖辣椒油。",
        "拌花生 1 分鐘（不含肉）。",
      ],
    },
  },
  {
    id: "home-vegan-mapo-tofu",
    name: "Vegan mapo tofu",
    cuisine: "Sichuan",
    time: 20,
    servings: 2,
    need: ["Tofu", "Chili oil", "Garlic"],
    optional: ["Ginger", "Soy sauce", "Sugar", "Cornstarch", "Spring onion", "White pepper", "Cooking oil", "Sichuan peppercorns", "Fermented black beans", "Dried chili", "Doubanjiang", "Sesame oil"],
    steps: [
      "Cube tofu; simmer gently in water 2 minutes and drain.",
      "Fry garlic, ginger, chili oil; add soy sauce, sugar, white pepper, and a splash of water.",
      "Add tofu; thicken lightly with cornstarch; spring onion. No meat or egg.",
    ],
    zh: {
      name: "全素麻婆豆腐",
      steps: [
        "豆腐切塊略焯 2 分鐘瀝乾。",
        "爆蒜薑辣椒油，加生抽糖白胡椒和少許水。",
        "下豆腐勾薄芡，撒蔥（無肉無蛋）。",
      ],
    },
  },
  {
    id: "home-singapore-noodles-no-shrimp",
    name: "Singapore noodles (no shrimp)",
    cuisine: "Hong Kong",
    time: 25,
    servings: 2,
    need: ["Rice vermicelli", "Eggs", "Chicken breast"],
    optional: ["Bean sprouts", "Onion", "Spring onion", "Soy sauce", "Curry powder", "Shrimp", "Bell pepper", "Celery", "Carrots", "Cooking oil", "Cornstarch", "Oyster sauce", "Salt", "Sugar", "Sesame oil"],
    steps: [
      "Soak vermicelli. Stir-fry chicken until 74°C / 165°F; scramble eggs.",
      "Toss noodles with curry powder or soy sauce, onion, and bean sprouts.",
      "Return chicken and eggs. No shrimp.",
    ],
    zh: {
      name: "星洲炒米（無蝦）",
      steps: [
        "米粉浸軟。雞絲炒至全熟（74°C）；炒蛋。",
        "米粉加咖哩粉或生抽、洋蔥芽菜炒匀。",
        "回雞和蛋（不含蝦）。",
      ],
    },
  },
  {
    id: "home-tofu-scramble-rice",
    name: "Tofu scramble rice",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Tofu", "Cooked rice"],
    optional: ["Spring onion", "Soy sauce", "Garlic", "Tomato", "Cornstarch", "Cooking oil", "White pepper", "Carrots", "Sesame oil", "Salt", "Shaoxing wine", "Corn"],
    steps: [
      "Crumble tofu; stir-fry with garlic until hot and lightly browned.",
      "Add cold rice and soy sauce; toss until steaming.",
      "Finish with spring onion and optional tomato. Vegetarian.",
    ],
    zh: {
      name: "豆腐炒蛋風味飯",
      steps: [
        "豆腐搓碎加蒜炒熱微焦。",
        "下隔夜飯和生抽炒至冒煙。",
        "撒蔥，可加番茄（素）。",
      ],
    },
  },
  {
    id: "home-chicken-tomato-beef-style",
    name: "Chicken tomato (beef-style)",
    cuisine: "Hong Kong",
    time: 25,
    servings: 2,
    need: ["Chicken breast", "Tomato", "Onion"],
    optional: ["Soy sauce", "Sugar", "Cornstarch", "Garlic", "Beef steak", "Baking soda", "Cooking oil", "Oyster sauce", "Sesame oil", "White pepper", "Ginger", "Shallot", "Spring onion", "Ketchup", "Shaoxing wine"],
    steps: [
      "Slice chicken; sear until cooked through (74°C / 165°F); remove.",
      "Cook tomato and onion until saucy with a pinch of sugar.",
      "Return chicken with soy sauce; serve. No beef.",
    ],
    zh: {
      name: "番茄雞片",
      steps: [
        "雞片炒至全熟（74°C）盛起。",
        "番茄洋蔥加少許糖煮至出汁。",
        "回雞加生抽（無牛肉）。",
      ],
    },
  },
  {
    id: "home-veg-dan-dan",
    name: "Vegetarian dan dan noodles",
    cuisine: "Sichuan",
    time: 15,
    servings: 1,
    need: ["Noodles", "Peanut butter"],
    optional: ["Chili oil", "Soy sauce", "Garlic", "Spring onion", "Sesame oil", "Cucumber", "Sichuan peppercorns", "Cooking oil", "Ground pork", "Shaoxing wine", "Five-spice powder", "Pickled mustard", "Sugar", "Lettuce", "Peanuts"],
    steps: [
      "Boil noodles. Whisk peanut butter, soy sauce, chili oil, garlic, and noodle water.",
      "Toss noodles in sauce.",
      "Top with cucumber and spring onion. No meat.",
    ],
    zh: {
      name: "素擔擔麵",
      steps: [
        "煮麵。花生醬、生抽、辣椒油、蒜和麵水調汁。",
        "拌麵。",
        "放青瓜蔥花（無肉）。",
      ],
    },
  },
  {
    id: "home-tofu-teriyaki",
    name: "Tofu teriyaki",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Tofu", "Soy sauce", "Sugar", "Bread"],
    optional: ["Garlic", "Ginger", "Sesame seeds", "Spring onion", "Cornstarch", "Cooking oil", "Onion", "Sesame oil"],
    steps: [
      "Pan-fry tofu slabs until golden.",
      "Add soy sauce, sugar, garlic, and ginger; glaze 2–3 minutes.",
      "Sesame seeds and spring onion.",
    ],
    zh: {
      name: "照燒豆腐",
      steps: [
        "豆腐塊煎至金黃。",
        "加生抽糖蒜薑收汁 2 至 3 分鐘。",
        "撒芝麻蔥花。",
      ],
    },
  },
  {
    id: "home-mushroom-bulgogi",
    name: "Mushroom bulgogi",
    cuisine: "Korean",
    time: 20,
    servings: 2,
    need: ["Mushroom", "Onion", "Soy sauce"],
    optional: ["Sugar", "Garlic", "Sesame oil", "Sesame seeds", "Gochujang"],
    steps: [
      "Slice mushrooms; marinate briefly in soy sauce, sugar, garlic, sesame oil.",
      "Stir-fry with onion on high until browned.",
      "Optional gochujang; sesame seeds. Vegetarian.",
    ],
    zh: {
      name: "蘑菇韓式烤肉風",
      steps: [
        "蘑菇片用生抽糖蒜麻油略醃。",
        "加大火與洋蔥炒至上色。",
        "可加韓式辣椒醬，撒芝麻（素）。",
      ],
    },
  },
  {
    id: "home-veg-bibimbap",
    name: "Vegetarian bibimbap",
    cuisine: "Korean",
    time: 25,
    servings: 2,
    need: ["Cooked rice", "Spinach", "Carrots", "Eggs"],
    optional: ["Bean sprouts", "Soy sauce", "Sesame oil", "Gochujang", "Zucchini"],
    steps: [
      "Sauté spinach, carrots, sprouts separately with sesame oil.",
      "Fry an egg. Arrange over rice.",
      "Gochujang and mix. No meat.",
    ],
    zh: {
      name: "素拌飯",
      steps: [
        "菠菜紅蘿蔔芽菜分別麻油炒。",
        "煎蛋鋪飯上。",
        "加辣椒醬拌匀（無肉）。",
      ],
    },
  },
  {
    id: "home-eggplant-mapo-veg",
    name: "Vegetarian mapo eggplant",
    cuisine: "Sichuan",
    time: 25,
    servings: 2,
    need: ["Eggplant", "Chili oil", "Garlic"],
    optional: ["Soy sauce", "Sugar", "Cornstarch", "Spring onion", "Ginger", "Ground pork", "Shaoxing wine", "Baking soda", "White pepper", "Cooking oil", "Sichuan peppercorns", "Doubanjiang", "Fermented black beans", "Chicken stock", "Sesame oil"],
    steps: [
      "Pan-fry eggplant until soft.",
      "Sauce with garlic, chili oil, soy sauce, sugar, and water; thicken.",
      "Toss eggplant; spring onion. No meat.",
    ],
    zh: {
      name: "素麻婆茄子",
      steps: [
        "茄子煎软。",
        "蒜辣椒油生抽糖加水勾芡。",
        "拌茄子撒蔥（無肉）。",
      ],
    },
  },
  {
    id: "home-no-seafood-chow-mein",
    name: "Vegetable chicken chow mein",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Noodles", "Chicken breast", "Cabbage", "Celery", "Water chestnuts"],
    optional: ["Carrots", "Bean sprouts", "Soy sauce", "Oyster sauce", "Garlic", "Peanuts", "Sesame oil", "Cornstarch", "Cooking oil", "Onion", "Chicken stock", "Salt", "Sugar"],
    steps: [
      "Stir-fry chicken until 74°C / 165°F; remove.",
      "Stir-fry cabbage and carrots; add noodles with soy/oyster sauce.",
      "Return chicken and bean sprouts. No shrimp.",
    ],
    zh: {
      name: "蔬菜雞絲炒麵",
      steps: [
        "雞絲炒至全熟（74°C）盛起。",
        "炒椰菜紅蘿蔔，下面加生抽蠔油。",
        "回雞和芽菜（無蝦）。",
      ],
    },
  },
  {
    id: "home-tofu-katsu",
    name: "Tofu katsu",
    cuisine: "Japanese",
    time: 25,
    servings: 2,
    need: ["Tofu", "Eggs", "Flour", "Bread"],
    optional: ["Salt", "Cabbage"],
    steps: [
      "Press tofu; cut slabs. Coat flour–egg–crumbs.",
      "Pan-fry until golden and hot through.",
      "Serve with cabbage. Vegetarian.",
    ],
    zh: {
      name: "豆腐吉列",
      steps: [
        "豆腐壓乾切件，沾粉蛋糠。",
        "煎至金黃熱透。",
        "配椰菜（素）。",
      ],
    },
  },
  {
    id: "home-veg-gyudon",
    name: "Mushroom onion rice bowl",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Mushroom", "Onion", "Cooked rice"],
    optional: ["Soy sauce", "Sugar", "Ginger", "Spring onion", "Salt", "White pepper", "Eggs", "Shaoxing wine", "Sesame oil", "Cooking oil"],
    steps: [
      "Simmer onion and mushrooms in soy sauce, sugar, and water until soft.",
      "Spoon over rice.",
      "Spring onion. No beef.",
    ],
    zh: {
      name: "蘑菇洋葱蓋飯",
      steps: [
        "洋蔥蘑菇加生抽糖水炆軟。",
        "蓋飯上。",
        "撒蔥（無牛）。",
      ],
    },
  },
  {
    id: "home-lentil-style-bean-stew",
    name: "Bean tomato stew",
    cuisine: "Western",
    time: 25,
    servings: 3,
    need: ["Beans", "Tomato", "Onion"],
    optional: ["Garlic", "Curry powder", "Salt", "Spinach"],
    steps: [
      "Sauté onion and garlic; add tomato and drained beans.",
      "Simmer 15 minutes; optional curry powder.",
      "Fold spinach; season. Vegan-leaning.",
    ],
    zh: {
      name: "番茄燉豆",
      steps: [
        "炒洋蔥蒜，下番茄和瀝乾豆。",
        "炆 15 分鐘，可加咖哩粉。",
        "拌菠菜調味（偏素）。",
      ],
    },
  },
  {
    id: "home-veg-sweet-sour",
    name: "Sweet and sour tofu",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Tofu", "Bell pepper", "Pineapple"],
    optional: ["Ketchup", "Vinegar", "Sugar", "Cornstarch", "Garlic", "Cooking oil", "Ginger", "Soy sauce"],
    steps: [
      "Pan-fry tofu cubes golden. Stir-fry pepper and pineapple.",
      "Mix ketchup, vinegar, sugar, and water into sauce; thicken.",
      "Toss all together. No pork.",
    ],
    zh: {
      name: "咕嚕豆腐",
      steps: [
        "豆腐丁煎金黃；炒燈籠椒菠蘿。",
        "茄汁醋糖加水勾芡。",
        "全部拌匀（無豬）。",
      ],
    },
  },
  {
    id: "home-spinach-tofu-scramble",
    name: "Spinach tofu scramble",
    cuisine: "Chinese",
    time: 12,
    servings: 2,
    need: ["Tofu", "Spinach", "Garlic"],
    optional: ["Soy sauce", "Sesame oil", "Spring onion", "Cooking oil", "Ginger", "Sugar", "Salt", "White pepper", "Shaoxing wine"],
    steps: [
      "Crumble tofu; stir-fry with garlic.",
      "Add spinach until wilted; soy sauce.",
      "Sesame oil and spring onion. Vegetarian.",
    ],
    zh: {
      name: "菠菜豆腐炒",
      steps: [
        "豆腐碎加蒜炒。",
        "下菠菜至軟，加生抽。",
        "麻油蔥花（素）。",
      ],
    },
  },
  {
    id: "home-cabbage-tofu-stew",
    name: "Cabbage tofu stew",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Cabbage", "Tofu"],
    optional: ["Garlic", "Soy sauce", "Sugar", "Sesame oil"],
    steps: [
      "Stir-fry cabbage with garlic until softening.",
      "Add tofu slabs and splash of water; simmer 8 minutes.",
      "Season with soy sauce and sugar.",
    ],
    zh: {
      name: "椰菜炆豆腐",
      steps: [
        "蒜蓉炒椰菜至软。",
        "下豆腐加水炆 8 分鐘。",
        "生抽糖調味。",
      ],
    },
  },
  {
    id: "home-veg-hot-sour-soup",
    name: "Vegetarian hot and sour soup",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Tofu", "Mushroom", "Eggs"],
    optional: ["Vinegar", "White pepper", "Soy sauce", "Cornstarch", "Chicken stock", "Salt", "Sugar", "Sesame oil", "Spring onion"],
    steps: [
      "Simmer mushrooms and tofu strips in water 8 minutes.",
      "Season with vinegar, white pepper, and soy sauce; thicken.",
      "Optional egg ribbons. No meat.",
    ],
    zh: {
      name: "素酸辣湯",
      steps: [
        "蘑菇豆腐絲加水煮 8 分鐘。",
        "醋白胡椒生抽調味勾芡。",
        "可加蛋花（無肉）。",
      ],
    },
  },
  {
    id: "home-zucchini-noodles-stir",
    name: "Zucchini noodle stir-fry",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Zucchini", "Garlic", "Eggs", "Ground pork", "Glass noodles"],
    optional: ["Soy sauce", "Carrots", "Sesame oil", "Shaoxing wine", "Cornstarch", "Chicken stock", "Oyster sauce", "Sugar", "Cooking oil", "Ginger", "Spring onion"],
    steps: [
      "Julienne zucchini as noodle strands. Scramble eggs; remove.",
      "Stir-fry zucchini and carrot quickly with garlic.",
      "Return eggs; soy sauce and sesame oil.",
    ],
    zh: {
      name: "翠玉瓜炒麵風",
      steps: [
        "翠玉瓜切絲。炒蛋盛起。",
        "快炒瓜絲紅蘿蔔配蒜。",
        "回蛋，生抽麻油。",
      ],
    },
  },
  {
    id: "home-pepper-tofu-stir",
    name: "Bell pepper tofu stir-fry",
    cuisine: "Cantonese",
    time: 18,
    servings: 2,
    need: ["Tofu", "Bell pepper"],
    optional: ["Onion", "Garlic", "Soy sauce", "Oyster sauce", "Beef steak", "Baking soda", "Sesame oil", "Cornstarch", "Cooking oil", "Shaoxing wine", "Salt", "Sugar", "White pepper", "Chicken stock"],
    steps: [
      "Pan-fry tofu; remove. Stir-fry pepper and onion with garlic.",
      "Return tofu with soy/oyster sauce.",
      "Toss 1 minute.",
    ],
    zh: {
      name: "燈籠椒炒豆腐",
      steps: [
        "豆腐煎香盛起；炒燈籠椒洋蔥蒜。",
        "回豆腐加生抽蠔油。",
        "拌 1 分鐘。",
      ],
    },
  },
  {
    id: "home-veg-claypot-rice",
    name: "Vegetable claypot-style rice",
    cuisine: "Hong Kong",
    time: 35,
    servings: 2,
    need: ["Rice", "Mushroom", "Chinese sausage", "Carrots", "Bell pepper", "Snow peas", "Eggs"],
    optional: ["Soy sauce", "Spring onion", "Cabbage", "Dried mushrooms", "Sesame oil", "Salt", "Onion", "Cooking oil", "Garlic", "White pepper", "Shaoxing wine"],
    steps: [
      "Cook rice in a heavy pot. Top with mushrooms and optional sliced sausage.",
      "Steam/cook until rice done; sausage heated through if used.",
      "Drizzle soy sauce; spring onion. (Omit sausage for vegetarian.)",
    ],
    zh: {
      name: "蔬菜煲仔飯風",
      steps: [
        "厚煲煮飯，鋪蘑菇（可加臘腸片）。",
        "煮至飯熟；有臘腸須熱透。",
        "淋生抽撒蔥（素食可免臘腸）。",
      ],
    },
  },
  {
    id: "home-no-red-meat-pasta",
    name: "Chicken tomato pasta",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Pasta", "Chicken breast", "Tomato"],
    optional: ["Garlic", "Onion", "Olive oil", "Salt", "Chicken stock", "White pepper"],
    steps: [
      "Cook pasta. Sauté chicken until 74°C / 165°F; remove.",
      "Make tomato-garlic sauce; return chicken.",
      "Toss with pasta. No red meat.",
    ],
    zh: {
      name: "雞肉番茄意粉",
      steps: [
        "煮意粉。雞片炒至全熟（74°C）盛起。",
        "煮番茄蒜汁回雞。",
        "拌麵（無紅肉）。",
      ],
    },
  },
  {
    id: "home-salmon-avocado-bowl",
    name: "Salmon avocado bowl",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Salmon", "Avocado", "Cooked rice"],
    optional: ["Soy sauce", "Sesame seeds", "Cucumber", "Lemon"],
    steps: [
      "Pan-sear salmon until just opaque; flake.",
      "Bowl rice with avocado and cucumber.",
      "Top salmon; soy sauce and sesame.",
    ],
    zh: {
      name: "三文魚牛油果飯",
      steps: [
        "三文魚煎至刚熟撕碎。",
        "飯碗放牛油果青瓜。",
        "鋪魚，生抽芝麻。",
      ],
    },
  },
  {
    id: "home-veg-ramen-home",
    name: "Vegetable miso ramen",
    cuisine: "Japanese",
    time: 20,
    servings: 1,
    need: ["Instant noodles", "Miso", "Mushroom", "Carrots", "Cabbage", "Snow peas"],
    optional: ["Spinach", "Spring onion", "Eggs", "Tofu", "Nori", "Soy sauce", "Sugar", "Sesame oil", "White pepper", "Cooking oil", "Garlic", "Shaoxing wine"],
    steps: [
      "Simmer mushrooms; dissolve miso off heat into broth.",
      "Cook instant noodles in broth (discard seasoning packet or use lightly).",
      "Add spinach/tofu; top spring onion and nori. Vegetarian-friendly.",
    ],
    zh: {
      name: "蔬菜味噌拉麵",
      steps: [
        "煮蘑菇湯，熄火化味噌。",
        "用湯煮即食麵（調味包可少用）。",
        "下菠菜豆腐，撒蔥紫菜（素食友好）。",
      ],
    },
  },
  {
    id: "home-egg-white-tomato",
    name: "Tomato egg white scramble",
    cuisine: "Chinese",
    time: 12,
    servings: 1,
    need: ["Eggs", "Tomato"],
    optional: ["Salt", "Spring onion", "Sugar"],
    steps: [
      "Use 3 egg whites (or whole eggs). Scramble softly; remove.",
      "Cook tomato until saucy.",
      "Fold whites back; spring onion.",
    ],
    zh: {
      name: "番茄蛋白炒",
      steps: [
        "用 3 隻蛋白（或全蛋）炒嫩盛起。",
        "番茄煮至出汁。",
        "拌回蛋白，撒蔥。",
      ],
    },
  },
  {
    id: "home-garlic-broccoli-tofu",
    name: "Garlic broccoli tofu",
    cuisine: "Chinese",
    time: 18,
    servings: 2,
    need: ["Broccoli", "Tofu", "Garlic"],
    optional: ["Soy sauce", "Oyster sauce", "Sesame oil", "Shaoxing wine", "Sugar", "Chicken stock", "White pepper", "Cooking oil", "Cornstarch"],
    steps: [
      "Blanch broccoli; pan-fry tofu.",
      "Fry garlic; toss broccoli and tofu with soy/oyster sauce.",
      "Sesame oil finish. Vegetarian if oyster sauce omitted.",
    ],
    zh: {
      name: "蒜蓉西蘭花豆腐",
      steps: [
        "西蘭花焯水；豆腐煎香。",
        "爆蒜拌菜和豆腐，加生抽蠔油。",
        "淋麻油（免蠔油可全素）。",
      ],
    },
  },
  {
    id: "home-cucumber-miso",
    name: "Cucumber miso salad",
    cuisine: "Japanese",
    time: 8,
    servings: 2,
    need: ["Cucumber", "Miso"],
    optional: ["Sugar", "Sesame seeds", "Sesame oil", "Garlic", "Cooking oil", "Vinegar"],
    steps: [
      "Slice cucumber; salt briefly and drain.",
      "Mix miso with a pinch of sugar and sesame oil.",
      "Toss; sesame seeds.",
    ],
    zh: {
      name: "味噌青瓜",
      steps: [
        "青瓜切片略醃瀝乾。",
        "味噌加少許糖麻油。",
        "拌匀撒芝麻。",
      ],
    },
  },
  {
    id: "home-tomato-egg-veg-soup",
    name: "Tomato egg veg soup",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Tomato", "Eggs", "Spinach"],
    optional: ["Salt", "White pepper", "Sesame oil"],
    steps: [
      "Simmer tomato wedges 5 minutes; add spinach.",
      "Stream in beaten egg while stirring.",
      "Season. Light vegetarian soup.",
    ],
    zh: {
      name: "番茄蛋菜湯",
      steps: [
        "番茄煮 5 分鐘下菠菜。",
        "邊攪邊倒蛋液。",
        "調味（清淡素湯）。",
      ],
    },
  },
  {
    id: "home-soy-butter-corn",
    name: "Soy butter corn rice",
    cuisine: "Japanese",
    time: 10,
    servings: 2,
    need: ["Cooked rice", "Corn", "Butter"],
    optional: ["Soy sauce", "Spring onion"],
    steps: [
      "Warm rice with butter.",
      "Stir in corn and soy sauce.",
      "Spring onion. Vegetarian.",
    ],
    zh: {
      name: "醬油牛油粟米飯",
      steps: [
        "牛油炒熱飯。",
        "拌粟米和生抽。",
        "撒蔥（素）。",
      ],
    },
  },
  {
    id: "home-herb-tofu-salad",
    name: "Cold tofu herb salad",
    cuisine: "Chinese",
    time: 10,
    servings: 2,
    need: ["Silken tofu", "Spring onion", "Carrots", "Cucumber", "Celery", "Bread"],
    optional: ["Soy sauce", "Sesame oil", "Garlic", "Chili oil", "Thai basil", "Sugar", "White pepper", "Vinegar", "Cilantro"],
    steps: [
      "Plate silken tofu; top with spring onion and optional basil.",
      "Dress with soy sauce, sesame oil, garlic, chili oil.",
      "No-cook vegetarian.",
    ],
    zh: {
      name: "涼拌香草豆腐",
      steps: [
        "嫩豆腐上碟，放蔥和羅勒。",
        "淋生抽麻油蒜辣椒油。",
        "免煮素食。",
      ],
    },
  },
]
