import type { Recipe } from "@/lib/recipes"

/**
 * Cuisine expansion w6a — title-matched exclusive sources only.
 * Materials (groups/amounts) synced from each dish sourceUrl.
 */
export const MORE_W6A: Recipe[] = [
  {
    id: "home-butter-chicken",
    name: "Butter chicken",
    cuisine: "Indian",
    time: 35,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/butter_chicken_01541",
    sourceName: "BBC Food",
    materials: [
      { name: "Chicken thighs", role: "core", group: "main", amount: 3, note: "boneless, skinless , trimmed and cut into 2cm/0.75in chunks" },
      { name: "Cardamom", role: "core", group: "main", amount: 6, note: "green  pods" },
      { name: "Fenugreek", role: "core", group: "main", note: "pinch dried  leaves" },
      { name: "Lemon", role: "core", group: "main", amount: 1, unit: "tbsp", note: "juice" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tsp", note: "sunflower oil" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 1, unit: "tsp" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 0.5, unit: "tsp", note: "ground" },
      { name: "Ground coriander", role: "staple", group: "main", amount: 0.5, unit: "tsp" },
      { name: "Paprika", role: "staple", group: "main", amount: 0.5, unit: "tsp", note: "(not smoked)" },
      { name: "Salt", role: "staple", group: "main", amount: 0.5, unit: "tsp", note: "flaked sea" },
      { name: "Dried chili", role: "core", group: "main", amount: 0.25, note: "flaked chillies" },
      { name: "Butter", role: "core", group: "main", amount: 2, unit: "tbsp" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, note: "cloves, finely grated" },
      { name: "Ginger", role: "staple", group: "main", amount: 15, unit: "g", note: "/0.5oz fresh root , finely grated" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 0.5, unit: "tsp", note: "ground" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "caster" },
      { name: "Tomato paste", role: "staple", group: "sauce", amount: 1.5, unit: "tbsp", note: "tomato purée" },
      { name: "Cream", role: "core", group: "main", amount: 100, unit: "ml", note: "/3.5fl oz double" },
    ],
    need: ["Chicken thighs","Cardamom","Fenugreek","Lemon","Dried chili","Butter","Cream"],
    optional: ["Cooking oil","Garam masala","Cumin","Ground coriander","Paprika","Salt","Garlic","Ginger","Turmeric","Sugar","Tomato paste"],
    steps: [
      "Preheat the oven to 220C/200C Fan/Gas 7.",
      "While the chicken is cooking, make the sauce. Heat the butter in a medium non-stick frying pan. Cook the garlic and ginger over a low heat for 1–2 minutes, or until softened but not coloured, stirring constantly. Add the garam masala, cumin, coriander and turmeric and cook for 30 seconds, stirring.",
      "Add 6 tablespoons cold water and the cream and bring to a simmer. Season with salt, to taste.",
      "Stir the chicken into the creamy sauce. Return to the oven for a further 10 minutes, or until the chicken is tender and the sauce is bubbling.",
      "Just before the chicken is done, roughly bash the cardamom pods in a pestle and mortar and remove the husks. Grind the seeds to a powder. Sprinkle the ground cardamom and remaining fenugreek over the butter chicken just before serving.",
    ],
    zh: {
      name: "奶油咖喱雞",
      steps: [
        "焗爐預熱 220°C。雞脾肉切件，與醃料拌勻，焗約 10 分鐘。",
        "另鍋熔牛油，低火炒香蒜薑，下印度綜合香料、孜然、芫荽粉和薑黃炒 30 秒。",
        "下葫蘆巴、辣椒碎、糖和番茄膏炒勻，加水與淡忌廉煮至微滾，調味。",
        "倒入焗好的雞再焗約 10 分鐘至全熟（74°C），撒豆蔻粉即可。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-chicken-tikka-masala",
    name: "Chicken tikka masala",
    cuisine: "Indian",
    time: 45,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/chickentikkamasala_67780",
    sourceName: "BBC Food",
    materials: [
      { name: "Chicken breast", role: "core", group: "main", amount: 4, note: "skinless, boneless s" },
      { name: "Curry powder", role: "staple", group: "main", amount: 4, unit: "tbsp", note: "ready-made tikka masala curry paste" },
      { name: "Yogurt", role: "core", group: "marinade", amount: 2, unit: "tbsp", note: "natural yoghurt" },
      { name: "Butter", role: "core", group: "main", amount: 3, unit: "tbsp", note: "vegetable oil or ghee (clarified )" },
      { name: "Cardamom", role: "core", group: "main", amount: 8, note: "pods" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "finely chopped" },
      { name: "Ginger", role: "staple", group: "main", amount: 3, note: "cm/1.25in piece of fresh , peeled and finely grated" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, note: "cloves, crushed" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "ground" },
      { name: "Ground coriander", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 0.5, unit: "tsp", note: "ground" },
      { name: "White pepper", role: "staple", group: "main", amount: 0.5, unit: "tsp", note: "cayenne pepper (depending on how hot you like it)" },
      { name: "Tomato", role: "core", group: "main", note: "half a 400g can chopped es" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 1.5, unit: "tsp" },
      { name: "Lemon", role: "core", group: "main", amount: 0.5, note: "juice only" },
      { name: "Salt", role: "staple", group: "main", amount: 0.5, unit: "tsp" },
    ],
    need: ["Chicken breast","Yogurt","Butter","Cardamom","Tomato","Lemon"],
    optional: ["Curry powder","Onion","Ginger","Garlic","Cumin","Ground coriander","Turmeric","White pepper","Garam masala","Salt"],
    steps: [
      "Cut the chicken into bite-size pieces and mix with the tandoori paste and yoghurt. Marinate in a non-metallic dish in the fridge for at least a couple of hours (or overnight), stirring occasionally.",
      "Heat the oil or ghee in a deep frying pan, and when it's very hot add the cinnamon, cardamom pods and onion. Fry for 5–6 minutes, or until beginning to brown, then add the ginger, garlic, cumin, coriander, turmeric and cayenne pepper.",
      "After the spices have cooked for about a minute, add the chicken with the marinade. Fry for 3–4 minutes, then add the tomatoes, chicken stock or water, garam masala, lemon juice and salt. Bring the curry to a simmer and cook on a low heat for about 10 minutes, or until the chicken is cooked through. Serve the chicken tikka masala straight away with rice or naan bread.",
    ],
    zh: {
      name: "咖喱烤雞瑪沙拉",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-chana-masala",
    name: "Chana masala",
    cuisine: "Indian",
    time: 35,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/chana_masala_24511",
    sourceName: "BBC Food",
    materials: [
      { name: "Olive oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "vegetable or" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "finely chopped" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Garlic", role: "staple", group: "main", amount: 4, note: "cloves, crushed" },
      { name: "Ginger", role: "staple", group: "main", amount: 5, note: "cm/2in piece fresh root , peeled and grated" },
      { name: "Cilantro", role: "core", group: "garnish", amount: 20, unit: "g", note: "/0.75oz fresh coriander, finely chopped, reserving a few leaves for garnish" },
      { name: "Chickpeas", role: "core", group: "main", amount: 400, unit: "g", note: "tin , drained" },
      { name: "Tomato", role: "core", group: "main", amount: 2, note: "x 400g tin chopped es" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp", note: "caster , to taste (optional)" },
      { name: "Salt", role: "staple", group: "main", note: "pinch , to taste" },
      { name: "Lemon", role: "core", group: "main", amount: 1, unit: "tbsp", note: "juice, to taste" },
    ],
    need: ["Cilantro","Chickpeas","Tomato","Lemon"],
    optional: ["Olive oil","Onion","Garam masala","Garlic","Ginger","Sugar","Salt"],
    steps: [
      "Heat the oil in a medium pan, add the onion and garam masala and cook for 5–8 minutes, until soft and translucent.",
      "Add the garlic, ginger, chillies and the chopped coriander, setting some coriander aside for garnish. Cook over a low heat for 3–5 minutes until fragrant.",
      "Add the chickpeas and tomatoes and bring to the boil. Reduce the heat and simmer uncovered for 20 minutes, until reduced to the consistency of thick soup. If it is looking too thick, add a splash of water.",
      "Remove from the heat, taste, and add the sugar, salt and lemon juice to taste.",
      "Serve sprinkled with reserved coriander leaves.",
    ],
    zh: {
      name: "鷹嘴豆咖喱",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-keralan-egg-curry",
    name: "Keralan egg curry",
    cuisine: "Indian",
    time: 30,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/keralan_egg_curry_02305",
    sourceName: "BBC Food",
    materials: [
      { name: "Potato", role: "core", group: "main", amount: 2, note: "medium-sized es (alternatively use 3–4 new potatoes), peeled and cut into wedges" },
      { name: "Eggs", role: "core", group: "main", amount: 8, note: "free-range" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "red , roughly chopped" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 0.5, unit: "tsp", note: "ground" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "oil" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 1, note: "tsp  seeds" },
      { name: "Salt", role: "staple", group: "main", note: "to taste" },
      { name: "Cooked rice", role: "core", group: "main", note: "cooked basmati rice" },
      { name: "Mustard", role: "staple", group: "main", amount: 1, unit: "tsp", note: "black  seeds" },
      { name: "Ginger", role: "staple", group: "main", amount: 2, note: "cm/0.75in fresh , julienned" },
    ],
    need: ["Potato","Eggs","Cooked rice"],
    optional: ["Onion","Turmeric","Cooking oil","Cumin","Salt","Mustard","Ginger"],
    steps: [
      "Boil the potatoes in a saucepan of boiling water, until just cooked and drain. Set aside.",
      "In a food processor or blender, blend the coconut (and any reserved coconut water) or coconut milk with the onion, chilli and turmeric to a smooth paste. Set aside.",
      "If the mixture looks dry, add a splash of water. Let the mixture simmer for 15–20 minutes, adding more water to retain a sauce consistency. It is ready when the raw onion flavour has gone.",
      "Add the reserved cooked potatoes and eggs – you may need to add a bit more water to bring it to a curry consistency. When everything is heated through, season with salt.",
      "Serve with rice and top with the grated coconut (if using), black mustard seeds, curry leaves and sliced ginger.",
    ],
    zh: {
      name: "喀拉拉咖喱蛋",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-aloo-gobi-jeera",
    name: "Aloo gobi with jeera rice",
    cuisine: "Indian",
    time: 45,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/aloo_gobi_and_jeera_rice_60396",
    sourceName: "BBC Food",
    materials: [
      { name: "Cooked rice", role: "core", group: "main", amount: 350, unit: "g", note: "/12oz basmati rice" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "sunflower oil" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "thinly sliced" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 2, unit: "tsp", note: "seeds" },
      { name: "Cardamom", role: "core", group: "main", amount: 3, note: "green  pods" },
      { name: "Butter", role: "core", group: "main", amount: 25, unit: "g", note: "/1oz  (or dairy-free alternative)" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 2, unit: "tsp", note: "ground" },
      { name: "Ginger", role: "staple", group: "main", amount: 4, note: "cm/1.5in fresh root , finely grated" },
      { name: "Fenugreek", role: "core", group: "main", amount: 3, unit: "tbsp", note: "leaves (methi)" },
      { name: "Cauliflower", role: "core", group: "main", amount: 1, note: "broken into florets, leaves chopped" },
      { name: "Potato", role: "core", group: "main", amount: 2, note: "es, cut into 2cm/0.75in cubes" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 2, unit: "tsp" },
      { name: "Salt", role: "staple", group: "main", note: "and freshly ground black pepper" },
      { name: "Cilantro", role: "core", group: "garnish", note: "handful fresh coriander, to garnish" },
    ],
    need: ["Cooked rice","Cardamom","Butter","Fenugreek","Cauliflower","Potato","Cilantro"],
    optional: ["Cooking oil","Onion","Cumin","Turmeric","Ginger","Garam masala","Salt"],
    steps: [
      "Prep ingredients as listed for Aloo gobi with jeera rice.",
      "Cook following the linked BBC Food method until proteins reach a safe temperature (poultry/mince 74°C / 165°F).",
      "Taste, adjust seasoning, and serve.",
    ],
    zh: {
      name: "薯仔椰菜花咖喱配孜然飯",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-palak-paneer",
    name: "Palak paneer",
    cuisine: "Indian",
    time: 35,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/palak_paneer_85769",
    sourceName: "BBC Food",
    materials: [
      { name: "Spinach", role: "core", group: "main", amount: 500, unit: "g", note: "/1lb 2oz" },
      { name: "Corn", role: "core", group: "main", amount: 3, unit: "tsp", note: "meal or fine polenta" },
      { name: "Butter", role: "core", group: "main", amount: 4, unit: "tsp", note: "ghee or 6 tsp sunflower or rapeseed oil" },
      { name: "Tofu", role: "core", group: "main", amount: 400, unit: "g", note: "/14oz paneer, cut into chunks" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "seeds" },
      { name: "Ginger", role: "staple", group: "main", amount: 20, unit: "g", note: "/0.75oz fresh root , peeled and grated" },
      { name: "Garlic", role: "staple", group: "main", amount: 20, unit: "g", note: "/0.75oz , finely chopped" },
      { name: "Onion", role: "staple", group: "main", amount: 125, unit: "g", note: "/4.5oz , finely chopped" },
      { name: "Dried chili", role: "core", group: "main", amount: 2, note: "green chillies, seeds in (bird’s eye or similar), chopped" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "ground" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 2, unit: "tsp" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
    ],
    need: ["Spinach","Corn","Butter","Tofu","Dried chili"],
    optional: ["Cumin","Ginger","Garlic","Onion","Turmeric","Garam masala","Salt"],
    steps: [
      "Tip the spinach into a saucepan and pour over the water. Bring to the boil and cook for 4–5 minutes until tender. Drain, reserving 50ml/2fl oz of the cooking water. Transfer the cooked spinach to a bowl.",
      "Heat 2 teaspoons of the ghee or oil in pan over a medium heat, then fry the paneer chunks until evenly browned on all sides. Transfer to a plate and set aside.",
      "Stir in the turmeric, garam masala and salt and cook for 1 minute more. Stir in the puréed spinach, lower the heat and cover the pan. Cook for another 4 minutes, then add the cooked paneer and cook for a further 2 minutes.",
      "Serve hot with a flatbread or plain rice.",
    ],
    zh: {
      name: "菠菜芝士咖喱",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-keema-peas",
    name: "Keema with peas",
    cuisine: "Indian",
    time: 35,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/keema_with_peas_51958",
    sourceName: "BBC Food",
    materials: [
      { name: "Garlic", role: "staple", group: "main", amount: 5, note: "cloves" },
      { name: "Ginger", role: "staple", group: "main", amount: 5, note: "cm/2in piece fresh root" },
      { name: "Lamb", role: "core", group: "main", amount: 500, unit: "g", note: "/1lb 2oz  mince" },
      { name: "Tomato", role: "core", group: "main", amount: 180, unit: "g", note: "/6oz es, roughly chopped" },
      { name: "Tomato paste", role: "staple", group: "sauce", amount: 1, unit: "tbsp", note: "tomato purée" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "vegetable oil" },
      { name: "Onion", role: "staple", group: "main", amount: 200, unit: "g", note: "/7oz , finely chopped" },
      { name: "Potato", role: "core", group: "main", amount: 200, unit: "g", note: "/7oz , peeled and chopped" },
      { name: "Salt", role: "staple", group: "main", note: "to taste" },
      { name: "Snow peas", role: "core", group: "main", amount: 80, unit: "g", note: "/3oz frozen green peas" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 1, unit: "tsp" },
      { name: "Lime", role: "core", group: "main", amount: 1, note: "juice only" },
      { name: "Cilantro", role: "core", group: "garnish", amount: 2, unit: "tbsp", note: "coriander, to garnish" },
    ],
    need: ["Lamb","Tomato","Potato","Snow peas","Lime","Cilantro"],
    optional: ["Garlic","Ginger","Tomato paste","Cooking oil","Onion","Salt","Garam masala"],
    steps: [
      "In a food processor, blend the garlic and ginger. Combine with the lamb mince in a large mixing bowl and set aside to marinate. Blend the tomatoes with the tomato purée and set aside.",
      "Heat the oil in a large, heavy-bottomed saucepan over a medium heat. Add the cinnamon and bay leaves and when they’re sizzling, add the onions. Fry for 15–17 minutes and as they start to turn light brown, add the chopped tomatoes and tomato purée.",
      "Fry for another 6–7 minutes until the mixture thickens and reduces slightly. Add the marinated minced lamb along with the chilli powder and cook for 5 minutes, stirring often.",
      "Add the potatoes, 200ml/7fl oz water and season to taste. Simmer over a low heat for 18–20 minutes with a lid on, stirring well after about 10 minutes.",
      "Add the green peas and garam masala, and simmer for another 5 minutes. Make sure the potatoes are cooked. Finish with lime juice and coriander, and serve immediately.",
    ],
    zh: {
      name: "免治肉青豆咖喱",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-indian-fish-curry",
    name: "Fish curry",
    cuisine: "Indian",
    time: 30,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/fish_curry_09718",
    sourceName: "BBC Food",
    materials: [
      { name: "White fish", role: "core", group: "main", amount: 800, unit: "g", note: "/1lb 12oz rohu steaks, gutted, scaled and cut into 2.5cm/1in-thick steaks acr…" },
      { name: "Salt", role: "staple", group: "main", amount: 0.5, unit: "tsp", note: "plus extra for seasoning" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 1, unit: "tsp" },
      { name: "Mustard", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "black  seeds" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "vegetable oil, for frying" },
      { name: "Onion", role: "staple", group: "main", amount: 2, note: "s, finely chopped" },
      { name: "Garlic", role: "staple", group: "main", amount: 1, note: "whole bulb  (about 8–10 cloves), peeled and pounded in a pestle and mortar" },
      { name: "Ground coriander", role: "staple", group: "main", amount: 1, note: "tsp" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 1, note: "tsp" },
      { name: "Paprika", role: "staple", group: "main", amount: 1, note: "tsp" },
      { name: "Cilantro", role: "core", group: "garnish", note: "handful of chopped coriander, plus extra leaves to garnish" },
      { name: "Dried chili", role: "core", group: "main", note: "green chillies, finely chopped" },
      { name: "Cooked rice", role: "core", group: "main", amount: 240, unit: "g", note: "/8.5–12.25oz basmati rice, cooked according to packet instructions" },
    ],
    need: ["White fish","Cilantro","Dried chili","Cooked rice"],
    optional: ["Salt","Turmeric","Mustard","Cooking oil","Onion","Garlic","Ground coriander","Garam masala","Paprika"],
    steps: [
      "Put the fish steaks in a large bowl. Sprinkle with salt and half the turmeric and mix together, making sure the fish is well coated. Set aside to marinade for a few minutes.",
      "Heat a large non-stick pan over a medium heat and add the vegetable oil. Once hot, tip in the onions and fry for 8–10 minutes over a medium-low heat until starting to colour. Season with salt and continue to cook for a few more minutes until lightly golden.",
      "Wash the fish by rinsing well with cold water. Then add to the pan along with enough hot water to cover the fish (approximately 150–200ml/5½–7fl oz). Swirl the pan to cover the fish in the sauce. Cook gently for around 6–8 minutes, carefully turning the fish halfway through cooking. The curry is ready when the fish is opaque and cooked through and the sauce has started to thicken (it should have a loose consistency). Add the freshly chopped coriander and season to taste with salt.",
      "Heat for another minute, don’t stir the pan as this might break up the fish – just give the pan a gentle swirl or shake. Serve the fish curry with sliced green chilli, extra coriander leaves and basmati rice.",
    ],
    zh: {
      name: "印式咖喱魚",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-cucumber-mint-raita",
    name: "Raita",
    cuisine: "Indian",
    time: 10,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/cucumberandmintraita_67787",
    sourceName: "BBC Food",
    materials: [
      { name: "Yogurt", role: "core", group: "marinade", amount: 250, unit: "ml", note: "/8fl oz natural yoghurt" },
      { name: "Cucumber", role: "core", group: "main", amount: 0.5, note: "grated or finely chopped" },
      { name: "Salt", role: "staple", group: "main", note: "pinch" },
      { name: "Dried chili", role: "core", group: "main", amount: 0.5, note: "green chilli, de-seeded and finely chopped (optional)" },
    ],
    need: ["Yogurt","Cucumber","Dried chili"],
    optional: ["Salt"],
    steps: [
      "Prep ingredients as listed for Raita.",
      "Cook following the linked BBC Food method until proteins reach a safe temperature (poultry/mince 74°C / 165°F).",
      "Taste, adjust seasoning, and serve.",
    ],
    zh: {
      name: "青瓜薄荷乳酪",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-mulligatawny",
    name: "Mulligatawny soup",
    cuisine: "Indian",
    time: 50,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/mulligatawny_soup_68949",
    sourceName: "BBC Food",
    materials: [
      { name: "Butter", role: "core", group: "main", amount: 25, unit: "g", note: "/1oz" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "sunflower oil" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "finely chopped" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, note: "cloves, chopped" },
      { name: "Carrots", role: "core", group: "main", amount: 2, note: "cut into 1.5cm/ ⅝in cubes" },
      { name: "Celery", role: "core", group: "main", amount: 2, note: "sticks, thinly sliced" },
      { name: "Sweet potato", role: "core", group: "main", amount: 1, note: "peeled, cut into 1.5cm/⅝in cubes" },
      { name: "Apple", role: "core", group: "main", amount: 1, note: "eating , peeled, quartered, cut into 1.5cm/⅝in cubes" },
      { name: "Curry powder", role: "staple", group: "main", amount: 1, unit: "tbsp" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 1, note: "vegetable or  cube (low-salt is best)" },
      { name: "Tomato paste", role: "staple", group: "sauce", amount: 1, unit: "tbsp", note: "tomato purée" },
      { name: "Mango", role: "core", group: "main", amount: 1, unit: "tbsp", note: "chutney" },
      { name: "Cooked rice", role: "core", group: "main", amount: 100, unit: "g", note: "/3.5oz  basmati rice" },
      { name: "Cream", role: "core", group: "main", amount: 100, unit: "g", note: "/3.5oz natural yoghurt or soured , to serve" },
      { name: "Cilantro", role: "core", group: "garnish", note: "coriander or flat-leaf parsley, to garnish (optional)" },
      { name: "Salt", role: "staple", group: "main", note: "and freshly ground black pepper" },
    ],
    need: ["Butter","Carrots","Celery","Sweet potato","Apple","Mango","Cooked rice","Cream","Cilantro"],
    optional: ["Cooking oil","Onion","Garlic","Curry powder","Chicken stock","Tomato paste","Salt"],
    steps: [
      "Melt the butter with the oil in a large saucepan and stir in the onion, garlic, carrots, celery and sweet potato. Cook over a medium heat for 10 minutes, stirring regularly until the vegetables are beginning to soften and brown lightly. Stir in the apple pieces and sprinkle over the curry powder. Cook for a further 2 minutes more, stirring as it cooks.",
      "While the soup is simmering, half-fill a medium pan with water and bring to the boil. Add the rice and return to the boil. Cook for 10 minutes, or until the rice is tender. Drain the rice in a sieve and rinse under running water until cold.",
      "Add enough water to give a good consistency, (about 150-200ml/5½-7fl oz). Heat the soup for 3–4 minutes until piping hot and check the seasoning, add salt and freshly ground black pepper to taste.",
      "Ladle the soup into deep bowls and top each with a spoonful of natural yoghurt or soured cream. Garnish with sprigs of coriander or flat-leaf parsley if you like.",
    ],
    zh: {
      name: "印式咖喱雞湯",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-chicken-korma",
    name: "Chicken korma",
    cuisine: "Indian",
    time: 40,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/chicken_korma_with_82650",
    sourceName: "BBC Food",
    materials: [
      { name: "Cooking oil", role: "staple", group: "main", amount: 50, unit: "ml", note: "/2fl oz vegetable oil" },
      { name: "Mustard", role: "staple", group: "main", amount: 1.5, unit: "tsp", note: "black  seeds" },
      { name: "Onion", role: "staple", group: "main", amount: 2, note: "s, roughly chopped" },
      { name: "Ginger", role: "staple", group: "main", amount: 3, note: "cm/1.25in piece , finely chopped or grated" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, note: "cloves, crushed" },
      { name: "Cream", role: "core", group: "main", amount: 100, unit: "g", note: "/3.5oz block ed coconut, grated" },
      { name: "Coconut milk", role: "core", group: "main", amount: 200, unit: "ml", note: "/7fl oz" },
      { name: "Dried chili", role: "core", group: "main", amount: 2, note: "green chillies, roughly chopped" },
      { name: "Salt", role: "staple", group: "main", amount: 2, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 2, unit: "tsp" },
      { name: "Chicken breast", role: "core", group: "main", amount: 3, note: "s (600g/1lb 5oz in total), cut into 1.5cm chunks" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 1, unit: "tsp" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 2, unit: "tbsp" },
      { name: "Ground coriander", role: "staple", group: "main", amount: 1.5, unit: "tbsp" },
      { name: "Cilantro", role: "core", group: "garnish", note: "handful fresh coriander, roughly chopped, to serve" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "seeds" },
      { name: "Cardamom", role: "core", group: "main", amount: 4, note: "black  pods" },
      { name: "Cooked rice", role: "core", group: "main", amount: 500, unit: "g", note: "/18oz white basmati rice, rinsed and drained" },
      { name: "Berries", role: "core", group: "main", amount: 1, unit: "tbsp", note: "goji , to serve" },
    ],
    need: ["Cream","Coconut milk","Dried chili","Chicken breast","Cilantro","Cardamom","Cooked rice","Berries"],
    optional: ["Cooking oil","Mustard","Onion","Ginger","Garlic","Salt","Sugar","Turmeric","Garam masala","Ground coriander","Cumin"],
    steps: [
      "To make the chicken korma, heat the oil in a heavy-based pan over a medium-high heat. Once hot, add the mustard seeds and fry until they fizz and pop. Add the onion, and cook for 6 minutes, then add the ginger, garlic, and curry leaves. Cook for a further 2 minutes or until golden brown.",
      "Just before serving, garnish with the chopped fresh coriander and pomegranate seeds.",
      "Add the apricot pieces and the rice. Toss together.",
      "Add the boiling water and the ground turmeric powder. Simmer on a medium-low heat until the rice is almost dry. This will take 15–20 minutes. Then put on the tight lid, switch off the heat and leave for 10 minutes to allow the rice to finish cooking.",
      "Just before serving, sprinkle the rice with the rose petals, goji berries and sliced almonds, and serve alongside the korma.",
    ],
    zh: {
      name: "奶油堅果咖喱雞",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-vegetable-curry-bbc",
    name: "Vegetable curry",
    cuisine: "Indian",
    time: 40,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/vegetablecurry_80763",
    sourceName: "BBC Food",
    materials: [
      { name: "Potato", role: "core", group: "main", amount: 2, note: "es (around 350g/12oz), peeled and cut into 2cm/0.75in chunks" },
      { name: "Carrots", role: "core", group: "main", amount: 1, note: "carrot, peeled and sliced diagonally" },
      { name: "Cauliflower", role: "core", group: "main", amount: 0.5, note: "(around 300g/10.5oz), cut into small florets and halved" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 3, unit: "tbsp", note: "sunflower or vegetable oil" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "coarsely grated or very finely chopped" },
      { name: "Curry powder", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "or hot" },
      { name: "Tomato", role: "core", group: "main", amount: 1, note: "x 227g tin chopped es" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 300, unit: "ml", note: "/10fl oz vegetable or  (made with 0.5 cube), gluten-free if required" },
      { name: "Spinach", role: "core", group: "main", amount: 100, unit: "g", note: "/3.5oz frozen peas or two large handfuls young  leaves, or a mixture" },
      { name: "Yogurt", role: "core", group: "main", note: "plain yoghurt or vegan alternative, to serve" },
      { name: "Mango", role: "core", group: "main", note: "chutney, to serve" },
    ],
    need: ["Potato","Carrots","Cauliflower","Tomato","Spinach","Yogurt","Mango"],
    optional: ["Cooking oil","Onion","Curry powder","Chicken stock"],
    steps: [
      "Half-fill a saucepan with cold water and add the potatoes and carrots. Bring to the boil and cook for 8 minutes. Add the cauliflower florets and cook for 2 minutes more. Drain in a colander and set aside.",
      "Heat the oil in a large, non-stick frying pan or wide-based saucepan. Add the onion and cook over a medium heat for 8 minutes or until well softened and lightly browned, stirring regularly. Sprinkle over the curry powder and cook for 30 seconds more, stirring.",
      "Add the tomatoes to the onions and cook for 2–3 minutes, stirring constantly. Add the stock and bring to a gentle simmer. Add the vegetables and peas or spinach and simmer gently for 5 minutes, stirring regularly. If the sauce thickens too much, add a splash of water.",
      "Serve immediately with yoghurt and mango chutney.",
    ],
    zh: {
      name: "印式雜菜咖喱",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-coconut-prawn-curry-bbc",
    name: "Coconut prawn curry",
    cuisine: "Indian",
    time: 25,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/coconut_prawn_curry_with_79671",
    sourceName: "BBC Food",
    materials: [
      { name: "Shallot", role: "core", group: "main", amount: 3, note: "banana s, roughly chopped" },
      { name: "Garlic", role: "staple", group: "main", amount: 7, note: "cloves, roughly chopped" },
      { name: "Ginger", role: "staple", group: "main", amount: 5, note: "cm/2in piece fresh root , peeled and roughly chopped" },
      { name: "Ground coriander", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 0.5, unit: "tsp", note: "ground" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 1, unit: "tsp" },
      { name: "Fenugreek", role: "core", group: "main", amount: 0.5, unit: "tsp", note: "ground" },
      { name: "Paprika", role: "staple", group: "main", amount: 0.5, unit: "tsp", note: "ground" },
      { name: "Cream", role: "core", group: "main", amount: 0.5, note: "block ed coconut, roughly chopped" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "White fish", role: "core", group: "main", amount: 300, unit: "ml", note: "/10fl oz fish stock" },
      { name: "Shrimp", role: "core", group: "main", amount: 600, unit: "g", note: "/1lb 5oz raw jumbo prawns, peeled and deveined (defrosted if frozen)" },
      { name: "Butter", role: "core", group: "main", amount: 1, unit: "tbsp", note: "ghee" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "seeds" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "chopped" },
      { name: "Cooked rice", role: "core", group: "main", amount: 300, unit: "g", note: "/10.5oz white basmati rice, soaked in cold water for 30–40 minutes" },
      { name: "Chicken stock", role: "staple", group: "main", amount: 600, unit: "ml", note: "/21fl oz vegetable stock" },
      { name: "Mustard", role: "staple", group: "main", amount: 1, unit: "tsp", note: "black  seeds" },
      { name: "Cilantro", role: "core", group: "garnish", note: "bunch fresh coriander, chopped" },
    ],
    need: ["Shallot","Fenugreek","Cream","White fish","Shrimp","Butter","Cooked rice","Cilantro"],
    optional: ["Garlic","Ginger","Ground coriander","Turmeric","Garam masala","Paprika","Salt","Cumin","Onion","Chicken stock","Mustard"],
    steps: [
      "To make the curry paste, blend the shallots, garlic, ginger and chillies to a smooth paste, using a mini food processor or stick blender.",
      "Add the creamed coconut, tamarind paste and salt. Pour in the fish stock and passata and bring to the boil, then reduce the heat to a gentle simmer and cook for 40–45 minutes, stirring frequently, until the oil separates.",
      "To finish the curry, add the prawns to the pan and cook for 8–10 minutes or until they are cooked through, stirring frequently.",
      "To make the tarka, heat the coconut oil in a small frying pan and once hot, add the mustard seeds and curry leaves. Heat for a minute or two until the seeds splutter. Add to the curry and stir together.",
      "Stir the cream into the curry. Spoon the pea pilau onto plates and serve the curry alongside, with the chopped coriander scattered over.",
    ],
    zh: {
      name: "椰汁蝦咖喱",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-baked-aloo-gobi",
    name: "Baked aloo gobi",
    cuisine: "Indian",
    time: 45,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/baked_aloo_gobi_with_32681",
    sourceName: "BBC Food",
    materials: [
      { name: "Cauliflower", role: "core", group: "main", amount: 1, note: "left whole" },
      { name: "Ginger", role: "staple", group: "main", amount: 2.5, note: "cm/1in piece fresh root , peeled and grated" },
      { name: "Dried chili", role: "core", group: "main", amount: 4, note: "green chillies, finely chopped and seeds removed" },
      { name: "Garlic", role: "staple", group: "main", amount: 4, note: "cloves, crushed" },
      { name: "Mustard", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "black  seeds" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 2, unit: "tsp", note: "ground" },
      { name: "Coconut milk", role: "core", group: "main", amount: 400, unit: "ml", note: "tin" },
      { name: "Lemon", role: "core", group: "main", amount: 1, note: "unwaxed , halved" },
      { name: "Potato", role: "core", group: "main", amount: 600, unit: "g", note: "/1lb 5oz es, scrubbed, skin left on and cut into 2cm/0.75in pieces" },
      { name: "Salt", role: "staple", group: "main", note: "and freshly ground black pepper" },
      { name: "Yogurt", role: "core", group: "main", amount: 50, unit: "g", note: "/1.75oz Greek-style yoghurt (or a thick dairy-free alternative), to serve" },
      { name: "Cilantro", role: "core", group: "garnish", note: "coriander leaves, to serve" },
      { name: "Flour", role: "staple", group: "main", amount: 200, unit: "g", note: "/7oz plain , plus extra for dusting" },
      { name: "Baking soda", role: "staple", group: "main", amount: 1, unit: "tsp", note: "baking powder" },
    ],
    need: ["Cauliflower","Dried chili","Coconut milk","Lemon","Potato","Yogurt","Cilantro"],
    optional: ["Ginger","Garlic","Mustard","Turmeric","Salt","Flour","Baking soda"],
    steps: [
      "For the aloo gobi, using a sharp pair of kitchen scissors, cut the large leaves and stalks away from the outside of the cauliflower. You can leave the smaller leaves close to the florets – they will go nice and crispy when roasted. Turn the cauliflower upside down and, using a small paring knife, carefully cut a hollow in the middle of the central stalk to help the cauliflower cook evenly. Take a casserole or lidded saucepan and half-fill it with water from the kettle and bring to the boil. Add salt to the pan, add the cauliflower, cover and simmer for 6 minutes. Drain the cauliflower and return to the pan off the heat, put the lid back on and leave the cauliflower to steam for 10 minutes.",
      "Pour the coconut milk into the casserole dish, stir well and season with a little pepper. Place the steamed cauliflower in a colander to drain off any water. When the milk starts to bubble gently, turn off the heat and place the cauliflower in the dish, then baste it with the coconut-spice mixture. Add the lemon halves to the dish and scatter the potatoes around the cauliflower so they sit in the coconut milk.",
      "Tip the dough out on a clean work surface that is lightly dusted with flour. Knead for a minute or two. Put the dough into a flour-dusted bowl and cover with a plate. Leave to rise for 10–15 minutes. It won’t rise like normal dough, but it may puff up slightly.",
      "Place a large frying pan or griddle pan that is slightly larger than your flatbreads over a medium heat. Once hot, cook each flatbread for 1–2 minutes on each side, turning with tongs, until nicely puffed up.",
      "Serve the aloo gobi with the yoghurt, almonds, coriander and flatbreads, if using.",
    ],
    zh: {
      name: "焗薯仔椰菜花",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-chicken-tikka",
    name: "Chicken tikka",
    cuisine: "Indian",
    time: 35,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/chicken_tikka_40165",
    sourceName: "BBC Food",
    materials: [
      { name: "Chicken thighs", role: "core", group: "main", amount: 800, unit: "g", note: "/1lb 12oz boned chicken (thighs, legs or breast), cut into 4cm/1.5in cubes" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 0.5, unit: "tsp", note: "ground" },
      { name: "Butter", role: "core", group: "main", amount: 40, unit: "g", note: "/1.5oz unsalted , softened" },
      { name: "Ginger", role: "staple", group: "main", amount: 40, unit: "g", note: "/1.5oz peeled fresh root" },
      { name: "Garlic", role: "staple", group: "main", amount: 6, note: "cloves, peeled" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "ground" },
      { name: "Ground coriander", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Lime", role: "core", group: "main", amount: 2, unit: "tbsp", note: "juice" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 0.5, unit: "tsp" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "rapeseed or sunflower oil" },
      { name: "Yogurt", role: "core", group: "main", amount: 150, unit: "g", note: "/5.5oz Greek-style yoghurt" },
      { name: "Salt", role: "staple", group: "main", note: "and ground black pepper" },
      { name: "White pepper", role: "staple", group: "main", amount: 2, note: "peppers, mixed colours preferably, sliced" },
      { name: "Dried chili", role: "core", group: "main", amount: 1, note: "green chillies, chopped (or to taste)" },
      { name: "Cilantro", role: "core", group: "garnish", amount: 5, note: "sprigs fresh coriander with leaves and stems, chopped" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "red , thinly sliced" },
      { name: "Bread", role: "core", group: "main", amount: 8, note: "chapatis or tortillas, to serve" },
    ],
    need: ["Chicken thighs","Butter","Lime","Yogurt","Dried chili","Cilantro","Bread"],
    optional: ["Turmeric","Ginger","Garlic","Cumin","Ground coriander","Garam masala","Cooking oil","Salt","White pepper","Onion"],
    steps: [
      "Rub salt, pepper and turmeric into the chicken and set aside in the fridge while you make the marinade.",
      "Add the chicken to the marinade in a bowl and coat well. The chicken is now best set aside in the refrigerator for at least 4–5 hours, ideally overnight. When you are ready to cook, skewer the pieces of chicken onto wooden skewers, or you can leave them loose.",
      "For the salad, combine the peppers, ginger, chilli, coriander, mint and red onion in a bowl. Drizzle over the lime juice and oil. (Alternatively you can fry the peppers and mix them into the salad once cooled.)",
      "To serve, partly cool the chicken tikka, then slice into strips. Put the tikka in a tortilla or a chapati, place some salad alongside, then roll up tightly.",
      "Heat a frying pan to hot and cook the wrap lightly on all sides. When all four sides are done, serve either whole or cut into pieces.",
    ],
    zh: {
      name: "印式烤雞塊",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-aubergine-biryani",
    name: "Aubergine biryani",
    cuisine: "Indian",
    time: 55,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/aubergine_biryani_56949",
    sourceName: "BBC Food",
    materials: [
      { name: "Yogurt", role: "core", group: "marinade", amount: 250, unit: "ml", note: "/9fl oz plain yoghurt" },
      { name: "Garlic", role: "staple", group: "main", amount: 6, note: "cloves, finely crushed" },
      { name: "Ginger", role: "staple", group: "main", amount: 30, unit: "g", note: "/1oz fresh root , finely grated" },
      { name: "Dried chili", role: "core", group: "main", amount: 3, note: "green chillies, finely chopped (don’t remove the seeds)" },
      { name: "Ground coriander", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 0.5, unit: "tsp", note: "ground" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 150, unit: "ml", note: "/0.25 pint vegetable oil" },
      { name: "Onion", role: "staple", group: "main", amount: 3, note: "s, thinly sliced" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 1, unit: "tsp" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "seeds" },
      { name: "Eggplant", role: "core", group: "main", amount: 750, unit: "g", note: "/1lb 10oz aubergines, cut into 3–4cm cubes" },
      { name: "Cardamom", role: "core", group: "main", amount: 5, note: "green  pods, bruised with a rolling pin" },
      { name: "Tomato", role: "core", group: "main", amount: 2, note: "es, chopped" },
      { name: "Spinach", role: "core", group: "main", amount: 200, unit: "g", note: "/7oz baby  leaves, washed" },
      { name: "Cooked rice", role: "core", group: "main", amount: 600, unit: "g", note: "/1lb 5oz basmati rice" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Butter", role: "core", group: "main", amount: 100, unit: "g", note: "/3.5oz ghee" },
      { name: "Milk", role: "core", group: "main", note: "pinch saffron soaked in 4 tbsp warm  for 15 minutes" },
      { name: "Cucumber", role: "core", group: "main", amount: 175, unit: "g", note: "/6oz unpeeled , halved lengthways" },
      { name: "Yogurt", role: "core", group: "main", amount: 275, unit: "g", note: "/9.75oz plain yoghurt" },
      { name: "Sugar", role: "staple", group: "main", amount: 0.5, unit: "tsp", note: "caster" },
      { name: "Lime", role: "core", group: "main", amount: 1, unit: "tsp", note: "juice" },
      { name: "White pepper", role: "staple", group: "main", note: "black pepper" },
    ],
    need: ["Yogurt","Dried chili","Eggplant","Cardamom","Tomato","Spinach","Cooked rice","Butter","Milk","Cucumber","Lime"],
    optional: ["Garlic","Ginger","Ground coriander","Turmeric","Cooking oil","Onion","Garam masala","Cumin","Salt","Sugar","White pepper"],
    steps: [
      "Combine all the marinade ingredients in a bowl, add the aubergine and toss to coat well. Set aside to marinate for 30 minutes.",
      "Stir in the baby spinach leaves – add a splash of water to the pan if the spinach catches on the bottom – and cook for a few more minutes until wilted. It’s important the sauce is almost dry by this stage and just coating the aubergine. Keep it warm over a low heat while you cook the rice.",
      "For the raita, scoop out the seeds from the cucumber using a teaspoon, then grate the flesh. Toss the cucumber with the salt, tip into a sieve and leave to drain for 20–30 minutes.",
      "To finish the raita, mix the drained cucumber with all the remaining raita ingredients. Taste and add a little extra salt, pepper or lime juice, if you like. Set aside.",
      "Spoon the biryani out onto a large serving platter and scatter with the remaining crisp onions and toasted cashews and pistachios. Serve with the raita.",
    ],
    zh: {
      name: "茄子香飯",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-chana-dal-tarka",
    name: "Chana dal with tarka",
    cuisine: "Indian",
    time: 50,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/chana_daal_with_tarka_62765",
    sourceName: "BBC Food",
    materials: [
      { name: "Chickpeas", role: "core", group: "main", amount: 250, unit: "g", note: "/9oz chana dal, soaked overnight or for at least 2 hours" },
      { name: "Garlic", role: "staple", group: "main", amount: 1, note: "clove" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 0.5, unit: "tsp", note: "ground" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "thinly sliced" },
      { name: "Butter", role: "core", group: "main", amount: 1, unit: "tbsp", note: "ghee" },
      { name: "Salt", role: "staple", group: "main", note: "to taste" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "seeds" },
      { name: "Mustard", role: "staple", group: "main", amount: 1, unit: "tsp", note: "seeds" },
      { name: "Ginger", role: "staple", group: "main", amount: 2.5, note: "cm/1in piece root , peeled and very thinly sliced" },
      { name: "Cilantro", role: "core", group: "garnish", note: "handful mixed fresh coriander, dill and chervil, finely chopped" },
    ],
    need: ["Chickpeas","Butter","Cilantro"],
    optional: ["Garlic","Turmeric","Onion","Salt","Cumin","Mustard","Ginger"],
    steps: [
      "Drain the chana dal and put it into a large saucepan with the garlic, red chilli powder, turmeric, cinnamon stick and salt.",
      "Cook for 15–20 minutes, or until soft. You are looking for a firm and not mushy dal. If it is a little watery, using a wooden spoon, crush some lentils around the sides of the pan to thicken the sauce. Season the dal and put it in a serving bowl.",
      "For the tarka, melt the ghee in a small frying pan over a medium heat. Fry the garlic until it starts to brown lightly. Add the cumin and mustard seeds and cook until they splutter. Quickly add the dried red chillies and curry leaves and cook for 5 seconds. Immediately pour the tarka over the dal.",
      "Garnish with the tamarind chutney, onions, herbs, ginger and chaat masala.",
    ],
    zh: {
      name: "鷹嘴豆扁豆撻卡",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-golden-egg-curry",
    name: "Golden egg curry",
    cuisine: "Indian",
    time: 30,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/golden_egg_curry_00708",
    sourceName: "BBC Food",
    materials: [
      { name: "Dried chili", role: "core", group: "main", amount: 2, note: "green chillies, de-seeded and roughly chopped" },
      { name: "Shallot", role: "core", group: "main", amount: 150, unit: "g", note: "/5.5oz s, peeled and roughly chopped" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, note: "cloves, roughly chopped" },
      { name: "Ginger", role: "staple", group: "main", amount: 25, unit: "g", note: "/1oz fresh , peeled and roughly chopped" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 15, unit: "g", note: "/0.5oz fresh , peeled and roughly chopped, or 1 tsp ground turmeric" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "vegetable oil" },
      { name: "Lemon", role: "core", group: "main", amount: 1, note: "grass stalk, trimmed and bruised" },
      { name: "Coconut milk", role: "core", group: "main", amount: 1, note: "x 400ml tin" },
      { name: "Salt", role: "staple", group: "main", amount: 2, unit: "tsp", note: "sea  flakes" },
      { name: "Eggs", role: "core", group: "main", amount: 4, note: "free-range , at room temperature" },
      { name: "Cooked rice", role: "core", group: "main", note: "rice or flatbreads (or both), to serve" },
    ],
    need: ["Dried chili","Shallot","Lemon","Coconut milk","Eggs","Cooked rice"],
    optional: ["Garlic","Ginger","Turmeric","Cooking oil","Salt"],
    steps: [
      "Blend the 2 green chillies and 1 roughly chopped green finger chilli, shallots, garlic, ginger and turmeric to a paste using a stick blender or mini food processor.",
      "Heat the oil in a heavy-based wok or a similar-sized pan with a lid, add the paste and the lemongrass and fry gently, stirring frequently, for 5 minutes, until the paste is cooked and softened.",
      "Add the coconut milk, salt and tamarind with 100ml/3½fl oz freshly boiled water. Make a couple of little incisions in each of the 3 whole finger chillies with the point of a small sharp knife and add to the pan. Turn the heat up to bring to a near boil, then reduce the heat and simmer gently for about 7 minutes, stirring frequently, until the sauce has cooked and reduced to a thick golden soup.",
      "Crack the eggs into the sauce, cover with a lid and leave to simmer very gently for about 4 minutes, or until the whites are set but the yolks still runny, or cook for longer if you want well-cooked yolks.",
      "Divide between two bowls, trying to spoon out most of the sauce from the pan first. Serve with rice, flatbreads or both.",
    ],
    zh: {
      name: "金黃咖喱蛋",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-saffron-chicken-korma",
    name: "Saffron chicken korma",
    cuisine: "Indian",
    time: 45,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/saffron_chicken_korma_69369",
    sourceName: "BBC Food",
    materials: [
      { name: "Yogurt", role: "core", group: "marinade", amount: 500, unit: "g", note: "/1lb 2oz Turkish or Greek-style yoghurt (10% fat)" },
      { name: "Garlic", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "paste" },
      { name: "Ginger", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "paste" },
      { name: "Chicken thighs", role: "core", group: "main", amount: 8, note: "(approximately 1kg/2lb 4oz), skin removed and bone in" },
      { name: "Milk", role: "core", group: "main", amount: 2, unit: "tbsp", note: "full-fat" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 6, unit: "tbsp", note: "vegetable oil" },
      { name: "Onion", role: "staple", group: "main", amount: 3, note: "white s, sliced into thin rings" },
      { name: "Cardamom", role: "core", group: "main", amount: 3, note: "green  pods" },
      { name: "Ground coriander", role: "staple", group: "main", amount: 1, unit: "tbsp" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tbsp" },
      { name: "Flour", role: "staple", group: "main", amount: 450, unit: "g", note: "/1lb wholemeal or chapati , plus extra for dusting" },
      { name: "Butter", role: "core", group: "main", amount: 4, unit: "tbsp", note: "or ghee, melted (or use oil)" },
    ],
    need: ["Yogurt","Chicken thighs","Milk","Cardamom","Butter"],
    optional: ["Garlic","Ginger","Cooking oil","Onion","Ground coriander","Salt","Sugar","Flour"],
    steps: [
      "To make the saffron chicken korma, combine the yoghurt with the garlic and ginger pastes in a small bowl.",
      "Heat the oil in the same pan again over a medium–high heat and add the bay, cassia, cardamom and clove. After a few seconds, add the ground coriander and continue to cook, stirring. After 1 minute, add the marinated chicken to the pan along with the marinade. Keeping the heat on medium–high, continue to stir gently.",
      "To shape the paratha, fold the top third of a circle down into the centre. Brush the dough with the melted butter, then lightly dust with flour. Fold the bottom third of the circle up into the centre. Again, brush with melted butter, then dust with flour.",
      "Turn the paratha over and cook the other side in the same way. The bread is cooked when it is freckled with small brown patches on both sides.",
      "Check the seasoning of the korma and season with salt and pepper if needed. Garnish the curry with the flaked almonds and fried onions and serve with the paratha on the side.",
    ],
    zh: {
      name: "藏紅花奶油咖喱雞",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-whole-eggs-coconut-curry",
    name: "Coconut egg curry",
    cuisine: "Indian",
    time: 30,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/whole_eggs_in_coconut_23624",
    sourceName: "BBC Food",
    materials: [
      { name: "Cooking oil", role: "staple", group: "main", amount: 3, unit: "tbsp", note: "vegetable oil" },
      { name: "Eggs", role: "core", group: "main", amount: 6, note: "free-range , hard-boiled, peeled and left whole" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "ground" },
      { name: "Coconut milk", role: "core", group: "main", amount: 400, unit: "ml", note: "/14fl oz" },
      { name: "Onion", role: "staple", group: "main", amount: 2, note: "red s, very thinly sliced" },
      { name: "Ginger", role: "staple", group: "main", amount: 4, note: "cm/1.5in fresh root , finely shredded" },
      { name: "Dried chili", role: "core", group: "main", amount: 3, note: "green chillies, thinly sliced, with seeds" },
      { name: "Salt", role: "staple", group: "main", amount: 0.5, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Cilantro", role: "core", group: "garnish", note: "handful of coriander leaves, chopped" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 0.5, unit: "tsp" },
      { name: "Cooked rice", role: "core", group: "main", note: "boiled basmati rice" },
    ],
    need: ["Eggs","Coconut milk","Dried chili","Cilantro","Cooked rice"],
    optional: ["Cooking oil","Turmeric","Onion","Ginger","Salt","Sugar","Garam masala"],
    steps: [
      "Prep ingredients as listed for Coconut egg curry.",
      "Cook following the linked BBC Food method until proteins reach a safe temperature (poultry/mince 74°C / 165°F).",
      "Taste, adjust seasoning, and serve.",
    ],
    zh: {
      name: "椰汁咖喱蛋",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-chickpea-spinach-egg",
    name: "Chickpea spinach and egg",
    cuisine: "Indian",
    time: 30,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/chickpea_spinach_and_egg_50755",
    sourceName: "BBC Food",
    materials: [
      { name: "Eggs", role: "core", group: "main", amount: 2, note: "free-range" },
      { name: "Olive oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "light" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 2, unit: "tsp", note: "seeds" },
      { name: "Mustard", role: "staple", group: "main", amount: 1, unit: "tsp", note: "black  seeds" },
      { name: "Curry powder", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "plus extra for sprinkling" },
      { name: "Garlic", role: "staple", group: "main", amount: 1, unit: "tsp", note: "granules" },
      { name: "Ginger", role: "staple", group: "main", amount: 1, unit: "tsp", note: "ground" },
      { name: "Tomato", role: "core", group: "main", amount: 400, unit: "g", note: "tin chopped es" },
      { name: "Chickpeas", role: "core", group: "main", amount: 400, unit: "g", note: "tin , drained and rinsed" },
      { name: "Lemon", role: "core", group: "main", amount: 1, unit: "tbsp", note: "juice" },
      { name: "Spinach", role: "core", group: "main", amount: 180, unit: "g", note: "/6oz baby leaf" },
      { name: "Salt", role: "staple", group: "main", note: "and freshly ground black pepper" },
      { name: "Cilantro", role: "core", group: "garnish", amount: 2, unit: "tbsp", note: "chopped fresh coriander, to garnish" },
    ],
    need: ["Eggs","Tomato","Chickpeas","Lemon","Spinach","Cilantro"],
    optional: ["Olive oil","Cumin","Mustard","Curry powder","Garlic","Ginger","Salt"],
    steps: [
      "Bring a small saucepan of water to the boil and cook the eggs for 6–8 minutes, or until done to your liking. When cool enough to handle, shell, halve and set aside.",
      "Meanwhile, heat the oil in a wide frying pan over a low heat. Add the cumin, black mustard seeds, curry powder, garlic granules and ground ginger and stir-fry for 1 minute.",
      "Add the tomatoes, chickpeas, lemon juice and boiling water and season with salt and pepper. Cook over a high heat for 6–8 minutes, or until reduced and thickened, stirring often. Add the spinach and cook until wilted.",
      "Divide the curry between two shallow bowls, top each with two egg halves and sprinkle over some curry powder. Scatter with coriander and serve immediately.",
    ],
    zh: {
      name: "鷹嘴豆菠菜蛋",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  }
]
