import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W5E: Recipe[] = [
  {
    id: "home-italian-caprese-salad-with-beef-tomato-black-tom",
    name: "Italian Caprese Salad with Beef Tomato Black Tomato Balsamic Pearls",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Tomato", "Mozzarella", "Thai basil"],
    optional: ["Vinegar", "Olive oil", "White pepper"],
    steps: [
      "Prep Beef steak and Tomato; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "流心水牛芝士番茄沙律伴黑醋珍珠",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-japanese-beef-rice-bowl-gyudon",
    name: "Japanese Beef Rice Bowl Gyudon",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Onion", "Garlic", "Spring onion", "Eggs"],
    optional: ["Soy sauce", "Mirin", "Chicken stock", "Sugar"],
    steps: [
      "Prep Beef steak and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "日式牛丼飯",
      steps: [
        "準備日式牛丼飯簡易醬汁比例分享 絕對比吉野家牛肉飯更好吃 日本材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-japanese-braised-pork-belly-using-vermicular-ove",
    name: "Japanese Braised Pork Belly Using Vermicular Oven Pot 2",
    cuisine: "Japanese",
    time: 45,
    servings: 3,
    need: ["Spring onion", "Ginger", "Spinach", "Eggs"],
    optional: ["Mirin", "Soy sauce", "Sugar"],
    steps: [
      "Cut Ground pork and vegetables into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "日式大根豚角煮",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-japanese-pork-bowl",
    name: "Japanese Pork Bowl",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Onion", "Cooked rice"],
    optional: ["Soy sauce", "Mirin", "Sugar"],
    steps: [
      "Prep Ground pork and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "日式醬汁豬腩片丼飯",
      steps: [
        "準備日式醬汁豬腩片丼飯簡易極速必學菜材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-japanese-soy-milk-chicken-hot-pot",
    name: "Japanese Soy Milk Chicken Hot Pot",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "日式豆乳雞肉蔬菜鍋",
      steps: [
        "準備日式豆乳雞肉蔬菜鍋只吃雞肉都很滿足的火鍋材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-japanese-steamed-egg-custard-chawanmushi-golden",
    name: "Japanese Steamed Egg Custard Chawanmushi Golden Ratio Dashi to Egg",
    cuisine: "Japanese",
    time: 45,
    servings: 3,
    need: ["Eggs", "Bread", "Chicken thighs", "Shrimp", "Salmon"],
    optional: ["Chicken stock", "Soy sauce", "Mirin", "Dashi"],
    steps: [
      "Blanch Eggs briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "日式茶碗蒸",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-jellied-tomato-consomme",
    name: "Jellied Tomato Consomme",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Tomato briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "蕃茄凍湯啫喱",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-lemon-chicken-breast-en-papillote",
    name: "Lemon Chicken Breast En Papillote",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Chicken thighs", "Lemon"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken breast and Chicken thighs plus Lemon; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken breast and cook until cooked through (74°C / 165°F).",
      "Add Chicken thighs and Lemon, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "紙包雞胸",
      steps: [
        "準備紙包雞胸材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-lemon-shredded-chicken",
    name: "Lemon Shredded Chicken",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Lemon", "Garlic", "Dried chili"],
    optional: ["Sesame seeds", "Salt", "Shaoxing wine", "Sugar", "Soy sauce", "Chicken stock", "Sesame oil"],
    steps: [
      "Prep Chicken thighs and Lemon; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add Lemon, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "涼拌檸檬手撕雞",
      steps: [
        "準備涼拌檸檬手撕雞超級開胃酸酸甜甜的手撕雞口味材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-lobster-tail-with-tomato-sauce",
    name: "Lobster Tail with Tomato Sauce",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Tomato", "Butter"],
    optional: ["Chicken stock", "Salt", "White pepper"],
    steps: [
      "Pat Shrimp dry; season with salt and white pepper. Slice Tomato if using as a side.",
      "Pan-fry in a lightly oiled skillet over medium heat until browned and cooked until just cooked.",
      "Deglaze with a splash of soy sauce or serve with a quick ginger-spring-onion drizzle.",
    ],
    zh: {
      name: "煎龍蝦尾配蕃茄龍蝦汁",
      steps: [
        "主料抹乾，加鹽白胡椒；配菜切片。",
        "中火少油煎至上色并熟透。",
        "可淋少許生抽或以薑蔥油提味。",
      ],
    },
  },
  {
    id: "home-maitake-with-garlic-and-beef-pot-rice-kamameshi",
    name: "Maitake with Garlic and Beef Pot Rice Kamameshi",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Onion", "Garlic", "Spring onion", "Rice"],
    optional: ["Soy sauce", "Dashi"],
    steps: [
      "Prep Beef steak and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "日式舞茸菇蒜片牛肉釜飯",
      steps: [
        "準備日式舞茸菇蒜片牛肉釜飯用鑄鐵鍋做出美味的釜飯 珍珠米浸過才好吃 日本Vermic材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-miso-maitake-mushroom-soup",
    name: "Miso Maitake Mushroom Soup",
    cuisine: "Japanese",
    time: 45,
    servings: 3,
    need: ["Onion", "Butter", "Mozzarella", "UHT Milk (opened)"],
    optional: ["Chicken stock", "Miso"],
    steps: [
      "Blanch Mushroom briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "白味噌舞茸菇湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-moroccan-style-braised-lamb-shanks",
    name: "Moroccan Style Braised Lamb Shanks",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Carrots", "Onion", "Garlic", "Ginger", "Bell pepper", "Cilantro", "Gochujang", "Tomato", "Chickpeas"],
    optional: ["Cumin", "Chicken stock", "Honey"],
    steps: [
      "Cut Beef steak and Onion into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "摩洛哥燉羊膝",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-mushroom-stuffed-chicken-breast",
    name: "Mushroom Stuffed Chicken Breast",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Chicken breast", "Tomato", "Mushroom", "Mozzarella", "Thai basil", "Bell pepper", "Garlic"],
    optional: [],
    steps: [
      "Heat oven to 200°C. Toss Chicken breast and Chicken thighs with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "焗釀芝士蘑菇雞胸",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-nagoya-style-deep-fried-chicken-wings",
    name: "Nagoya Style Deep Fried Chicken Wings",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Chicken wings", "Garlic", "Ginger"],
    optional: ["Sesame seeds", "Salt", "White pepper", "Cornstarch", "Soy sauce", "Mirin", "Shaoxing wine", "Sugar"],
    steps: [
      "Blanch Chicken wings briefly if it is meat; rinse. Cut Chicken thighs into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "名古屋手羽先",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-no-knead-focaccia-with-rosemary-and-garlic",
    name: "No Knead Focaccia with Rosemary and Garlic",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Flour", "Tomato"],
    optional: ["Salt", "Honey", "Olive oil"],
    steps: [
      "Prep Tofu and Pak choi; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Tofu and cook until just cooked.",
      "Add Pak choi, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "90%",
      steps: [
        "準備90%材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-okinawa-bitter-melon-salad-with-sesame-dressing",
    name: "Okinawa Bitter Melon Salad with Sesame Dressing",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Bitter melon", "Tomato"],
    optional: ["Sesame seeds", "Salt", "White pepper"],
    steps: [
      "Prep Bitter melon and vegetables; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "沖繩苦瓜沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-okinawa-simmered-pork-knuckle",
    name: "Okinawa Simmered Pork Knuckle",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Spring onion"],
    optional: ["Soy sauce", "Mirin", "Sugar"],
    steps: [
      "Prep Ground pork and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "沖繩汁煮豬手",
      steps: [
        "準備沖繩汁煮豬手腍到不用咬的豬手做法 骨膠原超豐富材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-ominipork-luncheon-vegan-risotto",
    name: "Ominipork Luncheon Vegan Risotto",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Luncheon meat", "Rice", "Mushroom", "Onion", "Garlic", "Lime"],
    optional: ["Salt", "White pepper"],
    steps: [
      "Prep Ground pork and Luncheon meat; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add Luncheon meat, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "新餐肉純素意大利飯",
      steps: [
        "準備新餐肉純素意大利飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-orange-cranberry-roasted-chicken",
    name: "Orange Cranberry Roasted Chicken",
    cuisine: "Vietnamese",
    time: 40,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "香橙蔓越莓烤雞",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-orzo-pasta-in-beef-cheek-stew-sauce",
    name: "Orzo Pasta in Beef Cheek Stew Sauce",
    cuisine: "Western",
    time: 45,
    servings: 3,
    need: ["Beef steak", "Pasta"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Beef steak and Pasta into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "燉牛肉汁燴米粒意大利麵",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-pan-fried-mushrooms-with-raw-egg-yolk",
    name: "Pan Fried Mushrooms with Raw Egg Yolk",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs", "Eggs"],
    optional: ["Salt", "White pepper"],
    steps: [
      "Prep Eggs and Mushroom; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Mushroom, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "炒蘑菇配蘭王蛋",
      steps: [
        "準備炒蘑菇配蘭王蛋材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-pan-fry-chicken-breast-with-lemon-butter-sauce",
    name: "Pan Fry Chicken Breast with Lemon Butter Sauce",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Chicken thighs", "Lemon"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Pat Chicken breast dry; season with salt and white pepper. Slice Chicken thighs if using as a side.",
      "Pan-fry in a lightly oiled skillet over medium heat until browned and cooked until cooked through (74°C / 165°F).",
      "Deglaze with a splash of soy sauce or serve with a quick ginger-spring-onion drizzle.",
    ],
    zh: {
      name: "香煎雞胸配檸檬牛油汁",
      steps: [
        "主料抹乾，加鹽白胡椒；配菜切片。",
        "中火少油煎至上色并熟透。",
        "可淋少許生抽或以薑蔥油提味。",
      ],
    },
  },
  {
    id: "home-pan-fry-pork-meat-patty-with-dried-squid-and-lot",
    name: "Pan Fry Pork Meat Patty with Dried Squid and Lotus Root",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Lotus root", "Spring onion"],
    optional: ["Soy sauce", "Sugar", "White pepper", "Oyster sauce"],
    steps: [
      "Pat Ground pork dry; season with salt and white pepper. Slice Squid if using as a side.",
      "Pan-fry in a lightly oiled skillet over medium heat until browned and cooked until cooked through (74°C / 165°F).",
      "Deglaze with a splash of soy sauce or serve with a quick ginger-spring-onion drizzle.",
    ],
    zh: {
      name: "土魷蓮藕煎肉餅飯",
      steps: [
        "主料抹乾，加鹽白胡椒；配菜切片。",
        "中火少油煎至上色并熟透。",
        "可淋少許生抽或以薑蔥油提味。",
      ],
    },
  },
  {
    id: "home-pan-roasted-chicken-breast-with-orange-salad-oil",
    name: "Pan Roasted Chicken Breast with Orange Salad Oil",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Chicken breast", "Orange"],
    optional: ["Olive oil"],
    steps: [
      "Prep Chicken breast and Chicken thighs; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "煎雞胸沙律伴香橙醬",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-pan-seared-chicken-breast-with-caesar-salad",
    name: "Pan Seared Chicken Breast with Caesar Salad",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Chicken breast", "Lettuce", "Parmesan", "Garlic", "Mustard", "Lemon", "Mayonnaise"],
    optional: ["Salt", "White pepper", "Cooking oil", "Olive oil"],
    steps: [
      "Prep Chicken breast and Chicken thighs; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "煎嫩滑雞胸 配凱撒沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-pan-seared-fish-fillet-with-taiwanese-squid-saus",
    name: "Pan Seared Fish Fillet with Taiwanese Squid Sausages",
    cuisine: "Taiwanese",
    time: 20,
    servings: 2,
    need: ["Chinese sausage", "Squid"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "White fish"],
    steps: [
      "Pat Chinese sausage dry; season with salt and white pepper. Slice Squid if using as a side.",
      "Pan-fry in a lightly oiled skillet over medium heat until browned and cooked until just cooked.",
      "Deglaze with a splash of soy sauce or serve with a quick ginger-spring-onion drizzle.",
    ],
    zh: {
      name: "煎魚柳配台灣墨魚腸",
      steps: [
        "主料抹乾，加鹽白胡椒；配菜切片。",
        "中火少油煎至上色并熟透。",
        "可淋少許生抽或以薑蔥油提味。",
      ],
    },
  },
  {
    id: "home-pan-seared-scallops-on-zucchini-noodles-with-yuz",
    name: "Pan Seared Scallops on Zucchini Noodles with Yuzu Vinegar",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Cucumber", "Daikon", "Shallot", "Garlic"],
    optional: ["Soy sauce"],
    steps: [
      "Prep Zucchini and Noodles; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Zucchini and cook until just cooked.",
      "Add Noodles, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "醬油帶子意大利黃瓜麵配柚子醋",
      steps: [
        "準備醬油帶子意大利黃瓜麵配柚子醋材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-panfried-pork-chop-in-orange-sauce",
    name: "Panfried Pork Chop in Orange Sauce",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Pork chops", "Orange", "Onion", "Orange juice"],
    optional: ["Sugar", "Salt", "White pepper"],
    steps: [
      "Pat Ground pork dry; season with salt and white pepper. Slice Pork chops if using as a side.",
      "Pan-fry in a lightly oiled skillet over medium heat until browned and cooked until cooked through (74°C / 165°F).",
      "Deglaze with a splash of soy sauce or serve with a quick ginger-spring-onion drizzle.",
    ],
    zh: {
      name: "香煎豬扒配香橙醬",
      steps: [
        "主料抹乾，加鹽白胡椒；配菜切片。",
        "中火少油煎至上色并熟透。",
        "可淋少許生抽或以薑蔥油提味。",
      ],
    },
  },
  {
    id: "home-pasta-al-quattro-pomodoro",
    name: "Pasta Al Quattro Pomodoro",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Garlic", "Tomato", "Cheddar", "Thai basil"],
    optional: ["Olive oil"],
    steps: [
      "Boil pasta in salted water until al dente; reserve ½ cup pasta water.",
      "Meanwhile sauté garlic/onion and Tomato in olive oil until just cooked.",
      "Toss pasta with the pan sauce and a splash of pasta water; adjust salt and finish with pepper or cheese if using.",
    ],
    zh: {
      name: "四重番茄意粉",
      steps: [
        "意粉盐水煮至 al dente，留半杯麵水。",
        "另鑊用橄欖油炒蒜洋蔥及主料至熟。",
        "拌入意粉和少許麵水調味，可加芝士或黑胡椒。",
      ],
    },
  },
  {
    id: "home-pea-shoots-and-pork-hot-pot",
    name: "Pea Shoots and Pork Hot Pot",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Beans", "Mozzarella"],
    optional: [],
    steps: [
      "Prep Ground pork and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "豆苗豚肉鍋",
      steps: [
        "準備豆苗豚肉鍋材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-perfect-steamed-rice-in-cast-iron-pot-in-5-steps",
    name: "Perfect Steamed Rice in Cast Iron Pot in 5 Steps",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Rice"],
    optional: [],
    steps: [
      "Arrange Cooked rice with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "鑄鐵鍋輕鬆煮白飯5步曲",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-persimmon-with-honey-lime-salad-oil",
    name: "Persimmon with Honey Lime Salad Oil",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Tomato", "Lime"],
    optional: ["Olive oil", "Honey"],
    steps: [
      "Prep Lime and vegetables; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "西班牙柿沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-pickled-cherry-tomatoes-in-japanese-plum-wine",
    name: "Pickled Cherry Tomatoes in Japanese Plum Wine",
    cuisine: "Japanese",
    time: 20,
    servings: 2,
    need: ["Tomato"],
    optional: ["Sugar"],
    steps: [
      "Prep Tomato and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Tomato and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "梅酒漬車厘茄",
      steps: [
        "準備梅酒漬車厘茄材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-poached-egg-on-avocado-sour-dough-toast",
    name: "Poached Egg on Avocado Sour Dough Toast",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Bread", "Avocado", "Salmon", "Eggs"],
    optional: ["Vinegar", "White pepper"],
    steps: [
      "Prep Salmon and White fish plus Avocado; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Salmon and cook until just cooked.",
      "Add White fish and Avocado, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "牛油果吐司配煙三文魚水波蛋",
      steps: [
        "準備牛油果吐司配煙三文魚水波蛋材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-pork-chop-in-mushroom-balsamic-vinegar-sauce",
    name: "Pork Chop in Mushroom Balsamic Vinegar Sauce",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Ground pork", "Pork chops", "Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Pat Ground pork dry; season with salt and white pepper. Slice Pork chops if using as a side.",
      "Pan-fry in a lightly oiled skillet over medium heat until browned and cooked until cooked through (74°C / 165°F).",
      "Deglaze with a splash of soy sauce or serve with a quick ginger-spring-onion drizzle.",
    ],
    zh: {
      name: "香煎豬梅頭扒配蘑菇黑醋汁",
      steps: [
        "主料抹乾，加鹽白胡椒；配菜切片。",
        "中火少油煎至上色并熟透。",
        "可淋少許生抽或以薑蔥油提味。",
      ],
    },
  },
  {
    id: "home-pork-chop-with-caramelized-apple",
    name: "Pork Chop with Caramelized Apple",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Garlic", "Apple", "Butter"],
    optional: ["Sugar"],
    steps: [
      "Pat Ground pork dry; season with salt and white pepper. Slice Pork chops if using as a side.",
      "Pan-fry in a lightly oiled skillet over medium heat until browned and cooked until cooked through (74°C / 165°F).",
      "Deglaze with a splash of soy sauce or serve with a quick ginger-spring-onion drizzle.",
    ],
    zh: {
      name: "香煎豬鞍配焦糖蘋果",
      steps: [
        "主料抹乾，加鹽白胡椒；配菜切片。",
        "中火少油煎至上色并熟透。",
        "可淋少許生抽或以薑蔥油提味。",
      ],
    },
  },
  {
    id: "home-poulet-basquaise-basque-style-chicken",
    name: "Poulet Basquaise Basque Style Chicken",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Onion", "Bell pepper", "Garlic", "Tomato"],
    optional: ["Paprika", "Chicken stock"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "巴斯克燉雞",
      steps: [
        "準備巴斯克燉雞簡單又好吃的燉雞 第一次煮就可學會材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-red-wine-braised-beef-tongue",
    name: "Red Wine Braised Beef Tongue",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Carrots", "Celery", "Onion", "Bacon", "Garlic", "Flour", "Butter"],
    optional: [],
    steps: [
      "Cut Beef steak and vegetables into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "紅酒燉牛舌",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-rigatoni-in-creamy-tomato-sauce-with-cod-fish",
    name: "Rigatoni in Creamy Tomato Sauce with Cod Fish",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["White fish", "Tomato", "Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep White fish and Tomato plus Noodles; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add White fish and cook until just cooked.",
      "Add Tomato and Noodles, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "鱈魚柳配手工蕃茄醬意大利麵",
      steps: [
        "準備鱈魚柳配手工蕃茄醬意大利麵材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-roast-chicken-leg-with-rosemary-in-cast-iron-pot",
    name: "Roast Chicken Leg with Rosemary in Cast Iron Pot",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Chicken thighs", "Garlic", "Carrots"],
    optional: ["White pepper"],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "香草煎焗雞腿",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-roasted-butternut-squash-soup",
    name: "Roasted Butternut Squash Soup",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Butter", "Onion", "Garlic", "Cream", "Cardamom", "Pumpkin", "Bacon"],
    optional: ["Chicken stock"],
    steps: [
      "Blanch Pumpkin briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "南瓜濃湯盅",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-roasted-chicken-stuffed-with-black-truffle-and-m",
    name: "Roasted Chicken Stuffed with Black Truffle and Mushrooms",
    cuisine: "Chinese",
    time: 40,
    servings: 2,
    need: ["Eggs", "Butter", "Garlic", "Chicken thighs", "Mushroom", "Carrots"],
    optional: ["Salt", "White pepper"],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and Mushroom with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "香草烤雞釀黑松露雜菌",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-roasted-pork-in-dutch-oven",
    name: "Roasted Pork in Dutch Oven",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Carrots", "Onion"],
    optional: ["Salt", "White pepper"],
    steps: [
      "Heat oven to 200°C. Toss Ground pork and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "露營食譜-烤焗豬肉",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-roasted-pork-shoulder-butt-in-vegetables",
    name: "Roasted Pork Shoulder Butt in Vegetables",
    cuisine: "Chinese",
    time: 40,
    servings: 2,
    need: ["Onion", "Celery", "Carrots", "Garlic", "Butter"],
    optional: ["Chicken stock", "Salt", "White pepper"],
    steps: [
      "Heat oven to 200°C. Toss Ground pork and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "蔬菜烘烤西班牙黑毛豬梅肉",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-roasted-pork-shoulder-butt-in-vegetables-2021",
    name: "Roasted Pork Shoulder Butt in Vegetables 2021",
    cuisine: "Chinese",
    time: 40,
    servings: 2,
    need: ["Onion", "Celery", "Carrots", "Garlic", "Butter"],
    optional: ["Chicken stock"],
    steps: [
      "Heat oven to 200°C. Toss Ground pork and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "蔬菜烘烤西班牙黑毛豬梅肉",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-roasted-savoy-cabbage",
    name: "Roasted Savoy Cabbage",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Cabbage", "Tomato", "Parmesan", "Bell pepper", "Butter", "Lime"],
    optional: ["Salt", "Chicken stock"],
    steps: [
      "Heat oven to 200°C. Toss Cabbage and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "烤焗皺葉椰菜",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-roasted-spring-chicken-in-furano-style",
    name: "Roasted Spring Chicken in Furano Style",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Butter", "Carrots", "Chicken thighs", "Onion", "Garlic"],
    optional: ["Salt"],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "富良野田園焗黄油春雞",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-sake-steamed-clams",
    name: "Sake Steamed Clams",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Clams", "Garlic", "Shallot", "Butter", "Spring onion"],
    optional: [],
    steps: [
      "Arrange Clams with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "清酒煮蜆",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-seared-duck-breast-salad-with-orange",
    name: "Seared Duck Breast Salad with Orange",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Chicken thighs", "Lettuce"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Prep Chicken thighs and Lettuce; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "橙肉鴨胸沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
]
