import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W4E: Recipe[] = [
  {
    id: "home-leftover-pork-fried-rice",
    name: "Leftover pork fried rice",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Cooked leftovers", "Cooked rice", "Eggs"],
    optional: ["Spring onion", "Soy sauce", "Garlic", "Sesame oil", "White pepper", "Carrots", "Corn", "Salt", "Cooking oil", "Sugar", "Chicken stock"],
    steps: [
      "Dice about 1 cup leftover pork (or mixed leftovers). Beat 2 eggs. Loosen 2 bowls cold cooked rice.",
      "Scramble eggs; remove. Stir-fry garlic if using, then leftovers 1 minute; add rice and soy sauce. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Return eggs; toss 1–2 minutes. Finish with spring onion, sesame oil, and white pepper.",
    ],
    zh: {
      name: "剩豬肉炒飯",
      steps: [
        "剩豬肉（或雜剩菜）約一杯切粒。打散兩隻蛋。兩碗隔夜飯抓散。",
        "炒蛋盛起；可爆香蒜蓉，下剩菜 1 分鐘，下飯和生抽。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "回蛋炒 1 至 2 分鐘，撒蔥花滴麻油加白胡椒。",
      ],
    },
  },
  {
    id: "home-leftover-soup-noodle",
    name: "Leftover soup noodle clearer",
    cuisine: "Asian",
    time: 15,
    servings: 1,
    need: ["Cooked leftovers", "Noodles"],
    optional: ["Spring onion", "Soy sauce", "Eggs", "Salt", "White pepper", "Spinach", "Tomato", "Sesame oil", "Vinegar", "Shrimp", "Cooking oil"],
    steps: [
      "Bring leftover soup (or leftovers plus about 3 cups water) to a simmer; season with soy sauce or salt. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Cook noodles in the broth until tender. Optional: drop in a cracked egg and spinach for 2 minutes.",
      "Top with spring onion and white pepper.",
    ],
    zh: {
      name: "剩湯清麵",
      steps: [
        "剩湯（或剩菜加水約三杯）燒開，加生抽或鹽調味。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "下面條煮至軟；可打一隻蛋和下菠菜煮 2 分鐘。",
        "撒蔥花和白胡椒。",
      ],
    },
  },
  {
    id: "home-dumpling-filling-stir",
    name: "Dumpling-filling stir-fry",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Ground pork", "Cabbage"],
    optional: ["Garlic", "Ginger", "Soy sauce", "Sesame oil", "Spring onion", "Cornstarch", "Salt"],
    steps: [
      "Mix 250 g ground pork with shredded cabbage, minced garlic/ginger, soy sauce, and cornstarch as for dumpling filling.",
      "Stir-fry the mixture on medium-high heat 6–8 minutes until pork reaches 74°C / 165°F and cabbage softens.",
      "Finish with sesame oil and spring onion. Eat with rice or wrap in lettuce.",
    ],
    zh: {
      name: "餃子餡炒菜",
      steps: [
        "免治豬肉約 250 克加椰菜絲、蒜薑蓉、生抽和生粉拌成餃子餡狀。",
        "中大火炒 6 至 8 分鐘至豬肉全熟（74°C）椰菜軟。",
        "滴麻油撒蔥花；伴飯或生菜包。",
      ],
    },
  },
  {
    id: "home-leftover-veg-frittata",
    name: "Leftover vegetable frittata",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Cooked leftovers", "Eggs", "Carrots", "Broccoli", "Celery", "Bean sprouts"],
    optional: ["Cheddar", "Onion", "Salt", "White pepper", "Milk", "Spring onion", "Garlic", "Cornstarch", "Soy sauce", "Oyster sauce", "Sugar", "Cooking oil", "Sesame oil"],
    steps: [
      "Chop about 1.5 cups leftover vegetables/protein. Beat 5 eggs with a splash of milk, salt, and white pepper.",
      "Warm leftovers in an oven-safe pan; pour eggs over and top with cheddar if using.",
      "Cook on stove 3 minutes, then bake at 190°C / 375°F for 10–12 minutes until set. Any leftover meat or poultry must reach 74°C / 165°F.",
    ],
    zh: {
      name: "剩菜烘蛋餅",
      steps: [
        "剩菜約一杯半切碎。五隻蛋加少許奶、鹽和白胡椒打散。",
        "鑊中熱透剩菜，倒入蛋液，可撒芝士。",
        "爐灶煮 3 分鐘，再 190°C 焗 10 至 12 分鐘至凝固。 隔夜肉類或家禽須煮至 74°C / 165°F。",
      ],
    },
  },
  {
    id: "home-leftover-curry-omelette",
    name: "Leftover curry omelette",
    cuisine: "Hong Kong",
    time: 15,
    servings: 1,
    need: ["Cooked leftovers", "Eggs", "Cooked rice"],
    optional: ["Curry powder", "Spring onion", "Salt", "Soy sauce"],
    steps: [
      "Warm leftover curry or saucy leftovers; loosen over cooked rice. Optional pinch of curry powder to refresh.",
      "Beat 2–3 eggs with salt; cook a thin omelette. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Drape omelette over curry rice; finish with spring onion and a drop of soy sauce if you like.",
    ],
    zh: {
      name: "剩咖喱煎蛋飯",
      steps: [
        "剩咖喱或濃汁剩菜熱透淋在飯上；可加少許咖喱粉提味。",
        "兩至三隻蛋加鹽打散，煎成薄蛋皮。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "蛋皮蓋在咖喱飯上，撒蔥花，可滴生抽。",
      ],
    },
  },
  {
    id: "home-leftover-brisket-noodles",
    name: "Leftover brisket noodle soup",
    cuisine: "Hong Kong",
    time: 20,
    servings: 2,
    need: ["Cooked leftovers", "Noodles"],
    optional: ["Spring onion", "Soy sauce", "Ginger", "Salt", "White pepper", "Choi sum", "Tomato", "Sesame oil", "Vinegar", "Shrimp", "Cooking oil", "Eggs"],
    steps: [
      "Slice leftover brisket or beef leftovers. Simmer with ginger in about 4 cups water 8–10 minutes; season with soy sauce. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Cook noodles separately; blanch choi sum if using.",
      "Assemble bowls with noodles, broth, brisket, greens, spring onion, and white pepper.",
    ],
    zh: {
      name: "剩牛腩湯麵",
      steps: [
        "剩牛腩切片，加薑加水約四杯煮 8 至 10 分鐘，加生抽調味。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "另煮麵；可焯菜心。",
        "碗中下面、湯、牛腩、蔬菜、蔥花和白胡椒。",
      ],
    },
  },
  {
    id: "home-leftover-rice-porridge",
    name: "Leftover rice porridge",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Cooked rice"],
    optional: ["Ginger", "Salt", "White pepper", "Spring onion", "Century egg", "Cooked leftovers", "Sesame oil"],
    steps: [
      "Combine 2 bowls cooked rice with about 4 cups water; simmer 15 minutes, mashing lightly until porridge-like.",
      "Add diced leftovers or century egg if using for the last 5 minutes.",
      "Season with salt and white pepper; finish with ginger, spring onion, and sesame oil.",
    ],
    zh: {
      name: "隔夜飯粥",
      steps: [
        "兩碗熟飯加水約四杯煮 15 分鐘，略壓至粥狀。",
        "最後 5 分鐘可下剩菜粒或皮蛋。",
        "加鹽白胡椒，撒薑絲蔥花滴麻油。",
      ],
    },
  },
  {
    id: "home-leftover-roast-sandwich",
    name: "Leftover roast sandwich",
    cuisine: "Western",
    time: 12,
    servings: 1,
    need: ["Cooked leftovers", "Bread"],
    optional: ["Cheddar", "Lettuce", "Tomato", "Mayonnaise", "Mustard", "Onion"],
    steps: [
      "Slice leftover roast meat or firm leftovers. Toast bread lightly.",
      "Spread mayonnaise or mustard; layer leftovers, cheddar, lettuce, tomato, and onion if using. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Press briefly in a pan until warm and cheese softens (2–3 minutes).",
    ],
    zh: {
      name: "剩烤肉三文治",
      steps: [
        "剩烤肉或較實剩菜切片。麵包略烤。",
        "塗蛋黃醬或芥末，夾剩菜、芝士、生菜番茄洋蔥（可用）。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "鑊中略壓 2 至 3 分鐘至暖熱芝士軟。",
      ],
    },
  },
  {
    id: "home-leftover-fish-pan",
    name: "Leftover fish pan-fry cakes",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Cooked leftovers", "Potato", "Eggs", "Salmon", "Shrimp"],
    optional: ["Spring onion", "Salt", "White pepper", "Flour", "Lemon", "Cilantro", "Cooking oil", "Sugar", "Chicken stock", "Cornstarch"],
    steps: [
      "Flake leftover cooked fish or seafood leftovers (about 1 cup). Mash 1 boiled potato; mix with fish, 1 egg, spring onion, salt, and white pepper.",
      "Shape into small cakes; dust with flour if using.",
      "Pan-fry 3–4 minutes per side until golden. Serve with lemon. Any leftover meat or poultry must reach 74°C / 165°F.",
    ],
    zh: {
      name: "剩魚煎餅",
      steps: [
        "剩熟魚或海鮮約一杯撕碎。一個熟薯仔壓蓉，加魚、一隻蛋、蔥花、鹽和白胡椒。",
        "搓成小餅，可拍麵粉。",
        "每面煎 3 至 4 分鐘至金黃，配檸檬。 隔夜肉類或家禽須煮至 74°C / 165°F。",
      ],
    },
  },
  {
    id: "home-leftover-wonton-clear",
    name: "Leftover wonton soup clearer",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Cooked leftovers", "Wonton wrappers", "Ground pork"],
    optional: ["Ginger", "Spring onion", "Salt", "White pepper", "Sesame oil", "Choi sum", "Soy sauce", "Shaoxing wine", "Chicken stock"],
    steps: [
      "Chop leftover mince or protein finely; place small spoonfuls on wonton wrappers and seal with water.",
      "Simmer wontons in about 4 cups water with ginger 4–5 minutes until wrappers turn translucent and filling is hot (mince to 74°C / 165°F).",
      "Add greens if using; season with salt and white pepper; finish with sesame oil and spring onion.",
    ],
    zh: {
      name: "剩餡雲吞湯",
      steps: [
        "剩肉碎切細，用雲吞皮包好，水封口。",
        "薑片加水約四杯，下雲吞煮 4 至 5 分鐘至皮透餡熱（肉類 74°C）。",
        "可下菜心；加鹽白胡椒，滴麻油撒蔥花。",
      ],
    },
  },
  {
    id: "home-leftover-veg-pancake",
    name: "Leftover vegetable pancake",
    cuisine: "Korean",
    time: 20,
    servings: 2,
    need: ["Cooked leftovers", "Eggs", "Flour", "Carrots", "Bell pepper"],
    optional: ["Spring onion", "Soy sauce", "Salt", "Kimchi", "Sichuan peppercorns", "Sesame oil", "Cooking oil", "Sesame seeds"],
    steps: [
      "Chop 1.5 cups leftover vegetables (kimchi OK). Mix with 1 egg, 1/2 cup flour, spring onion, salt, and enough water to make a thick batter.",
      "Spread in a hot oiled pan; cook 3–4 minutes per side until golden and set. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Slice and serve with soy sauce for dipping.",
    ],
    zh: {
      name: "剩菜煎餅",
      steps: [
        "剩蔬菜約一杯半切碎（可用泡菜）。加一隻蛋、半杯麵粉、蔥花、鹽和適量水成稠漿。",
        "熱油鑊攤平，每面煎 3 至 4 分鐘至金黃定形。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "切件蘸生抽。",
      ],
    },
  },
  {
    id: "home-leftover-meat-udon",
    name: "Leftover meat udon",
    cuisine: "Japanese",
    time: 15,
    servings: 1,
    need: ["Cooked leftovers", "Udon"],
    optional: ["Soy sauce", "Spring onion", "Miso", "Spinach", "Eggs", "Nori"],
    steps: [
      "Cook udon until tender; drain. Warm leftover sliced meat in a pan with soy sauce or a little miso dissolved in water.",
      "Optional: wilt spinach and soft-cook an egg. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Assemble udon with meat, greens, egg, spring onion, and nori.",
    ],
    zh: {
      name: "剩肉烏冬",
      steps: [
        "烏冬煮軟瀝乾。剩肉片加生抽或少許味噌水熱透。",
        "可炒軟菠菜和半熟蛋。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "烏冬上放肉、蔬菜、蛋、蔥花和紫菜。",
      ],
    },
  },
  {
    id: "home-leftover-tofu-bowl",
    name: "Leftover tofu scramble bowl",
    cuisine: "Asian",
    time: 12,
    servings: 1,
    need: ["Cooked leftovers", "Tofu", "Cooked rice"],
    optional: ["Soy sauce", "Spring onion", "Sesame oil", "Chili oil", "Garlic"],
    steps: [
      "Crumble 200 g tofu; chop leftover vegetables or bits.",
      "Stir-fry garlic if using; scramble tofu with leftovers and soy sauce 3–4 minutes. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Serve over hot rice with sesame oil, chili oil, and spring onion.",
    ],
    zh: {
      name: "剩菜豆腐碎飯",
      steps: [
        "豆腐約 200 克壓碎；剩菜切碎。",
        "可爆香蒜蓉，豆腐與剩菜加生抽炒 3 至 4 分鐘。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "蓋熱飯上，滴麻油辣椒油撒蔥花。",
      ],
    },
  },
  {
    id: "home-leftover-pasta-bake",
    name: "Leftover pasta bake",
    cuisine: "Western",
    time: 30,
    servings: 2,
    need: ["Cooked leftovers", "Pasta", "Cheddar"],
    optional: ["Tomato", "Onion", "Milk", "Salt", "White pepper"],
    steps: [
      "Boil 180 g pasta until just tender; drain. Chop leftovers and tomato/onion if using.",
      "Mix pasta with leftovers, a splash of milk, salt, and white pepper in a baking dish; top with grated cheddar.",
      "Bake at 200°C / 400°F for 12–15 minutes until bubbling and golden. Any leftover meat or poultry must reach 74°C / 165°F.",
    ],
    zh: {
      name: "剩菜焗意粉",
      steps: [
        "意粉約 180 克煮至刚熟瀝乾。剩菜切碎，可加番茄洋蔥。",
        "意粉與剩菜、少許奶、鹽和白胡椒拌匀入焗盤，撒切達芝士。",
        "200°C 焗 12 至 15 分鐘至起泡金黃。 隔夜肉類或家禽須煮至 74°C / 165°F。",
      ],
    },
  },
  {
    id: "home-leftover-chili-noodle",
    name: "Leftover chili oil noodle toss",
    cuisine: "Sichuan",
    time: 12,
    servings: 1,
    need: ["Cooked leftovers", "Noodles", "Chili oil"],
    optional: ["Soy sauce", "Garlic", "Spring onion", "Vinegar", "Sesame seeds", "Cucumber"],
    steps: [
      "Boil noodles until tender; drain. Warm leftover protein/veg briefly.",
      "Mix chili oil, soy sauce, minced garlic, and a splash of vinegar in a bowl. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Toss noodles and leftovers in the sauce; top with spring onion, sesame seeds, and cucumber if using.",
    ],
    zh: {
      name: "剩菜紅油拌麵",
      steps: [
        "麵煮軟瀝乾。剩菜略熱。",
        "碗中拌辣椒油、生抽、蒜蓉和少許醋。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "麵和剩菜拌匀，撒蔥花芝麻，可加青瓜絲。",
      ],
    },
  },
  {
    id: "home-leftover-bean-sprout-soup",
    name: "Leftover clear soup with bean sprouts",
    cuisine: "Korean",
    time: 15,
    servings: 2,
    need: ["Cooked leftovers", "Bean sprouts"],
    optional: ["Garlic", "Salt", "Soy sauce", "Spring onion", "Sesame oil", "Eggs"],
    steps: [
      "Simmer leftover bones/bits or diced leftovers in about 4 cups water with garlic 8 minutes. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Add a big handful of bean sprouts; cook 3–4 minutes. Optional cracked egg swirled in.",
      "Season with salt or soy sauce; finish with spring onion and sesame oil.",
    ],
    zh: {
      name: "剩菜芽菜清湯",
      steps: [
        "剩骨或剩菜粒加水約四杯，加蒜煮 8 分鐘。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "下一大把芽菜煮 3 至 4 分鐘；可打蛋散入。",
        "加鹽或生抽，撒蔥花滴麻油。",
      ],
    },
  },
  {
    id: "home-leftover-kimchi-pancake",
    name: "Leftover kimchi pancake",
    cuisine: "Korean",
    time: 18,
    servings: 2,
    need: ["Kimchi", "Flour", "Eggs", "Cabbage", "Bread"],
    optional: ["Cooked leftovers", "Spring onion", "Soy sauce", "Sesame oil", "Cornstarch", "Salt", "Cooking oil", "Vinegar", "Sugar"],
    steps: [
      "Chop 1 cup kimchi; mix with 1/2 cup flour, 1 egg, optional diced leftovers, spring onion, and enough water for a thick batter.",
      "Fry in a thin layer 3–4 minutes per side until crisp at the edges.",
      "Serve with soy sauce and a drop of sesame oil.",
    ],
    zh: {
      name: "泡菜煎餅清剩",
      steps: [
        "泡菜約一杯切碎，加半杯麵粉、一隻蛋、可加剩菜粒和蔥花，加水成稠漿。",
        "薄攤煎每面 3 至 4 分鐘至邊脆。",
        "蘸生抽，可滴麻油。",
      ],
    },
  },
  {
    id: "home-leftover-beef-fried-rice",
    name: "Leftover beef fried rice",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Cooked leftovers", "Cooked rice", "Eggs", "Beef steak"],
    optional: ["Spring onion", "Soy sauce", "Garlic", "Onion", "Sesame oil", "Ginger", "Oyster sauce", "White pepper", "Shaoxing wine", "Cornstarch"],
    steps: [
      "Slice leftover beef thinly. Beat 2 eggs; loosen 2 bowls cold rice.",
      "Scramble eggs; remove. Stir-fry onion/garlic, then beef 1 minute; add rice and soy sauce. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Return eggs; toss well. Finish with spring onion and sesame oil.",
    ],
    zh: {
      name: "剩牛肉炒飯",
      steps: [
        "剩牛肉切薄片。打散兩隻蛋；兩碗隔夜飯抓散。",
        "炒蛋盛起；炒洋蔥蒜蓉，下牛肉 1 分鐘，下飯和生抽。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "回蛋炒匀，撒蔥花滴麻油。",
      ],
    },
  },
  {
    id: "home-leftover-shrimp-fried-rice",
    name: "Leftover shrimp fried rice",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Cooked leftovers", "Cooked rice", "Eggs", "Shrimp", "Snow peas"],
    optional: ["Spring onion", "Soy sauce", "Garlic", "Corn", "Sesame oil", "Salt", "Cooking oil", "Onion", "Sugar", "White pepper", "Shaoxing wine"],
    steps: [
      "Use leftover cooked shrimp or mixed seafood leftovers, chopped. Beat 2 eggs; loosen cold rice.",
      "Scramble eggs; remove. Stir-fry garlic, leftovers, and corn if using; add rice and soy sauce. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Return eggs; toss 1–2 minutes. Finish with spring onion and sesame oil.",
    ],
    zh: {
      name: "剩蝦炒飯",
      steps: [
        "剩熟蝦或海鮮切碎。打散兩隻蛋；隔夜飯抓散。",
        "炒蛋盛起；爆香蒜蓉，下剩蝦和玉米（可用），下飯和生抽。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "回蛋炒 1 至 2 分鐘，撒蔥花滴麻油。",
      ],
    },
  },
  {
    id: "home-leftover-veggie-soup-clear",
    name: "Leftover vegetable clear soup",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Cooked leftovers", "Tofu"],
    optional: ["Ginger", "Salt", "White pepper", "Spring onion", "Corn", "Carrots"],
    steps: [
      "Chop leftover vegetables. Cube 200 g tofu. Simmer leftovers with ginger in about 4 cups water 10 minutes. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Add tofu (and corn/carrot if using) for 5 minutes.",
      "Season with salt and white pepper; finish with spring onion.",
    ],
    zh: {
      name: "剩菜豆腐清湯",
      steps: [
        "剩蔬菜切碎。豆腐約 200 克切塊。剩菜加薑加水約四杯煮 10 分鐘。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "下豆腐（可加玉米紅蘿蔔）再 5 分鐘。",
        "加鹽白胡椒，撒蔥花。",
      ],
    },
  },
]
