import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W5H: Recipe[] = [
  {
    id: "home-steamed-meat-loaf-with-tofu",
    name: "Steamed Meat Loaf with Tofu",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Ground pork", "Silken tofu", "Spring onion", "Mozzarella"],
    optional: ["Salt", "White pepper", "Sugar", "Cornstarch"],
    steps: [
      "Arrange Ground pork with Tofu on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through (poultry/mince to 74°C / 165°F).",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "滑豆腐蒸肉餅",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟（肉類至 74°C / 165°F）。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-japanese-style-steamed-egg",
    name: "Japanese Style Steamed Egg",
    cuisine: "Japanese",
    time: 25,
    servings: 2,
    need: ["Eggs", "Spinach", "Mushroom", "Shrimp", "Milk", "Mozzarella"],
    optional: ["Sesame oil"],
    steps: [
      "Arrange Eggs with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "茶碗蒸蛋",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-homemade-beef-rice-rolls",
    name: "Homemade Beef Rice Rolls",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Bean sprouts", "Rice vermicelli", "Mozzarella"],
    optional: ["Salt", "Chicken stock", "Cornstarch", "Soy sauce", "Sugar"],
    steps: [
      "Prep Beef steak and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "自家製牛肉腸粉",
      steps: [
        "準備自家製牛肉腸粉材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-steamed-chicken-with-rice-wine",
    name: "Steamed Chicken with Rice Wine",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Ginger", "Spring onion"],
    optional: ["Salt", "Sugar", "Cornstarch"],
    steps: [
      "Arrange Chicken thighs with Cooked rice on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through (poultry/mince to 74°C / 165°F).",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "清酒白蘿蔔蒸雞",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟（肉類至 74°C / 165°F）。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-chive-pork-salted-egg-soup",
    name: "Chive Pork Salted Egg Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Eggs", "Mozzarella"],
    optional: ["Cornstarch", "Salt", "White pepper"],
    steps: [
      "Blanch Ground pork briefly if it is meat; rinse. Cut Eggs into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "鹹蛋枸杞肉片湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-soft-scrambled-eggs-with-beef",
    name: "Soft Scrambled Eggs with Beef",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Eggs", "Spring onion"],
    optional: ["Chicken stock", "Sesame oil", "White pepper", "Salt", "Shaoxing wine"],
    steps: [
      "Prep Beef steak and Eggs; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Eggs, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "滑蛋牛肉",
      steps: [
        "準備滑蛋牛肉材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-cute-octopus-bento-box",
    name: "Cute Octopus Bento Box",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Bacon", "Cauliflower", "Carrots", "Beans"],
    optional: [],
    steps: [
      "Prep White fish and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add White fish and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "可愛章魚便當",
      steps: [
        "準備可愛章魚便當材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-fresh-lily-seafood-tofu-soup",
    name: "Fresh Lily Seafood Tofu Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Mozzarella", "Shrimp", "Carrots", "Beans", "Eggs"],
    optional: ["Chicken stock"],
    steps: [
      "Blanch Tofu briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "鮮百合海鮮豆腐羹",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-red-chili-beef",
    name: "Red Chili Beef",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Dried chili", "Spring onion", "Garlic", "Rice", "Mozzarella"],
    optional: ["Cornstarch", "White pepper"],
    steps: [
      "Prep Beef steak and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "小紅椒油爆牛肉",
      steps: [
        "準備小紅椒油爆牛肉材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-mini-egg-omelette-with-minced-pork",
    name: "Mini Egg Omelette with Minced Pork",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Ground beef", "Spring onion"],
    optional: ["Olive oil", "Salt"],
    steps: [
      "Prep Ground pork and Eggs; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add Eggs, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "肉碎蛋角",
      steps: [
        "準備肉碎蛋角材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-sweet-corn-and-water-chestnut-rice-balls",
    name: "Sweet Corn and Water Chestnut Rice Balls",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Corn", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Corn and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Corn and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "粟米馬蹄珍珠丸子",
      steps: [
        "準備粟米馬蹄珍珠丸子材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-prawn-and-bean-curd-hot-pot",
    name: "Prawn and Bean Curd Hot Pot",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Mozzarella"],
    optional: ["Chicken stock", "Salt", "Sugar"],
    steps: [
      "Prep Shrimp and Tofu; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add Tofu, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "鮮蝦豆腐鍋",
      steps: [
        "準備鮮蝦豆腐鍋材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-healthy-ginseng-chestnut-black-bean-rice",
    name: "Healthy Ginseng Chestnut Black Bean Rice",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Cooked rice", "Red beans", "Beans", "Mozzarella"],
    optional: [],
    steps: [
      "Prep Cooked rice and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Cooked rice and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "栗子人參黑豆營養飯",
      steps: [
        "準備栗子人參黑豆營養飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-lean-pork-cordyceps-rice",
    name: "Lean Pork Cordyceps Rice",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Cooked rice"],
    optional: ["Olive oil", "Salt"],
    steps: [
      "Prep Ground pork and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "瘦肉蟲草花拌飯",
      steps: [
        "準備瘦肉蟲草花拌飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-antioxidant-cordyceps-tofu-soup",
    name: "Antioxidant Cordyceps Tofu Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Tofu", "Mozzarella", "Spring onion"],
    optional: ["Chicken stock", "Sesame oil", "Cornstarch", "Shaoxing wine", "Oyster sauce", "Salt", "White pepper"],
    steps: [
      "Blanch Tofu briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "抗氧化蟲草花豆腐羹",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-general-tsos-chicken-2",
    name: "General Tso’s Chicken",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Eggs"],
    optional: [],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "左宗棠雞",
      steps: [
        "準備左宗棠雞材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-sake-steamed-chicken",
    name: "Sake Steamed Chicken",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Spring onion", "Ginger", "Garlic"],
    optional: ["Cornstarch", "Chicken stock", "Salt"],
    steps: [
      "Arrange Chicken thighs with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through (poultry/mince to 74°C / 165°F).",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "清酒蒸雞",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟（肉類至 74°C / 165°F）。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-yuzhu-ginseng-chicken-soup",
    name: "Yuzhu Ginseng Chicken Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Eggs", "Mozzarella"],
    optional: ["Sesame oil", "Salt"],
    steps: [
      "Blanch Chicken thighs briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "玉竹人參雞湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-steamed-chicken-with-cordyceps-and-black-fungus",
    name: "Steamed Chicken with Cordyceps and Black Fungus",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Ginger", "Orange", "Spring onion"],
    optional: ["Shaoxing wine", "Salt", "Cornstarch", "Sesame oil", "Sugar"],
    steps: [
      "Arrange Chicken thighs with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through (poultry/mince to 74°C / 165°F).",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "蟲草花大棗雲耳蒸滑雞",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟（肉類至 74°C / 165°F）。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-veggie-beef-rolls",
    name: "Veggie Beef Rolls",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Celery", "Carrots", "Mozzarella"],
    optional: ["Salt", "Cornstarch"],
    steps: [
      "Prep Beef steak and Eggs; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Eggs, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蔬菜牛肉捲",
      steps: [
        "準備蔬菜牛肉捲材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-korean-bulgogi",
    name: "Korean Bulgogi",
    cuisine: "Korean",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Garlic", "Onion", "Dried chili", "Ginger"],
    optional: ["Soy sauce", "Sugar", "Sesame oil", "Sesame seeds"],
    steps: [
      "Prep Beef steak and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "韓式炒牛肉",
      steps: [
        "準備韓式炒牛肉材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-black-pepper-fried-shrimps-with-eggplant",
    name: "Black Pepper Fried Shrimps with Eggplant",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Spring onion", "Garlic", "Shrimp", "Eggplant", "Bell pepper", "Rice"],
    optional: ["Sesame seeds"],
    steps: [
      "Prep Shrimp and Eggs plus Eggplant; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add Eggs and Eggplant, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "黑椒蝦球炸茄子",
      steps: [
        "準備黑椒蝦球炸茄子材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-dried-shrimps-with-jicama",
    name: "Dried Shrimps with Jicama",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Ginger", "Rice", "Mozzarella"],
    optional: ["Sugar", "Salt", "Cornstarch"],
    steps: [
      "Prep Shrimp and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蝦米炒沙葛",
      steps: [
        "準備蝦米炒沙葛材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-steamed-egg-whites-with-conpoy",
    name: "Steamed Egg Whites with Conpoy",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Eggs"],
    optional: ["Chicken stock", "Olive oil", "Salt"],
    steps: [
      "Arrange Eggs with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "瑤柱蒸蛋白",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-water-crest-with-fresh-fish-broth",
    name: "Water Crest with Fresh Fish Broth",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ginger", "Mozzarella"],
    optional: ["Salt"],
    steps: [
      "Blanch White fish briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "魚湯浸西洋菜",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-beautifying-chinese-yam-mixed-beans-with-chicken",
    name: "Beautifying Chinese Yam Mixed Beans with Chicken Feet Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Peanuts", "Beans", "Mozzarella"],
    optional: ["Salt"],
    steps: [
      "Blanch Chicken thighs briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "養顏•山藥雜豆煲雞腳",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-laksa-with-fatty-beef",
    name: "Laksa with fatty beef",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Coconut milk", "Beans", "Beef steak", "Spring onion", "Noodles"],
    optional: [],
    steps: [
      "Prep Beef steak and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "肥牛香菇喇沙",
      steps: [
        "準備肥牛香菇喇沙材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-three-color-steamed-egg",
    name: "Three Color Steamed Egg",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Century egg", "Eggs", "Mozzarella", "Spring onion"],
    optional: [],
    steps: [
      "Arrange Eggs with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "三色蒸蛋",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-radish-with-white-fish-stew",
    name: "Radish with White Fish Stew",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Cooked rice", "Ginger", "Celery", "Mozzarella"],
    optional: ["Sugar"],
    steps: [
      "Blanch White fish briefly if it is meat; rinse. Cut Cooked rice into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "白蘿蔔白飯魚湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-mini-heart-shaped-musubi-valentines-day-special",
    name: "Mini Heart-Shaped Musubi",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Luncheon meat", "Nori", "Eggs"],
    optional: ["Soy sauce", "Honey"],
    steps: [
      "Prep Luncheon meat and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Luncheon meat and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "愛心迷你午餐肉壽司",
      steps: [
        "準備愛心迷你午餐肉壽司材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-steamed-chicken-with-sour-plum",
    name: "Steamed Chicken with Sour Plum",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Chicken thighs", "Noodles", "Mozzarella", "Spring onion"],
    optional: ["Cornstarch"],
    steps: [
      "Arrange Chicken thighs with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through (poultry/mince to 74°C / 165°F).",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "酸梅蒸雞腿肉",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟（肉類至 74°C / 165°F）。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-boxthorn-leaf-with-fresh-fish-soup",
    name: "Boxthorn Leaf with Fresh Fish Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Mozzarella", "Ginger"],
    optional: ["Shaoxing wine", "White pepper", "Salt"],
    steps: [
      "Blanch White fish briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "枸杞魚片湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-healthy-tofu-balls-healthy-recipes",
    name: "Healthy Tofu Balls",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork", "Eggs", "Ginger"],
    optional: ["Cornstarch", "Soy sauce", "White pepper", "Shaoxing wine", "Salt"],
    steps: [
      "Blanch Tofu briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "豆腐湯丸",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-saute-leek-with-beef",
    name: "Saute Leek with Beef",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Spring onion", "Ginger"],
    optional: ["Oyster sauce"],
    steps: [
      "Prep Beef steak and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "大蔥炒牛肉",
      steps: [
        "準備大蔥炒牛肉材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-mushroom-chicken-soup",
    name: "Mushroom Chicken Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken breast", "Dried mushrooms", "Mozzarella"],
    optional: ["Chicken stock", "Salt", "Cornstarch"],
    steps: [
      "Blanch Chicken thighs briefly if it is meat; rinse. Cut Mushroom into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "冬菇雞絲羹",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-taiwanese-minced-pork-porridge",
    name: "Taiwanese Minced Pork Porridge",
    cuisine: "Taiwanese",
    time: 35,
    servings: 2,
    need: ["Ground pork", "Mushroom", "Cooked rice", "Spring onion", "Mozzarella"],
    optional: ["Chicken stock", "Sesame oil", "Salt", "White pepper"],
    steps: [
      "Rinse ½ cup rice; simmer with about 1.2 L water 30–35 minutes, stirring occasionally until creamy.",
      "Add sliced Ground pork in the last 8–10 minutes until cooked through (74°C / 165°F).",
      "Season with salt, white pepper, and sesame oil; top with spring onion.",
    ],
    zh: {
      name: "台式咸粥",
      steps: [
        "半杯米洗净，加水约 1.2 升煮 30 至 35 分鐘至绵密。",
        "最後 8 至 10 分鐘下切片主料煮熟。",
        "加鹽白胡椒麻油，撒蔥。",
      ],
    },
  },
  {
    id: "home-delicious-clam-porridge",
    name: "Delicious Clam Porridge",
    cuisine: "Cantonese",
    time: 35,
    servings: 2,
    need: ["Clams", "Cooked rice", "Ginger", "Mozzarella", "Spring onion"],
    optional: ["Olive oil", "Salt"],
    steps: [
      "Rinse ½ cup rice; simmer with about 1.2 L water 30–35 minutes, stirring occasionally until creamy.",
      "Add sliced Clams in the last 8–10 minutes until just cooked.",
      "Season with salt, white pepper, and sesame oil; top with spring onion.",
    ],
    zh: {
      name: "清甜蛤蜊粥 健康初春食譜]",
      steps: [
        "半杯米洗净，加水约 1.2 升煮 30 至 35 分鐘至绵密。",
        "最後 8 至 10 分鐘下切片主料煮熟。",
        "加鹽白胡椒麻油，撒蔥。",
      ],
    },
  },
  {
    id: "home-pork-ribs-and-taro-congee",
    name: "Pork Ribs and Taro Congee",
    cuisine: "Cantonese",
    time: 35,
    servings: 2,
    need: ["Taro", "Spare ribs", "Spring onion", "Cooked rice", "Ginger", "Mozzarella"],
    optional: ["White pepper", "Salt", "Chicken stock"],
    steps: [
      "Rinse ½ cup rice; simmer with about 1.2 L water 30–35 minutes, stirring occasionally until creamy.",
      "Add sliced Ground pork in the last 8–10 minutes until cooked through (74°C / 165°F).",
      "Season with salt, white pepper, and sesame oil; top with spring onion.",
    ],
    zh: {
      name: "芋頭排骨粥",
      steps: [
        "半杯米洗净，加水约 1.2 升煮 30 至 35 分鐘至绵密。",
        "最後 8 至 10 分鐘下切片主料煮熟。",
        "加鹽白胡椒麻油，撒蔥。",
      ],
    },
  },
  {
    id: "home-bak-choy-egg-plant",
    name: "Bak Choy Egg Plant",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Green beans", "Broccoli", "Eggplant", "Doubanjiang"],
    optional: ["Chicken stock", "White pepper", "Salt"],
    steps: [
      "Prep Eggs and Pak choi plus Eggplant; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Pak choi and Eggplant, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "白菜炒茄子",
      steps: [
        "準備白菜炒茄子材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-chili-oil-chicken",
    name: "Chili Oil Chicken",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Spring onion", "Garlic"],
    optional: ["Sugar", "Sesame oil", "Cornstarch"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "辣油炒雞柳",
      steps: [
        "準備辣油炒雞柳材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-olive-steamed-tofu",
    name: "Olive Steamed Tofu",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Tofu", "Spring onion"],
    optional: ["Sesame oil"],
    steps: [
      "Arrange Tofu with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "欖角蒸豆腐",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-clams-in-loofah-soup-with-noodles",
    name: "Clams in Loofah Soup with Noodles",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Clams", "Glass noodles", "Ginger", "Mozzarella"],
    optional: ["Chicken stock", "Salt"],
    steps: [
      "Blanch Clams briefly if it is meat; rinse. Cut Noodles into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "水瓜浸蜆",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-healthy-red-beet-soup",
    name: "Healthy Red Beet Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Carrots", "Corn", "Beef steak", "Onion", "Mozzarella"],
    optional: ["Shaoxing wine", "White pepper", "Salt"],
    steps: [
      "Blanch Tofu briefly if it is meat; rinse. Cut Mushroom into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "健康紅菜頭湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-mushroom-barley-rice",
    name: "Mushroom Barley Rice",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Rice", "Dried mushrooms", "Tofu", "Mung beans"],
    optional: ["Sesame oil", "Salt"],
    steps: [
      "Cut Mushroom and Cooked rice into pieces; lightly brown Mushroom in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Mushroom is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "香菇薏米燜飯",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-mini-party-noodles",
    name: "Mini Party Noodles",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Eggs", "Cucumber", "Mushroom", "Kimchi"],
    optional: ["Sesame oil", "Salt", "Sesame seeds"],
    steps: [
      "Blanch Noodles briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "宴會湯麵",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-classic-shrimp-toasts",
    name: "Classic Shrimp Toasts",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Bread", "Shrimp", "Mayonnaise", "Eggs", "Garlic", "Spring onion"],
    optional: ["Sesame oil", "Salt", "Sugar", "Cornstarch"],
    steps: [
      "Prep Shrimp and Bread; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add Bread, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "炸蝦多士",
      steps: [
        "準備炸蝦多士材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-bacon-cucumber-egg-sandwich",
    name: "Bacon Cucumber Egg Sandwich",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Bread", "Bacon", "Lettuce", "Tomato", "Eggs", "Mayonnaise", "Cucumber", "Mustard"],
    optional: ["Honey", "Salt", "White pepper"],
    steps: [
      "Prep Bacon and Eggs plus Cucumber; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Bacon and cook until just cooked.",
      "Add Eggs and Cucumber, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "煙肉雞蛋三文治",
      steps: [
        "準備煙肉雞蛋三文治材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-sour-cabbage-mini-clams",
    name: "Sour Cabbage Mini Clams",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Clams", "Pickles", "Spring onion", "Garlic", "Mozzarella"],
    optional: ["Shaoxing wine", "White pepper", "Cornstarch", "Sugar"],
    steps: [
      "Prep Clams and Cabbage plus Pickled mustard; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Clams and cook until just cooked.",
      "Add Cabbage and Pickled mustard, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "酸菜炒蜆仔",
      steps: [
        "準備酸菜炒蜆仔材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-cute-piglet-rice-bowl",
    name: "Cute Piglet Rice Bowl",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Cooked rice", "Bacon", "Nori", "Beans", "Tomato"],
    optional: ["Ketchup"],
    steps: [
      "Prep Cooked rice and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Cooked rice and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "小豬便當【親子食堂】",
      steps: [
        "準備小豬便當【親子食堂】材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-baked-chicken-breast-stuffed-with-ham-and-cheese",
    name: "Baked Chicken Breast Stuffed with Ham and Cheese",
    cuisine: "Chinese",
    time: 40,
    servings: 2,
    need: ["Chicken breast", "Cheddar", "Ham", "Flour", "Eggs", "Bread", "Butter", "Corn", "Cauliflower", "Tomato"],
    optional: ["Salt", "White pepper"],
    steps: [
      "Heat oven to 200°C. Toss Chicken breast and Chicken thighs with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "火腿芝士釀雞扒",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
]
