import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W5A: Recipe[] = [
  {
    id: "home-3-colored-beef-rolls-in-chicken-marinade",
    name: "3 Colored Beef Rolls in Chicken Marinade",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Bell pepper"],
    optional: ["Soy sauce", "Sesame oil", "White pepper"],
    steps: [
      "Prep Beef steak and Chicken thighs; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until cooked through (74°C / 165°F).",
      "Add Chicken thighs, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "三色牛柳卷",
      steps: [
        "準備三色牛柳卷材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-abalone-and-avocado-toast-with-mushroom-soup",
    name: "Abalone and Avocado Toast with Mushroom Soup",
    cuisine: "Western",
    time: 45,
    servings: 3,
    need: ["Bread", "Mozzarella", "Avocado", "Tomato", "Butter", "Lemon", "Mushroom", "Bacon", "Onion"],
    optional: [],
    steps: [
      "Blanch White fish briefly if it is meat; rinse. Cut Mushroom into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "牛油果鮑魚多士配蘑菇湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-abalone-and-braised-tofu-in-abalone-sauce",
    name: "Abalone and Braised Tofu in Abalone Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Tofu", "Garlic", "Ginger", "Spring onion"],
    optional: ["Cornstarch"],
    steps: [
      "Cut White fish and Tofu into pieces; lightly brown White fish in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until White fish is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "鮑魚鮑汁燜豆腐",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-abalone-and-jinhua-ham-steamed-rice",
    name: "Abalone and Jinhua Ham Steamed Rice",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Rice", "Ham", "Dried mushrooms", "Ginger", "Pickled mustard"],
    optional: ["Oyster sauce", "Sugar"],
    steps: [
      "Arrange Ham with White fish on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "鮑魚萬有Boss飯",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-abalone-and-shrimp-paste-stuffed-mushrooms-in-pr",
    name: "Abalone and Shrimp Paste Stuffed Mushrooms in Premium Oyster Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Dried mushrooms", "Shrimp"],
    optional: ["Cornstarch", "White pepper"],
    steps: [
      "Prep Shrimp and White fish plus Mushroom; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add White fish and Mushroom, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "鮑魚蝦滑釀冬菇",
      steps: [
        "準備鮑魚蝦滑釀冬菇材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-abalone-and-veggies-in-hairy-gourd-rings",
    name: "Abalone and Veggies in Hairy Gourd Rings",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Zucchini", "Dried mushrooms", "Carrots", "XO sauce"],
    optional: ["Chicken stock", "Sesame oil"],
    steps: [
      "Prep White fish and Eggs; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add White fish and cook until just cooked.",
      "Add Eggs, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "頂級鮑魚XO醬節瓜環",
      steps: [
        "準備頂級鮑魚XO醬節瓜環材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-abalone-braised-pork-with-red-braising-sauce",
    name: "Abalone Braised Pork with Red Braising Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ginger", "Garlic", "Spring onion"],
    optional: ["Sugar", "Soy sauce", "Shaoxing wine"],
    steps: [
      "Cut Ground pork and White fish into pieces; lightly brown Ground pork in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Ground pork is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "紅運常滿鮑魚燜肉",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-abalone-dices-on-fried-wanton-wrappers",
    name: "Abalone Dices on Fried Wanton Wrappers",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["XO sauce", "Bell pepper", "Pine nuts", "Wonton wrappers"],
    optional: ["Oyster sauce", "Sugar", "White pepper"],
    steps: [
      "Prep Tortilla and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Tortilla and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "XO醬鮑粒金盞",
      steps: [
        "準備XO醬鮑粒金盞材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-abalone-in-abalone-sauce-with-dried-scallop-and",
    name: "Abalone in Abalone Sauce with Dried Scallop and Noodles",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["White fish", "Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep White fish and Noodles; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add White fish and cook until just cooked.",
      "Add Noodles, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "鮑汁元貝鮑魚撈麵",
      steps: [
        "準備鮑汁元貝鮑魚撈麵材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-abalone-in-red-braising-sauce-with-dried-scallop",
    name: "Abalone in Red Braising Sauce with Dried Scallop and Noodles",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["White fish", "Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep White fish and Noodles; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add White fish and cook until just cooked.",
      "Add Noodles, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "紅燒元貝鮑魚撈麵",
      steps: [
        "準備紅燒元貝鮑魚撈麵材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-abalone-rice-ball",
    name: "Abalone Rice Ball",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Rice", "Shrimp", "Nori"],
    optional: ["Vinegar"],
    steps: [
      "Prep White fish and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add White fish and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "鮑魚飯糰",
      steps: [
        "準備鮑魚飯糰材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-air-fried-korean-style-beef-rice-burger",
    name: "Air Fried Korean Style Beef Rice Burger",
    cuisine: "Korean",
    time: 20,
    servings: 2,
    need: ["Cooked rice", "Nori", "Beef steak", "Kimchi", "Lettuce", "Rice", "Noodles"],
    optional: ["Sesame seeds", "Sesame oil"],
    steps: [
      "Prep Beef steak and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "氣炸韓式牛肉米漢堡",
      steps: [
        "準備氣炸韓式牛肉米漢堡材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-air-fried-pork-jowl-with-korean-style-soy-bean-s",
    name: "Air Fried Pork Jowl with Korean Style Soy Bean Sauce",
    cuisine: "Korean",
    time: 20,
    servings: 2,
    need: ["Garlic", "Noodles", "Rice"],
    optional: ["Sesame oil", "Sesame seeds"],
    steps: [
      "Prep Ground pork and Noodles; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add Noodles, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "氣炸韓式麵豉醬豬頸肉",
      steps: [
        "準備氣炸韓式麵豉醬豬頸肉材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-air-fried-stuffed-chicken-wings-with-kimchi",
    name: "Air Fried Stuffed Chicken Wings with Kimchi",
    cuisine: "Korean",
    time: 20,
    servings: 2,
    need: ["Kimchi"],
    optional: ["Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken wings and Chicken thighs plus Kimchi; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken wings and cook until cooked through (74°C / 165°F).",
      "Add Chicken thighs and Kimchi, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "氣炸泡菜釀雞翼",
      steps: [
        "準備氣炸泡菜釀雞翼材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-air-fryer-wunan-cumin-chicken-wings",
    name: "Air Fryer Wunan Cumin Chicken Wings",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Garlic", "Rice"],
    optional: ["Sugar", "Soy sauce", "Oyster sauce", "Cumin", "Five-spice powder", "Sesame seeds"],
    steps: [
      "Prep Chicken wings and Chicken thighs; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken wings and cook until cooked through (74°C / 165°F).",
      "Add Chicken thighs, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "氣炸土匪雞翼",
      steps: [
        "準備氣炸土匪雞翼材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-angel-hair-and-mushrooms-in-coconut-curry-sauce",
    name: "Angel Hair and Mushrooms in Coconut Curry Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Noodles", "Squid", "Onion", "Carrots"],
    optional: ["Oyster sauce"],
    steps: [
      "Prep Mushroom and Noodles; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Mushroom and cook until just cooked.",
      "Add Noodles, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "葡汁雙菇天使麵",
      steps: [
        "準備葡汁雙菇天使麵材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-aromatic-braised-lamb-shanks",
    name: "Aromatic Braised Lamb Shanks",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Flour", "Onion", "Celery", "Carrots", "Tomato", "Mustard", "Doubanjiang"],
    optional: ["Vinegar", "Oyster sauce", "White pepper", "Sugar"],
    steps: [
      "Cut Beef steak and Onion into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "惹味燴羊膝",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-asian-chicken-salad",
    name: "Asian Chicken Salad",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Bean sprouts", "Cucumber", "Carrots", "Peanuts", "Gochujang"],
    optional: ["Oyster sauce"],
    steps: [
      "Prep Chicken thighs and vegetables; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "亞洲風味雞肉沙拉",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-asparagus-rolls-in-oyster-sauce-2",
    name: "Asparagus Rolls in Oyster Sauce 2",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Water chestnuts"],
    optional: ["Salt", "White pepper", "Oyster sauce", "Sesame oil"],
    steps: [
      "Prep Eggs and Tomato; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Tomato, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蠔汁蘆筍卷",
      steps: [
        "準備蠔汁蘆筍卷材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-asparagus-salad-with-sesame-oil",
    name: "Asparagus Salad with Sesame Oil",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Prep Eggs and Tomato; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "麻油蘆筍沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-assorted-vegetables-in-vegetarian-oyster-sauce",
    name: "Assorted Vegetables in Vegetarian Oyster Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Carrots", "Celery", "Bean sprouts", "Dried mushrooms", "Ham"],
    optional: ["Sesame oil", "Oyster sauce"],
    steps: [
      "Prep Eggs and Tomato; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Tomato, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "萬福喜迎春",
      steps: [
        "準備萬福喜迎春材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-avocado-chicken-nori-roll",
    name: "Avocado Chicken Nori Roll",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs", "Avocado", "Cucumber", "Nori", "Mushroom", "Ginger", "Spring onion", "Mustard", "Mayonnaise"],
    optional: [],
    steps: [
      "Prep Chicken thighs and Avocado; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add Avocado, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "牛油果雞肉紫菜卷",
      steps: [
        "準備牛油果雞肉紫菜卷材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-baked-baby-pork-legs-with-xo-sauce-yogurt",
    name: "Baked Baby Pork Legs with Xo Sauce Yogurt",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Garlic", "Yogurt", "XO sauce"],
    optional: ["Soy sauce", "White pepper", "Sugar", "Sesame oil", "Cornstarch"],
    steps: [
      "Heat oven to 200°C. Toss Ground pork and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "香焗豬脾仔配XO醬乳酪",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-baked-cheese-and-abalone-noodles",
    name: "Baked Cheese and Abalone Noodles",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Noodles", "Bacon", "Mushroom", "Onion", "Spinach", "Cheddar", "Cream", "Flour"],
    optional: [],
    steps: [
      "Heat oven to 200°C. Toss White fish and Noodles with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "鮑魚芝士焗麵",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-baked-gammon-in-plum-sauce-serves-with-brussels",
    name: "Baked Gammon in Plum Sauce Serves with Brussels in Oyster Sauce",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Cabbage", "Garlic", "Shallot", "Hoisin sauce", "Lemon", "Ginger"],
    optional: ["Olive oil"],
    steps: [
      "Heat oven to 200°C. Toss Ham and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "蘇梅焗火腿伴蠔油炒什菜",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-baked-garlic-baby-back-ribs",
    name: "Baked Garlic Baby Back Ribs",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Garlic", "Eggs", "Butter", "Dried chili", "Spring onion"],
    optional: ["Chicken stock", "Sugar", "Soy sauce", "Shaoxing wine", "Cornstarch"],
    steps: [
      "Heat oven to 200°C. Toss Tofu and Pak choi with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "焗蒜香一字骨",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-baked-garlic-eggplant",
    name: "Baked Garlic Eggplant",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Eggplant", "Spring onion"],
    optional: ["Soy sauce"],
    steps: [
      "Heat oven to 200°C. Toss Eggs and Eggplant with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "焗蒜香茄子",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-baked-hong-kong-classic-pork-chop-over-rice",
    name: "Baked Hong Kong Classic Pork Chop Over Rice",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Pork chops", "Tomato", "Onion", "Cooked rice", "Cheddar", "Eggs"],
    optional: ["Oyster sauce", "Cornstarch", "Ketchup"],
    steps: [
      "Heat oven to 200°C. Toss Ground pork and Pork chops with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "簡易版焗豬扒飯",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-baked-mushroom-with-black-truffle-and-oyster-sau",
    name: "Baked Mushroom with Black Truffle and Oyster Sauce in Shell Pasta",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Dried mushrooms", "Onion", "Garlic", "Mozzarella", "Cheddar"],
    optional: ["Oyster sauce"],
    steps: [
      "Boil pasta in salted water until al dente; reserve ½ cup pasta water.",
      "Meanwhile sauté garlic/onion and Mushroom in olive oil until just cooked.",
      "Toss pasta with the pan sauce and a splash of pasta water; adjust salt and finish with pepper or cheese if using.",
    ],
    zh: {
      name: "焗蠔皇黑松露芝士雜菌釀貝殼粉",
      steps: [
        "意粉盐水煮至 al dente，留半杯麵水。",
        "另鑊用橄欖油炒蒜洋蔥及主料至熟。",
        "拌入意粉和少許麵水調味，可加芝士或黑胡椒。",
      ],
    },
  },
  {
    id: "home-baked-portobello-mushroom-with-tomato-cheese-spi",
    name: "Baked Portobello Mushroom with Tomato Cheese Spinach and Chicken",
    cuisine: "Chinese",
    time: 40,
    servings: 2,
    need: ["Tomato", "Mozzarella", "Spinach", "Garlic", "Bread", "Thai basil"],
    optional: ["Ketchup", "Oyster sauce"],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and Tomato with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "番茄芝士菠菜雞肉烤釀大啡菇",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-barbecued-pork-pizza",
    name: "Barbecued Pork Pizza",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Mushroom", "Cheddar", "Tomato", "Thai basil"],
    optional: [],
    steps: [
      "Prep Ground pork and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "叉燒批",
      steps: [
        "準備叉燒批材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-basil-supreme-first-draw-soy-sauce-chicken-wings",
    name: "Basil Supreme First Draw Soy Sauce Chicken Wings",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Spring onion", "Garlic", "Thai basil"],
    optional: ["Sugar", "Chicken stock", "Shaoxing wine", "Sesame oil", "Soy sauce"],
    steps: [
      "Prep Chicken wings and Chicken thighs; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken wings and cook until cooked through (74°C / 165°F).",
      "Add Chicken thighs, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "羅勒頭抽皇雞翼",
      steps: [
        "準備羅勒頭抽皇雞翼材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-bean-curd-in-oyster-sauce-with-dried-scallop",
    name: "Bean Curd in Oyster Sauce with Dried Scallop",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Tofu", "Spring onion"],
    optional: ["Oyster sauce"],
    steps: [
      "Prep Tofu and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Tofu and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "瑤柱蠔油豆腐",
      steps: [
        "準備瑤柱蠔油豆腐材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-bean-vermicelli-with-oyster-sauce",
    name: "Bean Vermicelli with Oyster Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Glass noodles", "Ground pork", "Ginger", "Spring onion", "Garlic"],
    optional: ["Sesame oil", "Oyster sauce"],
    steps: [
      "Prep Rice vermicelli and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Rice vermicelli and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蠔油粉絲",
      steps: [
        "準備蠔油粉絲材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-beef-and-mushroom-lasagna",
    name: "Beef and Mushroom Lasagna",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Onion", "Celery", "Carrots", "Mushroom", "Garlic", "Noodles", "Cheddar", "Mozzarella", "Parmesan", "Tomato"],
    optional: ["Olive oil", "Oyster sauce"],
    steps: [
      "Prep Beef steak and Mushroom plus Noodles; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Mushroom and Noodles, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蘑菇牛肉千層麵",
      steps: [
        "準備蘑菇牛肉千層麵材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-beef-and-pineapple-bell-pepper-parcels",
    name: "Beef and Pineapple Bell Pepper Parcels",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Pineapple", "Bell pepper"],
    optional: ["Oyster sauce", "Cornstarch"],
    steps: [
      "Prep Beef steak and Bell pepper plus Pineapple; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Bell pepper and Pineapple, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "菠蘿牛肉粒甜椒盒",
      steps: [
        "準備菠蘿牛肉粒甜椒盒材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-beef-fried-rice",
    name: "Beef Fried Rice",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Ground beef", "Eggs", "Lettuce", "Spring onion", "Cooked rice"],
    optional: ["Oyster sauce", "Sesame oil"],
    steps: [
      "Loosen cold cooked rice; beat 2 eggs if eggs are in the dish. Dice other mix-ins small.",
      "Scramble eggs in a hot oiled pan; push aside or remove. Stir-fry aromatics and proteins until cooked.",
      "Add rice and 1–2 tbsp soy sauce; toss on high heat until hot and lightly toasted. Finish with spring onion.",
    ],
    zh: {
      name: "生炒香蔥牛肉飯",
      steps: [
        "隔夜飯撥散；如用蛋可先打散。配料切細。",
        "熱鑊炒蛋盛起；爆香蒜薑及蛋白質炒熟。",
        "下飯加 1 至 2 湯匙生抽大火炒香，撒蔥起鑊。",
      ],
    },
  },
  {
    id: "home-beef-rolls-in-oyster-sauce",
    name: "Beef Rolls in Oyster Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Carrots"],
    optional: ["Oyster sauce", "Sugar"],
    steps: [
      "Prep Beef steak and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蠔皇牛肉卷",
      steps: [
        "準備蠔皇牛肉卷材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-beef-rolls-with-enoki-mushrooms",
    name: "Beef Rolls with Enoki Mushrooms",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak"],
    optional: ["Oyster sauce"],
    steps: [
      "Prep Beef steak and Mushroom; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Mushroom, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "金菇肥牛卷",
      steps: [
        "準備金菇肥牛卷材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-beef-short-ribs-with-mushroom-baguette",
    name: "Beef Short Ribs with Mushroom Baguette",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Mushroom", "Garlic", "Butter"],
    optional: ["Salt", "Oyster sauce", "White pepper"],
    steps: [
      "Prep Beef steak and Mushroom; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Mushroom, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蘑菇牛小排法包",
      steps: [
        "準備蘑菇牛小排法包材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-beef-with-black-bean-sauce",
    name: "Beef with Black Bean Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Bell pepper", "Garlic"],
    optional: [],
    steps: [
      "Prep Beef steak and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "豆豉牛肉",
      steps: [
        "準備豆豉牛肉材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-black-pepper-and-pork-bone-hot-pot",
    name: "Black Pepper and Pork Bone Hot Pot",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Ground pork", "Bell pepper"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Ground pork and Bell pepper; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add Bell pepper, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "黑胡椒豬骨火鍋",
      steps: [
        "準備黑胡椒豬骨火鍋材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-black-pepper-beef-rice-with-garlic-soy-sauce",
    name: "Black Pepper Beef Rice with Garlic Soy Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Onion", "Corn", "Cooked rice", "Spring onion", "Butter"],
    optional: ["Soy sauce", "White pepper"],
    steps: [
      "Prep Beef steak and Bell pepper plus Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Bell pepper and Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蒜香黑椒牛肉飯",
      steps: [
        "準備蒜香黑椒牛肉飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-black-pepper-chicken-fillets-with-onion",
    name: "Black Pepper Chicken Fillets with Onion",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Onion", "Garlic"],
    optional: ["White pepper", "Cornstarch"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "黑椒洋蔥雞排",
      steps: [
        "準備黑椒洋蔥雞排材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-black-pepper-steak-with-spicy-salad",
    name: "Black Pepper Steak with Spicy Salad",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Beef steak", "Tomato", "Cucumber", "Avocado"],
    optional: ["Oyster sauce", "Chili oil", "Olive oil", "Vinegar"],
    steps: [
      "Prep Beef steak and Bell pepper; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "黑椒牛扒伴香辣沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-boat-lady-fried-rice",
    name: "Boat Lady Fried Rice",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Cooked rice", "Eggs", "Spring onion", "Shallot"],
    optional: ["Oyster sauce", "Soy sauce"],
    steps: [
      "Loosen cold cooked rice; beat 2 eggs if eggs are in the dish. Dice other mix-ins small.",
      "Scramble eggs in a hot oiled pan; push aside or remove. Stir-fry aromatics and proteins until cooked.",
      "Add rice and 1–2 tbsp soy sauce; toss on high heat until hot and lightly toasted. Finish with spring onion.",
    ],
    zh: {
      name: "艇妹炒飯",
      steps: [
        "隔夜飯撥散；如用蛋可先打散。配料切細。",
        "熱鑊炒蛋盛起；爆香蒜薑及蛋白質炒熟。",
        "下飯加 1 至 2 湯匙生抽大火炒香，撒蔥起鑊。",
      ],
    },
  },
  {
    id: "home-braised-abalone-rice-with-premium-oyster-sauce",
    name: "Braised Abalone Rice with Premium Oyster Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Shrimp", "Rice", "Shallot", "Spring onion"],
    optional: ["Sesame oil", "Soy sauce", "Shaoxing wine"],
    steps: [
      "Cut White fish and Cooked rice into pieces; lightly brown White fish in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until White fish is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "花開富貴鮑魚燴飯",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-abalone-with-shrimp-egg-and-sea-cucumber",
    name: "Braised Abalone with Shrimp Egg and Sea Cucumber",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ginger", "Spring onion", "Garlic", "Lettuce", "Shrimp"],
    optional: ["Oyster sauce", "Soy sauce", "Chicken stock", "Sesame oil", "Sugar"],
    steps: [
      "Cut Shrimp and White fish into pieces; lightly brown Shrimp in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Shrimp is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "蝦籽海參扣鮑魚",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-abalone-with-xo-sauce",
    name: "Braised Abalone with Xo Sauce",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Shrimp", "XO sauce", "Garlic", "Ginger", "Spring onion", "Mushroom"],
    optional: ["White pepper", "Soy sauce"],
    steps: [
      "Cut White fish and vegetables into pieces; lightly brown White fish in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until White fish is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "鮑魚XO海皇煲",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-braised-bean-curd-with-vegetables",
    name: "Braised Bean Curd with Vegetables",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Tofu", "Broccoli", "Carrots"],
    optional: ["Oyster sauce"],
    steps: [
      "Cut Tofu and Broccoli into pieces; lightly brown Tofu in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Tofu is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "豆腐扒西蘭花",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
]
