import type { Recipe } from "@/lib/recipes"

/** Tofu + greens dishes — Theme D. */
export const MORE_W1D: Recipe[] = [
  {
    id: "home-homestyle-tofu",
    name: "Home-style tofu",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Tofu", "Bell pepper", "Garlic", "Ground pork"],
    optional: ["Soy sauce", "Sugar", "Spring onion", "Cornstarch", "Ginger", "Cooking oil", "Oyster sauce", "Shaoxing wine", "Salt"],
    steps: [
      "Cut 1 block (about 350 g) tofu into 2 cm cubes; pat dry. Slice 1 bell pepper; mince 3 garlic cloves.",
      "Pan-fry tofu in 2 tbsp oil until golden on both sides; set aside. Stir-fry pepper and garlic 2 minutes.",
      "Return tofu with 2 tbsp soy sauce, ½ tsp sugar, and ¼ cup water. Simmer 3–4 minutes until saucy; thicken with a little cornstarch slurry if using. Finish with spring onion.",
    ],
    zh: {
      name: "家常豆腐",
      steps: [
        "約 350 克豆腐切 2 厘米方塊，抹乾。1 個甜椒切片；拍碎 3 瓣蒜。",
        "約 2 湯匙油煎豆腐兩面金黃盛起；炒甜椒和蒜約兩分鐘。",
        "倒回豆腐，加 2 湯匙生抽、半茶匙糖和約 ¼ 杯水煮 3 至 4 分鐘；可勾薄芡，撒蔥花。",
      ],
    },
  },
  {
    id: "home-braised-tofu-veg",
    name: "Braised tofu with vegetables",
    cuisine: "Cantonese",
    time: 30,
    servings: 2,
    need: ["Tofu", "Carrots", "Pak choi"],
    optional: ["Garlic", "Soy sauce", "Oyster sauce", "Ginger", "Cornstarch", "Cooking oil", "Chicken stock", "Sesame oil", "Sugar", "Salt", "Spring onion", "Shaoxing wine"],
    steps: [
      "Cube 1 block tofu. Slice 1 carrot into thin coins; cut 1 bunch pak choi into sections. Mince garlic/ginger if using.",
      "Lightly brown tofu in 1–2 tbsp oil; add carrot and aromatics, then ½ cup water, 1 tbsp soy sauce, and 1 tsp oyster sauce if using.",
      "Cover and braise 8–10 minutes. Nestle in pak choi for the last 3 minutes until wilted. Thicken lightly if you like; serve hot.",
    ],
    zh: {
      name: "蔬菜炆豆腐",
      steps: [
        "一磚豆腐切丁。1 條甘筍切薄片；1 束白菜切段。有蒜薑可切碎。",
        "1 至 2 湯匙油略煎豆腐，下甘筍和香料，加約半杯水、1 湯匙生抽和 1 茶匙蠔油（如有）。",
        "加蓋炆 8 至 10 分鐘；最後 3 分鐘下白菜至軟。可勾薄芡，熱吃。",
      ],
    },
  },
  {
    id: "home-cold-tofu-soy",
    name: "Cold tofu with soy",
    cuisine: "Cantonese",
    time: 10,
    servings: 2,
    need: ["Silken tofu", "Soy sauce"],
    optional: ["Sesame oil", "Spring onion", "Garlic", "Chili oil", "Cooking oil"],
    steps: [
      "Chill 1 pack (about 300 g) silken tofu. Drain carefully onto a plate and score the top lightly.",
      "Mix 2 tbsp soy sauce with 1 tsp sesame oil and minced garlic if using.",
      "Pour the dressing over the tofu; top with spring onion and a little chili oil if you like heat. Serve cold.",
    ],
    zh: {
      name: "涼拌豆腐",
      steps: [
        "一盒約 300 克嫩豆腐冷藏。小心瀝水上碟，表面可輕劃幾刀。",
        "2 湯匙生抽混 1 茶匙麻油和蒜蓉（如有）。",
        "淋在豆腐上，撒蔥花，可加少許辣椒油，凍食。",
      ],
    },
  },
  {
    id: "home-mapo-tofu-veg",
    name: "Mapo tofu (vegetarian)",
    cuisine: "Sichuan",
    time: 20,
    servings: 2,
    need: ["Tofu", "Chili oil", "Garlic", "Ground pork"],
    optional: ["Ginger", "Spring onion", "Soy sauce", "Cornstarch", "White pepper", "Shallot", "Cooking oil", "Oyster sauce", "Sugar", "Salt", "Sesame oil"],
    steps: [
      "Cube 1 block tofu; mince 3 garlic cloves and a little ginger if using.",
      "Warm 1–2 tbsp chili oil; fry garlic (and ginger) 30 seconds. Add ½ cup water and the tofu; simmer gently 5–7 minutes.",
      "Season with 1 tbsp soy sauce and a pinch of white pepper. Thicken with a little cornstarch slurry if desired; finish with spring onion. No meat.",
    ],
    zh: {
      name: "素麻婆豆腐",
      steps: [
        "一磚豆腐切丁；拍碎 3 瓣蒜，有薑可切碎。",
        "熱 1 至 2 湯匙辣椒油爆蒜（及薑）約 30 秒。加半杯水和豆腐，小火煮 5 至 7 分鐘。",
        "加 1 湯匙生抽和少許白胡椒；可勾薄芡，撒蔥花。不含肉。",
      ],
    },
  },
  {
    id: "home-tofu-skin-stirfry",
    name: "Tofu skin stir-fry",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Tofu", "Bean sprouts", "Garlic"],
    optional: ["Soy sauce", "Spring onion", "Sesame oil", "Carrots"],
    steps: [
      "Slice 1 block firm tofu into thin strips (stand-in for tofu skin). Rinse 2 cups bean sprouts; mince 2 garlic cloves; julienne half a carrot if using.",
      "Stir-fry garlic and carrot 1 minute in 1 tbsp oil, then add tofu strips and toss until lightly browned and hot.",
      "Add bean sprouts, 1 tbsp soy sauce, and a drop of sesame oil; cook 1–2 minutes until sprouts soften. Finish with spring onion.",
    ],
    zh: {
      name: "豆腐皮炒",
      steps: [
        "一磚硬豆腐切薄條（代替豆腐皮）。洗約兩杯芽菜；拍碎兩瓣蒜；有甘筍可切絲。",
        "1 湯匙油爆蒜和甘筍約一分鐘，下豆腐條炒至微黃熱透。",
        "下芽菜、1 湯匙生抽和少許麻油炒 1 至 2 分鐘至芽菜軟，撒蔥花。",
      ],
    },
  },
  {
    id: "home-egg-tofu-stew",
    name: "Egg tofu stew",
    cuisine: "Cantonese",
    time: 18,
    servings: 2,
    need: ["Silken tofu", "Eggs"],
    optional: ["Soy sauce", "Spring onion", "Garlic", "Cornstarch", "Sesame oil"],
    steps: [
      "Drain 1 pack silken tofu and cut into thick rounds. Beat 2 eggs with a pinch of salt.",
      "Gently pan-fry tofu in 1 tbsp oil until lightly coloured. Pour beaten eggs around and over the tofu; cook on low until eggs set fully.",
      "Splash 1 tbsp soy sauce and a little water; simmer 1 minute. Finish with spring onion and sesame oil.",
    ],
    zh: {
      name: "玉子豆腐炆",
      steps: [
        "一盒嫩豆腐瀝乾切厚片。打散兩隻蛋加少許鹽。",
        "1 湯匙油略煎豆腐至微色，倒入蛋液蓋住，小火煮至蛋全熟凝固。",
        "淋 1 湯匙生抽和少許水再炆一分鐘；撒蔥花淋麻油。",
      ],
    },
  },
  {
    id: "home-spinach-egg-drop",
    name: "Spinach egg drop",
    cuisine: "Chinese",
    time: 12,
    servings: 2,
    need: ["Spinach", "Eggs"],
    optional: ["Garlic", "Sesame oil", "Soy sauce", "White pepper"],
    steps: [
      "Wash 200 g spinach and cut into short lengths. Beat 2 eggs. Bring 3 cups water or light stock to a simmer.",
      "Add spinach (and a smashed garlic clove if using); cook 1–2 minutes until wilted.",
      "Stir the pot and slowly pour in eggs to make ribbons until fully set. Season with soy sauce, white pepper, and a drop of sesame oil.",
    ],
    zh: {
      name: "菠菜蛋花",
      steps: [
        "洗約 200 克菠菜切短段。打散兩隻蛋。煮滾約 3 杯水或清湯。",
        "下菠菜（可加拍扁蒜瓣）煮 1 至 2 分鐘至軟。",
        "轉圈倒下蛋液成蛋花至全熟；加生抽、白胡椒和少許麻油。",
      ],
    },
  },
  {
    id: "home-garlic-lettuce",
    name: "Garlic lettuce",
    cuisine: "Cantonese",
    time: 8,
    servings: 2,
    need: ["Lettuce", "Garlic"],
    optional: ["Soy sauce", "Oyster sauce", "Sesame oil", "Cooking oil"],
    steps: [
      "Wash 1 large head of lettuce and tear or cut into large pieces; drain well. Mince 4 garlic cloves.",
      "Heat 1–2 tbsp oil until shimmering; fry garlic 15–20 seconds until fragrant but not burnt.",
      "Add lettuce and toss 1–2 minutes until just wilted but still crisp. Splash soy or oyster sauce and a drop of sesame oil; serve immediately.",
    ],
    zh: {
      name: "蒜蓉生菜",
      steps: [
        "洗淨 1 棵大生菜撕或切大件，瀝乾。拍碎 4 瓣蒜。",
        "熱 1 至 2 湯匙油，爆蒜 15 至 20 秒至香勿焦。",
        "下生菜快炒 1 至 2 分鐘至剛軟仍爽；淋生抽或蠔油和少許麻油，即上碟。",
      ],
    },
  },
  {
    id: "home-tomato-cabbage",
    name: "Tomato cabbage stir-fry",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Tomato", "Cabbage"],
    optional: ["Garlic", "Soy sauce", "Sugar", "Salt"],
    steps: [
      "Cut ¼ medium cabbage into bite-sized pieces (about 3 cups). Cut 2 tomatoes into wedges; mince 2 garlic cloves if using.",
      "Stir-fry cabbage in 1 tbsp oil 3–4 minutes until it softens and shrinks. Add garlic and tomato.",
      "Cook 4–5 minutes until tomato turns saucy. Season with ½ tsp salt, a pinch of sugar, and soy sauce to taste.",
    ],
    zh: {
      name: "番茄炒椰菜",
      steps: [
        "約 ¼ 個椰菜切小件（約 3 杯）。兩個番茄切瓣；有蒜可拍碎兩瓣。",
        "1 湯匙油炒椰菜 3 至 4 分鐘至軟縮，下蒜和番茄。",
        "再炒 4 至 5 分鐘至番茄出汁；加半茶匙鹽、少許糖和生抽調味。",
      ],
    },
  },
  {
    id: "home-mushroom-bok-choy",
    name: "Mushroom bok choy",
    cuisine: "Cantonese",
    time: 12,
    servings: 2,
    need: ["Mushroom", "Pak choi"],
    optional: ["Garlic", "Soy sauce", "Oyster sauce", "Sesame oil", "Cooking oil", "Salt", "Shaoxing wine", "Sugar", "White pepper", "Cornstarch"],
    steps: [
      "Slice 200 g mushrooms. Halve 1 bunch pak choi lengthwise; mince 2 garlic cloves if using.",
      "Stir-fry mushrooms in 1 tbsp oil 3–4 minutes until browned and their liquid mostly evaporates.",
      "Add pak choi and garlic; cook 2–3 minutes until greens wilt. Season with soy or oyster sauce and a drop of sesame oil.",
    ],
    zh: {
      name: "蘑菇白菜",
      steps: [
        "約 200 克蘑菇切片。1 束白菜直切開半；有蒜可拍碎兩瓣。",
        "1 湯匙油炒蘑菇 3 至 4 分鐘至上色、水分大致收乾。",
        "下白菜和蒜炒 2 至 3 分鐘至菜軟；加生抽或蠔油和少許麻油。",
      ],
    },
  },
  {
    id: "home-tofu-egg-scramble",
    name: "Tofu and egg scramble",
    cuisine: "Chinese",
    time: 12,
    servings: 2,
    need: ["Tofu", "Eggs"],
    optional: ["Spring onion", "Soy sauce", "Garlic", "White pepper"],
    steps: [
      "Crumble or dice ½ block (about 175 g) tofu. Beat 3 eggs with a pinch of salt and white pepper.",
      "Scramble eggs in 1 tbsp oil until just set; push aside. Warm tofu (and minced garlic if using) 1–2 minutes.",
      "Fold everything together with 1 tsp soy sauce and spring onion; cook until eggs are fully set and tofu is hot.",
    ],
    zh: {
      name: "豆腐炒蛋",
      steps: [
        "半磚約 175 克豆腐壓碎或切丁。打散 3 隻蛋加少許鹽和白胡椒。",
        "1 湯匙油炒蛋至剛凝固推開；下豆腐（及蒜蓉）炒 1 至 2 分鐘。",
        "拌勻，加 1 茶匙生抽和蔥花，炒至蛋全熟、豆腐熱透。",
      ],
    },
  },
  {
    id: "home-century-egg-tofu-soup",
    name: "Soft tofu with century egg soup",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Silken tofu", "Century egg"],
    optional: ["Ginger", "Spring onion", "White pepper", "Sesame oil", "Salt", "Chicken stock", "Cooking oil", "Eggs", "Mushroom", "Cabbage", "Cilantro"],
    steps: [
      "Cube 1 pack silken tofu. Peel and chop 1–2 century eggs. Slice a few pieces of ginger if using.",
      "Bring 3 cups water to a simmer with ginger; add tofu and century egg. Cook gently 4–5 minutes.",
      "Season with salt and white pepper; finish with spring onion and a drop of sesame oil. Serve steaming hot.",
    ],
    zh: {
      name: "皮蛋豆腐湯",
      steps: [
        "一盒嫩豆腐切丁。1 至 2 隻皮蛋去殼切粒。有薑可切片。",
        "約 3 杯水加薑煮滾，下豆腐和皮蛋，小火煮 4 至 5 分鐘。",
        "加鹽和白胡椒調味，撒蔥花淋少許麻油，趁熱喝。",
      ],
    },
  },
  {
    id: "home-ginger-choi-sum",
    name: "Choi sum with ginger",
    cuisine: "Cantonese",
    time: 10,
    servings: 2,
    need: ["Choi sum", "Ginger"],
    optional: ["Garlic", "Soy sauce", "Oyster sauce", "Sesame oil"],
    steps: [
      "Wash 1 bunch choi sum; cut stems and leaves into sections. Julienne a 3 cm piece of ginger (about 2 tbsp).",
      "Heat 1–2 tbsp oil; fry ginger (and minced garlic if using) 20–30 seconds until fragrant.",
      "Add choi sum stems first for 1 minute, then leaves; stir-fry 2–3 minutes until tender-crisp. Splash soy or oyster sauce and sesame oil.",
    ],
    zh: {
      name: "薑絲菜心",
      steps: [
        "洗淨 1 束菜心，莖葉分切。約 3 厘米薑切絲（約 2 湯匙）。",
        "熱 1 至 2 湯匙油，爆薑絲（及蒜蓉）約 20 至 30 秒至香。",
        "先炒菜莖一分鐘再下葉，炒 2 至 3 分鐘至熟爽；淋生抽或蠔油和麻油。",
      ],
    },
  },
  {
    id: "home-broccoli-beef-garlic",
    name: "Broccoli beef (soy-garlic)",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Broccoli", "Beef steak", "Garlic"],
    optional: ["Soy sauce", "Oyster sauce", "Cornstarch", "Ginger", "Sesame oil", "Carrots", "Cooking oil", "Salt", "Baking soda", "White pepper", "Sugar", "Shaoxing wine"],
    steps: [
      "Slice 250 g beef steak thin against the grain; toss with 1 tbsp soy sauce and 1 tsp cornstarch. Cut broccoli into florets; mince 3 garlic cloves.",
      "Blanch or stir-fry broccoli 2–3 minutes until bright green; set aside. Sear beef in a hot oiled pan until browned and cooked through (74°C / 165°F).",
      "Return broccoli with garlic, 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water; toss 1 minute until glossy.",
    ],
    zh: {
      name: "蒜香西蘭花牛肉",
      steps: [
        "約 250 克牛扒逆紋切薄片，拌 1 湯匙生抽和 1 茶匙生粉。西蘭花切小朵；拍碎 3 瓣蒜。",
        "焯或炒西蘭花 2 至 3 分鐘至翠綠盛起。熱油快炒牛肉至上色全熟（74°C）。",
        "倒回西蘭花和蒜，加 1 湯匙生抽、1 茶匙蠔油（如有）和少許水炒約一分鐘至亮汁。",
      ],
    },
  },
  {
    id: "home-eggplant-mince",
    name: "Eggplant with minced pork",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Eggplant", "Ground pork", "Garlic", "Eggs", "Pasta", "Bell pepper"],
    optional: ["Soy sauce", "Chili oil", "Spring onion", "Sugar", "Ginger", "Salt", "Shaoxing wine", "White pepper", "Sesame oil", "Cornstarch", "Cooking oil", "Oyster sauce", "Chicken stock", "Cilantro"],
    steps: [
      "Cut 2 medium eggplants into batons (about 400 g). Mince 3 garlic cloves. Have 150 g ground pork ready.",
      "Brown the pork with garlic until cooked through (74°C / 165°F). Add eggplant and ½ cup water; cover and cook 6–8 minutes until soft.",
      "Season with 1–2 tbsp soy sauce, a pinch of sugar, and chili oil if using. Reduce until glossy; finish with spring onion.",
    ],
    zh: {
      name: "肉碎炒茄子",
      steps: [
        "兩條茄子約 400 克切條。拍碎 3 瓣蒜。準備約 150 克免治豬肉。",
        "豬肉加蒜炒至全熟（74°C）。下茄子和約半杯水，加蓋煮 6 至 8 分鐘至軟。",
        "加 1 至 2 湯匙生抽、少許糖和辣椒油（如有）收汁至亮，撒蔥花。",
      ],
    },
  },
  {
    id: "home-celery-tofu",
    name: "Celery tofu stir-fry",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Celery", "Tofu"],
    optional: ["Garlic", "Soy sauce", "Sesame oil", "White pepper"],
    steps: [
      "Slice 3 celery stalks on the bias into thin pieces. Cube ½–1 block tofu; mince 2 garlic cloves if using.",
      "Pan-fry tofu in 1 tbsp oil until lightly golden; set aside. Stir-fry celery and garlic 2–3 minutes until crisp-tender.",
      "Return tofu with 1 tbsp soy sauce and a pinch of white pepper; toss 1 minute. Finish with sesame oil.",
    ],
    zh: {
      name: "西芹炒豆腐",
      steps: [
        "3 條西芹斜切薄片。半磚至一磚豆腐切丁；有蒜可拍碎兩瓣。",
        "1 湯匙油煎豆腐至微金盛起；炒西芹和蒜 2 至 3 分鐘至熟爽。",
        "倒回豆腐，加 1 湯匙生抽和少許白胡椒炒一分鐘，淋麻油。",
      ],
    },
  },
  {
    id: "home-cabbage-pork-filling",
    name: "Cabbage pork dumpling-filling pan",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Cabbage", "Ground pork", "Garlic"],
    optional: ["Ginger", "Soy sauce", "Sesame oil", "Spring onion", "White pepper"],
    steps: [
      "Finely chop 3 cups cabbage and squeeze out excess water. Mince 2 garlic cloves and a little ginger. Have 200 g ground pork ready.",
      "Brown pork with garlic and ginger until cooked through (74°C / 165°F). Add cabbage and stir-fry 4–5 minutes until softened.",
      "Season with 1–2 tbsp soy sauce, white pepper, and sesame oil. Taste like dumpling filling; finish with spring onion.",
    ],
    zh: {
      name: "白菜豬肉快炒",
      steps: [
        "約 3 杯白菜切碎擠乾水。拍碎兩瓣蒜和少許薑。準備約 200 克免治豬肉。",
        "豬肉加蒜薑炒至全熟（74°C）。下白菜炒 4 至 5 分鐘至軟。",
        "加 1 至 2 湯匙生抽、白胡椒和麻油，味道像餃子餡；撒蔥花。",
      ],
    },
  },
  {
    id: "home-salt-pepper-mushrooms",
    name: "Salt and pepper mushrooms",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Mushroom", "Garlic"],
    optional: ["White pepper", "Salt", "Spring onion", "Chili oil", "Cornstarch", "Ginger", "Cooking oil", "Shaoxing wine", "Eggs", "Five-spice powder"],
    steps: [
      "Halve or thick-slice 300 g mushrooms; pat dry. Toss lightly with 1 tsp cornstarch if using. Mince 3 garlic cloves.",
      "Pan-fry mushrooms in 2 tbsp oil over medium-high heat 5–7 minutes until browned and dry. Add garlic for the last minute.",
      "Season with ¼–½ tsp salt and ½ tsp white pepper; toss well. Finish with spring onion or a little chili oil.",
    ],
    zh: {
      name: "椒鹽蘑菇",
      steps: [
        "約 300 克蘑菇切開或厚片，抹乾；可拌 1 茶匙生粉。拍碎 3 瓣蒜。",
        "約 2 湯匙油中大火煎蘑菇 5 至 7 分鐘至上色收乾；最後一分鐘下蒜。",
        "加 ¼ 至半茶匙鹽和半茶匙白胡椒拌勻；可撒蔥花或少許辣椒油。",
      ],
    },
  },
  {
    id: "home-garlic-snow-peas",
    name: "Garlic snow peas",
    cuisine: "Cantonese",
    time: 10,
    servings: 2,
    need: ["Snow peas", "Garlic", "Beef steak"],
    optional: ["Soy sauce", "Sesame oil", "Salt", "Ginger", "Sugar"],
    steps: [
      "Trim 250 g snow peas; rinse and drain. Mince 3 garlic cloves; slice a little ginger if using.",
      "Heat 1 tbsp oil; fry garlic (and ginger) 15 seconds until fragrant.",
      "Add snow peas and stir-fry 2–3 minutes until bright green and tender-crisp. Season with a pinch of salt or splash of soy sauce; finish with sesame oil.",
    ],
    zh: {
      name: "蒜蓉蜜豆",
      steps: [
        "約 250 克蜜豆去蒂洗淨瀝乾。拍碎 3 瓣蒜；有薑可切片。",
        "熱 1 湯匙油，爆蒜（及薑）約 15 秒至香。",
        "下蜜豆快炒 2 至 3 分鐘至翠綠爽口；加少許鹽或生抽，淋麻油。",
      ],
    },
  },
  {
    id: "home-tomato-potato-stew",
    name: "Tomato potato stew",
    cuisine: "Chinese",
    time: 35,
    servings: 2,
    need: ["Tomato", "Potato"],
    optional: ["Onion", "Garlic", "Soy sauce", "Sugar", "Salt"],
    steps: [
      "Peel and cube 2 medium potatoes (about 400 g). Cut 3 tomatoes into chunks; slice half an onion and mince 2 garlic cloves if using.",
      "Sauté onion and garlic in 1 tbsp oil 2 minutes. Add potato and tomato with 1 cup water; bring to a simmer.",
      "Cover and cook 15–20 minutes until potatoes are tender and the tomato is saucy. Season with salt, a pinch of sugar, and soy sauce.",
    ],
    zh: {
      name: "番茄薯仔炆",
      steps: [
        "兩個中薯約 400 克去皮切丁。三個番茄切塊；有洋蔥可切半個，蒜拍碎兩瓣。",
        "1 湯匙油炒洋蔥和蒜約兩分鐘。下薯仔和番茄加約 1 杯水煮滾。",
        "加蓋炆 15 至 20 分鐘至薯軟、番茄出汁；加鹽、少許糖和生抽調味。",
      ],
    },
  },
]
