import type { Recipe } from "@/lib/recipes"

/**
 * Taiwanese + SEA batch W3J — cookable searchable outlines only.
 * Shelf stand-ins noted in comments where specialty items are missing.
 */
export const MORE_W3J: Recipe[] = [
  {
    id: "home-san-bei-chicken",
    name: "San bei chicken",
    cuisine: "Taiwanese",
    time: 35,
    servings: 2,
    need: ["Chicken thighs", "Sesame oil", "Soy sauce", "Thai basil", "Chicken wings"],
    optional: ["Garlic", "Ginger", "Shaoxing wine", "Sugar", "Chili oil", "Cooking oil"],
    steps: [
      "Cut 400 g chicken thighs into chunks. Crush garlic and slice ginger.",
      "Heat 2–3 tbsp sesame oil; brown chicken with garlic and ginger. Add 2–3 tbsp soy sauce, Shaoxing wine if using, and a pinch of sugar.",
      "Cover and simmer 12–15 minutes until chicken reaches 74°C / 165°F. Uncover, reduce sauce, then fold in a handful of Thai basil.",
    ],
    zh: {
      name: "三杯雞",
      steps: [
        "雞脾約 400 克切件。拍蒜、薑切片。",
        "熱 2 至 3 湯匙麻油，下雞、蒜、薑煎香；加 2 至 3 湯匙生抽、料酒和少許糖。",
        "加蓋炆 12 至 15 分鐘至雞全熟（74°C），揭蓋收汁，拌入金不換。",
      ],
    },
  },
  {
    id: "home-lu-rou-fan",
    name: "Lu rou fan",
    cuisine: "Taiwanese",
    time: 45,
    servings: 3,
    need: ["Ground pork", "Soy sauce", "Cooked rice"],
    optional: ["Garlic", "Onion", "Sugar", "Eggs", "Pickles", "White pepper", "Cooking oil", "Shaoxing wine", "Sichuan peppercorns", "Ginger"],
    steps: [
      "Mince garlic and finely chop onion. Soften onion/garlic in oil; add 350 g ground pork and cook until no longer pink.",
      "Add 3–4 tbsp soy sauce, 1–2 tsp sugar, white pepper, and 1 cup water. Simmer 25–30 minutes until saucy and savory.",
      "Spoon over hot cooked rice. Optional: top with a soft-boiled egg and pickles.",
    ],
    zh: {
      name: "滷肉飯",
      steps: [
        "蒜蓉和洋蔥切碎。炒軟後下免治豬肉約 350 克炒至變色。",
        "加 3 至 4 湯匙生抽、1 至 2 茶匙糖、白胡椒和一杯水，炆 25 至 30 分鐘至濃香。",
        "淋在熱飯上；可加半熟蛋和醃瓜。",
      ],
    },
  },
  {
    id: "home-oyster-omelette",
    name: "Oyster omelette-home",
    cuisine: "Taiwanese",
    time: 20,
    servings: 2,
    // Stand-in: Eggs + Shrimp for oyster omelette
    need: ["Eggs", "Shrimp"],
    optional: ["Flour", "Cornstarch", "Spring onion", "Garlic", "Soy sauce", "Chili oil", "Salt"],
    steps: [
      "Beat 3 eggs. Mix 2 tbsp flour or cornstarch with a little water into a thin batter. Peel shrimp and season lightly with salt.",
      "Pour batter into a hot oiled pan; scatter shrimp, then pour eggs over. Cook until set on the bottom.",
      "Flip or scramble gently until eggs are cooked and shrimp are opaque. Serve with soy sauce or chili oil; spring onion on top.",
    ],
    zh: {
      name: "蚵仔煎風",
      steps: [
        "打散三隻蛋。兩湯匙麵粉或生粉加少許水成稀漿。蝦去殼略撒鹽。",
        "熱油倒粉漿，撒蝦，再倒蛋液，煎至底部定型。",
        "翻面或略炒至蛋熟蝦熟，淋生抽或辣椒油，撒葱花。",
      ],
    },
  },
  {
    id: "home-scallion-pancake",
    name: "Scallion pancake",
    cuisine: "Taiwanese",
    time: 35,
    servings: 2,
    need: ["Flour", "Spring onion"],
    optional: ["Salt", "Sesame oil", "Eggs", "Butter", "Cooking oil", "Avocado", "Soy sauce", "Chili oil", "Bread"],
    steps: [
      "Mix 1½ cups flour with about 2/3 cup hot water and a pinch of salt into a soft dough; rest 15 minutes.",
      "Roll thin, brush sesame oil or butter, scatter chopped spring onion, roll up and coil into a disc; roll flat again.",
      "Pan-fry both sides in a little oil until blistered and golden, 3–4 minutes per side. Optional: brush with beaten egg for extra color.",
    ],
    zh: {
      name: "蔥油餅",
      steps: [
        "麵粉約一杯半加約三分二杯熱水、少許鹽揉成軟麵團，醒 15 分鐘。",
        "擀薄掃麻油或牛油，撒葱花，捲起再盤成餅再擀扁。",
        "少油兩面煎 3 至 4 分鐘至金黄起泡；可掃蛋液增色。",
      ],
    },
  },
  {
    id: "home-minced-pork-pickles",
    name: "Minced pork with pickles",
    cuisine: "Taiwanese",
    time: 20,
    servings: 2,
    need: ["Ground pork", "Pickles"],
    optional: ["Garlic", "Soy sauce", "Sugar", "Spring onion", "Chili oil", "Cooked rice"],
    steps: [
      "Finely chop pickles. Soften garlic in oil; add 250 g ground pork and cook until browned.",
      "Stir in pickles, 1 tbsp soy sauce, and a pinch of sugar; cook 3–4 minutes until fragrant and slightly dry.",
      "Finish with spring onion or chili oil. Serve over cooked rice.",
    ],
    zh: {
      name: "瓜仔肉",
      steps: [
        "醃瓜切碎。爆香蒜蓉，下免治豬肉約 250 克炒至上色。",
        "下醃瓜、一湯匙生抽和少許糖，炒 3 至 4 分鐘至香乾。",
        "撒葱或加辣椒油，拌飯吃。",
      ],
    },
  },
  {
    id: "home-thai-basil-chicken",
    name: "Thai basil chicken",
    cuisine: "Thai",
    time: 20,
    servings: 2,
    need: ["Chicken thighs", "Thai basil", "Carrots"],
    optional: ["Garlic", "Chili oil", "Soy sauce", "Oyster sauce", "Sugar", "Onion", "Cooked rice", "Cornstarch", "Spring onion", "Cooking oil"],
    steps: [
      "Mince 350 g chicken thighs or chop finely. Crush garlic.",
      "Stir-fry garlic and chili oil; add chicken and cook until it reaches 74°C / 165°F, about 5–7 minutes.",
      "Season with soy sauce, oyster sauce, and a pinch of sugar. Fold in a big handful of Thai basil and onion if using. Serve with rice.",
    ],
    zh: {
      name: "打拋雞",
      steps: [
        "雞脾約 350 克剁碎或切細。拍蒜。",
        "爆香蒜和辣椒油，下雞炒至全熟（74°C），約 5 至 7 分鐘。",
        "加生抽、蠔油和少許糖，拌入大量金不換（可加洋蔥），伴飯。",
      ],
    },
  },
  {
    id: "home-pad-thai",
    name: "Pad Thai home",
    cuisine: "Thai",
    time: 30,
    servings: 2,
    need: ["Rice vermicelli", "Eggs", "Bean sprouts", "Chicken breast"],
    optional: ["Shrimp", "Peanuts", "Soy sauce", "Sugar", "Vinegar", "Garlic", "Spring onion", "Chili oil", "Tofu", "White pepper", "Cornstarch", "Shallot", "Cooking oil"],
    steps: [
      "Soak rice vermicelli until pliable; drain. Beat 2 eggs. Mix 2 tbsp soy sauce, 1 tbsp sugar, and 1 tsp vinegar as a quick pad-Thai-style sauce.",
      "Stir-fry garlic; scramble eggs, then push aside. Add shrimp or tofu if using until just cooked.",
      "Add noodles and sauce; toss until coated. Fold in bean sprouts, crushed peanuts, and spring onion; chili oil to taste.",
    ],
    zh: {
      name: "泰式炒河風",
      steps: [
        "米粉浸軟瀝乾。打散兩隻蛋。兩湯匙生抽、一湯匙糖、一茶匙醋拌成醬。",
        "爆香蒜，炒蛋推開；可下蝦或豆腐炒至刚熟。",
        "下米粉和醬炒匀，拌芽菜、碎花生和葱，可加辣椒油。",
      ],
    },
  },
  {
    id: "home-tom-yum",
    name: "Tom yum home",
    cuisine: "Thai",
    time: 30,
    servings: 2,
    need: ["Shrimp", "Lemongrass", "Mushroom"],
    // Soy sauce stands in for fish sauce in seasoning steps
    optional: ["Lemon", "Chili oil", "Tomato", "Garlic", "Salt", "Sugar", "Soy sauce", "Spring onion", "Cooking oil", "Chicken stock", "Shallot", "Cilantro", "Dried chili"],
    steps: [
      "Bruise lemongrass and cut into lengths. Slice mushrooms; peel shrimp.",
      "Simmer lemongrass (and garlic/tomato if using) in 4 cups water 8–10 minutes. Add mushrooms; cook 3 minutes.",
      "Add shrimp until pink, 2–3 minutes. Season with soy sauce (fish-sauce stand-in), lemon juice, chili oil, salt, and a pinch of sugar. Finish with spring onion.",
    ],
    zh: {
      name: "冬陰功風",
      steps: [
        "香茅拍扁切段。蘑菇切片，蝦去殼。",
        "香茅（可加蒜番茄）加水四杯煮 8 至 10 分鐘；下蘑菇再煮 3 分鐘。",
        "下蝦煮 2 至 3 分鐘至變色；用生抽（代替魚露）、檸檬汁、辣椒油、鹽和少許糖調味，撒葱。",
      ],
    },
  },
  {
    id: "home-vietnamese-caramel-pork",
    name: "Vietnamese caramel pork",
    cuisine: "Vietnamese",
    time: 40,
    servings: 3,
    need: ["Pork chops", "Sugar", "Soy sauce"],
    optional: ["Garlic", "Ginger", "Spring onion", "Chili oil", "Cooked rice", "Eggs"],
    steps: [
      "Cut 400 g pork chops into bite-size pieces. Melt 2–3 tbsp sugar in a pan until amber caramel (watch closely).",
      "Add pork and toss to coat; add soy sauce, garlic/ginger, and 1/2 cup water.",
      "Simmer covered 20–25 minutes until tender and sauce is sticky-savory. Optional soft egg on the side; serve with rice.",
    ],
    zh: {
      name: "越式焦糖豬肉",
      steps: [
        "豬扒約 400 克切件。鑊中溶 2 至 3 湯匙糖至琥珀色（留意勿焦）。",
        "下豬肉拌匀，加生抽、蒜薑和半杯水。",
        "加蓋炆 20 至 25 分鐘至軟汁稠；可配半熟蛋和白飯。",
      ],
    },
  },
  {
    id: "home-lemongrass-chicken",
    name: "Lemongrass chicken",
    cuisine: "Vietnamese",
    time: 30,
    servings: 2,
    need: ["Chicken thighs", "Lemongrass"],
    optional: ["Garlic", "Soy sauce", "Sugar", "Chili oil", "Onion", "Cooked rice", "Sesame oil", "Oyster sauce", "Shallot", "Lemon"],
    steps: [
      "Mince lemongrass finely (tender white part). Cut 400 g chicken thighs into pieces; toss with lemongrass, garlic, soy sauce, and a pinch of sugar.",
      "Marinate 10 minutes. Stir-fry or pan-fry until chicken reaches 74°C / 165°F, about 8–10 minutes.",
      "Add onion strips if using; finish with chili oil or sesame oil. Serve with rice.",
    ],
    zh: {
      name: "香茅雞",
      steps: [
        "香茅嫩白部切蓉。雞脾約 400 克切件，加香茅、蒜、生抽和少許糖醃 10 分鐘。",
        "炒或煎至雞全熟（74°C），約 8 至 10 分鐘。",
        "可加洋蔥絲，淋辣椒油或麻油，伴飯。",
      ],
    },
  },
  {
    id: "home-coconut-curry-tofu",
    name: "Coconut curry tofu",
    cuisine: "Thai",
    time: 30,
    servings: 2,
    need: ["Tofu", "Coconut milk", "Curry powder"],
    optional: ["Onion", "Garlic", "Bell pepper", "Potato", "Salt", "Sugar", "Cooked rice", "Cooking oil", "Ginger", "Cilantro"],
    steps: [
      "Cube tofu; pan-fry until golden. Soften onion and garlic; stir in 1–2 tsp curry powder until fragrant.",
      "Pour in 1 cup coconut milk and a splash of water; add potato or bell pepper if using.",
      "Simmer 10–12 minutes; return tofu and warm through. Season with salt and a pinch of sugar. Serve with rice.",
    ],
    zh: {
      name: "椰香咖喱豆腐",
      steps: [
        "豆腐切塊煎至金黄。炒軟洋蔥蒜蓉，下 1 至 2 茶匙咖喱粉炒香。",
        "倒入一杯椰漿和少許水；可加薯仔或燈籠椒。",
        "炆 10 至 12 分鐘，回豆腐加热，加鹽和少許糖，伴飯。",
      ],
    },
  },
  {
    id: "home-pineapple-fried-rice",
    name: "Pineapple fried rice",
    cuisine: "Thai",
    time: 25,
    servings: 2,
    need: ["Cooked rice", "Pineapple", "Eggs", "Carrots", "Chicken breast"],
    optional: ["Shrimp", "Onion", "Garlic", "Soy sauce", "Curry powder", "Spring onion", "Peanuts", "Salt", "Cooking oil", "Sesame oil", "Cornstarch", "White pepper", "Sugar"],
    steps: [
      "Dice pineapple; beat 2 eggs. Soften onion/garlic; scramble eggs, then add shrimp if using until just cooked.",
      "Add cold cooked rice and toss until hot. Season with soy sauce, optional 1/2 tsp curry powder, and salt.",
      "Fold in pineapple and crushed peanuts; finish with spring onion.",
    ],
    zh: {
      name: "菠蘿炒飯",
      steps: [
        "菠蘿切丁，打散兩隻蛋。炒軟洋蔥蒜，炒蛋，可下蝦炒至刚熟。",
        "下隔夜飯炒熱，加生抽、可加半茶匙咖喱粉和鹽。",
        "拌入菠蘿和碎花生，撒葱花。",
      ],
    },
  },
  {
    id: "home-taiwanese-tomato-egg-rice",
    name: "Taiwanese tomato eggs on rice",
    cuisine: "Taiwanese",
    time: 20,
    servings: 2,
    need: ["Tomato", "Eggs", "Cooked rice"],
    optional: ["Sugar", "Salt", "Soy sauce", "Spring onion", "Ketchup", "Ginger", "Cornstarch", "Cooking oil"],
    steps: [
      "Cut tomatoes into wedges; beat 3 eggs with a pinch of salt.",
      "Scramble eggs until just set; remove. Cook tomatoes with sugar and ketchup until saucy, 4–5 minutes.",
      "Fold eggs back in; spoon over hot cooked rice. Finish with spring onion or a dash of soy sauce.",
    ],
    zh: {
      name: "台式番茄蛋飯",
      steps: [
        "番茄切角；三隻蛋加少許鹽打散。",
        "炒蛋至刚凝固盛起；番茄加糖和茄汁煮 4 至 5 分鐘至出汁。",
        "拌回雞蛋，鋪熱飯上，可撒葱或淋少許生抽。",
      ],
    },
  },
  {
    id: "home-sesame-chicken-taiwanese",
    name: "Sesame chicken Taiwanese-ish",
    cuisine: "Taiwanese",
    time: 30,
    servings: 2,
    need: ["Chicken thighs", "Sesame seeds", "Soy sauce"],
    optional: ["Garlic", "Ginger", "Sugar", "Sesame oil", "Cornstarch", "Spring onion", "Cooking oil", "Flour", "Baking soda", "Salt", "Eggs", "Chicken stock", "White pepper", "Oyster sauce", "Vinegar", "Broccoli"],
    steps: [
      "Cut 400 g chicken thighs into pieces; toss with soy sauce, cornstarch, and minced garlic/ginger.",
      "Pan-fry until golden and chicken reaches 74°C / 165°F, about 8–10 minutes.",
      "Toss with a pinch of sugar, sesame oil, and toasted sesame seeds. Finish with spring onion.",
    ],
    zh: {
      name: "芝麻雞",
      steps: [
        "雞脾約 400 克切件，加生抽、生粉和蒜薑蓉拌匀。",
        "煎至金黄全熟（74°C），約 8 至 10 分鐘。",
        "拌少許糖、麻油和炒香芝麻，撒葱花。",
      ],
    },
  },
  {
    id: "home-thai-cucumber-salad",
    name: "Thai cucumber salad",
    cuisine: "Thai",
    time: 15,
    servings: 2,
    need: ["Cucumber", "Sugar", "Vinegar"],
    optional: ["Chili oil", "Soy sauce", "Peanuts", "Spring onion", "Salt", "Garlic", "Cooking oil", "Sesame oil"],
    steps: [
      "Slice cucumber thinly. Mix 1 tbsp sugar, 2 tbsp vinegar, a splash of soy sauce, and chili oil if using.",
      "Toss cucumber with dressing and a pinch of salt; rest 5–10 minutes.",
      "Top with crushed peanuts, spring onion, and minced garlic if using.",
    ],
    zh: {
      name: "泰式青瓜沙律",
      steps: [
        "青瓜切薄片。一湯匙糖、兩湯匙醋、少許生抽和辣椒油拌匀。",
        "拌青瓜加少許鹽，静置 5 至 10 分鐘。",
        "撒碎花生、葱花，可加蒜蓉。",
      ],
    },
  },
  {
    id: "home-vietnamese-garlic-fish",
    name: "Vietnamese garlic fish",
    cuisine: "Vietnamese",
    time: 25,
    servings: 2,
    need: ["White fish", "Garlic"],
    optional: ["Soy sauce", "Sugar", "Lemon", "Chili oil", "Spring onion", "Salt", "Cooked rice"],
    steps: [
      "Pat fish dry; season with salt. Mince a generous amount of garlic.",
      "Pan-fry fish 3–4 minutes per side until opaque and flaky. Soften garlic in the same pan with a little oil.",
      "Add soy sauce (fish-sauce stand-in), a pinch of sugar, lemon juice, and chili oil; spoon over fish. Finish with spring onion; serve with rice.",
    ],
    zh: {
      name: "越式蒜香魚",
      steps: [
        "魚抹乾撒鹽。多量蒜切蓉。",
        "魚每面煎 3 至 4 分鐘至熟透可拆；同鑊炒香蒜蓉。",
        "加生抽（代替魚露）、少許糖、檸檬汁和辣椒油淋魚，撒葱，伴飯。",
      ],
    },
  },
  {
    id: "home-green-curry-chicken",
    name: "Green curry chicken",
    cuisine: "Thai",
    time: 35,
    servings: 3,
    need: ["Chicken thighs", "Coconut milk", "Thai basil"],
    optional: ["Curry powder", "Eggplant", "Green beans", "Garlic", "Onion", "Salt", "Sugar", "Chili oil", "Cooked rice", "Cornstarch", "Oyster sauce", "Cooking oil", "Chicken stock"],
    steps: [
      "Cut 400 g chicken thighs into chunks. Soften garlic/onion; stir in 1–2 tsp curry powder and chili oil as a green-curry-style base.",
      "Add coconut milk and chicken; simmer 15–18 minutes until chicken reaches 74°C / 165°F.",
      "Add eggplant or green beans if using for the last 8 minutes. Season with salt and sugar; fold in Thai basil. Serve with rice.",
    ],
    zh: {
      name: "青咖喱雞",
      steps: [
        "雞脾約 400 克切件。炒軟蒜洋蔥，下 1 至 2 茶匙咖喱粉和辣椒油作青咖喱風味底。",
        "加椰漿和雞炆 15 至 18 分鐘至全熟（74°C）。",
        "最後 8 分鐘可加茄子或四季豆；加鹽糖，拌金不換，伴飯。",
      ],
    },
  },
  {
    id: "home-thai-shrimp-stir-fry",
    name: "Thai shrimp stir-fry",
    cuisine: "Thai",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Thai basil"],
    optional: ["Garlic", "Chili oil", "Soy sauce", "Oyster sauce", "Onion", "Bell pepper", "Sugar", "Broccoli", "Cooking oil", "Cooked rice", "Shaoxing wine", "Sesame oil", "Salt", "White pepper", "Eggs"],
    steps: [
      "Peel 350 g shrimp. Crush garlic.",
      "Stir-fry garlic and chili oil; add shrimp and cook until pink and opaque, 2–3 minutes.",
      "Season with soy sauce, oyster sauce, and a pinch of sugar. Toss in Thai basil and onion/pepper if using.",
    ],
    zh: {
      name: "泰式炒蝦",
      steps: [
        "蝦約 350 克去殼。拍蒜。",
        "爆香蒜和辣椒油，下蝦炒 2 至 3 分鐘至變色熟透。",
        "加生抽、蠔油和少許糖，拌入金不換，可加洋蔥燈籠椒。",
      ],
    },
  },
  {
    id: "home-beef-pho-style",
    name: "Beef pho-style noodle soup home",
    cuisine: "Vietnamese",
    time: 50,
    servings: 2,
    need: ["Beef brisket", "Rice vermicelli", "Onion"],
    optional: ["Ginger", "Soy sauce", "Spring onion", "Bean sprouts", "Lemon", "Chili oil", "Salt", "White pepper", "Tomato", "Sesame oil", "Vinegar", "Shrimp", "Cooking oil", "Eggs"],
    steps: [
      "Cut 350 g beef brisket into slices or chunks. Char or soften onion and ginger in a dry pan for aroma.",
      "Simmer onion, ginger, and beef in about 1.2 L water 35–40 minutes until beef is tender. Season with soy sauce (fish-sauce stand-in), salt, and white pepper.",
      "Cook rice vermicelli; divide into bowls. Ladle hot broth and beef over noodles; top with bean sprouts, spring onion, lemon, and chili oil.",
    ],
    zh: {
      name: "牛肉粉風",
      steps: [
        "牛腩約 350 克切片或件。洋蔥薑乾鑊略烤或炒香。",
        "洋蔥薑和牛肉加水約 1.2 升炆 35 至 40 分鐘至軟；用生抽（代替魚露）、鹽和白胡椒調味。",
        "米粉煮熟分碗，淋熱湯和牛肉，加芽菜、葱、檸檬和辣椒油。",
      ],
    },
  },
  {
    id: "home-taiwanese-cabbage-pork",
    name: "Taiwanese cabbage pork",
    cuisine: "Taiwanese",
    time: 25,
    servings: 2,
    need: ["Ground pork", "Cabbage"],
    optional: ["Garlic", "Soy sauce", "Sugar", "Sesame oil", "Chili oil", "Spring onion"],
    steps: [
      "Shred cabbage. Soften garlic; brown 250 g ground pork.",
      "Add cabbage and stir-fry 5–7 minutes until wilted but still crisp-tender.",
      "Season with soy sauce, a pinch of sugar, sesame oil, and chili oil if using. Finish with spring onion.",
    ],
    zh: {
      name: "高麗菜炒肉末",
      steps: [
        "椰菜切絲。爆香蒜蓉，下免治豬肉約 250 克炒香。",
        "下椰菜炒 5 至 7 分鐘至软但仍爽。",
        "加生抽、少許糖、麻油，可加辣椒油，撒葱花。",
      ],
    },
  },
  {
    id: "home-garlic-morning-glory",
    name: "SEA garlic morning glory",
    cuisine: "Asian",
    time: 12,
    servings: 2,
    need: ["Water spinach", "Garlic"],
    optional: ["Chili oil", "Soy sauce", "Oyster sauce", "Fermented tofu", "Sugar", "Salt"],
    steps: [
      "Wash water spinach and cut into lengths. Crush garlic.",
      "Heat oil until very hot; stir-fry garlic (and chili oil) until fragrant, then add water spinach.",
      "Season with soy sauce or oyster sauce (fermented tofu mash optional) and a pinch of sugar; toss 1–2 minutes until just wilted.",
    ],
    zh: {
      name: "蒜蓉通菜",
      steps: [
        "通菜洗净切段。拍蒜。",
        "油大熱爆香蒜蓉（可加辣椒油），下通菜。",
        "加生抽或蠔油（可加腐乳蓉）和少許糖，快炒 1 至 2 分鐘至刚软。",
      ],
    },
  },
  {
    id: "home-lemongrass-tofu",
    name: "Lemongrass tofu",
    cuisine: "Vietnamese",
    time: 25,
    servings: 2,
    need: ["Tofu", "Lemongrass"],
    optional: ["Garlic", "Soy sauce", "Sugar", "Chili oil", "Onion", "Sesame oil", "Cooked rice"],
    steps: [
      "Cube tofu and pan-fry until golden. Mince lemongrass and garlic.",
      "Stir-fry lemongrass and garlic; add tofu, soy sauce, a pinch of sugar, and chili oil.",
      "Toss 2–3 minutes with onion if using. Finish with sesame oil; serve with rice.",
    ],
    zh: {
      name: "香茅豆腐",
      steps: [
        "豆腐切塊煎至金黄。香茅和蒜切蓉。",
        "炒香香茅蒜蓉，下豆腐、生抽、少許糖和辣椒油。",
        "拌炒 2 至 3 分鐘，可加洋蔥，滴麻油，伴飯。",
      ],
    },
  },
  {
    id: "home-basil-eggplant",
    name: "Basil eggplant",
    cuisine: "Thai",
    time: 25,
    servings: 2,
    need: ["Eggplant", "Thai basil"],
    optional: ["Garlic", "Chili oil", "Soy sauce", "Oyster sauce", "Sugar", "Onion", "Chicken breast", "Cooking oil", "Cornstarch", "Spring onion", "Shaoxing wine", "Sesame oil", "White pepper", "Chicken stock"],
    steps: [
      "Cut eggplant into batons; pan-fry or steam until soft.",
      "Stir-fry garlic and chili oil; add eggplant with soy sauce, oyster sauce, and a pinch of sugar.",
      "Toss 2 minutes; fold in Thai basil and onion if using until wilted and fragrant.",
    ],
    zh: {
      name: "金不換茄子",
      steps: [
        "茄子切條，煎或蒸至软。",
        "爆香蒜和辣椒油，下茄子加生抽、蠔油和少許糖。",
        "炒 2 分鐘，拌入金不換（可加洋蔥）至香软。",
      ],
    },
  },
  {
    id: "home-chicken-satay-rice",
    name: "Chicken satay rice",
    cuisine: "Asian",
    time: 30,
    servings: 2,
    need: ["Chicken thighs", "Satay sauce", "Cooked rice"],
    optional: ["Onion", "Garlic", "Soy sauce", "Cucumber", "Peanuts", "Chili oil", "Cornstarch", "Cooking oil", "Oyster sauce", "Eggs", "Ginger", "White pepper", "Sugar", "Salt", "Bean sprouts", "Spring onion", "Shaoxing wine"],
    steps: [
      "Cut 350 g chicken thighs into strips; toss with a little soy sauce and garlic.",
      "Pan-fry chicken until it reaches 74°C / 165°F, about 8–10 minutes. Soften onion if using.",
      "Stir in 3–4 tbsp satay sauce and a splash of water until coated and glossy. Serve over rice with cucumber and crushed peanuts.",
    ],
    zh: {
      name: "沙爹雞肉飯",
      steps: [
        "雞脾約 350 克切條，加少許生抽和蒜蓉。",
        "煎至雞全熟（74°C），約 8 至 10 分鐘；可炒软洋蔥。",
        "下 3 至 4 湯匙沙爹醬和少許水拌至亮澤，鋪飯上，伴青瓜和碎花生。",
      ],
    },
  },
  {
    id: "home-peanut-tofu-stir-fry",
    name: "Peanut tofu stir-fry",
    cuisine: "Asian",
    time: 25,
    servings: 2,
    need: ["Tofu", "Peanuts"],
    optional: ["Garlic", "Soy sauce", "Chili oil", "Sugar", "Spring onion", "Bell pepper", "Sesame oil"],
    steps: [
      "Cube tofu; pan-fry until golden. Roughly crush peanuts.",
      "Stir-fry garlic and bell pepper if using; return tofu with soy sauce, chili oil, and a pinch of sugar.",
      "Toss with peanuts 1 minute. Finish with spring onion and sesame oil.",
    ],
    zh: {
      name: "花生豆腐炒",
      steps: [
        "豆腐切塊煎至金黄。花生略壓碎。",
        "爆香蒜（可加燈籠椒），回豆腐加生抽、辣椒油和少許糖。",
        "拌花生炒 1 分鐘，撒葱滴麻油。",
      ],
    },
  },
]
