import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W2E: Recipe[] = [
  {
    id: "home-kung-pao-chicken",
    name: "Kung pao chicken",
    cuisine: "Sichuan",
    time: 25,
    servings: 2,
    need: ["Chicken thighs", "Peanuts", "Bell pepper"],
    optional: ["Garlic", "Ginger", "Spring onion", "Soy sauce", "Chili oil", "Sugar", "Cornstarch", "Vinegar", "Broccoli", "Celery", "Carrots", "Shallot", "Cooking oil", "Salt", "Shaoxing wine", "White pepper", "Oyster sauce"],
    steps: [
      "Dice 300 g chicken thighs; toss with 1 tsp soy sauce, 1 tsp cornstarch, and a pinch of salt.",
      "Stir-fry chicken in a hot oiled pan until cooked through (74°C / 165°F); remove. Flash-fry diced bell pepper, garlic, and ginger.",
      "Return chicken with 1 tbsp soy sauce, 1 tsp vinegar, ½ tsp sugar, chili oil to taste, and a handful of peanuts; toss 1 minute with spring onion.",
    ],
    zh: {
      name: "宮保雞丁",
      steps: [
        "雞髀 300 克切丁，加 1 茶匙生抽、1 茶匙生粉和少許鹽拌勻。",
        "熱鑊下油炒雞至全熟（74°C / 165°F）盛起；快炒燈籠椒丁、蒜、薑。",
        "回雞，加 1 湯匙生抽、1 茶匙醋、半茶匙糖、適量辣椒油和花生米，拌炒 1 分鐘，撒蔥。",
      ],
    },
  },
  {
    id: "home-twice-cooked-pork",
    name: "Twice-cooked pork",
    cuisine: "Sichuan",
    time: 30,
    servings: 2,
    need: ["Carrots", "Tofu", "Onion", "Garlic", "Cabbage", "Pork chops", "Hoisin sauce", "Doubanjiang"],
    optional: ["White pepper", "Cooking oil", "Shaoxing wine", "Sesame oil", "Oyster sauce", "Soy sauce", "Sugar", "Cornstarch"],
    steps: [
      "Simmer 2 pork chops in water 12–15 minutes until just cooked; cool and slice thin.",
      "Stir-fry garlic and ginger; add pork slices and fry until edges curl and lightly browned.",
      "Add cabbage and bell pepper strips with 1 tbsp soy sauce, chili oil, and a pinch of sugar; toss until veg is crisp-tender.",
    ],
    zh: {
      name: "回鍋肉",
      steps: [
        "豬扒兩塊加水煮 12 至 15 分鐘至剛熟，晾涼切薄片。",
        "爆香蒜薑，下豬肉片炒至邊緣捲曲微焦。",
        "下椰菜和燈籠椒絲，加 1 湯匙生抽、辣椒油和少許糖，炒至菜爽脆。",
      ],
    },
  },
  {
    id: "home-dan-dan-noodles",
    name: "Dan dan noodles",
    cuisine: "Sichuan",
    time: 20,
    servings: 2,
    need: ["Noodles", "Ground pork"],
    optional: ["Garlic", "Ginger", "Soy sauce", "Chili oil", "Peanut butter", "Spring onion", "Sesame oil", "Sichuan peppercorns", "Cooking oil", "Shaoxing wine", "Five-spice powder", "Pickled mustard", "Sugar", "Lettuce", "Peanuts"],
    steps: [
      "Boil noodles until tender; drain, reserving ½ cup cooking water.",
      "Brown 150 g ground pork with garlic and ginger until cooked through (74°C / 165°F).",
      "Whisk 1 tbsp soy sauce, 1 tsp chili oil, 1 tsp peanut butter, and noodle water; toss with noodles and pork. Finish with spring onion and sesame oil.",
    ],
    zh: {
      name: "擔擔麵",
      steps: [
        "麵煮熟瀝乾，留半杯麵水。",
        "免治豬肉 150 克加蒜薑炒至全熟（74°C / 165°F）。",
        "用 1 湯匙生抽、1 茶匙辣椒油、1 茶匙花生醬和麵水調汁，拌麵和肉，可加蔥花麻油。",
      ],
    },
  },
  {
    id: "home-dry-pot-cauliflower",
    name: "Sichuan dry pot cauliflower",
    cuisine: "Sichuan",
    time: 25,
    servings: 2,
    need: ["Pork chops", "Cauliflower", "Garlic", "Ginger", "Dried chili", "Bell pepper", "Spring onion"],
    optional: ["Salt", "Soy sauce", "Shaoxing wine", "Cooking oil", "Sesame oil", "White pepper", "Oyster sauce", "Sugar"],
    steps: [
      "Cut cauliflower into bite-size florets; blanch 2 minutes and drain well.",
      "Render diced bacon until crisp; add garlic, ginger, and optional chili oil.",
      "Add cauliflower (and bell pepper if using); stir-fry on high 4–5 minutes with 1 tbsp soy sauce until charred at edges.",
    ],
    zh: {
      name: "乾鍋菜花",
      steps: [
        "椰菜花切小朵，焯水 2 分鐘瀝乾。",
        "煙肉粒煎出油，下蒜薑和適量辣椒油。",
        "下菜花（可加燈籠椒），大火炒 4 至 5 分鐘，加 1 湯匙生抽至邊位微焦。",
      ],
    },
  },
  {
    id: "home-chili-oil-noodles",
    name: "Chili oil noodles",
    cuisine: "Sichuan",
    time: 15,
    servings: 1,
    need: ["Noodles", "Garlic"],
    optional: ["Chili oil", "Soy sauce", "Vinegar", "Spring onion", "Sesame seeds", "Sugar"],
    steps: [
      "Boil a portion of noodles until tender; drain.",
      "In the serving bowl mix 2 tsp chili oil, 1 tbsp soy sauce, 1 tsp vinegar, minced garlic, and a pinch of sugar.",
      "Toss hot noodles in the sauce; top with spring onion and sesame seeds.",
    ],
    zh: {
      name: "紅油拌麵",
      steps: [
        "煮一碗麵至熟，瀝乾。",
        "碗內調 2 茶匙辣椒油、1 湯匙生抽、1 茶匙醋、蒜蓉和少許糖。",
        "熱麵拌勻，撒蔥花和芝麻。",
      ],
    },
  },
  {
    id: "home-yuxiang-shredded-pork",
    name: "Fish-fragrant shredded pork",
    cuisine: "Sichuan",
    time: 25,
    servings: 2,
    need: ["Pork chops", "Broccoli", "Carrots", "Bell pepper"],
    optional: ["Cornstarch", "Cooking oil", "White pepper", "Shaoxing wine", "Vinegar", "Sugar", "Salt", "Chili oil"],
    steps: [
      "Slice pork into thin shreds; toss with 1 tsp soy sauce and 1 tsp cornstarch.",
      "Stir-fry pork until cooked through (74°C / 165°F); remove. Stir-fry carrot and pepper shreds with garlic and ginger.",
      "Return pork with 1 tbsp soy sauce, 1 tsp vinegar, 1 tsp sugar, and chili oil; toss 1 minute with spring onion.",
    ],
    zh: {
      name: "魚香肉絲",
      steps: [
        "豬扒切絲，加 1 茶匙生抽和生粉拌勻。",
        "炒肉絲至全熟（74°C）盛起；炒紅蘿蔔、燈籠椒絲配蒜薑。",
        "回肉，加 1 湯匙生抽、1 茶匙醋、1 茶匙糖和辣椒油，拌炒 1 分鐘，撒蔥。",
      ],
    },
  },
  {
    id: "home-garlic-cucumber-spicy",
    name: "Hot garlic cucumber",
    cuisine: "Sichuan",
    time: 10,
    servings: 2,
    need: ["Cucumber", "Garlic"],
    optional: ["Chili oil", "Soy sauce", "Vinegar", "Sugar", "Sesame oil"],
    steps: [
      "Smash and chop 1–2 cucumbers; salt lightly 5 minutes, then drain.",
      "Mix minced garlic with 1 tbsp soy sauce, 1 tsp vinegar, chili oil, and a pinch of sugar.",
      "Toss cucumber in the dressing; finish with a few drops of sesame oil.",
    ],
    zh: {
      name: "蒜泥青瓜",
      steps: [
        "拍開 1 至 2 條青瓜切段，略醃鹽 5 分鐘後瀝乾。",
        "蒜蓉加 1 湯匙生抽、1 茶匙醋、辣椒油和少許糖拌勻。",
        "淋上青瓜拌勻，可滴少許麻油。",
      ],
    },
  },
  {
    id: "home-chongqing-noodles",
    name: "Chongqing noodles (home)",
    cuisine: "Sichuan",
    time: 20,
    servings: 1,
    need: ["Noodles", "Ground pork"],
    optional: ["Garlic", "Ginger", "Chili oil", "Soy sauce", "Spring onion", "Peanuts"],
    steps: [
      "Boil noodles; brown 100 g ground pork with garlic until cooked through (74°C / 165°F).",
      "In the bowl mix chili oil, 1 tbsp soy sauce, and minced ginger.",
      "Add noodles and pork; top with spring onion and crushed peanuts.",
    ],
    zh: {
      name: "重慶小麵",
      steps: [
        "煮麵；免治豬肉 100 克加蒜炒至全熟（74°C）。",
        "碗內調辣椒油、1 湯匙生抽和薑蓉。",
        "下面和肉，撒蔥花和壓碎花生。",
      ],
    },
  },
  {
    id: "home-cumin-beef",
    name: "Spicy cumin beef",
    cuisine: "Sichuan",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Onion"],
    optional: ["Garlic", "Chili oil", "Soy sauce", "White pepper", "Spring onion"],
    steps: [
      "Slice 250 g beef steak thin against the grain; toss with 1 tsp soy sauce.",
      "Sear beef in a very hot oiled pan in batches until just browned; remove.",
      "Stir-fry onion and garlic; return beef with white pepper, chili oil, and 1 tbsp soy sauce; toss 1 minute with spring onion. (Home cumin-style heat.)",
    ],
    zh: {
      name: "孜然牛肉",
      steps: [
        "牛扒 250 克逆紋切薄片，加 1 茶匙生抽拌勻。",
        "熱鑊分批快炒至表面上色盛起。",
        "炒洋蔥蒜頭，回牛肉加白胡椒、辣椒油和 1 湯匙生抽，拌 1 分鐘撒蔥（家常孜然風味）。",
      ],
    },
  },
  {
    id: "home-laziji-chicken",
    name: "Laziji-style chicken (mild home)",
    cuisine: "Sichuan",
    time: 30,
    servings: 2,
    need: ["Chicken thighs", "Dried mushrooms"],
    optional: ["Garlic", "Ginger", "Chili oil", "Soy sauce", "Sugar", "Spring onion", "Peanuts"],
    steps: [
      "Dice chicken thighs; toss with soy sauce and a pinch of sugar.",
      "Stir-fry until cooked through (74°C / 165°F) and lightly crisp at edges.",
      "Add garlic, ginger, chili oil to taste, optional soaked dried mushrooms, and peanuts; toss with spring onion.",
    ],
    zh: {
      name: "辣子雞（家常）",
      steps: [
        "雞髀切丁，加生抽和少許糖拌勻。",
        "炒至全熟（74°C）並邊位微脆。",
        "下蒜薑、適量辣椒油、浸軟冬菇和花生，拌蔥花。",
      ],
    },
  },
  {
    id: "home-shuizhu-mild",
    name: "Shuizhu-style veg pork (mild)",
    cuisine: "Sichuan",
    time: 30,
    servings: 2,
    need: ["Ground pork", "Cabbage", "Tofu"],
    optional: ["Garlic", "Ginger", "Chili oil", "Soy sauce", "White pepper", "Spring onion"],
    steps: [
      "Shape ground pork into small meatballs or loose crumbles; simmer in salted water until cooked through (74°C / 165°F).",
      "Blanch cabbage and tofu slabs in the same pot 2–3 minutes; arrange in a deep bowl with the pork.",
      "Spoon over garlic, white pepper, soy sauce, and chili oil; ladle a little hot broth and finish with spring onion.",
    ],
    zh: {
      name: "水煮（家常輕辣）",
      steps: [
        "免治豬肉搓小丸或鬆散下鍋，煮至全熟（74°C）。",
        "同鍋焯椰菜和豆腐塊 2 至 3 分鐘，連肉盛大碗。",
        "淋蒜蓉、白胡椒、生抽和辣椒油，再舀少許熱湯，撒蔥。",
      ],
    },
  },  {
    id: "home-chili-oil-wonton",
    name: "Spicy wonton in chili oil",
    cuisine: "Sichuan",
    time: 35,
    servings: 2,
    need: ["Ground pork", "Spring onion", "Wonton wrappers", "Garlic"],
    optional: ["Sesame oil", "Soy sauce", "Shaoxing wine", "Salt", "Sugar", "Cooking oil", "White pepper", "Vinegar", "Chili oil"],
    steps: [
      "Mix 200 g ground pork with minced ginger, 1 tsp soy sauce, and a pinch of salt. Wrap in wonton skins.",
      "Boil wontons until they float and pork is cooked through (74°C / 165°F), about 4–5 minutes.",
      "Dress with chili oil, soy sauce, vinegar, garlic, and sesame oil; top with spring onion.",
    ],
    zh: {
      name: "紅油抄手",
      steps: [
        "免治豬肉 200 克加薑蓉、1 茶匙生抽和少許鹽拌勻，包雲吞。",
        "水滾下雲吞，浮起再煮約 4 至 5 分鐘至肉全熟（74°C）。",
        "淋辣椒油、生抽、醋、蒜蓉和麻油，撒蔥。",
      ],
    },
  },
  {
    id: "home-chili-oil-lettuce",
    name: "Garlic chili oil lettuce",
    cuisine: "Sichuan",
    time: 10,
    servings: 2,
    need: ["Lettuce", "Garlic"],
    optional: ["Chili oil", "Soy sauce", "Sesame oil"],
    steps: [
      "Blanch lettuce leaves 20–30 seconds in salted boiling water; drain and plate.",
      "Sizzle minced garlic in 1 tbsp hot oil (or use chili oil).",
      "Mix with 1 tsp soy sauce and a drop of sesame oil; pour over lettuce.",
    ],
    zh: {
      name: "紅油生菜",
      steps: [
        "生菜葉落鹽水焯 20 至 30 秒，瀝乾上碟。",
        "熱油爆香蒜蓉（或用辣椒油）。",
        "加 1 茶匙生抽和少許麻油，淋在生菜上。",
      ],
    },
  },
  {
    id: "home-mapo-eggplant",
    name: "Mapo eggplant",
    cuisine: "Sichuan",
    time: 25,
    servings: 2,
    need: ["Eggplant", "Ground pork"],
    optional: ["Garlic", "Ginger", "Chili oil", "Soy sauce", "Sugar", "Cornstarch", "Spring onion", "Shaoxing wine", "Baking soda", "White pepper", "Cooking oil", "Sichuan peppercorns", "Doubanjiang", "Fermented black beans", "Chicken stock", "Sesame oil"],
    steps: [
      "Pan-fry eggplant pieces until soft; set aside. Brown ground pork until cooked through (74°C / 165°F).",
      "Add garlic, ginger, chili oil, 1 tbsp soy sauce, and a pinch of sugar with a splash of water.",
      "Return eggplant; thicken with a little cornstarch slurry and finish with spring onion.",
    ],
    zh: {
      name: "麻婆茄子",
      steps: [
        "茄子塊煎软盛起；免治豬肉炒至全熟（74°C）。",
        "下蒜薑、辣椒油、1 湯匙生抽、少許糖和少許水。",
        "回茄子，生粉水勾芡，撒蔥。",
      ],
    },
  },
  {
    id: "home-sour-cabbage-pork",
    name: "Sour cabbage with pork",
    cuisine: "Sichuan",
    time: 20,
    servings: 2,
    need: ["Pickles", "Pork chops"],
    optional: ["Garlic", "Ginger", "Chili oil", "Soy sauce", "Spring onion"],
    steps: [
      "Slice pork thin; stir-fry with garlic until cooked through (74°C / 165°F).",
      "Add chopped pickles (sour cabbage style) and ginger; stir-fry 2–3 minutes.",
      "Season with soy sauce and chili oil; finish with spring onion.",
    ],
    zh: {
      name: "酸菜炒肉",
      steps: [
        "豬肉切薄片，加蒜炒至全熟（74°C）。",
        "下切碎酸菜和薑絲，炒 2 至 3 分鐘。",
        "加生抽和辣椒油調味，撒蔥。",
      ],
    },
  },
  {
    id: "home-chili-fried-tofu",
    name: "Chili fried tofu",
    cuisine: "Sichuan",
    time: 20,
    servings: 2,
    need: ["Tofu", "Garlic"],
    optional: ["Chili oil", "Soy sauce", "Spring onion", "Cornstarch", "White pepper"],
    steps: [
      "Pat tofu dry, cube, and pan-fry until golden on most sides.",
      "Add garlic and chili oil; splash soy sauce and a pinch of white pepper.",
      "Toss gently 1 minute; finish with spring onion.",
    ],
    zh: {
      name: "香辣豆腐",
      steps: [
        "豆腐抹乾切塊，煎至多面金黃。",
        "下蒜和辣椒油，加生抽和少許白胡椒。",
        "小心拌炒 1 分鐘，撒蔥。",
      ],
    },
  },
  {
    id: "home-cold-chili-noodles",
    name: "Cold noodles with chili",
    cuisine: "Sichuan",
    time: 15,
    servings: 1,
    need: ["Noodles", "Cucumber"],
    optional: ["Chili oil", "Soy sauce", "Vinegar", "Garlic", "Sesame oil", "Sugar"],
    steps: [
      "Boil noodles, rinse under cold water, and drain well.",
      "Shred cucumber. Mix 1 tbsp soy sauce, 1 tsp vinegar, chili oil, garlic, and a pinch of sugar.",
      "Toss noodles with sauce and cucumber; drizzle sesame oil.",
    ],
    zh: {
      name: "涼麵",
      steps: [
        "麵煮熟過冷河瀝乾。",
        "青瓜切絲。調 1 湯匙生抽、1 茶匙醋、辣椒油、蒜蓉和少許糖。",
        "拌麵和青瓜，滴麻油。",
      ],
    },
  },
]
