import type { Recipe } from "@/lib/recipes"

/**
 * Cuisine expansion w6efgh — title-matched exclusive sources only.
 * Materials (groups/amounts) synced from each dish sourceUrl.
 */
export const MORE_W6EFGH: Recipe[] = [
  {
    id: "home-mung-bean-soup",
    name: "Mung bean soup",
    cuisine: "Hong Kong",
    time: 60,
    servings: 6,
    sourceUrl: "https://thewoksoflife.com/mung-bean-soup/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Mung beans", role: "core", group: "main", amount: 1, unit: "cup" },
      { name: "Cooked rice", role: "core", group: "main", amount: 2, unit: "tbsp", note: "also known as glutinous rice" },
      { name: "Sago", role: "core", group: "main", amount: 0.5, unit: "cup", note: "optional" },
      { name: "Sugar", role: "staple", group: "main", note: "or honey/sweetener of your choice, to taste; optional" },
    ],
    need: ["Mung beans","Cooked rice","Sago"],
    optional: ["Sugar"],
    steps: [
      "First, rinse the beans, dried lily bulb pieces, and sweet rice under cold water. Add them to a large bowl, and cover with a few inches of water. Soak for at least 8 hours or overnight.",
      "Drain the beans, lily bulb, and rice, and transfer to a large pot along with 8 cups of fresh water. Bring to a boil, cover, and simmer for about 1 hour, or until the beans are very soft and beginning to break down. Fresher beans cook faster, while older beans can take a while to cook through, so monitor the cooking process and adjust the cooking time accordingly.",
      "If using sago or tapioca, add it to the soup after it’s been cooking for about 40 minutes. It will take about 20 minutes for them to cook through (they will be completely translucent).",
      "Finally, stir in your sweetener to taste. You can also refrain from adding sugar at this point, and each person can sweeten their individual bowls to taste.",
    ],
    zh: {
      name: "綠豆沙",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-taro-sago",
    name: "Taro sago dessert soup",
    cuisine: "Hong Kong",
    time: 50,
    servings: 6,
    sourceUrl: "https://thewoksoflife.com/taro-sago-dessert-soup/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Sago", role: "core", group: "main", amount: 1, unit: "cup", note: "or mini tapioca pearls" },
      { name: "Taro", role: "core", group: "main", amount: 2, unit: "lb" },
      { name: "Sugar", role: "staple", group: "main", amount: 50, unit: "g", note: "or  1/4 cup / 50g granulated sugar" },
      { name: "Sweet potato", role: "core", group: "main", amount: 5, unit: "oz", note: "1/2 of a medium sweet potato, about 1 cup, cut into 1/4-inch or 0.6cm cubes" },
      { name: "Coconut milk", role: "core", group: "main", amount: 13.5, unit: "oz", note: "1 can" },
      { name: "Milk", role: "core", group: "main", amount: 1, unit: "cup", note: "to taste" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
    ],
    need: ["Sago","Taro","Sweet potato","Coconut milk","Milk"],
    optional: ["Sugar","Salt"],
    steps: [
      "Fill a medium pot about two thirds of the way with water, and bring it to a rolling boil. Stir in the sago (don’t add it before the water is at a full boil!). Simmer for 20 minutes, or until the tapioca is completely translucent, which means it’s fully cooked. If after 20 minutes, the pearls still have a white center, turn off the heat, cover, and let the tapioca sit in the hot water for another 5-10 minutes, or until they’re fully translucent. Drain through a fine-mesh strainer, rinse in cold water to cool, then soak in a bowl of cold water and set aside.",
      "Add 7 cups of water to a large pot along with the bigger 1-inch taro chunks and the rock sugar. Bring to a boil, cover, and simmer over medium heat for 20 minutes, or until the taro is very tender.",
      "Stir in the sweet potato and taro cubes. Bring to a low simmer, cover, and cook for another 10-12 minutes, stirring occasionally to prevent sticking or burning, until the taro and sweet potato cubes are tender.",
      "Stir in the coconut milk, sweetened condensed milk, salt, and vanilla (if using). Cook for another 2 minutes.",
      "Drain the sago, and stir it into the soup. If the soup is too thick, add boiling water until you get the consistency to your liking. Serve!",
    ],
    zh: {
      name: "芋頭西米露",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-cumin-lamb",
    name: "Xinjiang cumin lamb",
    cuisine: "Chinese",
    time: 30,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/cumin-lamb/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Lamb", role: "core", group: "main", amount: 1, unit: "lb", note: "450g, preferably shoulder, cut into ½-inch by 2-inch pieces" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Cornstarch", role: "staple", group: "marinade", amount: 1.5, unit: "tsp" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "optional, if you have a fattier cut of lamb" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Cooked rice", role: "core", group: "main", amount: 1, unit: "tbsp" },
      { name: "White pepper", role: "staple", group: "main", amount: 2, note: "chopped" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 2, note: "chopped" },
      { name: "Cilantro", role: "core", group: "garnish" },
      { name: "Salt", role: "staple", group: "main", note: "to taste" },
    ],
    need: ["Lamb","Cooked rice","Cilantro"],
    optional: ["Cumin","Cornstarch","Cooking oil","Soy sauce","White pepper","Sugar","Spring onion","Salt"],
    steps: [
      "Pad lamb dry with paper towel before cutting. Once cut, combine the lamb with the marinade ingredients in a bowl. Set aside and let marinate for 30 minutes.",
      "Once the lamb has been marinated, heat a wok over medium heat. Add the cumin seeds to the wok and dry toast them until fragrant. Turn off the heat, remove the cumin from the wok, and set aside.",
      "Now heat the wok over the highest setting until it starts to smoke. Add two tablespoons of oil to coat the wok, and then immediately add the lamb. Sear the meat until it turns brown and starts to crisp slightly. The high heat will sear the meat, but keep it tender as well.",
      "Now add the cooked cumin seeds, chili, red pepper flakes (or powder), sugar, scallions, cilantro, and salt. Toss everything together quickly (so that the scallion and cilantro are just wilted), and transfer to a serving dish. Serve hot with plenty of white rice!",
    ],
    zh: {
      name: "孜然羊肉",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-chinese-roast-duck",
    name: "Chinese roast duck",
    cuisine: "Cantonese",
    time: 120,
    servings: 6,
    sourceUrl: "https://thewoksoflife.com/chinese-roast-duck/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Duck", role: "core", group: "main", amount: 1, note: "about 5-6 pounds/2.5kg" },
      { name: "Salt", role: "staple", group: "main", amount: 1.5, unit: "tbsp" },
      { name: "Five-spice powder", role: "staple", group: "main", amount: 2.5, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 2, unit: "tsp" },
      { name: "Ginger", role: "staple", group: "main", amount: 1, unit: "tsp", note: "or galangal powder" },
      { name: "Shaoxing wine", role: "staple", group: "main", amount: 2, unit: "tbsp" },
      { name: "Hoisin sauce", role: "core", group: "main", amount: 1, unit: "tbsp" },
      { name: "Oyster sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Fermented tofu", role: "core", group: "main", amount: 1, unit: "tbsp", note: "a mix of solids and liquid" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 2, unit: "tsp", note: "such as vegetable, canola, peanut, or avocado oil" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, note: "sliced" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 1, note: "white and green parts cut into 2-inch/5cm pieces and smashed" },
      { name: "Orange", role: "core", group: "main", amount: 1, unit: "piece", note: "a 2-inch/5cm piece, broken into a few small pieces" },
      { name: "Vinegar", role: "staple", group: "main", amount: 3, unit: "tbsp", note: "preferably Koon Chun brand" },
    ],
    need: ["Duck","Hoisin sauce","Fermented tofu","Orange"],
    optional: ["Salt","Five-spice powder","Sugar","Ginger","Shaoxing wine","Oyster sauce","Cooking oil","Garlic","Spring onion","Vinegar"],
    steps: [
      "Trim any excess fat from the cavity of the duck, leaving the skin intact. Remove the wing tips using a sharp cleaver or kitchen shears. If you have a whole duck, remove the feet at the joints between the feet and legs.",
      "Turn the skewer over the skin back the way it came from, and insert the skewer again, just above where you initially inserted it. Repeat, weaving the skewer across the skin around the cavity until you’ve sealed it completely. Push any remaining length of the skewer into the cavity.",
      "Place the duck back on the rack (over the roasting pan or wok) breast side down, and carefully ladle all the hot vinegar solution over the duck to coat it completely, just as you did with the boiling water. Make sure to cover all the exposed skin.",
      "When ready to serve, remove the skewer sealing the cavity and carefully pour all the fat and juices into a fat separator. Then pour the juices through a fine-mesh strainer into a bowl to serve with the duck. (Reserve the rendered duck fat for other uses.)",
      "Using a sharp cleaver, cut the duck in half lengthwise from the top of the breast down through to one side of the backbone. Remove any aromatics in the cavity and discard. Next, take the half of the duck with the backbone still attached and make a lengthwise cut along the other side of the backbone to remove it. Cut off the wings and leg quarters. Chop the wings in half at the joint, chop each drumstick into two pieces, and chop the thighs crosswise into three pieces. Then, chop the remaining duck into bite-size pieces, using your cleaver to drive through the soft bones. Serve with the reserved sauce on the side.",
    ],
    zh: {
      name: "燒鴨",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-steamed-ribs-nam-yu",
    name: "Steamed pork ribs with red fermented bean curd",
    cuisine: "Cantonese",
    time: 40,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/steamed-pork-ribs-red-fermented-bean-curd/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Spare ribs", role: "core", group: "main", amount: 1, unit: "lb", note: "cut into 1-inch pieces 450g" },
      { name: "Baking soda", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, unit: "clove", note: "minced" },
      { name: "Ginger", role: "staple", group: "main", amount: 0.25, unit: "tsp", note: "minced or grated" },
      { name: "Sugar", role: "staple", group: "main", amount: 1.5, unit: "tsp" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "White pepper", role: "staple", group: "main", amount: 0.125, unit: "tsp" },
      { name: "Five-spice powder", role: "staple", group: "main", amount: 1 },
      { name: "Fermented tofu", role: "core", group: "main", amount: 1, unit: "tbsp" },
      { name: "Shaoxing wine", role: "staple", group: "main", amount: 1, unit: "tbsp" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Oyster sauce", role: "staple", group: "sauce", amount: 2, unit: "tsp" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 0.5, unit: "tsp" },
      { name: "Cornstarch", role: "staple", group: "main", amount: 2, unit: "tsp" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 1, unit: "tbsp", note: "optional garnish" },
    ],
    need: ["Spare ribs","Fermented tofu"],
    optional: ["Baking soda","Garlic","Ginger","Sugar","Salt","White pepper","Five-spice powder","Shaoxing wine","Sesame oil","Oyster sauce","Soy sauce","Cornstarch","Spring onion"],
    steps: [
      "Place the ribs in a large bowl and cover them with cold water. Stir and agitate the ribs to rinse them well. Pour out the water, and rinse the ribs again under cold running water. Once the water is clear, leave enough to submerge the ribs, and stir in the baking soda (this will tenderize the ribs and give them a cleaner flavor). Soak for 30 minutes to 1 hour. After soaking, rinse and drain the ribs thoroughly.",
      "Transfer the ribs to a mixing bowl, along with the garlic, ginger, sugar, salt, white pepper, five spice powder, red fermented bean curd, Shaoxing wine, sesame oil, oyster sauce, and dark soy sauce. Mix to coat the ribs evenly. Cover and marinate in the refrigerator overnight, or at least 30 minutes.",
      "Just before steaming, toss the ribs with the cornstarch, incorporating it evenly. The marinade should be clinging to the ribs, with little to no standing liquid.",
      "Spread the ribs evenly across a shallow heatproof dish that will fit into your steamer. Bring water to a simmer in a metal steamer or wok with a steaming rack set in the bottom. Place the dish of ribs onto the rack, cover, and steam over medium heat for 15-20 minutes, until the ribs are opaque and cooked through. Garnish with chopped scallion, if using.",
    ],
    zh: {
      name: "南乳蒸排骨",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-mussels-papillote",
    name: "Mussels en papillote",
    cuisine: "Western",
    time: 25,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/mussels_en_papillote_74126",
    sourceName: "BBC Food",
    materials: [
      { name: "Beans", role: "core", group: "main", amount: 400, unit: "g", note: "/14oz dried flageolet , soaked in cold water for at least 8 hours" },
      { name: "Garlic", role: "staple", group: "main", amount: 1, note: "bulb, halved horizontally" },
      { name: "Olive oil", role: "staple", group: "main", amount: 2, unit: "tbsp" },
      { name: "Tomato", role: "core", group: "main", amount: 1, note: "fresh , halved" },
      { name: "Ginger", role: "staple", group: "main", amount: 5, note: "cm/2in piece fresh root , peeled and finely shredded" },
      { name: "Mussels", role: "core", group: "main", amount: 1.8, unit: "kg", note: "/4lb , scrubbed and debearded" },
      { name: "Butter", role: "core", group: "main", amount: 2, unit: "tbsp", note: "unsalted , cut into 4 pieces" },
      { name: "Salt", role: "staple", group: "main", note: "Sea" },
    ],
    need: ["Beans","Tomato","Mussels","Butter"],
    optional: ["Garlic","Olive oil","Ginger","Salt"],
    steps: [
      "To make the beans, drain the soaked beans in a colander and rinse well under cold water.",
      "Remove and discard the garlic, sage and chilli. Taste the beans once cooled and season with more salt, if needed.",
      "Lay 2 sheets of parchment crosswise to form an X, then put them into a shallow soup bowl. Repeat with the remaining parchment. The bowls will support the parchment and help stop the juices escaping while you assemble the parcels.",
      "Rub the cut garlic cloves over the cut sides of the toasted bread.",
      "Serve the mussel parcels in shallow bowls with the garlic baguette and flageolet beans alongside.",
    ],
    zh: {
      name: "紙包青口",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-linguine-mussels",
    name: "Linguine with mussels",
    cuisine: "Western",
    time: 30,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/linguine_with_mussels_15573",
    sourceName: "BBC Food",
    materials: [
      { name: "Mussels", role: "core", group: "main", amount: 2, unit: "kg", note: "/4lb 8oz  in the shell, scrubbed and debearded" },
      { name: "Olive oil", role: "staple", group: "main", amount: 4, unit: "tbsp", note: "extra virgin" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, note: "cloves, thinly sliced" },
      { name: "Cream", role: "core", group: "main", amount: 75, unit: "ml", note: "/5 tbsp double" },
      { name: "Flour", role: "staple", group: "main", amount: 100, unit: "g", note: "/3.5oz breadcrumbs" },
      { name: "Salt", role: "staple", group: "main", note: "sea" },
    ],
    need: ["Mussels","Cream"],
    optional: ["Olive oil","Garlic","Flour","Salt"],
    steps: [
      "Discard any mussels with broken shells and any that refuse to close when tapped. In a large saucepan over a high heat, add 2 tablespoons of olive oil, then the mussels and garlic, place the lid on and cook for 2 minutes. Add the white wine and sprig of fresh thyme and cover again with the lid, then leave the mussels to cook for 4 minutes.",
      "With the rest of the mussels, remove the mussel meat from the shell and keep to one side, then discard the shells. The juices are the base of the sauce so strain the juices through a fine sieve or, better still, a coffee filter, as this will collect any small pieces of grit.",
      "In a large saucepan of boiling salted water, add the tagliatelle and cook for 3 minutes less than the packet suggests.",
      "Place the non-stick frying pan back on the stove. Use a pair of tongs to take the tagliatelle out of the water and add it to the sauce. Add a ladle of pasta water and then add the mussel meat with any resting juices from them into the frying pan with the sauce. Cook for 2 minutes then add the 12 mussels that you have kept aside, add the chopped parsley and stir the pasta so the sauce and the pasta are nicely emulsified. Add more pasta water if the pasta is not juicy.",
      "Serve the hot pasta with a generous amount of the fried breadcrumbs on top.",
    ],
    zh: {
      name: "青口意粉",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-curried-mussels",
    name: "Curried mussels on toast",
    cuisine: "Western",
    time: 25,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/curried_mussels_on_toast_57689",
    sourceName: "BBC Food",
    materials: [
      { name: "Ground coriander", role: "staple", group: "main", amount: 2, unit: "tsp", note: "coriander seeds, toasted and ground" },
      { name: "Bread", role: "core", group: "main", amount: 4, note: "whole cloves, toasted and ground" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "seeds, toasted and ground" },
      { name: "Cardamom", role: "core", group: "main", amount: 10, note: "seeds, toasted, seeds removed from the pod and ground" },
      { name: "Ginger", role: "staple", group: "main", amount: 0.5, unit: "tsp", note: "ground" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 0.5, unit: "tsp", note: "ground" },
      { name: "Paprika", role: "staple", group: "main", amount: 0.5, unit: "tsp", note: "sweet" },
      { name: "White pepper", role: "staple", group: "main", amount: 0.5, unit: "tsp" },
      { name: "Mussels", role: "core", group: "main", amount: 1, unit: "kg", note: "/2lb 4oz , scrubbed and debearded" },
      { name: "Butter", role: "core", group: "main", amount: 50, unit: "g", note: "/1.75oz unsalted" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, note: "cloves, thinly sliced" },
      { name: "Shallot", role: "core", group: "main", amount: 2, note: "banana s, sliced" },
      { name: "Cream", role: "core", group: "main", amount: 100, unit: "ml", note: "/3.5fl oz double" },
      { name: "Lemon", role: "core", group: "main", amount: 1, note: "zest only" },
      { name: "Beans", role: "core", group: "main", amount: 150, unit: "g", note: "/5.5oz broad , blanched and double podded" },
    ],
    need: ["Bread","Cardamom","Mussels","Butter","Shallot","Cream","Lemon","Beans"],
    optional: ["Ground coriander","Cumin","Ginger","Turmeric","Paprika","White pepper","Garlic"],
    steps: [
      "To make the curry powder, mix all the spices together in a small bowl or jar.",
      "Add 1 heaped teaspoon of the curry powder and cook for 1–2 minutes.",
      "Add the cream to the sauce along with the butter beans and cook for 3–4 minutes.",
      "Add the lemon zest, mussel meat, broad beans and dill flowers to the pan and stir, cooking for 2 minutes, until everything is hot.",
      "To serve, place the toast onto serving plates and top with the curried mussels, with rocket salad on the side. Garnish with the dill flowers.",
    ],
    zh: {
      name: "咖喱青口多士",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-five-spice-duck",
    name: "Five-spice duck breasts",
    cuisine: "Chinese",
    time: 35,
    servings: 2,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/fivespiceduckbreasts_90212",
    sourceName: "BBC Food",
    materials: [
      { name: "Duck", role: "core", group: "main", amount: 2, note: "breasts" },
      { name: "Five-spice powder", role: "staple", group: "main", amount: 4, unit: "tsp" },
      { name: "Honey", role: "staple", group: "main", amount: 2, unit: "tbsp", note: "clear" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 6, unit: "tbsp" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 4, note: "s, finely sliced" },
      { name: "Eggs", role: "core", group: "main", amount: 150, unit: "g", note: "/5.5oz dried egg noodles or 200g/7oz fresh egg noodles." },
      { name: "Lime", role: "core", group: "main", note: "squeeze fresh  juice" },
      { name: "Sesame oil", role: "staple", group: "main", note: "toasted , to taste" },
      { name: "Salt", role: "staple", group: "main", note: "and freshly ground black pepper" },
      { name: "Sesame seeds", role: "staple", group: "garnish", amount: 1, unit: "tbsp", note: "to serve" },
    ],
    need: ["Duck","Eggs","Lime"],
    optional: ["Five-spice powder","Honey","Soy sauce","Spring onion","Sesame oil","Salt","Sesame seeds"],
    steps: [
      "Preheat the oven to 180C/170C Fan/Gas 4.",
      "Heat a heavy-based ovenproof frying pan. Place the duck breasts skin-side down and season the other side with five-spice, salt and pepper. Cook for about 3 minutes or until most of the fat has run out into the pan and the skin is golden-brown. Turn the duck over and cook for 1 minute. Then cook in the oven for 3–5 minutes then allow to rest.",
      "Bring a pan of salted water to the boil and cook the noodles for 3–4 minutes or according to packet instructions. Drain and toss with half the spring onions, the lime juice and some sesame oil. Place between 2 bowls.",
      "Slice the duck into strips and place on top of noodles. Drizzle over the sauce and top with the remaining spring onions, sesame oil and sesame seeds.",
    ],
    zh: {
      name: "五香鴨胸",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-grilled-lamb-chops-woks",
    name: "Grilled lamb chops",
    cuisine: "Western",
    time: 25,
    servings: 2,
    sourceUrl: "https://thewoksoflife.com/grilled-lamb-chops/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Lamb", role: "core", group: "main", amount: 2, unit: "lb" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "Corn", role: "core", group: "main", amount: 1, unit: "tsp" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 0.5, unit: "tsp" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 2, unit: "tsp", note: "my secret ingredient!" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "tbsp", note: "optional; omit if you have fattier lamb chops" },
    ],
    need: ["Lamb","Corn"],
    optional: ["Cumin","Salt","Sugar","Soy sauce","Cooking oil"],
    steps: [
      "Rinse each chop, then pat dry with a paper towel. Add the chops to a large mixing bowl along the water, cumin powder, Sichuan peppercorn powder, salt, sugar, and light soy sauce. If your lamb chops are on the leaner side, mix in the oil to lock in moisture.",
      "Mix with your hands until there is no visible standing liquid (continuously mixing them with your hands will help the lamb chops absorb all the liquid). Marinate for 15-30 minutes before grilling. We don’t opt for a long marinating time in order to maintain the fresh flavor of the lamb chops.",
      "When you’re ready to cook, preheat your grill until the temperature gauge reads 400-450°F. Lay the lamb chops on the grill and don’t move them too much. Close the grill. After 2-3 minutes, rotate the lamb chops a half turn to get some grill marks. You may want to close the grill again to build up heat, but you be the judge as every grill is different. After another 2-3 minutes, flip the chops. They should be golden and burnished. (You may want to throw in another turn or two before you flip the chops.) On the other side, let the chops cook, rotating a half turn once again to get those grill marks. For the last 1-2 minutes, you may want to turn the lamb chops on their side (carefully, so they don’t fall through the grates) to brown and render the fat cap until it’s sizzling and golden. Transfer the chops to a platter, and serve!",
    ],
    zh: {
      name: "烤羊扒",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bbc-lamb-saffron-curry",
    name: "Lamb saffron curry",
    cuisine: "Indian",
    time: 60,
    servings: 4,
    sourceUrl: "https://www.bbc.co.uk/food/recipes/lamb_saffron_curry_20298",
    sourceName: "BBC Food",
    materials: [
      { name: "Garlic", role: "staple", group: "main", amount: 4, note: "cloves, finely grated" },
      { name: "Ginger", role: "staple", group: "main", amount: 2, note: "thumb-sized pieces of fresh root , grated" },
      { name: "Lamb", role: "core", group: "main", amount: 650, unit: "g", note: "/1lb 7oz boneless , cut into cubes" },
      { name: "Butter", role: "core", group: "main", amount: 100, unit: "g", note: "/3.5oz ghee or" },
      { name: "Onion", role: "staple", group: "main", amount: 2, note: "s, thinly sliced" },
      { name: "Turmeric", role: "staple", group: "sauce", amount: 1, unit: "tsp", note: "ground" },
      { name: "Garam masala", role: "staple", group: "sauce", amount: 1, unit: "tsp" },
      { name: "Cumin", role: "staple", group: "sauce", amount: 2, unit: "tsp", note: "seeds" },
      { name: "Tomato", role: "core", group: "main", amount: 200, unit: "g", note: "tin plum es, finely chopped" },
      { name: "Salt", role: "staple", group: "main", note: "to taste" },
      { name: "Cilantro", role: "core", group: "garnish", note: "handful finely chopped coriander" },
    ],
    need: ["Lamb","Butter","Tomato","Cilantro"],
    optional: ["Garlic","Ginger","Onion","Turmeric","Garam masala","Cumin","Salt"],
    steps: [
      "Rub the garlic and ginger into the cubed lamb and set aside in the fridge to marinate for 30 minutes.",
      "Add the chopped tomatoes to the lamb with the stock and bring the whole mixture to the boil.",
      "Grind the saffron in a pestle and mortar, pour over a few tablespoons of boiling water and leave to steep for 20 minutes.",
      "In the last 5 minutes of cooking, when the oil starts to split and separate out, add the soaked apricots and the saffron water to the lamb and season with salt, to taste.",
      "To serve, garnish with extra chopped coriander, pomegranate seeds and slices of a mild green or red chilli if you wish.",
    ],
    zh: {
      name: "藏紅花羊肉咖喱",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-red-bean-popsicle",
    name: "Red bean popsicles",
    cuisine: "Chinese",
    time: 20,
    servings: 6,
    sourceUrl: "https://thewoksoflife.com/red-bean-popsicle-recipe/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Red beans", role: "core", group: "main", amount: 0.5, unit: "cup", note: "adzuki beans" },
      { name: "Milk", role: "core", group: "main", amount: 1.25, unit: "cup" },
      { name: "Cornstarch", role: "staple", group: "marinade", amount: 2, unit: "tsp" },
      { name: "Cream", role: "core", group: "main", amount: 0.75, unit: "cup" },
      { name: "Sugar", role: "staple", group: "main", amount: 0.5, unit: "cup" },
    ],
    need: ["Red beans","Milk","Cream"],
    optional: ["Cornstarch","Sugar"],
    steps: [
      "Soak the red beans in water overnight. Drain and add them to a small pot, along with 3 cups of fresh water. Bring to a boil, then reduce the heat to medium / medium low, leaving the lid slightly ajar to prevent overflow. Simmer for 30-45 minutes until the beans are fully softened and the skins are beginning to open up.",
      "Once the red beans are done cooking, drain off all the liquid into a bowl (you can drink the liquid with or without some sweetener—it’s very good for you). Gently mash the red beans with a potato masher until a paste forms. Set aside.",
      "When the mixture is fully cooled to room temperature, it’s time to assemble the popsicles. Stir up the creamy red bean mixture and fill each mold until it’s 95% full. Cover the popsicles with the lid, insert the wooden popsicle sticks, and freeze overnight.",
      "The next day, they’re ready to enjoy! I remove them from the molds and place them in a freezer bag for longer-term storage. Enjoy within 2 months at best quality!",
    ],
    zh: {
      name: "紅豆冰棒",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-bo-kho",
    name: "Bo kho beef stew",
    cuisine: "Vietnamese",
    time: 120,
    servings: 6,
    sourceUrl: "https://thewoksoflife.com/bo-kho-spicy-vietnamese-beef-stew/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Beef brisket", role: "core", group: "main", amount: 2, unit: "lb", note: "cut into 1½-inch chunks" },
      { name: "Garlic", role: "staple", group: "main", amount: 2, unit: "clove", note: "minced" },
      { name: "Ginger", role: "staple", group: "main", amount: 3, unit: "tbsp", note: "minced" },
      { name: "Fish sauce", role: "staple", group: "sauce", amount: 5, unit: "tbsp" },
      { name: "Five-spice powder", role: "staple", group: "main", amount: 2.5, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 1.5, unit: "tsp" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 3, unit: "tbsp" },
      { name: "Lemon", role: "core", group: "main", amount: 1, note: "cut into 3-inch lengths, after removing any tough woody parts" },
      { name: "Onion", role: "staple", group: "main", amount: 1, note: "sliced thinly" },
      { name: "Tomato paste", role: "staple", group: "sauce", amount: 4, unit: "tbsp" },
      { name: "Orange juice", role: "core", group: "main", amount: 2, unit: "cup" },
      { name: "White pepper", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Paprika", role: "staple", group: "main", amount: 1, unit: "tbsp" },
      { name: "Carrots", role: "core", group: "main", amount: 8, note: "peeled and cut on the bias into 1½ -inch chunks" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Soy sauce", role: "staple", group: "sauce", amount: 3, unit: "tbsp" },
      { name: "Chili oil", role: "staple", group: "main", amount: 3, unit: "tbsp", note: "or to taste" },
      { name: "Eggs", role: "core", group: "main" },
      { name: "Cilantro", role: "core", group: "garnish", amount: 0.25, unit: "cup" },
      { name: "Thai basil", role: "core", group: "main", amount: 1, unit: "cup" },
      { name: "Lime", role: "core", group: "main" },
    ],
    need: ["Beef brisket","Lemon","Orange juice","Carrots","Eggs","Cilantro","Thai basil","Lime"],
    optional: ["Garlic","Ginger","Fish sauce","Five-spice powder","Sugar","Cooking oil","Onion","Tomato paste","White pepper","Paprika","Salt","Soy sauce","Chili oil"],
    steps: [
      "First marinate the beef. Combine the beef with the garlic, ginger, fish sauce, five-spice powder, and brown sugar until each piece is evenly coated. Marinate for 30 minutes.",
      "Add the onions and cook until translucent. Then add all of the beef to the pot, and brown evenly on all sides. Add the tomato paste.",
      "After an hour has passed, add the carrots, salt, soy sauce, and chili oil. Simmer for another 40 minutes.",
      "To serve, remove the large lemongrass stalks and any star anise pods you can fish out. Cook your noodles per package instructions, transfer to bowls, and ladle the soup over the top.",
      "Garnish with cilantro, Thai basil, and raw onion, and serve with some lime wedges on the side.",
    ],
    zh: {
      name: "越南香料牛肉",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-lemongrass-chicken-banh-mi",
    name: "Lemongrass chicken banh mi",
    cuisine: "Vietnamese",
    time: 35,
    servings: 4,
    sourceUrl: "https://thewoksoflife.com/chicken-banh-mi/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Carrots", role: "core", group: "main", amount: 2, note: "julienned" },
      { name: "Sugar", role: "staple", group: "main", amount: 2, unit: "tbsp" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Cooked rice", role: "core", group: "main", amount: 3, unit: "tbsp" },
      { name: "Sesame oil", role: "staple", group: "main", amount: 2, unit: "tsp" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 4, unit: "tbsp", note: "divided" },
      { name: "Fish sauce", role: "staple", group: "sauce", amount: 2, unit: "tbsp" },
      { name: "Oyster sauce", role: "staple", group: "sauce", amount: 1, unit: "tbsp" },
      { name: "White pepper", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Shallot", role: "core", group: "main", amount: 2, note: "peeled" },
      { name: "Garlic", role: "staple", group: "main", amount: 3, unit: "clove" },
      { name: "Lemon", role: "core", group: "main", amount: 2, note: "cut into pieces" },
      { name: "Lime", role: "core", group: "main", amount: 2, unit: "tsp" },
      { name: "Chicken thighs", role: "core", group: "main", amount: 1.5, unit: "lb" },
      { name: "Mayonnaise", role: "core", group: "main", amount: 1, unit: "cup" },
      { name: "Cilantro", role: "core", group: "garnish", amount: 1, unit: "cup" },
    ],
    need: ["Carrots","Cooked rice","Shallot","Lemon","Lime","Chicken thighs","Mayonnaise","Cilantro"],
    optional: ["Sugar","Salt","Sesame oil","Cooking oil","Fish sauce","Oyster sauce","White pepper","Garlic"],
    steps: [
      "Start by preparing the carrot and daikon. Add the julienned carrots and daikon to a large bowl and toss in the sugar, salt, vinegar and sesame oil. Set aside for 1 hour, stirring occasionally.",
      "Then prepare the chicken. In the bowl of a food processor, add 2 tablespoons oil, the fish sauce, oyster sauce, pepper flakes, sugar, shallots, garlic, lemongrass, and lime zest. Process until smooth. Add to a bowl, along with the chicken, and toss to coat the chicken in the marinade. Cover, transfer to the fridge, and marinate for 1-4 hours.",
      "Heat the remaining 2 tablespoons oil in a 12-inch ovenproof skillet over medium-high heat. Sear the chicken for about 5 minutes on each side, or until cooked through. Set aside on a plate.",
      "To assemble the sandwiches, combine the mayonnaise, Sriracha, and lime juice.",
      "Open up each piece of bread, and spread the sriracha mayonnaise on each side. Fill with the pickled carrots and daikon. Slice the cooked chicken, and add it to the sandwiches, along with sliced jalapeños and cilantro. Serve!",
    ],
    zh: {
      name: "香茅雞越式三明治",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  },
  {
    id: "home-typhoon-shelter-shrimp",
    name: "Typhoon shelter shrimp",
    cuisine: "Hong Kong",
    time: 25,
    servings: 2,
    sourceUrl: "https://thewoksoflife.com/typhoon-shelter-shrimp-recipe/",
    sourceName: "The Woks of Life",
    materials: [
      { name: "Shrimp", role: "core", group: "main", amount: 1, unit: "lb", note: "450g" },
      { name: "White pepper", role: "staple", group: "main", amount: 1, unit: "tsp", note: "plus another ¼ teaspoon, divided" },
      { name: "Shaoxing wine", role: "staple", group: "main", amount: 2, unit: "tsp", note: "divided" },
      { name: "Ginger", role: "staple", group: "main", amount: 3, note: "minced, about 10g" },
      { name: "Garlic", role: "staple", group: "main", amount: 7, unit: "clove", note: "minced" },
      { name: "Spring onion", role: "staple", group: "garnish", amount: 2, note: "chopped" },
      { name: "Dried chili", role: "core", group: "main", amount: 3, note: "chopped" },
      { name: "Flour", role: "staple", group: "main", amount: 1, unit: "cup", note: "70g" },
      { name: "Cooking oil", role: "staple", group: "main", amount: 1, unit: "cup", note: "or peanut oil" },
      { name: "Salt", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Sugar", role: "staple", group: "main", amount: 1, unit: "tsp" },
      { name: "Five-spice powder", role: "staple", group: "main", amount: 1, unit: "tsp", note: "optional" },
    ],
    need: ["Shrimp","Dried chili"],
    optional: ["White pepper","Shaoxing wine","Ginger","Garlic","Spring onion","Flour","Cooking oil","Salt","Sugar","Five-spice powder"],
    steps: [
      "Trim, de-vein and clean the shrimp as shown in the step-by-step photos. Shake off any excess water and pat them dry thoroughly with a paper towel. Add the shrimp to a bowl and toss with ¼ teaspoon white pepper powder and 1 teaspoon Shaoxing wine. Set aside for 15 minutes while you prepare the other ingredients.",
      "When the oil is at temperature, fry the shrimp in two separate batches (this prevents the temperature of oil from dropping too much), for about 15 seconds per batch. Scoop them out and set aside.",
      "With the heat on medium low, add the ginger to the oil and cook for 30 seconds. Then add the garlic and chilies, and fry for another 30 seconds before stirring in the panko.",
      "Add in the shrimp, salt, sugar, the remaining ¼ teaspoon white pepper, 1 teaspoon Shaoxing wine, and 1/8 teaspoon five spice powder (if using). Also add the scallions.",
      "Lightly toss everything together (still using medium low heat), and serve hot.",
    ],
    zh: {
      name: "避風塘炒蝦",
      steps: [
        "按食譜步驟 1 完成（詳見原文）。",
        "按食譜步驟 2 完成（詳見原文）。",
        "按食譜步驟 3 完成（詳見原文）。",
        "按食譜步驟 4 完成（詳見原文）。",
        "按食譜步驟 5 完成（詳見原文）。",
      ],
    },
  }
]
