import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W5G: Recipe[] = [
  {
    id: "home-traditional-bean-sprouts-with-ground-pork",
    name: "Traditional Bean Sprouts with Ground Pork",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Ground pork", "Bean sprouts"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Ground pork and Bean sprouts; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add Bean sprouts, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "肉碎炒芽菜",
      steps: [
        "準備肉碎炒芽菜材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-loofah-mushroom-with-egg-soup",
    name: "Loofah Mushroom with Egg Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Eggs", "Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Eggs briefly if it is meat; rinse. Cut Mushroom into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "雞蛋絲瓜滾豬肚菇湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-mustard-green-tofu-soup",
    name: "Mustard Green Tofu Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Tofu", "Pickled mustard"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Tofu briefly if it is meat; rinse. Cut Pickled mustard into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "芥菜豆腐湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-stir-fry-rice-noodles-with-eggs",
    name: "Stir Fry Rice Noodles with Eggs",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Eggs and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "桂花炒粉絲",
      steps: [
        "準備桂花炒粉絲材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-homemade-fish-ball-tofu-soup",
    name: "Homemade Fish Ball Tofu Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["White fish", "Tofu"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch White fish briefly if it is meat; rinse. Cut Tofu into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "鯪魚球豆腐湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-barley-porridge-with-lean-pork-and-thousand-year",
    name: "Barley Porridge with Lean Pork and Thousand Year Eggs",
    cuisine: "Cantonese",
    time: 35,
    servings: 2,
    need: ["Ground pork", "Eggs", "Rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Century egg"],
    steps: [
      "Rinse ½ cup rice; simmer with about 1.2 L water 30–35 minutes, stirring occasionally until creamy.",
      "Add sliced Ground pork in the last 8–10 minutes until cooked through (74°C / 165°F).",
      "Season with salt, white pepper, and sesame oil; top with spring onion.",
    ],
    zh: {
      name: "皮蛋瘦肉薏米粥",
      steps: [
        "半杯米洗净，加水约 1.2 升煮 30 至 35 分鐘至绵密。",
        "最後 8 至 10 分鐘下切片主料煮熟。",
        "加鹽白胡椒麻油，撒蔥。",
      ],
    },
  },
  {
    id: "home-avocado-egg-sushi",
    name: "Avocado Egg Sushi",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Avocado"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Eggs and Avocado; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Avocado, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "牛油果雞蛋壽司",
      steps: [
        "準備牛油果雞蛋壽司材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-taiwan-styled-fried-rice-noodles",
    name: "Taiwan Styled Fried Rice Noodles",
    cuisine: "Taiwanese",
    time: 15,
    servings: 2,
    need: ["Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Loosen cold cooked rice; beat 2 eggs if eggs are in the dish. Dice other mix-ins small.",
      "Scramble eggs in a hot oiled pan; push aside or remove. Stir-fry aromatics and proteins until cooked.",
      "Add rice and 1–2 tbsp soy sauce; toss on high heat until hot and lightly toasted. Finish with spring onion.",
    ],
    zh: {
      name: "台式炒米粉",
      steps: [
        "隔夜飯撥散；如用蛋可先打散。配料切細。",
        "熱鑊炒蛋盛起；爆香蒜薑及蛋白質炒熟。",
        "下飯加 1 至 2 湯匙生抽大火炒香，撒蔥起鑊。",
      ],
    },
  },
  {
    id: "home-mixed-steamed-egg",
    name: "Mixed Steamed Egg",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Eggs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Arrange Eggs with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "八寶蒸水蛋",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-spring-chicken-with-sticky-rice-and-gingers",
    name: "Spring Chicken with Sticky Rice and Gingers",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "糯米釀薑米雞",
      steps: [
        "準備糯米釀薑米雞材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-spicy-thai-chicken-noodles",
    name: "Spicy Thai Chicken Noodles",
    cuisine: "Thai",
    time: 20,
    servings: 2,
    need: ["Chicken thighs", "Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and Noodles; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add Noodles, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "酸辣泰國雞肉麵",
      steps: [
        "準備酸辣泰國雞肉麵材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-classic-baked-pork-chop-over-rice",
    name: "Classic Baked Pork Chop over Rice",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Ground pork", "Pork chops", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Heat oven to 200°C. Toss Ground pork and Pork chops with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "傳統焗豬扒飯",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-steamed-tofu-with-minced-pork-and-mustard-green",
    name: "Steamed Tofu with Minced Pork and Mustard Green",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Ground pork", "Tofu"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Arrange Ground pork with Tofu on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through (poultry/mince to 74°C / 165°F).",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "肉碎雪菜蒸豆腐",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟（肉類至 74°C / 165°F）。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-baked-fried-pork-chop-over-rice",
    name: "Baked Fried Pork Chop over Rice",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Ground pork", "Pork chops", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Heat oven to 200°C. Toss Ground pork and Pork chops with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "焗炸豬扒飯",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-fresh-shrimp-rice-rolls",
    name: "Fresh Shrimp Rice Rolls",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Shrimp and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "自家製鮮蝦腸粉",
      steps: [
        "準備自家製鮮蝦腸粉材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-steamed-tofu-with-scallops",
    name: "Steamed Tofu with Scallops",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Tofu"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Arrange Tofu with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "帶子蒸豆腐",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-bbq-pork-string-beans-scrambled-eggs",
    name: "BBQ Pork String Beans Scrambled Eggs",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Ground pork", "Eggs", "Green beans"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Ground pork and Eggs plus Green beans; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add Eggs and Green beans, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "叉燒豆角炒蛋",
      steps: [
        "準備叉燒豆角炒蛋材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-egg-veggie-pinwheel",
    name: "Egg Veggie Pinwheel",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Eggs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Eggs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "雞蛋蔬菜捲",
      steps: [
        "準備雞蛋蔬菜捲材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-fresh-lily-stir-fry-with-celery-and-shrimps",
    name: "Fresh Lily Stir Fry with Celery and Shrimps",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Celery"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Shrimp and Celery; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add Celery, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "西芹百合炒蝦仁",
      steps: [
        "準備西芹百合炒蝦仁材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-beef-saute-asparagus",
    name: "Beef Saute Asparagus",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Beef steak and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蘆筍炒牛肉",
      steps: [
        "準備蘆筍炒牛肉材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-white-melon-with-chicken",
    name: "White Melon with Chicken",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs", "Pak choi"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and Pak choi; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add Pak choi, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "白菜果炒雞柳",
      steps: [
        "準備白菜果炒雞柳材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-salmon-ochatsuke",
    name: "Salmon Ochatsuke",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Salmon", "White fish"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Salmon and White fish; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Salmon and cook until just cooked.",
      "Add White fish, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "三文魚綠茶泡燕麥飯",
      steps: [
        "準備三文魚綠茶泡燕麥飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-satay-beef-noodles-ddc",
    name: "Satay Beef Noodles",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Beef steak and Noodles; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Noodles, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "沙爹肥牛公仔麵",
      steps: [
        "準備沙爹肥牛公仔麵材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-tangy-eggplant-vermicelli",
    name: "Tangy Eggplant Vermicelli",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["White fish", "Eggs", "Eggplant", "Rice vermicelli"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut White fish and Eggs into pieces; lightly brown White fish in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until White fish is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "魚香茄子燜米粉",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-chicken-oyako-don",
    name: "Chicken Oyako-Don",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "親子燕麥飯",
      steps: [
        "準備親子燕麥飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-kimchee-jigae-with-pork",
    name: "Kimchee Jigae with Pork",
    cuisine: "Korean",
    time: 45,
    servings: 3,
    need: ["Ground pork", "Kimchi"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Ground pork briefly if it is meat; rinse. Cut Kimchi into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "韓國泡菜湯（豬肉版)",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-curry-fish-balls-with-pork-grinds",
    name: "Curry Fish Balls with Pork Grinds",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Ground pork", "White fish"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Ground pork and White fish; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add White fish, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "咖喱魚蛋豬皮蘿蔔",
      steps: [
        "準備咖喱魚蛋豬皮蘿蔔材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-sour-cabbage-beef-tripe",
    name: "Sour Cabbage Beef Tripe",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Cabbage", "Pickled mustard"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Beef steak and Cabbage plus Pickled mustard; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Cabbage and Pickled mustard, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "酸菜炒牛栢葉",
      steps: [
        "準備酸菜炒牛栢葉材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-scrambled-egg-whites-with-vegetarian-shark-fin",
    name: "Scrambled Egg Whites with Vegetarian Shark Fin",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Eggs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Eggs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "賽螃蟹炒素翅",
      steps: [
        "準備賽螃蟹炒素翅材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-steamed-white-eggplant-in-preserved-mustard-gree",
    name: "Steamed White Eggplant in Preserved Mustard Greens",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Eggs", "Eggplant"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Arrange Eggs with Eggplant on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "梅菜蒸茄子",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-stir-fry-fish-maw",
    name: "Stir Fry Fish Maw",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["White fish"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep White fish and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add White fish and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "貴花炒魚肚",
      steps: [
        "準備貴花炒魚肚材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-saut-bak-choy-with-dried-shrimps",
    name: "Sauté Bak Choy with Dried Shrimps",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Pak choi"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Shrimp and Pak choi; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add Pak choi, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "清淡•蝦乾炒大白菜",
      steps: [
        "準備清淡•蝦乾炒大白菜材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-beautifying-papaya-peanut-chicken-soup-with-red",
    name: "Beautifying Papaya Peanut Chicken Soup with Red Dates",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Chicken thighs briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "養顏•木瓜大棗煲花生雞湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-vegetables-chicken-roll-chinese-new-year-recipe",
    name: "Vegetables Chicken Roll",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "春節家常菜鑲翠雞捲",
      steps: [
        "準備春節家常菜鑲翠雞捲材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-fresh-oysters-vermicelli-soup-with-radish-1",
    name: "Fresh Oysters Vermicelli Soup with Radish",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Rice vermicelli"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Rice vermicelli briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "清淡•香菇瑶柱炆蘿蔔",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-chicken-soup-with-whelk",
    name: "Chicken Soup with Whelk",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Chicken thighs briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "海螺雞湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-shrimps-stir-fry-with-bitter-melon-in-black-bean",
    name: "Shrimps Stir Fry with Bitter Melon in Black Bean Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Bitter melon"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Shrimp and Bitter melon; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add Bitter melon, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "涼瓜豆豉炒蝦",
      steps: [
        "準備涼瓜豆豉炒蝦材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-fish-balls-with-pork-grinds",
    name: "Fish Balls with Pork Grinds",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Ground pork", "White fish"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Ground pork and White fish; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add White fish, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "柱侯魚蛋豬皮",
      steps: [
        "準備柱侯魚蛋豬皮材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-luffa-with-dried-shrimps-soup-early-spring-soups",
    name: "Luffa with Dried Shrimps Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Shrimp"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Shrimp briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "蝦乾絲瓜湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-spinach-and-mushroom-porridge",
    name: "Spinach and Mushroom Porridge",
    cuisine: "Cantonese",
    time: 35,
    servings: 2,
    need: ["Spinach", "Mushroom", "Rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Rinse ½ cup rice; simmer with about 1.2 L water 30–35 minutes, stirring occasionally until creamy.",
      "Add sliced Spinach in the last 8–10 minutes until just cooked.",
      "Season with salt, white pepper, and sesame oil; top with spring onion.",
    ],
    zh: {
      name: "菠菜肉香米粥",
      steps: [
        "半杯米洗净，加水约 1.2 升煮 30 至 35 分鐘至绵密。",
        "最後 8 至 10 分鐘下切片主料煮熟。",
        "加鹽白胡椒麻油，撒蔥。",
      ],
    },
  },
  {
    id: "home-spinach-bacon-rice-rolls",
    name: "Spinach Bacon Rice Rolls",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Bacon", "Spinach", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Bacon and Spinach plus Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Bacon and cook until just cooked.",
      "Add Spinach and Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "菠菜培根飯糰",
      steps: [
        "準備菠菜培根飯糰材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-spinach-wolfberry-soup-with-pork-liver",
    name: "Spinach Wolfberry Soup with Pork Liver",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork", "Spinach"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Ground pork briefly if it is meat; rinse. Cut Spinach into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "豬潤枸杞菠菜湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-healthy-vegetable-beef-soup",
    name: "Healthy Vegetable Beef Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Beef steak", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms", "Potato"],
    steps: [
      "Blanch Beef steak briefly if it is meat; rinse. Cut Tomato into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "番茄芹菜洋蔥薯仔牛肉湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-saute-squid-with-morning-glory-in-shrimp-paste-s",
    name: "Saute Squid with Morning Glory in Shrimp Paste Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Squid", "Water spinach"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Shrimp and Squid plus Water spinach; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add Squid and Water spinach, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "椒絲蝦醬鮮魷炒通菜",
      steps: [
        "準備椒絲蝦醬鮮魷炒通菜材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-shrimp-and-vegetable-crepes",
    name: "Shrimp and Vegetable Crepes",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Tortilla"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Shrimp and Tortilla; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add Tortilla, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蔬菜蝦肉法式薄餅",
      steps: [
        "準備蔬菜蝦肉法式薄餅材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-white-bates-omelette",
    name: "White Bates Omelette",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["White fish", "Eggs", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Pat White fish dry; season with salt and white pepper. Slice Eggs if using as a side.",
      "Pan-fry in a lightly oiled skillet over medium heat until browned and cooked until just cooked.",
      "Deglaze with a splash of soy sauce or serve with a quick ginger-spring-onion drizzle.",
    ],
    zh: {
      name: "白飯魚煎蛋",
      steps: [
        "主料抹乾，加鹽白胡椒；配菜切片。",
        "中火少油煎至上色并熟透。",
        "可淋少許生抽或以薑蔥油提味。",
      ],
    },
  },
  {
    id: "home-steamed-tofu-with-broccoli",
    name: "Steamed Tofu with Broccoli",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Tofu", "Broccoli"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Arrange Tofu with Broccoli on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "荷塘豆腐",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-fish-maw-wolfberry-soup",
    name: "Fish Maw Wolfberry Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["White fish"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch White fish briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "枸杞花膠豬展湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-chinese-cabbage-with-fried-fish-maw",
    name: "Chinese Cabbage with Fried Fish Maw",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["White fish", "Pak choi", "Cabbage"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep White fish and Pak choi plus Cabbage; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add White fish and cook until just cooked.",
      "Add Pak choi and Cabbage, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "白菜炒沙​​爆魚肚",
      steps: [
        "準備白菜炒沙​​爆魚肚材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-steamed-fish-belly-with-preserved-cabbage",
    name: "Steamed Fish Belly with Preserved Cabbage",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["White fish", "Cabbage"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Arrange White fish with Cabbage on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "梅菜蒸鯇魚腩",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
]
