import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W5I: Recipe[] = [
  {
    id: "home-keroro-rice-bowl",
    name: "Keroro Rice Bowl",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Cooked rice and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Cooked rice and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "KERORO軍曹飯【親子食堂 】",
      steps: [
        "準備KERORO軍曹飯【親子食堂 】材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-fish-maw-saute-with-squid",
    name: "Fish Maw Saute with Squid",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Squid", "White fish"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Squid and White fish; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Squid and cook until just cooked.",
      "Add White fish, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "魚肚炒鮮魷",
      steps: [
        "準備魚肚炒鮮魷材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-cantalope-double-boiled-chicken-soup",
    name: "Cantalope Double Boiled Chicken Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Chicken thighs briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "烏雞蜜瓜清補湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-sweet-sour-fish-fillet",
    name: "Sweet & Sour Fish Fillet",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["White fish"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep White fish and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add White fish and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "糖醋魚柳",
      steps: [
        "準備糖醋魚柳材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-saute-chinese-celery-with-conpoy",
    name: "Saute Chinese Celery with Conpoy",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Celery"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Celery and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Celery and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "炒乾貝芹菜",
      steps: [
        "準備炒乾貝芹菜材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-salted-fish-chinese-broccoli",
    name: "Salted Fish Chinese Broccoli",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["White fish", "Gai lan", "Broccoli"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep White fish and Gai lan plus Broccoli; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add White fish and cook until just cooked.",
      "Add Gai lan and Broccoli, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "鹹魚炒芥蘭",
      steps: [
        "準備鹹魚炒芥蘭材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-salmon-sashimi-lettuce-salad",
    name: "Salmon Sashimi Lettuce Salad",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Salmon", "White fish", "Lettuce"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Prep Salmon and White fish; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "三文魚生菜沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-rich-pumpkin-rice",
    name: "Rich Pumpkin Rice",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Pumpkin", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Pumpkin and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Pumpkin and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "濃香南瓜飯",
      steps: [
        "準備濃香南瓜飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-radish-stew-with-vermicelli",
    name: "Radish Stew with Vermicelli",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Shrimp", "Rice vermicelli"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Shrimp and Rice vermicelli into pieces; lightly brown Shrimp in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Shrimp is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "白蘿蔔蝦米燜米粉",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-mini-vietnamese-spring-rolls",
    name: "Mini Vietnamese Spring Rolls",
    cuisine: "Vietnamese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Eggs and Tomato; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Tomato, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "迷你越南春捲",
      steps: [
        "準備迷你越南春捲材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-deep-fry-tofu",
    name: "Deep Fry Tofu",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Tofu"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Tofu and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Tofu and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "琵琶豆腐",
      steps: [
        "準備琵琶豆腐材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-fried-fish-maw-winter-melon-soup",
    name: "Fried Fish Maw Winter Melon Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["White fish", "Winter melon"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch White fish briefly if it is meat; rinse. Cut Winter melon into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "沙爆魚肚冬瓜羹",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-steamed-fish-with-chinese-olives",
    name: "Steamed Fish with Chinese Olives",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["White fish"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Arrange White fish with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "欖角蒸鯪魚",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-green-bean-celery-soup",
    name: "Green Bean Celery Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Celery", "Green beans"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Celery briefly if it is meat; rinse. Cut Green beans into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "綠豆芹菜湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-steamed-egg-with-sea-urchin",
    name: "Steamed Egg with Sea Urchin",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Eggs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Arrange Eggs with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "海膽蒸蛋",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-flower-crab-congee",
    name: "Flower Crab Congee",
    cuisine: "Cantonese",
    time: 35,
    servings: 2,
    need: ["Rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Rinse ½ cup rice; simmer with about 1.2 L water 30–35 minutes, stirring occasionally until creamy.",
      "Add sliced Rice in the last 8–10 minutes until just cooked.",
      "Season with salt, white pepper, and sesame oil; top with spring onion.",
    ],
    zh: {
      name: "生滾花蟹粥",
      steps: [
        "半杯米洗净，加水约 1.2 升煮 30 至 35 分鐘至绵密。",
        "最後 8 至 10 分鐘下切片主料煮熟。",
        "加鹽白胡椒麻油，撒蔥。",
      ],
    },
  },
  {
    id: "home-clams-soup",
    name: "Clams Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Clams", "Winter melon"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Clams briefly if it is meat; rinse. Cut Winter melon into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "牛蒡冬瓜泥蜆肉湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-beef-steak-soup",
    name: "Beef Steak Soup",
    cuisine: "Japanese",
    time: 45,
    servings: 3,
    need: ["Beef steak", "Udon"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Beef steak briefly if it is meat; rinse. Cut Udon into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "日式牛肉湯烏冬",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-beef-steak-braise",
    name: "Beef Steak Braise",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Beef steak", "Carrots"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Beef steak and Carrots into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "甘筍燴牛尾",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-avocado-salad",
    name: "Avocado Salad",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Avocado"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Prep Avocado and vegetables; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "羽衣甘藍牛油果雞沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-chicken-thighs-stirfry",
    name: "Chicken Thighs Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken thighs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "香菇露荀雞肉凍卷",
      steps: [
        "準備香菇露荀雞肉凍卷材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-eggs-salad",
    name: "Eggs Salad",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Prep Eggs and Tomato; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "暖芝士通粉沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-white-fish-soup",
    name: "White Fish Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["White fish"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch White fish briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "雜菜魚湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-white-fish-panfry",
    name: "White Fish Panfry",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["White fish"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Pat White fish dry; season with salt and white pepper. Slice vegetables if using as a side.",
      "Pan-fry in a lightly oiled skillet over medium heat until browned and cooked until just cooked.",
      "Deglaze with a splash of soy sauce or serve with a quick ginger-spring-onion drizzle.",
    ],
    zh: {
      name: "香煎魚柳",
      steps: [
        "主料抹乾，加鹽白胡椒；配菜切片。",
        "中火少油煎至上色并熟透。",
        "可淋少許生抽或以薑蔥油提味。",
      ],
    },
  },
  {
    id: "home-mushroom-stirfry",
    name: "Mushroom Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Mushroom"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Mushroom and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Mushroom and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "金菇肥牛煲",
      steps: [
        "準備金菇肥牛煲材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-gai-lan-stirfry",
    name: "Gai Lan Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Gai lan"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Gai lan and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Gai lan and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "雪山飛天芥蘭",
      steps: [
        "準備雪山飛天芥蘭材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-beef-steak-stirfry",
    name: "Beef Steak Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Broccoli"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Beef steak and Broccoli; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Broccoli, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "西蘭花炒牛柳",
      steps: [
        "準備西蘭花炒牛柳材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-shrimp-soup",
    name: "Shrimp Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Shrimp", "Eggs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Shrimp briefly if it is meat; rinse. Cut Eggs into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "紫菜蝦米蛋花蔥花雞湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-corn-soup",
    name: "Corn Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Corn"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Corn briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "粟米馬蹄百合肉片湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-tofu-soup",
    name: "Tofu Soup",
    cuisine: "Cantonese",
    time: 40,
    servings: 3,
    need: ["Tofu", "Corn"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Tofu briefly if it is meat; rinse. Cut Corn into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "粟米草菇豆腐羹",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-eggs-soup",
    name: "Eggs Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Eggs", "Corn"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Eggs briefly if it is meat; rinse. Cut Corn into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "粟米肉粒蛋花雞湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-pumpkin-stirfry",
    name: "Pumpkin Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Pumpkin"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Pumpkin and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Pumpkin and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "南瓜嫩雞意大利飯",
      steps: [
        "準備南瓜嫩雞意大利飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-eggs-stirfry",
    name: "Eggs Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Eggs and Tomato; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Tomato, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蘋果和梨金寶脆脆",
      steps: [
        "準備蘋果和梨金寶脆脆材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-eggs-braise",
    name: "Eggs Braise",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Cut Eggs and Tomato into pieces; lightly brown Eggs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Eggs is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "意式燴豬仔脾",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-eggs-bake",
    name: "Eggs Bake",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Heat oven to 200°C. Toss Eggs and Tomato with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "牛肝菌焗釀蟹蓋",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-ground-pork-stirfry",
    name: "Ground Pork Stirfry",
    cuisine: "Hong Kong",
    time: 20,
    servings: 2,
    need: ["Ground pork", "Tortilla"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Ground pork and Tortilla; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add Tortilla, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "健脾淮山素肉餅煲仔藜麥飯",
      steps: [
        "準備健脾淮山素肉餅煲仔藜麥飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-ground-pork-fried-rice",
    name: "Ground Pork Fried Rice",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Ground pork", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Loosen cold cooked rice; beat 2 eggs if eggs are in the dish. Dice other mix-ins small.",
      "Scramble eggs in a hot oiled pan; push aside or remove. Stir-fry aromatics and proteins until cooked.",
      "Add rice and 1–2 tbsp soy sauce; toss on high heat until hot and lightly toasted. Finish with spring onion.",
    ],
    zh: {
      name: "私房豬肉乾炒飯",
      steps: [
        "隔夜飯撥散；如用蛋可先打散。配料切細。",
        "熱鑊炒蛋盛起；爆香蒜薑及蛋白質炒熟。",
        "下飯加 1 至 2 湯匙生抽大火炒香，撒蔥起鑊。",
      ],
    },
  },
  {
    id: "home-ham-stirfry",
    name: "Ham Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Ham", "Eggs", "Spinach", "Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Ham and Eggs plus Spinach; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ham and cook until just cooked.",
      "Add Eggs and Spinach, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "火腿菠菜蛋炒糙米飯",
      steps: [
        "準備火腿菠菜蛋炒糙米飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-spinach-stirfry",
    name: "Spinach Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Spinach"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Spinach and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Spinach and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "涼拌芝麻菠菜",
      steps: [
        "準備涼拌芝麻菠菜材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-cucumber-stirfry",
    name: "Cucumber Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Cucumber"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Cucumber and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Cucumber and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "芝麻雲耳拌青瓜",
      steps: [
        "準備芝麻雲耳拌青瓜材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-tofu-stirfry",
    name: "Tofu Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Tofu", "Pak choi"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Tofu and Pak choi; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Tofu and cook until just cooked.",
      "Add Pak choi, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "鮮露沙薑撈豬手",
      steps: [
        "準備鮮露沙薑撈豬手材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-tortilla-stirfry",
    name: "Tortilla Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Tortilla"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Tortilla and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Tortilla and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "脆脆薯餅",
      steps: [
        "準備脆脆薯餅材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-shrimp-stirfry",
    name: "Shrimp Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Shrimp and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "香芒沙拉脆蝦球",
      steps: [
        "準備香芒沙拉脆蝦球材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-chicken-wings-stirfry",
    name: "Chicken Wings Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken wings"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken wings and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken wings and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "奇亞籽香茅牛油雞翼",
      steps: [
        "準備奇亞籽香茅牛油雞翼材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-lettuce-stirfry",
    name: "Lettuce Stirfry",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Lettuce"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Lettuce and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Lettuce and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "海鮮生菜煲",
      steps: [
        "準備海鮮生菜煲材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-ground-pork-soup",
    name: "Ground Pork Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Ground pork", "Pak choi", "Mushroom", "Glass noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Ground pork briefly if it is meat; rinse. Cut Pak choi into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "冬菇津白肉碎粉絲湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-noodles-soup",
    name: "Noodles Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Noodles briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "三鮮湯上海麵",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-mushroom-soup",
    name: "Mushroom Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Mushroom", "Noodles"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Chicken stock", "Dried mushrooms"],
    steps: [
      "Blanch Mushroom briefly if it is meat; rinse. Cut Noodles into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "冬菇肉絲湯麵",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-shrimp-panfry",
    name: "Shrimp Panfry",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Eggs", "Tortilla"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Pat Shrimp dry; season with salt and white pepper. Slice Eggs if using as a side.",
      "Pan-fry in a lightly oiled skillet over medium heat until browned and cooked until just cooked.",
      "Deglaze with a splash of soy sauce or serve with a quick ginger-spring-onion drizzle.",
    ],
    zh: {
      name: "金不換蝦粒煎蛋餅",
      steps: [
        "主料抹乾，加鹽白胡椒；配菜切片。",
        "中火少油煎至上色并熟透。",
        "可淋少許生抽或以薑蔥油提味。",
      ],
    },
  },
  {
    id: "home-cooked-rice-fried-rice",
    name: "Cooked Rice Fried Rice",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Cooked rice"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Loosen cold cooked rice; beat 2 eggs if eggs are in the dish. Dice other mix-ins small.",
      "Scramble eggs in a hot oiled pan; push aside or remove. Stir-fry aromatics and proteins until cooked.",
      "Add rice and 1–2 tbsp soy sauce; toss on high heat until hot and lightly toasted. Finish with spring onion.",
    ],
    zh: {
      name: "鮮露叉燒燒鴨粒炒飯",
      steps: [
        "隔夜飯撥散；如用蛋可先打散。配料切細。",
        "熱鑊炒蛋盛起；爆香蒜薑及蛋白質炒熟。",
        "下飯加 1 至 2 湯匙生抽大火炒香，撒蔥起鑊。",
      ],
    },
  },
]
