import type { Recipe } from "@/lib/recipes"
import { MORE_EXTRA } from "@/lib/more-dishes-extra"
import { MORE_W1A } from "@/lib/more-dishes-w1a"
import { MORE_W1B } from "@/lib/more-dishes-w1b"
import { MORE_W1C } from "@/lib/more-dishes-w1c"
import { MORE_W1D } from "@/lib/more-dishes-w1d"
import { MORE_W2E } from "@/lib/more-dishes-w2e"
import { MORE_W2F } from "@/lib/more-dishes-w2f"
import { MORE_W2G } from "@/lib/more-dishes-w2g"
import { MORE_W2H } from "@/lib/more-dishes-w2h"
import { MORE_W3I } from "@/lib/more-dishes-w3i"
import { MORE_W3J } from "@/lib/more-dishes-w3j"
import { MORE_W3K } from "@/lib/more-dishes-w3k"
import { MORE_W3L } from "@/lib/more-dishes-w3l"
import { MORE_W4A } from "@/lib/more-dishes-w4a"
import { MORE_W4B } from "@/lib/more-dishes-w4b"
import { MORE_W4C } from "@/lib/more-dishes-w4c"
import { MORE_W4D } from "@/lib/more-dishes-w4d"
import { MORE_W4E } from "@/lib/more-dishes-w4e"
import { MORE_W4F } from "@/lib/more-dishes-w4f"

/**
 * Best cookable Tonight book — searchable home classics only.
 * Prefer dishes people can look up on Made With Lau / Lee Kum Kee HK / BBC Food;
 * steps are a quick outline, not the cook-along. `sourceUrl` only when verified.
 */
const MORE_CORE: Recipe[] = [
  {
    id: "home-tomato-egg",
    name: "Tomato egg stir-fry",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Tomato", "Eggs"],
    optional: ["Spring onion", "Sugar", "Soy sauce", "Ginger", "Ketchup", "Cornstarch", "Cooking oil", "Salt"],
    steps: [
      "Cut 2–3 tomatoes into wedges. Beat 3 eggs with a pinch of salt.",
      "Scramble the eggs in a hot, lightly oiled pan until just set; transfer out.",
      "Cook the tomatoes 3–4 minutes until saucy (ginger/sugar/ketchup help), then fold the eggs back in. Finish with spring onion.",
    ],
    zh: {
      name: "番茄炒蛋",
      steps: [
        "切開 2–3 個番茄。打散 3 隻蛋，加少許鹽。",
        "熱鑊下油炒蛋至剛凝固，盛起。",
        "番茄煮 3 至 4 分鐘至出汁（可加薑絲、糖、茄汁），拌回雞蛋，可撒蔥花。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/tomato-and-eggs",
    sourceName: "Made With Lau",
  },
  {
    id: "home-tomato-egg-rice",
    name: "Tomato egg rice",
    cuisine: "Hong Kong",
    time: 20,
    servings: 2,
    need: ["Tomato", "Eggs", "Cooked rice"],
    optional: ["Spring onion", "Soy sauce"],
    steps: [
      "Beat 2 eggs with a pinch of salt. Cut 2 tomatoes into wedges and loosen 2 bowls of cooked rice.",
      "Scramble the eggs in a hot, lightly oiled pan until just set; transfer to a plate.",
      "Cook the tomatoes with a splash of water for 3–4 minutes until saucy. Fold the eggs back in and spoon over hot rice.",
    ],
    zh: {
      name: "番茄炒蛋飯",
      steps: [
        "打散兩隻蛋，加少許鹽。切開兩個番茄，準備兩碗熟飯。",
        "熱鑊下油炒蛋至剛凝固，先盛起。",
        "番茄加少許水煮 3 至 4 分鐘，拌入雞蛋，鋪在熱飯上。",
      ],
    },
  },
  {
    id: "home-egg-fried-rice",
    name: "Egg fried rice",
    cuisine: "Hong Kong",
    time: 15,
    servings: 2,
    need: ["Cooked rice", "Eggs"],
    optional: ["Spring onion", "Soy sauce", "Garlic", "Carrots", "Corn", "Salt", "Cooking oil", "Sugar", "Chicken stock"],
    steps: [
      "Break up 2 bowls of cold cooked rice. Beat 2 eggs and slice spring onion if using.",
      "Scramble the eggs in a hot oiled pan, then add the rice and toss until steaming hot throughout.",
      "Season with soy sauce and spring onion; cook another minute and serve.",
    ],
    zh: {
      name: "蛋炒飯",
      steps: [
        "把兩碗隔夜飯搓散。打散兩隻蛋，有蔥可切蔥花。",
        "熱鑊下油炒蛋，再下飯炒至全熱。",
        "加生抽和蔥花再炒一分鐘即可。",
      ],
    },
  },
  {
    id: "home-steamed-eggs",
    name: "Steamed eggs",
    cuisine: "Cantonese",
    time: 18,
    servings: 2,
    need: ["Eggs"],
    optional: ["Soy sauce", "Spring onion", "Sesame oil", "Salt", "Chicken stock", "Cooking oil"],
    steps: [
      "Beat 2 eggs gently with 1 cup of warm water and a pinch of salt. Strain into a shallow heatproof dish.",
      "Steam covered over medium heat 10–12 minutes until just set (eggs fully opaque).",
      "Rest 2 minutes. Add a little soy sauce, sesame oil, and spring onion if you like.",
    ],
    zh: {
      name: "蒸水蛋",
      steps: [
        "打散兩隻蛋，加入約 1 杯暖水和少許鹽，隔渣倒入深碟。",
        "中火蒸 10 至 12 分鐘至剛好凝固。",
        "靜置兩分鐘，可淋生抽、麻油和蔥花。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/steamed-egg",
    sourceName: "Made With Lau",
  },
  {
    id: "home-egg-drop-soup",
    name: "Egg drop soup",
    cuisine: "Chinese",
    time: 12,
    servings: 2,
    need: ["Eggs"],
    optional: ["Spring onion", "Sesame oil", "Corn", "Shrimp", "White pepper", "Cornstarch", "Carrots", "Silken tofu", "Chicken stock", "Salt", "Cooking oil", "Sugar"],
    steps: [
      "Bring 3 cups of water or light stock to a gentle simmer. Beat 2 eggs.",
      "Stir the pot in a circle and slowly pour in the eggs to make ribbons. Eggs should be fully set.",
      "Season lightly, add spring onion and a drop of sesame oil, and serve.",
    ],
    zh: {
      name: "蛋花湯",
      steps: [
        "煮滾約 3 杯水或清湯。打散兩隻蛋。",
        "湯水轉圈攪動，慢慢倒下蛋液成蛋花，煮至蛋全熟。",
        "調味，加蔥花和少許麻油即可。",
      ],
    },
  },
  {
    id: "home-garlic-choi-sum",
    name: "Garlic choi sum",
    cuisine: "Cantonese",
    time: 12,
    servings: 2,
    need: ["Choi sum", "Garlic"],
    optional: ["Soy sauce", "Oyster sauce"],
    steps: [
      "Wash and drain a bunch of choi sum. Cut stems and leaves into bite-sized pieces; mince 2 garlic cloves.",
      "Heat a little oil in a pan. Stir-fry the stems for 2 minutes, then add the leaves and garlic.",
      "Cook 2–3 more minutes until tender. Splash soy or oyster sauce if you like.",
    ],
    zh: {
      name: "蒜蓉菜心",
      steps: [
        "洗淨一束菜心，瀝乾後切段；拍碎兩瓣蒜。",
        "熱鑊下少許油，先炒菜莖兩分鐘，再加入菜葉和蒜蓉。",
        "再炒兩三分鐘至菜熟，按喜好加生抽或蠔油。",
      ],
    },
  },
  {
    id: "home-garlic-pak-choi",
    name: "Garlic pak choi",
    cuisine: "Cantonese",
    time: 10,
    servings: 2,
    need: ["Pak choi", "Garlic"],
    optional: ["Soy sauce", "Cooking oil", "Sugar"],
    steps: [
      "Halve or quarter pak choi lengthwise and rinse well. Mince 2 garlic cloves.",
      "Stir-fry garlic in a little oil for 20 seconds, then add pak choi and a splash of water.",
      "Cover briefly, then toss until tender-crisp. Season with soy sauce if using.",
    ],
    zh: {
      name: "蒜蓉白菜",
      steps: [
        "白菜直切兩半或四份，洗淨；拍碎兩瓣蒜。",
        "熱鑊下油爆香蒜蓉，下白菜並加少許水。",
        "蓋煮片刻再炒至爽脆，可加生抽調味。",
      ],
    },
  },
  {
    id: "home-oyster-gai-lan",
    name: "Oyster sauce gai lan",
    cuisine: "Cantonese",
    time: 12,
    servings: 2,
    need: ["Gai lan", "Garlic"],
    optional: ["Oyster sauce", "Soy sauce", "Salt", "Cooking oil"],
    steps: [
      "Trim gai lan and cut into lengths. Mince 2 garlic cloves.",
      "Blanch or stir-fry stems first, then leaves, until bright and tender.",
      "Quickly fry garlic, then add oyster sauce and a splash of water; toss with the greens.",
    ],
    zh: {
      name: "蠔油芥蘭",
      steps: [
        "芥蘭去老莖切段；拍碎兩瓣蒜。",
        "先炒或焯菜莖，再下菜葉至變翠綠軟熟。",
        "爆香蒜蓉，加蠔油和少許水，與芥蘭拌勻。",
      ],
    },
  },
  {
    id: "home-ginger-chicken",
    name: "Ginger chicken",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Chicken breast", "Ginger"],
    optional: ["Spring onion", "Soy sauce", "Cooked rice", "Garlic", "Cooking oil", "Shallot", "Shaoxing wine", "Chicken stock", "White pepper", "Oyster sauce", "Cornstarch"],
    steps: [
      "Slice 300 g chicken thinly and cut a thumb of ginger into matchsticks.",
      "Cook chicken and ginger in a lightly oiled pan over medium heat until the chicken is fully cooked through (74°C / 165°F).",
      "Add a splash of water and soy sauce if you have it. Serve with spring onion, over rice if you like.",
    ],
    zh: {
      name: "薑蔥雞",
      steps: [
        "約 300 克雞肉切薄片，薑切絲。",
        "熱鑊下油，中火炒薑和雞肉，煮至雞肉完全熟透（中心達 74°C）。",
        "加少許水和生抽，可撒蔥花，伴飯吃。",
      ],
    },
  },
  {
    id: "home-soy-chicken",
    name: "Soy sauce chicken",
    cuisine: "Cantonese",
    time: 35,
    servings: 2,
    need: ["Chicken thighs", "Soy sauce", "Ginger"],
    optional: ["Spring onion", "Sugar", "Cooked rice", "Shallot", "Cooking oil", "Shaoxing wine", "Cornstarch"],
    steps: [
      "Pat 2 chicken thighs dry. Slice a few ginger coins.",
      "Brown the skin side in a little oil, then add soy sauce, ginger, a pinch of sugar, and enough water to come halfway up the chicken.",
      "Simmer covered 15–20 minutes, turning once, until fully cooked through (74°C / 165°F). Rest and slice; spoon sauce over.",
    ],
    zh: {
      name: "豉油雞",
      steps: [
        "兩隻雞腿抹乾；薑切片。",
        "熱鑊下少許油煎香皮面，加入生抽、薑、少許糖和半量水。",
        "蓋煮 15 至 20 分鐘，中途翻面，至全熟（74°C），切片淋汁。",
      ],
    },
  },
  {
    id: "home-chicken-broccoli",
    name: "Chicken broccoli stir-fry",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Broccoli", "Garlic", "Gai lan"],
    optional: ["Soy sauce", "Ginger", "Cornstarch", "Cooking oil", "Oyster sauce", "Chicken stock", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Slice 250 g chicken and cut broccoli into florets. Mince garlic.",
      "Stir-fry chicken until opaque and cooked through (74°C / 165°F); set aside.",
      "Stir-fry broccoli with garlic and a splash of water, return chicken, season with soy sauce, and toss.",
    ],
    zh: {
      name: "西蘭花炒雞片",
      steps: [
        "約 250 克雞肉切片，西蘭花切小朵；拍碎蒜。",
        "先炒雞肉至全熟（74°C），盛起。",
        "再炒西蘭花和蒜，加少許水，倒回雞肉，淋生抽拌勻。",
      ],
    },
  },
  {
    id: "home-slippery-egg-chicken",
    name: "Slippery egg chicken",
    cuisine: "Hong Kong",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Eggs"],
    optional: ["Spring onion", "Soy sauce", "Cooked rice"],
    steps: [
      "Slice 200 g chicken thinly; beat 3 eggs with a pinch of salt.",
      "Quickly stir-fry the chicken until fully cooked through (74°C / 165°F).",
      "Lower the heat, pour in the eggs, and fold gently until softly set. Serve over rice if you like.",
    ],
    zh: {
      name: "滑蛋雞",
      steps: [
        "約 200 克雞肉切薄片；打散 3 隻蛋加少許鹽。",
        "快炒雞肉至全熟（74°C）。",
        "轉小火倒入蛋液，輕輕翻動至嫩滑凝固，可伴飯。",
      ],
    },
  },
  {
    id: "home-mapo-tofu",
    name: "Mapo tofu",
    cuisine: "Sichuan",
    time: 25,
    servings: 2,
    need: ["Tofu", "Ground pork", "Garlic"],
    optional: ["Ginger", "Spring onion", "Chili oil", "Soy sauce", "Cooking oil", "Dried chili", "Sichuan peppercorns", "Doubanjiang", "Chicken stock", "Cornstarch", "Sesame oil", "Sugar"],
    steps: [
      "Cube tofu; mince garlic and ginger. Brown 150 g ground pork in a little oil until cooked through (74°C / 165°F).",
      "Add aromatics, then a splash of water and chili oil if using. Nestle in tofu and simmer 5–7 minutes.",
      "Season with soy sauce and top with spring onion. Serve with rice.",
    ],
    zh: {
      name: "麻婆豆腐",
      steps: [
        "豆腐切丁，蒜薑拍碎。約 150 克免治豬肉炒至全熟（74°C）。",
        "下蒜薑，加水及辣椒油（如有），放入豆腐煮 5 至 7 分鐘。",
        "加生抽調味，撒蔥花，伴飯吃。",
      ],
    },
    sourceUrl: "https://thewoksoflife.com/ma-po-tofu-real-deal/",
    sourceName: "The Woks of Life",
  },
  {
    id: "home-tomato-tofu",
    name: "Tomato tofu",
    cuisine: "Chinese",
    time: 18,
    servings: 2,
    need: ["Tofu", "Tomato"],
    optional: ["Garlic", "Spring onion", "Soy sauce", "Cooking oil", "Shaoxing wine", "Sugar", "Salt", "Sesame oil", "White pepper", "Cornstarch"],
    steps: [
      "Drain a block of tofu and cut into cubes. Chop 2 tomatoes; mince garlic if using.",
      "Cook the tomato and garlic in a lightly oiled pan for 5 minutes, adding a little water to make a sauce.",
      "Add tofu and simmer gently for 5 minutes. Season and finish with spring onion.",
    ],
    zh: {
      name: "番茄豆腐",
      steps: [
        "豆腐瀝乾切件，兩個番茄切塊；有蒜可切碎。",
        "熱鑊下油，煮番茄和蒜約五分鐘，加少許水煮成醬。",
        "加入豆腐，小火再煮五分鐘，調味後撒蔥花。",
      ],
    },
  },
  {
    id: "home-century-egg-tofu",
    name: "Century egg tofu",
    cuisine: "Cantonese",
    time: 10,
    servings: 2,
    need: ["Tofu", "Century egg"],
    optional: ["Soy sauce", "Sesame oil", "Spring onion", "Garlic"],
    steps: [
      "Drain silken or soft tofu onto a plate. Peel and chop 1–2 century eggs.",
      "Scatter the century egg over the tofu.",
      "Mix soy sauce with a little sesame oil and minced garlic if using; pour over and top with spring onion.",
    ],
    zh: {
      name: "皮蛋豆腐",
      steps: [
        "豆腐瀝乾放碟上。1–2 隻皮蛋去殼切粒。",
        "皮蛋粒舖在豆腐上。",
        "生抽混少許麻油和蒜蓉（如有）淋上，撒蔥花。",
      ],
    },
  },
  {
    id: "home-tomato-beef",
    name: "Tomato beef",
    cuisine: "Hong Kong",
    time: 30,
    servings: 2,
    need: ["Beef steak", "Tomato", "Onion"],
    optional: ["Soy sauce", "Sugar", "Cooked rice", "Cornstarch", "Baking soda", "Cooking oil", "Oyster sauce", "Sesame oil", "White pepper", "Ginger", "Garlic", "Shallot", "Spring onion", "Ketchup", "Shaoxing wine"],
    steps: [
      "Slice 250 g beef thinly; cut 2 tomatoes and half an onion into wedges.",
      "Quickly sear the beef until just browned, then set aside (finish cooking in the sauce).",
      "Cook onion and tomato until saucy, return beef, season with soy sauce and a pinch of sugar, and simmer 1–2 minutes until beef is cooked through. Serve with rice.",
    ],
    zh: {
      name: "番茄牛肉",
      steps: [
        "約 250 克牛肉切薄片；切開兩個番茄和半個洋蔥。",
        "熱鑊快炒牛肉至微變色，盛起。",
        "炒洋蔥和番茄至出汁，倒回牛肉，加生抽和少許糖再煮 1 至 2 分鐘至全熟，伴飯。",
      ],
    },
  },
  {
    id: "home-pork-mince-noodles",
    name: "Pork mince noodles",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Ground pork", "Noodles", "Garlic"],
    optional: ["Spring onion", "Soy sauce", "Chili oil", "Cornstarch", "Cooking oil", "Shaoxing wine", "Oyster sauce", "Chicken stock", "Sesame oil", "Sugar", "White pepper", "Carrots"],
    steps: [
      "Cook noodles per pack; drain. Brown ground pork with garlic until the pork is fully cooked through (74°C / 165°F).",
      "Add soy sauce and a splash of water to make a light sauce.",
      "Toss with noodles and spring onion; add chili oil if you like heat.",
    ],
    zh: {
      name: "免治肉拌麵",
      steps: [
        "煮熟麵條瀝乾。免治豬肉加蒜蓉炒至全熟（74°C）。",
        "加生抽和少許水煮成醬汁。",
        "拌入麵條和蔥花，可加辣椒油。",
      ],
    },
  },
  {
    id: "home-century-egg-congee",
    name: "Century egg pork congee",
    cuisine: "Cantonese",
    time: 45,
    servings: 2,
    need: ["Rice", "Century egg", "Ground pork"],
    optional: ["Ginger", "Spring onion", "Soy sauce", "Salt", "Cooking oil", "White pepper", "Cornstarch", "Baking soda", "Sesame oil"],
    steps: [
      "Rinse 1/2 cup rice. Slice ginger; chop 1–2 century eggs. Break up 100 g ground pork.",
      "Simmer rice with 5 cups water (and ginger) until thick and creamy, 35–40 minutes, stirring now and then.",
      "Add pork in small pieces and cook until fully done (74°C / 165°F). Stir in century egg; finish with spring onion.",
    ],
    zh: {
      name: "皮蛋瘦肉粥",
      steps: [
        "洗半杯米。薑切片，皮蛋切粒；約 100 克免治豬肉撕散。",
        "米加水約 5 杯（可加薑）煮 35 至 40 分鐘至綿滑，不時攪拌。",
        "下豬肉煮至全熟（74°C），拌入皮蛋，撒蔥花。",
      ],
    },
  },
  {
    id: "home-congee",
    name: "Plain congee",
    cuisine: "Cantonese",
    time: 45,
    servings: 2,
    need: ["Rice", "Ginger"],
    optional: ["Spring onion", "Century egg", "Soy sauce"],
    steps: [
      "Rinse 1/2 cup rice. Slice a thumb of ginger.",
      "Simmer rice with 5 cups water and ginger, stirring now and then, until thick and creamy (35–40 minutes).",
      "Season lightly. Add spring onion or century egg if you like.",
    ],
    zh: {
      name: "白粥",
      steps: [
        "洗半杯米；薑切片。",
        "米加 5 杯水和薑煮 35 至 40 分鐘至綿滑，不時攪拌。",
        "少許調味，可加蔥花或皮蛋。",
      ],
    },
  },
  {
    id: "home-steamed-fish",
    name: "Steamed fish with ginger",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["White fish", "Ginger", "Spring onion"],
    optional: ["Soy sauce", "Sesame oil", "Cilantro", "Cooking oil", "Shaoxing wine", "White pepper", "Sugar", "Salt"],
    steps: [
      "Pat fish dry. Scatter ginger matchsticks over the fish on a heatproof plate.",
      "Steam over high heat until the fish flakes easily and is opaque throughout (usually 8–12 minutes depending on thickness).",
      "Top with spring onion, soy sauce, and sesame oil.",
    ],
    zh: {
      name: "清蒸魚",
      steps: [
        "魚抹乾，舖上薑絲，放深碟。",
        "大火蒸至魚肉易撕、全熟不透明（約 8 至 12 分鐘，視厚度）。",
        "撒蔥絲，淋生抽和麻油。",
      ],
    },
  },
  {
    id: "home-shrimp-egg",
    name: "Shrimp egg scramble",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Shrimp", "Eggs"],
    optional: ["Spring onion", "Sesame oil"],
    steps: [
      "Pat shrimp dry and season lightly. Beat 3 eggs.",
      "Quickly cook shrimp in a hot oiled pan until just pink and opaque; set aside.",
      "Scramble eggs softly, fold shrimp back in with spring onion, and finish with sesame oil.",
    ],
    zh: {
      name: "蝦仁炒蛋",
      steps: [
        "蝦抹乾略調味；打散 3 隻蛋。",
        "熱鑊快炒蝦至轉色全熟，盛起。",
        "炒蛋至嫩滑，拌回蝦仁和蔥花，可加麻油。",
      ],
    },
  },
  {
    id: "home-scallion-noodles",
    name: "Scallion oil noodles",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Noodles", "Spring onion", "Soy sauce"],
    optional: ["Garlic", "Sesame oil", "Cooking oil", "Sugar"],
    steps: [
      "Cook noodles; drain. Slice a bunch of spring onion.",
      "Warm a little oil in a pan and fry the spring onion (and garlic) until fragrant but not burnt.",
      "Toss noodles with the onion oil, soy sauce, and a drop of sesame oil. Serve hot.",
    ],
    zh: {
      name: "蔥油拌麵",
      steps: [
        "煮熟麵條瀝乾；蔥切段。",
        "熱油爆香蔥段（可加蒜），至出香味但不要焦。",
        "麵拌蔥油、生抽和少許麻油，趁熱吃。",
      ],
    },
  },
  {
    id: "home-tomato-egg-noodles",
    name: "Tomato egg noodles",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Noodles", "Tomato", "Eggs"],
    optional: ["Spring onion", "Soy sauce"],
    steps: [
      "Cook noodles and set aside. Beat 2 eggs; cut 2 tomatoes into wedges.",
      "Scramble eggs lightly and remove. Cook tomatoes with a splash of water until saucy.",
      "Fold eggs back in, toss with the noodles, and finish with spring onion.",
    ],
    zh: {
      name: "番茄蛋麵",
      steps: [
        "煮麵瀝乾。打散兩隻蛋；切開兩個番茄。",
        "先炒蛋盛起，再煮番茄加少許水至出汁。",
        "拌回雞蛋和麵，撒蔥花。",
      ],
    },
  },
  {
    id: "home-hk-macaroni-soup",
    name: "HK macaroni soup",
    cuisine: "Hong Kong",
    time: 20,
    servings: 1,
    need: ["Pasta", "Eggs", "Ham"],
    optional: ["Spring onion", "Milk", "Corn"],
    steps: [
      "Boil elbow pasta in lightly salted water until tender; drain, saving a cup of the cooking water.",
      "Warm the pasta with a little cooking water or milk into a light soup; add diced ham and corn if using.",
      "Slip in a softly boiled or scrambled egg. Season lightly and finish with spring onion.",
    ],
    zh: {
      name: "港式通粉湯",
      steps: [
        "通心粉加水煮至軟熟，瀝乾並留一杯煮粉水。",
        "通粉加少許煮粉水或牛奶成清湯，可加入火腿粒和粟米。",
        "放入水蛋或炒蛋，調味後撒蔥花。",
      ],
    },
  },
  {
    id: "home-french-toast",
    name: "Hong Kong French toast",
    cuisine: "Hong Kong",
    time: 15,
    servings: 2,
    need: ["Bread", "Eggs", "Milk", "Cream cheese", "Banana"],
    optional: ["Butter", "Peanut butter", "Sugar"],
    steps: [
      "Beat 2 eggs with 1/2 cup milk and a pinch of salt. Soak 4 bread slices briefly.",
      "Pan-fry in butter or oil over medium heat until both sides are golden and the egg is fully set.",
      "Serve hot; peanut butter or a sprinkle of sugar if you like.",
    ],
    zh: {
      name: "西多士",
      steps: [
        "打散兩隻蛋，加半杯牛奶和少許鹽。四片麵包略浸。",
        "中火用牛油或油煎至兩面金黃、蛋全熟。",
        "趁熱吃，可加花生醬或糖。",
      ],
    },
  },
  {
    id: "home-luncheon-fried-rice",
    name: "Luncheon meat fried rice",
    cuisine: "Hong Kong",
    time: 18,
    servings: 2,
    need: ["Cooked rice", "Luncheon meat", "Eggs", "Carrots"],
    optional: ["Spring onion", "Soy sauce", "Cooking oil", "Onion", "Shaoxing wine"],
    steps: [
      "Dice luncheon meat and break up 2 bowls of cold rice. Beat 2 eggs.",
      "Brown the meat in a little oil, scramble in the eggs, then add rice and toss until hot.",
      "Season with soy sauce and spring onion.",
    ],
    zh: {
      name: "餐肉炒飯",
      steps: [
        "餐肉切丁，隔夜飯搓散；打散兩隻蛋。",
        "先煎香餐肉，炒入雞蛋，再下飯炒熱。",
        "加生抽和蔥花拌勻。",
      ],
    },
  },
  {
    id: "home-chinese-sausage-rice",
    name: "Chinese sausage rice",
    cuisine: "Cantonese",
    time: 30,
    servings: 2,
    need: ["Rice", "Chinese sausage", "Eggs"],
    optional: ["Spring onion", "Soy sauce", "Onion", "Salt", "Sugar", "Sesame oil", "White pepper", "Cooking oil", "Shaoxing wine"],
    steps: [
      "Rinse 1 cup of rice. Slice 2 Chinese sausages on the diagonal.",
      "Cook rice as usual. In the last 10 minutes, steam the sausage slices on top of the rice (or pan-fry briefly and serve over).",
      "Fluff the rice, drizzle a little soy sauce if you like, and add spring onion.",
    ],
    zh: {
      name: "臘腸飯",
      steps: [
        "洗一杯米；兩條臘腸斜切。",
        "正常煮飯，最後約 10 分鐘把臘腸放飯面蒸熟（或另煎香）。",
        "把飯拌鬆，可淋少許生抽，撒蔥花。",
      ],
    },
  },
  {
    id: "home-kimchi-fried-rice",
    name: "Kimchi fried rice",
    cuisine: "Korean",
    time: 18,
    servings: 2,
    need: ["Cooked rice", "Kimchi", "Eggs"],
    optional: ["Spring onion", "Sesame oil", "Luncheon meat", "Cornstarch", "Soy sauce", "Sugar", "Shaoxing wine", "Cooking oil", "Onion", "Salt"],
    steps: [
      "Chop kimchi. Beat 2 eggs. Break up cold rice.",
      "Stir-fry kimchi (and diced luncheon meat if using), add rice, and toss until hot.",
      "Push aside and scramble eggs until set, mix through, and finish with sesame oil and spring onion.",
    ],
    zh: {
      name: "泡菜炒飯",
      steps: [
        "泡菜切碎；打散兩隻蛋；隔夜飯搓散。",
        "先炒泡菜（可加餐肉丁），再下飯炒熱。",
        "推開炒蛋至凝固，拌勻，加麻油和蔥花。",
      ],
    },
  },
  {
    id: "home-smashed-cucumber",
    name: "Smashed cucumber salad",
    cuisine: "Chinese",
    time: 10,
    servings: 2,
    need: ["Cucumber", "Garlic"],
    optional: ["Vinegar", "Sesame oil", "Soy sauce", "Spring onion", "Cilantro", "Salt", "Sugar", "Oyster sauce", "Sesame seeds", "Cooking oil"],
    steps: [
      "Smash cucumber with the side of a knife and tear into chunks. Mince garlic.",
      "Toss with garlic, vinegar, soy sauce, and sesame oil.",
      "Taste and adjust; serve cold.",
    ],
    zh: {
      name: "拍青瓜",
      steps: [
        "青瓜用刀背拍裂撕塊；蒜蓉拍碎。",
        "拌入蒜蓉、醋、生抽和麻油。",
        "試味後冷食。",
      ],
    },
  },
  {
    id: "home-garlic-broccoli",
    name: "Garlic broccoli",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Broccoli", "Garlic"],
    optional: ["Soy sauce", "Sesame oil", "Shaoxing wine", "Sugar", "Chicken stock", "White pepper", "Cooking oil", "Cornstarch"],
    steps: [
      "Cut broccoli into florets; mince 2 garlic cloves.",
      "Stir-fry garlic in oil, add broccoli and a splash of water; cover briefly.",
      "Season with soy sauce and a drop of sesame oil.",
    ],
    zh: {
      name: "蒜蓉西蘭花",
      steps: [
        "西蘭花切小朵；拍碎兩瓣蒜。",
        "爆香蒜蓉，下西蘭花加少許水，蓋煮片刻。",
        "加生抽和少許麻油拌勻。",
      ],
    },
  },
  {
    id: "home-potato-stirfry",
    name: "Shredded potato stir-fry",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Potato", "Garlic"],
    optional: ["Vinegar", "Chili oil", "Spring onion"],
    steps: [
      "Peel and julienne 2 potatoes; rinse and pat dry. Mince garlic.",
      "Stir-fry garlic, then potato over medium-high heat until tender-crisp (6–8 minutes).",
      "Splash vinegar if using, season, and finish with chili oil or spring onion.",
    ],
    zh: {
      name: "醋溜土豆絲",
      steps: [
        "兩個薯仔去皮切絲，沖水抹乾；拍碎蒜。",
        "爆香蒜蓉，大火炒薯絲 6 至 8 分鐘至爽脆。",
        "可加醋、辣椒油或蔥花。",
      ],
    },
  },
  {
    id: "home-avocado-toast",
    name: "Avocado toast",
    cuisine: "Western",
    time: 8,
    servings: 1,
    need: ["Bread", "Avocado"],
    optional: ["Eggs", "Lemon", "Tomato", "Garlic", "Salt", "Olive oil", "Cilantro"],
    steps: [
      "Toast bread. Mash avocado with a pinch of salt and lemon if using.",
      "Spread on toast.",
      "Top with a fried or boiled egg if you like (cook egg until whites are set).",
    ],
    zh: {
      name: "牛油果多士",
      steps: [
        "烤香麵包。牛油果壓蓉，加少許鹽和檸檬汁（如有）。",
        "塗在多士上。",
        "可加煎蛋或水煮蛋（蛋白要全熟）。",
      ],
    },
    sourceUrl: "https://www.bbc.co.uk/food/recipes/smashed_avocado_on_toast_89082",
    sourceName: "BBC Food",
  },
  {
    id: "home-bacon-egg-rice",
    name: "Bacon egg rice",
    cuisine: "Western",
    time: 15,
    servings: 1,
    need: ["Bacon", "Eggs", "Cooked rice"],
    optional: ["Spring onion", "Cooking oil", "Onion", "Salt", "Sugar", "Soy sauce", "Shaoxing wine", "White pepper"],
    steps: [
      "Fry bacon until crisp; drain on paper.",
      "Fry eggs in the same pan until whites are fully set. Warm rice in a bowl.",
      "Top rice with bacon and eggs; add spring onion if you like.",
    ],
    zh: {
      name: "培根蛋飯",
      steps: [
        "煎香培根，吸乾油分。",
        "同鑊煎蛋至蛋白全熟；熱飯盛碗。",
        "鋪上培根和蛋，可撒蔥花。",
      ],
    },
  },
  {
    id: "home-instant-noodles-egg",
    name: "Instant noodles with egg",
    cuisine: "Hong Kong",
    time: 10,
    servings: 1,
    need: ["Instant noodles", "Eggs"],
    optional: ["Luncheon meat", "Spring onion", "Choi sum"],
    steps: [
      "Boil water and cook instant noodles per pack instructions.",
      "Crack in an egg and simmer until the white is set (yolk as you like).",
      "Add luncheon meat or greens if using; finish with spring onion.",
    ],
    zh: {
      name: "公仔麵加蛋",
      steps: [
        "按包裝煮即食麵。",
        "打入一隻蛋，煮至蛋白凝固。",
        "可加餐肉或菜心，撒蔥花。",
      ],
    },
  },
  {
    id: "home-leftover-fried-rice",
    name: "Leftover fried rice",
    cuisine: "Hong Kong",
    time: 15,
    servings: 2,
    need: ["Cooked rice", "Eggs", "Cooked leftovers"],
    optional: ["Spring onion", "Soy sauce", "Garlic", "Carrots", "Corn", "Salt", "Cooking oil", "Sugar", "Chicken stock"],
    steps: [
      "Dice leftovers and break up cold rice. Beat 2 eggs.",
      "Scramble eggs, add leftovers to warm through thoroughly, then toss with rice until steaming hot.",
      "Season with soy sauce and spring onion. Make sure leftovers are heated thoroughly.",
    ],
    zh: {
      name: "隔夜菜炒飯",
      steps: [
        "隔夜菜切粒，隔夜飯搓散；打散兩隻蛋。",
        "先炒蛋，再下隔夜菜炒至熱透，拌入飯炒至冒煙。",
        "加生抽和蔥花。隔夜菜必須徹底加熱。",
      ],
    },
  },

  // --- Confident classics from Made With Lau / Lee Kum Kee HK ---
  {
    id: "home-steamed-egg-pork",
    name: "Steamed egg with minced pork",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Eggs", "Ground pork"],
    optional: ["Spring onion", "Oyster sauce", "Soy sauce", "White pepper", "Cornstarch", "Salt", "Cooking oil"],
    steps: [
      "Marinate 120 g ground pork with a little oyster sauce and white pepper. Spread in a shallow dish and steam until the pork is cooked through (74°C / 165°F), about 6–8 minutes.",
      "Beat 3 eggs with about 1 cup warm water and a pinch of salt. Gently pour over the pork.",
      "Steam covered 10–12 minutes until the egg is just set. Rest, then finish with soy sauce and spring onion.",
    ],
    zh: {
      name: "肉碎蒸蛋",
      steps: [
        "約 120 克免治豬肉加蠔油、白胡椒略醃，鋪在深碟大火蒸至全熟（74°C），約 6 至 8 分鐘。",
        "打散 3 隻蛋，加約 1 杯暖水和少許鹽，慢慢倒在肉碎上。",
        "加蓋蒸 10 至 12 分鐘至蛋剛凝固，可淋生抽和蔥花。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/steamed-egg-minced-pork",
    sourceName: "Made With Lau",
  },
  {
    id: "home-beef-broccoli",
    name: "Beef and broccoli",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Beef steak", "Broccoli"],
    optional: ["Garlic", "Ginger", "Oyster sauce", "Soy sauce", "Cornstarch", "Carrots", "Cooking oil", "Salt", "Sesame oil", "Baking soda", "White pepper", "Sugar", "Shaoxing wine"],
    steps: [
      "Slice 250 g beef thin against the grain; toss with a little soy sauce and cornstarch. Cut broccoli into florets.",
      "Blanch or stir-fry broccoli until bright green and tender-crisp; set aside. Sear the beef in a hot oiled pan until just browned and cooked through.",
      "Return broccoli with oyster sauce, soy sauce, and a splash of water; toss 1 minute until glossy.",
    ],
    zh: {
      name: "西蘭花炒牛肉",
      steps: [
        "牛肉約 250 克切薄片，加生抽、生粉略醃。西蘭花切小朵。",
        "西蘭花焯或快炒至翠綠，盛起。熱鑊下油快炒牛肉至全熟。",
        "回菜，加蠔油、生抽和少許水炒至上芡。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/beef-broccoli",
    sourceName: "Made With Lau",
  },
  {
    id: "home-salt-pepper-tofu",
    name: "Salt and pepper tofu",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Tofu"],
    optional: ["Garlic", "Spring onion", "Bell pepper", "White pepper", "Cornstarch", "Eggs", "Salt", "Cooking oil"],
    steps: [
      "Pat tofu dry and cut into cubes. Dust lightly with cornstarch (dip in a little beaten egg if you want a thicker crust).",
      "Pan-fry in a thin layer of oil, turning, until golden and crisp on most sides.",
      "Toss briefly with minced garlic, spring onion, and a mix of salt + white pepper. Serve hot.",
    ],
    zh: {
      name: "椒鹽豆腐",
      steps: [
        "豆腐吸乾水切丁，可拍少許生粉（或薄薄裹蛋液）。",
        "鑊內下油，兩面煎至金黃香脆。",
        "快炒蒜蓉、蔥段，灑椒鹽（鹽+白胡椒）拌勻即可。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/salt-pepper-tofu",
    sourceName: "Made With Lau",
  },
  {
    id: "home-ginger-fried-rice",
    name: "Ginger fried rice",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Cooked rice", "Eggs", "Ginger"],
    optional: ["Chicken breast", "Spring onion", "Soy sauce", "Salt", "Cooking oil", "Cornstarch"],
    steps: [
      "Mince a thumb of ginger. Break up 2 bowls of cold rice; beat 2 eggs. Dice chicken if using.",
      "Scramble eggs and set aside. Stir-fry chicken until cooked through (74°C / 165°F) if using, then fry ginger until fragrant.",
      "Add rice and toss until steaming hot; fold eggs back in. Season and finish with spring onion.",
    ],
    zh: {
      name: "薑炒飯",
      steps: [
        "薑切蓉。兩碗隔夜飯搓散；打散兩隻蛋。有雞肉可切粒。",
        "先炒蛋盛起。雞肉炒至全熟（74°C），爆香薑蓉。",
        "下飯炒至冒煙，拌回雞蛋，調味後撒蔥花。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/ginger-fried-rice",
    sourceName: "Made With Lau",
  },
  {
    id: "home-tomato-tofu-soup",
    name: "Tomato tofu soup",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Tomato", "Tofu", "Eggs"],
    optional: ["Ginger", "Spring onion", "Mushroom", "Soy sauce", "Cornstarch", "Chicken stock", "Ketchup", "Salt", "Sugar", "Sesame oil", "Cooking oil"],
    steps: [
      "Cut 2 tomatoes into chunks and tofu into cubes. Softly beat 2 eggs.",
      "Sauté tomato (and ginger) in a little oil until juicy, add 3 cups water or stock and the tofu, and simmer 5–8 minutes.",
      "Slowly drizzle in the eggs while stirring to make ribbons. Season and finish with spring onion.",
    ],
    zh: {
      name: "番茄豆腐湯",
      steps: [
        "兩個番茄切塊，豆腐切丁；打散兩隻蛋。",
        "略炒番茄（可加薑），加水約三杯和豆腐煮 5 至 8 分鐘。",
        "邊攪邊倒入蛋液成蛋花，調味後撒蔥花。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/tomato-tofu-soup",
    sourceName: "Made With Lau",
  },
  {
    id: "home-potato-chicken",
    name: "Potato braised chicken",
    cuisine: "Hong Kong",
    time: 35,
    servings: 3,
    need: ["Chicken thighs", "Potato", "Garlic"],
    optional: ["Onion", "Oyster sauce", "Soy sauce", "Sugar", "Spring onion"],
    steps: [
      "Cut 400 g chicken thighs into chunks; peel and chunk 2 potatoes. Marinate chicken briefly with oyster sauce if using.",
      "Brown the chicken in a little oil until the surface is coloured; remove. Soften garlic (and onion), then add potato and a cup of water; cover until potato starts to soften.",
      "Return chicken, add oyster sauce/soy/sugar to taste, and simmer covered until chicken is cooked through (74°C / 165°F) and sauce thickens. Finish with spring onion.",
    ],
    zh: {
      name: "薯仔炆雞",
      steps: [
        "雞脾約 400 克切件，兩個薯仔去皮切角；雞可用蠔油略醃。",
        "雞件煎至上色盛起。爆香蒜（可加洋蔥），下薯仔加水一碗加蓋煮至開始軟。",
        "回雞，加蠔油/生抽/糖調味，加蓋炆至雞全熟（74°C）汁濃，撒蔥花。",
      ],
    },
    sourceUrl: "https://hk.lkk.com/zh-hk/recipes/oyster-flavoured-braised-chicken-wings-with-potatoes",
    sourceName: "Lee Kum Kee",
  },
  {
    id: "home-oyster-tofu",
    name: "Oyster sauce tofu",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Tofu", "Oyster sauce"],
    optional: ["Eggs", "Spring onion", "Mushroom", "Cornstarch", "Garlic"],
    steps: [
      "Cut tofu into thick slices; pat dry. Optionally dust with cornstarch and brush with beaten egg.",
      "Pan-fry both sides until golden. Add sliced mushroom if using.",
      "Add oyster sauce loosened with a few tablespoons of water; simmer until glossy. Finish with spring onion.",
    ],
    zh: {
      name: "蠔油豆腐",
      steps: [
        "豆腐切厚片吸乾水；可拍生粉或掃薄蛋液。",
        "兩面煎至金黃，可加入蘑菇片。",
        "蠔油加少許水煮至收汁上芡，撒蔥花。",
      ],
    },
    sourceUrl: "https://hk.lkk.com/zh-hk/recipes/home-style-oyster-sauce-silken-tofu",
    sourceName: "Lee Kum Kee",
  },
  {
    id: "home-garlic-eggplant",
    name: "Garlic eggplant",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Eggplant", "Garlic"],
    optional: ["Ground pork", "Soy sauce", "Oyster sauce", "Vinegar", "Spring onion", "Bell pepper", "Sugar", "Cornstarch", "Shaoxing wine", "Sesame oil", "White pepper", "Cooking oil", "Ginger", "Dried chili"],
    steps: [
      "Cut eggplant into bite-size pieces. Steam or pan-fry with a little oil until soft (8–12 minutes).",
      "In a pan, cook minced pork if using until browned and cooked through (74°C / 165°F), then add lots of garlic.",
      "Add soy sauce, oyster sauce, a splash of vinegar and water; toss with eggplant until coated. Finish with spring onion.",
    ],
    zh: {
      name: "蒜蓉茄子",
      steps: [
        "茄子切件，蒸或少油煎至軟（約 8 至 12 分鐘）。",
        "有免治豬肉先炒至全熟（74°C），再爆大量蒜蓉。",
        "加生抽、蠔油、少許醋和水，拌入茄子炒勻，撒蔥花。",
      ],
    },
    sourceUrl: "https://thewoksoflife.com/chinese-eggplant-garlic-sauce/",
    sourceName: "The Woks of Life",
  },
  {
    id: "home-cabbage-stirfry",
    name: "Garlic cabbage",
    cuisine: "Chinese",
    time: 12,
    servings: 2,
    need: ["Cabbage", "Garlic", "Glass noodles"],
    optional: ["Soy sauce", "Spring onion", "Chili oil", "Vinegar", "White pepper", "Sesame oil", "Sugar", "Cooking oil", "Ginger", "Dried chili", "Salt"],
    steps: [
      "Slice 1/4–1/2 cabbage into ribbons. Slice garlic.",
      "Stir-fry garlic in a hot oiled pan 15 seconds, then add cabbage and a splash of water; cook 3–5 minutes until wilted but still crisp.",
      "Season with soy sauce (chili oil if you like) and spring onion.",
    ],
    zh: {
      name: "蒜蓉炒椰菜",
      steps: [
        "椰菜切絲，蒜切片。",
        "熱鑊爆香蒜，下椰菜加少許水炒 3 至 5 分鐘至軟脆。",
        "加生抽調味，可加辣椒油和蔥花。",
      ],
    },
  },
  {
    id: "home-bean-sprout-stirfry",
    name: "Bean sprout stir-fry",
    cuisine: "Cantonese",
    time: 10,
    servings: 2,
    need: ["Bean sprouts", "Garlic"],
    optional: ["Spring onion", "Soy sauce", "Eggs", "Carrots"],
    steps: [
      "Rinse and drain bean sprouts well. Slice garlic and spring onion.",
      "Optional: scramble an egg and set aside. Stir-fry garlic, then sprouts (and carrot shreds) on high heat 1–2 minutes so they stay crisp.",
      "Season lightly with soy sauce; fold egg back in if using. Serve immediately.",
    ],
    zh: {
      name: "銀芽炒",
      steps: [
        "芽菜洗淨瀝乾，蒜和蔥切片。",
        "可先炒一隻蛋盛起。大火爆香蒜，下芽菜（可加紅蘿蔔絲）炒 1 至 2 分鐘保持爽脆。",
        "少許生抽調味，拌回雞蛋即上碟。",
      ],
    },
  },
  {
    id: "home-chicken-mushroom",
    name: "Chicken and mushroom stir-fry",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Chicken breast", "Mushroom"],
    optional: ["Garlic", "Ginger", "Oyster sauce", "Soy sauce", "Spring onion", "Shaoxing wine", "Shallot", "Sugar", "Salt", "White pepper", "Cornstarch", "Sesame oil", "Cooking oil"],
    steps: [
      "Slice chicken and mushrooms. Marinate chicken briefly with soy sauce.",
      "Stir-fry chicken until cooked through (74°C / 165°F); remove. Cook mushrooms until they release moisture, then add garlic/ginger.",
      "Return chicken with oyster sauce and a splash of water; toss until glossy. Finish with spring onion.",
    ],
    zh: {
      name: "蘑菇炒雞片",
      steps: [
        "雞肉和蘑菇切片；雞可用生抽略醃。",
        "雞片炒至全熟（74°C）盛起。炒香蘑菇出水，可加蒜薑。",
        "回雞，加蠔油和少許水炒勻，撒蔥花。",
      ],
    },
  },

  // --- Western classics (BBC Food) ---
  {
    id: "home-bacon-pasta",
    name: "Bacon tomato pasta",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Pasta", "Bacon", "Tomato"],
    optional: ["Garlic", "Onion", "Spinach", "Olive oil", "Chicken stock", "White pepper"],
    steps: [
      "Boil pasta in salted water until al dente; reserve a cup of cooking water.",
      "Fry bacon until crisp; soften onion/garlic if using, then add chopped tomato and cook until saucy.",
      "Toss pasta with the bacon-tomato mix (spinach if using), loosen with pasta water, and serve.",
    ],
    zh: {
      name: "培根番茄意粉",
      steps: [
        "意粉加鹽水煮至彈牙，留一杯煮粉水。",
        "煎香培根；可炒軟洋蔥蒜蓉，再下番茄煮至出汁。",
        "拌入意粉（可加菠菜），用煮粉水調稠稀上碟。",
      ],
    },
    sourceUrl: "https://www.bbc.co.uk/food/recipes/one-pot_bacon_spinach_50776",
    sourceName: "BBC Food",
  },
  {
    id: "home-scrambled-egg-toast",
    name: "Scrambled eggs on toast",
    cuisine: "Western",
    time: 10,
    servings: 1,
    need: ["Eggs", "Bread"],
    optional: ["Butter", "Milk", "Bacon", "Tomato", "White pepper"],
    steps: [
      "Toast bread. Softly beat 2 eggs with a splash of milk if using.",
      "Melt butter on low heat; scramble eggs gently until just set (no raw runny white).",
      "Serve on toast; add cooked bacon or grilled tomato if you like.",
    ],
    zh: {
      name: "炒蛋多士",
      steps: [
        "烤香麵包。打散兩隻蛋，可加少許牛奶。",
        "小火融化牛油，慢炒蛋至剛好凝固（蛋白要熟）。",
        "鋪在多士上，可配培根或烤番茄。",
      ],
    },
    sourceUrl: "https://www.bbc.co.uk/food/recipes/scrambledeggandtoast_75736",
    sourceName: "BBC Food",
  },
]

export const MORE: Recipe[] = [
  ...MORE_CORE,
  ...MORE_EXTRA,
  ...MORE_W1A,
  ...MORE_W1B,
  ...MORE_W1C,
  ...MORE_W1D,
  ...MORE_W2E,
  ...MORE_W2F,
  ...MORE_W2G,
  ...MORE_W2H,
  ...MORE_W3I,
  ...MORE_W3J,
  ...MORE_W3K,
  ...MORE_W3L,
  ...MORE_W4A,
  ...MORE_W4B,
  ...MORE_W4C,
  ...MORE_W4D,
  ...MORE_W4E,
  ...MORE_W4F,
]

/** Outline-catalogue ZH name hints (not home recipe titles). */
export const MORE_ZH: Record<string, string> = {
  "char-siu": "叉燒",
  "wonton-noodle": "雲吞麵",
  "brisket-noodle": "牛腩麵",
  "claypot-rice": "煲仔飯",
  "sweet-sour-pork": "咕嚕肉",
  "steamed-egg": "蒸水蛋",
  "hainan-chicken": "海南雞飯",
  "pork-chop-rice": "豬扒飯",
  "tomato-beef": "番茄牛肉",
  "kung-pao": "宮保雞丁",
  "dan-dan": "擔擔麵",
  "curry-rice": "咖喱飯",
  gyudon: "牛丼",
  bibimbap: "拌飯",
  "pad-thai": "泰式炒河",
  pho: "越南河粉",
  carbonara: "卡邦尼",
  bolognese: "肉醬意粉",
  shakshuka: "北非蛋",
  "fried-chicken": "炸雞",
  steak: "煎牛扒",
  dumplings: "煎餃",
  laksa: "喇沙",
  "french-toast": "西多士",
  "mac-cheese": "芝士通粉",
  ramen: "醬油拉麵",
  "udon-stir": "炒烏冬",
  "green-curry": "青咖喱",
}
