import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W4D: Recipe[] = [
  {
    id: "home-savory-oatmeal",
    name: "Savory oatmeal bowl",
    cuisine: "Breakfast",
    time: 15,
    servings: 1,
    need: ["Oats", "Eggs"],
    optional: ["White pepper", "Soy sauce", "Cooking oil", "Onion", "Spring onion", "Cheddar", "Salt", "Milk", "Sesame oil"],
    steps: [
      "Simmer 1/2 cup oats with 1 cup water (or milk from pantry) 5–7 minutes until creamy; season with salt.",
      "Fry or poach 1–2 eggs until whites are set (yolks as you like).",
      "Top oats with egg, spring onion, soy sauce, sesame oil, white pepper, and cheddar if using.",
    ],
    zh: {
      name: "鹹味燕麥碗",
      steps: [
        "半杯燕麥加一杯水（或奶）煮 5 至 7 分鐘至稠，加鹽。",
        "煎或水波一至兩隻蛋至蛋白凝固。",
        "燕麥上放蛋、蔥花、生抽麻油白胡椒，可加芝士。",
      ],
    },
  },
  {
    id: "home-egg-muffin-cups",
    name: "Egg muffin cups",
    cuisine: "Breakfast",
    time: 30,
    servings: 3,
    need: ["Eggs", "Spinach", "Cheddar"],
    optional: ["White pepper", "Tomato", "Onion", "Salt", "Ham"],
    steps: [
      "Beat 6 eggs with salt and white pepper. Chop spinach, ham, onion, and tomato if using.",
      "Divide fillings into a greased muffin tin; pour egg over and top with grated cheddar.",
      "Bake at 180°C / 350°F for 18–20 minutes until set and lightly golden.",
    ],
    zh: {
      name: "雞蛋瑪芬杯",
      steps: [
        "六隻蛋加鹽白胡椒打散。菠菜、火腿、洋蔥番茄（可用）切碎。",
        "填料分入抹油瑪芬模，倒入蛋液撒切達芝士。",
        "180°C 焗 18 至 20 分鐘至凝固微金。",
      ],
    },
  },
  {
    id: "home-jianbing-wrap",
    name: "Jianbing-style egg wrap",
    cuisine: "Breakfast",
    time: 15,
    servings: 1,
    need: ["Eggs", "Tortilla"],
    optional: ["Soy sauce", "Cooking oil", "Lettuce", "Onion", "Spring onion", "Chili oil", "Cucumber", "Ham"],
    steps: [
      "Warm 1 large tortilla in a pan. Pour a beaten egg over it; cook until just set, flipping carefully if needed.",
      "Spread a little chili oil and soy sauce; add spring onion, lettuce, cucumber, and ham if using.",
      "Fold or roll and serve hot.",
    ],
    zh: {
      name: "煎餅果子風蛋餅",
      steps: [
        "一張大餅皮（代替煎餅）暖熱，倒入打散蛋液至凝固，可小心翻面。",
        "塗少許辣椒油和生抽，加蔥花、生菜、青瓜和火腿（可用）。",
        "摺起或卷起趁熱吃。",
      ],
    },
  },
  {
    id: "home-bao-leftover-plate",
    name: "Leftover bao-style plate",
    cuisine: "Breakfast",
    time: 15,
    servings: 2,
    need: ["Cooked leftovers", "Eggs", "Tortilla"],
    optional: ["Soy sauce", "Bread", "Cooking oil", "Lettuce", "Onion", "Spring onion", "Chili oil", "Cucumber"],
    steps: [
      "Warm leftover protein/veg in a pan with a splash of soy sauce. Warm tortillas or soft bread as bao stand-ins.",
      "Fry 2 eggs. Slice cucumber/lettuce if using. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Build plates: wrap or open-face with leftovers, egg, veg, chili oil, and spring onion.",
    ],
    zh: {
      name: "剩菜包式早餐碟",
      steps: [
        "剩菜加少許生抽熱透。餅皮或軟包暖熱作包子代替。",
        "煎兩隻蛋；可切片青瓜生菜。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "包起或開面放剩菜、蛋、蔬菜、辣椒油和蔥花。",
      ],
    },
  },
  {
    id: "home-milk-butter-toast",
    name: "Milk butter toast",
    cuisine: "Breakfast",
    time: 10,
    servings: 1,
    need: ["Bread", "Milk", "Butter"],
    optional: ["Condensed milk", "Sugar"],
    steps: [
      "Brush 2 bread slices lightly with milk; spread butter.",
      "Toast in a pan or toaster oven until golden on both sides (3–4 minutes).",
      "Optional: drizzle condensed milk or sprinkle sugar. For richer toast, dip in beaten egg before pan-frying.",
    ],
    zh: {
      name: "牛奶牛油多士",
      steps: [
        "兩片麵包薄掃牛奶，塗牛油。",
        "平底鑊或焗爐烤至兩面金黃約 3 至 4 分鐘。",
        "可淋煉奶或撒糖；想更豐富可先沾蛋液再煎。",
      ],
    },
  },
  {
    id: "home-congee-fish-slice",
    name: "Fish slice congee",
    cuisine: "Breakfast",
    time: 35,
    servings: 2,
    need: ["Cooked rice", "White fish"],
    optional: ["White pepper", "Cooking oil", "Onion", "Spring onion", "Salt", "Sesame oil", "Ginger", "Oyster sauce", "Shaoxing wine", "Chicken stock"],
    steps: [
      "Rinse 3/4 cup rice; simmer with about 6 cups water 25 minutes, stirring often until creamy.",
      "Slice 200 g white fish thinly; add with ginger for the last 5 minutes until fish is opaque.",
      "Season with salt and white pepper; finish with spring onion and sesame oil.",
    ],
    zh: {
      name: "魚片粥",
      steps: [
        "米約四分三杯洗净，加水約六杯煮 25 分鐘常攪至稠。",
        "白魚約 200 克切薄，最後 5 分鐘連薑下鍋至魚熟。",
        "加鹽白胡椒，撒蔥花滴麻油。",
      ],
    },
  },
  {
    id: "home-congee-pork-mince",
    name: "Pork mince congee",
    cuisine: "Breakfast",
    time: 35,
    servings: 2,
    need: ["Cooked rice", "Ground pork"],
    optional: ["White pepper", "Soy sauce", "Onion", "Spring onion", "Salt", "Ginger", "Century egg", "Cooking oil", "Cornstarch", "Baking soda", "Sesame oil"],
    steps: [
      "Simmer 3/4 cup rice with about 6 cups water 25 minutes until creamy.",
      "Season 200 g ground pork with soy sauce; drop small pinches into the congee. Cook 8–10 minutes until pork reaches 74°C / 165°F.",
      "Optional century egg cubes. Season with salt and white pepper; top with ginger and spring onion.",
    ],
    zh: {
      name: "肉碎粥",
      steps: [
        "米約四分三杯加水約六杯煮 25 分鐘至稠。",
        "免治豬肉約 200 克加生抽，捏小塊下粥煮 8 至 10 分鐘至全熟（74°C）。",
        "可加皮蛋粒；加鹽白胡椒，撒薑絲蔥花。",
      ],
    },
  },
  {
    id: "home-berry-yogurt-oats",
    name: "Berry yogurt oats",
    cuisine: "Breakfast",
    time: 10,
    servings: 1,
    need: ["Oats", "Yogurt", "Berries"],
    optional: ["Milk", "Banana", "Honey"],
    steps: [
      "Stir 1/2 cup oats with 1/2 cup yogurt and a splash of milk until loose.",
      "Top with a handful of berries and sliced banana if using.",
      "Drizzle honey to taste; eat cold or warm the oats first.",
    ],
    zh: {
      name: "莓果乳酪燕麥",
      steps: [
        "半杯燕麥加半杯乳酪和少許奶拌鬆。",
        "放一把莓果，可加蕉片。",
        "按喜好淋蜜糖；可冷食或先熱燕麥。",
      ],
    },
  },
  {
    id: "home-egg-cheese-tortilla",
    name: "Egg cheese breakfast tortilla",
    cuisine: "Breakfast",
    time: 12,
    servings: 1,
    need: ["Eggs", "Tortilla", "Cheddar"],
    optional: ["Tomato", "Spinach", "Onion", "Salt", "Ham"],
    steps: [
      "Scramble 2 eggs with salt until just set; fold in spinach/ham/onion if using.",
      "Warm tortilla; add eggs and grated cheddar. Optional tomato slices.",
      "Fold and press in the pan 1 minute until cheese melts.",
    ],
    zh: {
      name: "芝士蛋早餐餅",
      steps: [
        "兩隻蛋加鹽炒至剛熟，可拌菠菜火腿洋蔥。",
        "暖熱餅皮，放蛋和切達芝士，可加番茄片。",
        "摺起在鑊略壓 1 分鐘至芝士融化。",
      ],
    },
  },
  {
    id: "home-breakfast-fried-noodles",
    name: "Breakfast fried noodles",
    cuisine: "Breakfast",
    time: 15,
    servings: 1,
    need: ["Noodles", "Eggs"],
    optional: ["Soy sauce", "Cooking oil", "Onion", "Spring onion", "Bean sprouts", "Sesame oil", "Ham", "Ginger", "Baking soda", "Oyster sauce", "White pepper", "Cornstarch", "Ketchup", "Sugar", "Salt"],
    steps: [
      "Boil noodles until tender; drain. Beat 1–2 eggs.",
      "Scramble eggs in a pan; add noodles, ham if using, soy sauce, and sesame oil.",
      "Toss 1–2 minutes; finish with bean sprouts and spring onion.",
    ],
    zh: {
      name: "早餐炒麵",
      steps: [
        "麵煮軟瀝乾。打散一至兩隻蛋。",
        "先炒蛋，下面、火腿（可用）、生抽和麻油。",
        "炒 1 至 2 分鐘，拌芽菜蔥花。",
      ],
    },
  },
  {
    id: "home-ham-egg-rice-bowl",
    name: "Ham egg rice bowl",
    cuisine: "Breakfast",
    time: 12,
    servings: 1,
    need: ["Cooked rice", "Ham", "Eggs"],
    optional: ["White pepper", "Soy sauce", "Onion", "Spring onion", "Butter"],
    steps: [
      "Warm 1 bowl cooked rice with a knob of butter if using. Dice ham and warm in a pan.",
      "Fry 1–2 eggs to your liking.",
      "Top rice with ham and eggs; season with soy sauce, white pepper, and spring onion.",
    ],
    zh: {
      name: "火腿蛋飯",
      steps: [
        "一碗熟飯可加牛油熱透。火腿切粒炒熱。",
        "按喜好煎一至兩隻蛋。",
        "飯上放火腿和蛋，加生抽白胡椒蔥花。",
      ],
    },
  },  {
    id: "home-honey-yogurt-oats",
    name: "Honey yogurt oat cup",
    cuisine: "Breakfast",
    time: 8,
    servings: 1,
    need: ["Oats", "Yogurt", "Honey"],
    optional: ["Peanut butter", "Berries", "Milk", "Banana", "Butter"],
    steps: [
      "Layer 1/2 cup oats with 1/2 cup yogurt in a cup or bowl.",
      "Drizzle 1–2 tsp honey; add banana or berries if using.",
      "Optional: loosen with milk or swirl peanut butter. Eat immediately or chill 10 minutes.",
    ],
    zh: {
      name: "蜜糖乳酪燕麥杯",
      steps: [
        "半杯燕麥與半杯乳酪分層放入杯。",
        "淋一至兩茶匙蜜糖，可加蕉或莓果。",
        "可加奶調稀或拌花生醬；即食或冷藏 10 分鐘。",
      ],
    },
  },
  {
    id: "home-banana-oat-pancakes",
    name: "Banana oat pancakes",
    cuisine: "Breakfast",
    time: 20,
    servings: 2,
    need: ["Banana", "Oats", "Eggs"],
    optional: ["Berries", "Milk", "Honey", "Cooking oil"],
    steps: [
      "Mash 1 ripe banana; mix with 1 egg and 1/2 cup oats (splash of milk if thick).",
      "Cook small pancakes in a lightly buttered pan 2–3 minutes per side until set.",
      "Serve with honey and berries if using.",
    ],
    zh: {
      name: "香蕉燕麥煎餅",
      steps: [
        "一隻熟香蕉壓蓉，加一隻蛋和半杯燕麥（稠可加少許奶）。",
        "少牛油鑊中煎小餅，每面 2 至 3 分鐘至熟。",
        "可淋蜜糖配莓果。",
      ],
    },
  },
  {
    id: "home-sausage-egg-toast",
    name: "Sausage egg toast",
    cuisine: "Breakfast",
    time: 15,
    servings: 1,
    need: ["Sausages", "Eggs", "Bread"],
    optional: ["Cheddar", "Ketchup", "Butter", "Salt"],
    steps: [
      "Pan-fry 1–2 sausages until cooked through (74°C / 165°F if pork). Toast bread with butter if using.",
      "Fry 1–2 eggs.",
      "Build toast with sausage and egg; optional cheddar melt and ketchup.",
    ],
    zh: {
      name: "香腸蛋多士",
      steps: [
        "一至兩條香腸煎至全熟（豬肉類 74°C）。麵包可塗牛油烤香。",
        "煎一至兩隻蛋。",
        "多士上放香腸和蛋；可熔芝士加茄汁。",
      ],
    },
  },
  {
    id: "home-spinach-egg-wrap",
    name: "Spinach egg breakfast wrap",
    cuisine: "Breakfast",
    time: 12,
    servings: 1,
    need: ["Spinach", "Eggs", "Tortilla"],
    optional: ["Tomato", "Bread", "Cheddar", "Salt", "Onion"],
    steps: [
      "Wilt a handful of spinach in a pan; scramble 2 eggs with salt.",
      "Warm tortilla; fill with spinach, eggs, cheddar, and tomato if using.",
      "Roll tightly and toast seam-side down 1 minute.",
    ],
    zh: {
      name: "菠菜蛋早餐卷",
      steps: [
        "一把菠菜炒軟；兩隻蛋加鹽炒熟。",
        "暖熱餅皮，放入菠菜、蛋、芝士和番茄（可用）。",
        "卷緊，封口向下烙 1 分鐘。",
      ],
    },
  },
  {
    id: "home-miso-breakfast-bowl",
    name: "Miso breakfast bowl",
    cuisine: "Breakfast",
    time: 15,
    servings: 1,
    need: ["Miso", "Tofu", "Cooked rice"],
    optional: ["Chicken stock", "Nori", "Onion", "Spring onion", "Sesame seeds"],
    steps: [
      "Warm 1 bowl cooked rice. Cube 100 g tofu; simmer in 1.5 cups water 3 minutes.",
      "Off heat, dissolve 1 tbsp miso into the broth.",
      "Serve rice beside or under tofu miso soup; top with nori, spring onion, sesame seeds, and optional soft egg.",
    ],
    zh: {
      name: "味噌早餐碗",
      steps: [
        "一碗熱飯。豆腐約 100 克切塊，加水約一杯半煮 3 分鐘。",
        "離火拌入一湯匙味噌。",
        "飯配味噌豆腐湯，撒紫菜蔥花芝麻，可加半熟蛋。",
      ],
    },
  },
  {
    id: "home-rice-cake-breakfast",
    name: "Breakfast rice cake stir",
    cuisine: "Breakfast",
    time: 15,
    servings: 1,
    need: ["Rice cakes", "Eggs"],
    optional: ["Gochujang", "Soy sauce", "Cooking oil", "Onion", "Spring onion", "Sesame oil", "Sugar"],
    steps: [
      "Soak or boil rice cakes until soft. Beat 1–2 eggs.",
      "Stir-fry rice cakes with a little gochujang or soy sauce and pinch of sugar 2–3 minutes.",
      "Push aside; scramble eggs, then toss together with sesame oil and spring onion.",
    ],
    zh: {
      name: "早餐炒年糕",
      steps: [
        "年糕浸或煮至軟。打散一至兩隻蛋。",
        "年糕加少許韓式辣椒醬或生抽和糖炒 2 至 3 分鐘。",
        "撥開炒蛋再拌匀，滴麻油撒蔥花。",
      ],
    },
  },
  {
    id: "home-corned-beef-hash",
    name: "Corned beef hash",
    cuisine: "Breakfast",
    time: 25,
    servings: 2,
    need: ["Corned beef", "Potato", "Onion"],
    optional: ["White pepper", "Eggs", "Spring onion", "Ketchup", "Salt"],
    steps: [
      "Dice 2 potatoes; boil 8–10 minutes until just tender, drain. Chop onion; flake corned beef.",
      "Fry onion and potato until golden; add corned beef and crisp 4–5 minutes. Season with white pepper.",
      "Optional: top with fried eggs and spring onion; serve with ketchup.",
    ],
    zh: {
      name: "咸牛肉薯仔早餐",
      steps: [
        "兩個薯仔切粒煮 8 至 10 分鐘至剛軟瀝乾。洋蔥切碎；咸牛肉撕開。",
        "炒香洋蔥薯仔至金黃，下咸牛肉再煎脆 4 至 5 分鐘，加白胡椒。",
        "可放煎蛋蔥花，配茄汁。",
      ],
    },
  },  {
    id: "home-soy-milk-oats",
    name: "Warm milk oats",
    cuisine: "Breakfast",
    time: 10,
    servings: 1,
    need: ["Oats", "Milk"],
    optional: ["Condensed milk", "Berries", "Banana", "Honey", "Sugar"],
    steps: [
      "Simmer 1/2 cup oats with 1 cup milk 5–7 minutes until thick, stirring.",
      "Sweeten with honey, sugar, or a drizzle of condensed milk.",
      "Top with banana or berries if using.",
    ],
    zh: {
      name: "牛奶燕麥粥",
      steps: [
        "半杯燕麥加一杯牛奶煮 5 至 7 分鐘至稠，常攪。",
        "用蜜糖、糖或煉奶調甜。",
        "可加蕉片或莓果。",
      ],
    },
  },
  {
    id: "home-leftover-congee-fry",
    name: "Pan-fried leftover congee cakes",
    cuisine: "Breakfast",
    time: 15,
    servings: 1,
    need: ["Cooked leftovers", "Eggs"],
    optional: ["White pepper", "Soy sauce", "Onion", "Spring onion", "Salt"],
    steps: [
      "Mix leftover congee (as cooked leftovers) with 1 beaten egg, spring onion, salt, and white pepper until thick.",
      "Spoon into a lightly oiled pan as small cakes; fry 3–4 minutes per side until set and golden. Any leftover meat or poultry must reach 74°C / 165°F.",
      "Serve with soy sauce on the side.",
    ],
    zh: {
      name: "剩粥煎餅",
      steps: [
        "剩粥（作熟剩菜）加一隻打散蛋、蔥花、鹽和白胡椒拌稠。",
        "少油鑊中煎成小餅，每面 3 至 4 分鐘至定形金黃。 隔夜肉類或家禽須煮至 74°C / 165°F。",
        "可蘸生抽吃。",
      ],
    },
  },
  {
    id: "home-bacon-potato-hash",
    name: "Bacon potato breakfast hash",
    cuisine: "Breakfast",
    time: 25,
    servings: 2,
    need: ["Bacon", "Potato", "Onion"],
    optional: ["White pepper", "Eggs", "Bell pepper", "Spring onion", "Salt"],
    steps: [
      "Dice 2 potatoes; boil until just tender, drain. Chop bacon and onion.",
      "Render bacon until crisp; add onion, potato, and bell pepper if using. Crisp 6–8 minutes.",
      "Season with white pepper; optional fried eggs and spring onion on top.",
    ],
    zh: {
      name: "煙肉薯仔早餐",
      steps: [
        "兩個薯仔切粒煮至剛軟瀝乾。煙肉洋蔥切碎。",
        "煙肉煎出油至脆，下洋蔥薯仔和燈籠椒（可用）再煎 6 至 8 分鐘。",
        "加白胡椒；可放煎蛋蔥花。",
      ],
    },
  },  {
    id: "home-mushroom-egg-cups",
    name: "Mushroom egg breakfast cups",
    cuisine: "Breakfast",
    time: 20,
    servings: 2,
    need: ["Mushroom", "Eggs"],
    optional: ["White pepper", "Onion", "Spring onion", "Cheddar", "Butter", "Salt"],
    steps: [
      "Remove stems from 4 large mushrooms; brush caps with butter if using. Season lightly.",
      "Crack an egg into each cap; top with cheddar if using.",
      "Bake at 190°C / 375°F for 12–15 minutes until whites set. Finish with spring onion and white pepper.",
    ],
    zh: {
      name: "蘑菇蛋早餐杯",
      steps: [
        "四個大蘑菇去蒂，可掃牛油略調味。",
        "每隻蘑菇倒入一隻蛋，可撒芝士。",
        "190°C 焗 12 至 15 分鐘至蛋白凝固，撒蔥花白胡椒。",
      ],
    },
  },
]
