import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W3K: Recipe[] = [
  {
    id: "home-shakshuka",
    name: "Shakshuka",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Garlic", "Shallot", "Bell pepper", "Tomato", "Eggs", "Eggplant", "Zucchini", "Cheddar"],
    optional: ["Olive oil", "Salt", "White pepper", "Paprika", "Cumin"],
    steps: [
      "Softer onion and bell pepper in oil 5 minutes; add chopped tomato and simmer 8–10 minutes until saucy.",
      "Make wells; crack in 3–4 eggs. Cover until whites set but yolks soft, 5–7 minutes.",
      "Season with salt and chili oil; serve with bread.",
    ],
    zh: {
      name: "北非蛋",
      steps: [
        "洋蔥燈籠椒炒軟約 5 分鐘；下番茄煮 8 至 10 分鐘至出汁。",
        "開穴打入 3 至 4 隻蛋，加蓋煮至蛋白凝固約 5 至 7 分鐘。",
        "加鹽和辣椒油，配麵包。",
      ],
    },
  },
  {
    id: "home-chickpea-curry",
    name: "Chickpea curry",
    cuisine: "Western",
    time: 25,
    servings: 3,
    need: ["Beans", "Curry powder", "Coconut milk", "Tomato"],
    optional: ["Onion", "Garlic", "Ginger", "Spinach", "Salt", "Bread", "Cilantro", "Cooking oil"],
    steps: [
      "Sauté onion and garlic; stir in 1–2 tbsp curry powder 30 seconds.",
      "Add drained beans, chopped tomato, and 1 cup coconut milk; simmer 12 minutes.",
      "Fold in spinach if using; season and serve.",
    ],
    zh: {
      name: "鷹嘴豆咖哩",
      steps: [
        "炒洋蔥蒜頭，下 1 至 2 湯匙咖哩粉爆香。",
        "下瀝乾豆、番茄和 1 杯椰奶，炆 12 分鐘。",
        "可拌菠菜，調味即可。",
      ],
    },
  },
  {
    id: "home-sheet-pan-chicken-veg",
    name: "Sheet-pan chicken veg",
    cuisine: "Western",
    time: 35,
    servings: 3,
    need: ["Chicken thighs", "Broccoli", "Carrots"],
    optional: ["Potato", "Olive oil", "Salt", "Garlic", "Lemon"],
    steps: [
      "Toss chicken and chopped veg with oil, salt, and garlic on a tray.",
      "Roast at 200°C / 400°F about 25–30 minutes until chicken is 74°C / 165°F.",
      "Squeeze lemon over and serve.",
    ],
    zh: {
      name: "焗盤雞菜",
      steps: [
        "雞髀和切件蔬菜拌油鹽蒜鋪焗盤。",
        "200°C 焗約 25 至 30 分鐘至雞全熟（74°C）。",
        "可搾檸檬汁。",
      ],
    },
  },
  {
    id: "home-pesto-pasta",
    name: "Pesto pasta (home)",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Parmesan", "Garlic", "Tomato", "Berries"],
    optional: ["Salt", "Olive oil"],
    steps: [
      "Boil pasta in salted water until al dente; reserve ½ cup water.",
      "Blend or finely chop basil with garlic, olive oil, and a pinch of salt (cheese optional).",
      "Toss pasta with pesto and pasta water until coated; lemon if using.",
    ],
    zh: {
      name: "青醬意粉",
      steps: [
        "意粉煮至有咬勁，留半杯麵水。",
        "羅勒與蒜、橄欖油和少許鹽剁蓉（可加芝士）。",
        "拌麵和麵水至匀，可加檸檬。",
      ],
    },
  },
  {
    id: "home-tuna-melt",
    name: "Tuna melt",
    cuisine: "Western",
    time: 15,
    servings: 1,
    need: ["Canned tuna", "Bread", "Cheddar"],
    optional: ["Mayonnaise", "Onion", "Butter", "Tomato"],
    steps: [
      "Mix drained tuna with 1 tbsp mayonnaise and minced onion.",
      "Pile on bread, top with cheddar; grill or pan-lid until cheese melts.",
      "Optional tomato slice inside; butter outside for toasting.",
    ],
    zh: {
      name: "吞拿魚熔芝士多士",
      steps: [
        "吞拿魚瀝乾加 1 湯匙蛋黃醬和洋蔥碎。",
        "鋪麵包上放車打芝士，焗或加蓋至芝士融化。",
        "可加番茄片，外塗牛油煎香。",
      ],
    },
  },
  {
    id: "home-baked-beans-toast",
    name: "Baked beans on toast",
    cuisine: "Western",
    time: 10,
    servings: 1,
    need: ["Beans", "Bread", "Tomato"],
    optional: ["Butter", "Onion", "Sugar", "Salt", "Cheddar"],
    steps: [
      "Warm drained beans with chopped tomato, a pinch of sugar/salt, and optional onion 5–7 minutes.",
      "Toast bread and butter lightly.",
      "Spoon beans over toast; optional cheese.",
    ],
    zh: {
      name: "茄汁豆多士",
      steps: [
        "瀝乾豆加番茄碎、少許糖鹽（可加洋蔥）煮 5 至 7 分鐘。",
        "多士烤香塗牛油。",
        "鋪豆，可加芝士。",
      ],
    },
  },
  {
    id: "home-mushroom-risotto",
    name: "Mushroom risotto (simple)",
    cuisine: "Western",
    time: 35,
    servings: 2,
    need: ["Chicken thighs", "Lemongrass", "Onion", "Mushroom", "Rice", "Spring onion", "Parmesan"],
    optional: ["Salt", "Olive oil", "Chicken stock"],
    steps: [
      "Sauté onion and mushrooms in butter until browned.",
      "Stir in ¾ cup raw rice 1 minute; add hot water ½ cup at a time, stirring, ~20 minutes until creamy and tender.",
      "Finish with butter/cheese and salt.",
    ],
    zh: {
      name: "蘑菇意式燉飯",
      steps: [
        "牛油炒洋蔥蘑菇至上色。",
        "下 ¾ 杯生米拌 1 分鐘；分次加半杯熱水攪拌約 20 分鐘至軟滑。",
        "拌牛油／芝士和鹽。",
      ],
    },
  },
  {
    id: "home-pan-fish-peas",
    name: "Pan fish with greens",
    cuisine: "Western",
    time: 18,
    servings: 2,
    need: ["White fish", "Green beans"],
    optional: ["Lemon", "Butter", "Salt", "Garlic", "Olive oil"],
    steps: [
      "Pat fish dry; season. Pan-sear 3–4 minutes per side until opaque and flaky.",
      "In same pan, sauté green beans with garlic 4–5 minutes.",
      "Finish with butter and lemon.",
    ],
    zh: {
      name: "香煎魚配青豆",
      steps: [
        "魚抹乾調味，每面煎 3 至 4 分鐘至熟透可撕。",
        "同鑊蒜蓉炒豆角 4 至 5 分鐘。",
        "加牛油和檸檬。",
      ],
    },
  },
  {
    id: "home-yogurt-cucumber-bowl",
    name: "Greek yogurt cucumber bowl",
    cuisine: "Western",
    time: 10,
    servings: 1,
    need: ["Yogurt", "Cucumber"],
    optional: ["Garlic", "Lemon", "Salt", "Olive oil", "Bread"],
    steps: [
      "Dice cucumber; mix into thick yogurt with minced garlic, salt, and lemon.",
      "Drizzle olive oil.",
      "Eat as a bowl or with bread.",
    ],
    zh: {
      name: "乳酪青瓜碗",
      steps: [
        "青瓜切粒拌入乳酪，加蒜蓉、鹽和檸檬。",
        "淋橄欖油。",
        "可配麵包。",
      ],
    },
  },
  {
    id: "home-tomato-mozzarella-toast",
    name: "Tomato mozzarella toast",
    cuisine: "Western",
    time: 10,
    servings: 1,
    need: ["Bread", "Tomato", "Mozzarella"],
    optional: ["Olive oil", "Salt", "Thai basil"],
    steps: [
      "Toast bread. Slice tomato and mozzarella.",
      "Layer on toast with salt and olive oil.",
      "Optional basil leaves on top.",
    ],
    zh: {
      name: "番茄莫札瑞拉多士",
      steps: [
        "多士烤香；番茄和芝士切片。",
        "鋪上加鹽和橄欖油。",
        "可放羅勒葉。",
      ],
    },
  },  {
    id: "home-meatball-tomato-pasta",
    name: "Beef meatball tomato pasta",
    cuisine: "Western",
    time: 30,
    servings: 3,
    need: ["Ground beef", "Pasta", "Tomato"],
    optional: ["Onion", "Garlic", "Eggs", "Salt", "White pepper", "Beef steak", "Cornstarch", "Baking soda", "Cooking oil", "Oyster sauce", "Soy sauce", "Sugar", "Sesame oil", "Ginger", "Shallot", "Spring onion", "Ketchup", "Shaoxing wine"],
    steps: [
      "Mix ground beef with salt, optional egg, and white pepper; roll small meatballs.",
      "Brown meatballs; simmer in tomato sauce with garlic/onion 12–15 minutes until 74°C / 165°F.",
      "Serve over pasta.",
    ],
    zh: {
      name: "牛肉丸番茄意粉",
      steps: [
        "免治牛肉加鹽（可加蛋）和白胡椒搓小丸。",
        "煎香後放入番茄汁配蒜洋蔥炆 12 至 15 分鐘至全熟（74°C）。",
        "配意粉。",
      ],
    },
  },
  {
    id: "home-chicken-caesar-wrap",
    name: "Chicken Caesar-ish wrap",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Tortilla", "Lettuce"],
    optional: ["Mayonnaise", "Cheddar", "Lemon", "Garlic", "Salt"],
    steps: [
      "Cook chicken until 74°C / 165°F; slice. Mix mayo with lemon and garlic for dressing.",
      "Warm tortilla; fill with lettuce, chicken, dressing, and optional cheese.",
      "Roll tight and slice.",
    ],
    zh: {
      name: "雞肉凱撒風卷",
      steps: [
        "雞胸煮至 74°C 切片。蛋黃醬加檸檬蒜作醬。",
        "餅皮放生菜、雞、醬和芝士。",
        "捲緊切開。",
      ],
    },
  },
  {
    id: "home-western-veg-omelette",
    name: "Western veg omelette",
    cuisine: "Western",
    time: 12,
    servings: 1,
    need: ["Eggs", "Bell pepper", "Onion"],
    optional: ["Cheddar", "Ham", "Butter", "Salt"],
    steps: [
      "Beat 2–3 eggs. Soften diced pepper and onion in butter.",
      "Pour eggs; add optional ham/cheese. Cook until just set.",
      "Fold and plate.",
    ],
    zh: {
      name: "西式雜菜奄列",
      steps: [
        "打散 2 至 3 隻蛋。牛油炒軟燈籠椒洋蔥。",
        "倒蛋，可加火腿芝士，煮至刚凝固。",
        "對折上碟。",
      ],
    },
  },
  {
    id: "home-grilled-cheese-tomato",
    name: "Grilled cheese tomato",
    cuisine: "Western",
    time: 12,
    servings: 1,
    need: ["Zucchini", "Tomato", "Garlic", "Thai basil", "Cream cheese", "Butter", "Bread", "Cheddar"],
    optional: ["Olive oil", "Tomato paste", "Salt", "Vinegar"],
    steps: [
      "Butter bread outside. Fill with cheddar and tomato slices.",
      "Pan-grill both sides until golden and cheese melts.",
      "Rest 1 minute; cut.",
    ],
    zh: {
      name: "番茄芝士三文治",
      steps: [
        "麵包外塗牛油，夾芝士和番茄。",
        "兩面煎至金黃芝士融化。",
        "歇 1 分鐘切開。",
      ],
    },
  },  {
    id: "home-overnight-oats",
    name: "Overnight oats",
    cuisine: "Breakfast",
    time: 5,
    servings: 1,
    need: ["Oats", "Milk"],
    optional: ["Yogurt", "Honey", "Berries", "Banana"],
    steps: [
      "Mix ½ cup oats with ½ cup milk (and yogurt if using) in a jar.",
      "Refrigerate at least 4 hours or overnight.",
      "Top with fruit and honey before eating.",
    ],
    zh: {
      name: "隔夜燕麥",
      steps: [
        "半杯燕麥加半杯牛奶（可加乳酪）放入盒。",
        "雪櫃至少 4 小時或隔夜。",
        "食前加水果和蜜糖。",
      ],
    },
  },
  {
    id: "home-banana-peanut-toast",
    name: "Banana peanut toast",
    cuisine: "Breakfast",
    time: 8,
    servings: 1,
    need: ["Bread", "Banana", "Peanut butter"],
    optional: ["Honey", "Butter"],
    steps: [
      "Toast bread. Spread peanut butter.",
      "Top with banana slices.",
      "Optional honey drizzle.",
    ],
    zh: {
      name: "香蕉花生醬多士",
      steps: [
        "多士烤香塗花生醬。",
        "鋪香蕉片。",
        "可淋蜜糖。",
      ],
    },
  },
  {
    id: "home-tuna-white-bean-salad",
    name: "Tuna white bean salad",
    cuisine: "Western",
    time: 12,
    servings: 2,
    need: ["Canned tuna", "Beans", "Cucumber"],
    optional: ["Lemon", "Olive oil", "Onion", "Salt", "Lettuce"],
    steps: [
      "Drain tuna and beans; toss with diced cucumber and onion.",
      "Dress with olive oil, lemon, and salt.",
      "Serve over lettuce if using.",
    ],
    zh: {
      name: "吞拿魚白豆沙律",
      steps: [
        "吞拿魚和豆瀝乾，拌青瓜洋蔥粒。",
        "橄欖油、檸檬和鹽調味。",
        "可鋪生菜上。",
      ],
    },
  },
  {
    id: "home-creamy-mushroom-chicken",
    name: "Creamy mushroom chicken",
    cuisine: "Western",
    time: 30,
    servings: 2,
    need: ["Chicken thighs", "Mushroom", "Milk"],
    optional: ["Onion", "Garlic", "Butter", "Salt", "Flour", "Ginger", "Shaoxing wine", "Shallot", "Oyster sauce", "Soy sauce", "Sugar", "White pepper", "Cornstarch", "Sesame oil", "Cooking oil"],
    steps: [
      "Brown chicken until nearly done; remove. Sauté mushrooms and onion in butter.",
      "Sprinkle a little flour; whisk in milk into a light sauce.",
      "Return chicken; simmer until 74°C / 165°F and sauce thickens.",
    ],
    zh: {
      name: "忌廉蘑菇雞",
      steps: [
        "雞件煎至差不多熟盛起；牛油炒蘑菇洋蔥。",
        "撒少許麵粉，倒入牛奶打成淡汁。",
        "回雞炆至全熟（74°C）汁稠。",
      ],
    },
  },
]
