import type { Recipe } from "@/lib/recipes"

/** Auto-built cookable classics — original outlines, searchable names. */
export const MORE_W5F: Recipe[] = [
  {
    id: "home-shell-pasta-with-garlic-and-karl",
    name: "Shell Pasta with Garlic and Karl",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Tomato", "Parmesan", "Garlic", "Pine nuts", "Lime"],
    optional: ["Salt", "White pepper"],
    steps: [
      "Boil pasta in salted water until al dente; reserve ½ cup pasta water.",
      "Meanwhile sauté garlic/onion and Pasta in olive oil until just cooked.",
      "Toss pasta with the pan sauce and a splash of pasta water; adjust salt and finish with pepper or cheese if using.",
    ],
    zh: {
      name: "蒜香甘藍貝殼粉配合桃、松子仁",
      steps: [
        "意粉盐水煮至 al dente，留半杯麵水。",
        "另鑊用橄欖油炒蒜洋蔥及主料至熟。",
        "拌入意粉和少許麵水調味，可加芝士或黑胡椒。",
      ],
    },
  },
  {
    id: "home-simple-celery-soup",
    name: "Simple Celery Soup",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Celery", "Onion", "Garlic", "Milk"],
    optional: ["Chicken stock", "White pepper"],
    steps: [
      "Blanch Celery briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "西芹濃湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-simple-chicken-soup",
    name: "Simple Chicken Soup",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Carrots", "Onion", "Celery"],
    optional: ["Chicken stock", "Salt", "White pepper"],
    steps: [
      "Blanch Chicken thighs briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "簡易雞湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-smoked-pork-belly",
    name: "Smoked Pork Belly",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Ground pork"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Ground pork and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "田園煙燻豬腩",
      steps: [
        "準備田園煙燻豬腩材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-sous-vide-chicken-breast-with-c",
    name: "Sous Vide Chicken Breast with C",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Chicken thighs"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Chicken breast and Chicken thighs; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken breast and cook until cooked through (74°C / 165°F).",
      "Add Chicken thighs, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蘆筍配慢煮百里香雞胸",
      steps: [
        "準備蘆筍配慢煮百里香雞胸材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-sous-vide-chicken-breast-with-lemon-and-thyme",
    name: "Sous Vide Chicken Breast with Lemon and Thyme",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Lemon"],
    optional: ["Olive oil", "Salt"],
    steps: [
      "Prep Chicken breast and Chicken thighs plus Lemon; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken breast and cook until cooked through (74°C / 165°F).",
      "Add Chicken thighs and Lemon, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "檸檬百里香慢煮雞胸",
      steps: [
        "準備檸檬百里香慢煮雞胸嫩滑雞胸肉 健身常備菜材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-sous-vide-pork-chop-with-apple-and-honey-mustard",
    name: "Sous Vide Pork Chop with Apple and Honey Mustard Sauce",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Ground pork", "Pork chops"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Oyster sauce", "Cornstarch", "Shaoxing wine"],
    steps: [
      "Prep Ground pork and Pork chops; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Ground pork and cook until cooked through (74°C / 165°F).",
      "Add Pork chops, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "慢煮豬鞍配蘋果蜜糖芥末醬",
      steps: [
        "準備慢煮豬鞍配蘋果蜜糖芥末醬材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-spanish-garlic-prawn-tapas-gambas-al-ajillo",
    name: "Spanish Garlic Prawn Tapas Gambas Al Ajillo",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Garlic", "Cilantro", "Dried chili", "Lemon"],
    optional: ["Paprika", "Olive oil"],
    steps: [
      "Prep Shrimp and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "西班牙蒜油蝦",
      steps: [
        "準備西班牙蒜油蝦Gambas al材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-squid-ink-pasta-with-onion-and-mushroom",
    name: "Squid Ink Pasta with Onion and Mushroom",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Squid", "Pasta"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Olive oil", "Cheddar", "Onion"],
    steps: [
      "Boil pasta in salted water until al dente; reserve ½ cup pasta water.",
      "Meanwhile sauté garlic/onion and Squid in olive oil until just cooked.",
      "Toss pasta with the pan sauce and a splash of pasta water; adjust salt and finish with pepper or cheese if using.",
    ],
    zh: {
      name: "洋蔥磨菇醬炒墨汁意粉",
      steps: [
        "意粉盐水煮至 al dente，留半杯麵水。",
        "另鑊用橄欖油炒蒜洋蔥及主料至熟。",
        "拌入意粉和少許麵水調味，可加芝士或黑胡椒。",
      ],
    },
  },
  {
    id: "home-steam-snow-crab-female-with-vinegar-jelly",
    name: "Steam Snow Crab Female with Vinegar Jelly",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Arrange Eggs with Tomato on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "香箱蟹配蟹醋啫喱",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-clams-with-japanese-sake",
    name: "Steamed Clams with Japanese Sake",
    cuisine: "Japanese",
    time: 25,
    servings: 2,
    need: ["Clams", "Garlic", "Spring onion", "Butter"],
    optional: [],
    steps: [
      "Arrange Clams with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "清酒煮花甲王",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-clams-with-white-wine-and-garlic",
    name: "Steamed Clams with White Wine and Garlic",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Clams", "Garlic", "Tomato", "Butter"],
    optional: [],
    steps: [
      "Arrange Clams with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "白酒煮蜆",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-egg-white-with-milk-in-coconut-shell",
    name: "Steamed Egg White with Milk in Coconut Shell",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Milk", "Eggs"],
    optional: ["Sugar"],
    steps: [
      "Blanch Eggs briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "椰皇桃膠鮮奶燉蛋白配湯圓",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-steamed-egg-with-fresh-clams",
    name: "Steamed Egg with Fresh Clams",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Eggs", "Clams"],
    optional: [],
    steps: [
      "Arrange Clams with Eggs on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "花甲王蒸水蛋",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-japanese-hairy-crab",
    name: "Steamed Japanese Hairy Crab",
    cuisine: "Japanese",
    time: 25,
    servings: 2,
    need: ["Eggs", "Tomato"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Arrange Eggs with Tomato on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "清蒸毛蟹",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-lobster-with-garlic-butter-sauce",
    name: "Steamed Lobster with Garlic Butter Sauce",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Shrimp", "Garlic", "Butter"],
    optional: ["Sugar", "Soy sauce"],
    steps: [
      "Arrange Shrimp with vegetables on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "清蒸原隻龍蝦",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-milk-with-peach-resin",
    name: "Steamed Milk with Peach Resin",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Milk"],
    optional: ["Sugar"],
    steps: [
      "Arrange Eggs with Tomato on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "鮮奶燉桃膠",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-mussels-in-lemongrass-and-lime",
    name: "Steamed Mussels in Lemongrass and Lime",
    cuisine: "Thai",
    time: 25,
    servings: 2,
    need: ["Lemon", "Lime"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil", "Shaoxing wine"],
    steps: [
      "Arrange Lemon with Lime on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "香茅青檸藍青口",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-mussels-with-white-wine-and-cream",
    name: "Steamed Mussels with White Wine and Cream",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Mussels", "Bacon", "Tomato", "Onion", "Garlic", "Cream", "Butter"],
    optional: [],
    steps: [
      "Arrange Eggs with Tomato on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "白酒忌廉煮藍青口",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-mussels-with-wine-and-saffron",
    name: "Steamed Mussels with Wine and Saffron",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Mussels", "Shallot", "Garlic", "Tomato", "Cilantro", "Cream"],
    optional: [],
    steps: [
      "Arrange Salmon with White fish on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "番紅花白酒煮青口配三文魚",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-new-zealand-mussels-in-white-wine",
    name: "Steamed New Zealand Mussels in White Wine",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Mussels", "Onion", "Garlic", "Tomato", "Butter"],
    optional: [],
    steps: [
      "Arrange Eggs with Tomato on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "白酒煮青口",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-prawn-over-lotus-rice",
    name: "Steamed Prawn Over Lotus Rice",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Shrimp", "Cooked rice", "Eggs", "Garlic", "Spring onion", "Cilantro"],
    optional: ["Sugar", "Soy sauce"],
    steps: [
      "Arrange Shrimp with Lotus root on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "籠仔金銀蒜蒸蝦荷葉飯",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-rice-with-giant-grouper-in-lotus-leaf",
    name: "Steamed Rice with Giant Grouper in Lotus Leaf",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Dried mushrooms", "Garlic", "Spring onion", "Cooked rice", "Eggs", "Ginger"],
    optional: ["Soy sauce", "Oyster sauce", "Sugar", "Cornstarch", "White pepper"],
    steps: [
      "Arrange Lotus root with Cooked rice on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "籠仔蒸龍躉荷葉飯",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-stewed-beef-brisket-in-chu-hou-sauce-with-japane",
    name: "Stewed Beef Brisket in Chu Hou Sauce with Japanese Daikon",
    cuisine: "Japanese",
    time: 45,
    servings: 3,
    need: ["Beef brisket", "Ginger", "Spring onion", "Garlic", "Hoisin sauce"],
    optional: ["Shaoxing wine", "Oyster sauce", "Sugar", "Salt", "Cornstarch"],
    steps: [
      "Cut Beef steak and Beef brisket into pieces; lightly brown Beef steak in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Beef steak is tender; reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "柱侯蘿蔔炆牛腩",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-stir-fried-crab-with-ginger-and-spring-onion",
    name: "Stir Fried Crab with Ginger and Spring Onion",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Spring onion", "Ginger", "Eggs"],
    optional: ["Salt", "Sugar"],
    steps: [
      "Prep Tofu and Pak choi; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Tofu and cook until just cooked.",
      "Add Pak choi, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "家鄉薑蔥炒蟹",
      steps: [
        "準備家鄉薑蔥炒蟹材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-stuffed-chicken-cushion",
    name: "Stuffed Chicken Cushion",
    cuisine: "Western",
    time: 40,
    servings: 2,
    need: ["Bacon", "Orange", "Onion", "Mushroom", "Bread", "Eggs", "Carrots"],
    optional: [],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "焗釀無骨雞咕𠱸",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-tamagoyaki-using-vermicular-egg-and-toast-pan",
    name: "Tamagoyaki Using Vermicular Egg and Toast Pan",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Eggs"],
    optional: ["Chicken stock", "Soy sauce", "Sugar"],
    steps: [
      "Prep Eggs and Bread; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add Bread, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "玉子燒",
      steps: [
        "準備玉子燒綿滑口感的玉子燒有辦法材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-the-best-pan-seared-chicken-breast",
    name: "The Best Pan Seared Chicken Breast",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Chicken breast"],
    optional: ["Salt", "White pepper"],
    steps: [
      "Prep Chicken breast and Chicken thighs; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "煎嫩滑雞胸 配凱撒沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-tofu-salad-with-sesame-dressing",
    name: "Tofu Salad with Sesame Dressing",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Silken tofu", "Tomato"],
    optional: ["Sesame seeds"],
    steps: [
      "Prep Tofu and vegetables; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "豆腐麻醬沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-tomato-and-beetroot-salad-in-zucchini-ring",
    name: "Tomato and Beetroot Salad in Zucchini Ring",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Tomato", "Zucchini"],
    optional: ["Cooking oil", "Salt", "Soy sauce", "Garlic", "Ginger", "Spring onion", "White pepper", "Sugar", "Sesame oil"],
    steps: [
      "Prep Tomato and Zucchini; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "意大利黃瓜圈野菜沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-tomato-basil-soup",
    name: "Tomato Basil Soup",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Tomato", "Thai basil", "Carrots", "Onion", "Cream"],
    optional: ["Chicken stock"],
    steps: [
      "Blanch Tomato briefly if it is meat; rinse. Cut vegetables into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "羅勒番茄濃湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-tomato-burrata-cheese-salad",
    name: "Tomato Burrata Cheese Salad",
    cuisine: "Western",
    time: 15,
    servings: 2,
    need: ["Tomato", "Mozzarella"],
    optional: ["Olive oil", "Vinegar", "Salt", "White pepper"],
    steps: [
      "Prep Tomato and vegetables; cook any protein through and cool slightly.",
      "Whisk a dressing of soy/vinegar/sesame oil (or lemon + olive oil).",
      "Toss everything lightly; serve cool or room temperature.",
    ],
    zh: {
      name: "蕃茄水牛芝士沙律",
      steps: [
        "準備材料；蛋白質煮熟放涼。",
        "用生抽／醋／麻油（或檸檬橄欖油）調汁。",
        "拌匀後冷食或室温食用。",
      ],
    },
  },
  {
    id: "home-tomato-chicken-stew",
    name: "Tomato Chicken Stew",
    cuisine: "Chinese",
    time: 45,
    servings: 3,
    need: ["Chicken thighs", "Carrots", "Onion", "Garlic", "Celery", "Tomato", "Flour"],
    optional: ["Chicken stock", "Tomato paste"],
    steps: [
      "Cut Chicken thighs and Tomato into pieces; lightly brown Chicken thighs in a little oil.",
      "Add garlic, 1.5 tbsp soy sauce, a pinch of sugar, and enough water to come halfway up the ingredients.",
      "Cover and braise 20–30 minutes until Chicken thighs is tender until cooked through (74°C / 165°F); reduce sauce and finish with spring onion.",
    ],
    zh: {
      name: "番茄燉雞",
      steps: [
        "材料切件，蛋白質略煎上色。",
        "下蒜、1.5 湯匙生抽、少許糖，加水至材料一半高度。",
        "加蓋炆 20 至 30 分鐘至軟，收汁後撒蔥。",
      ],
    },
  },
  {
    id: "home-typhoon-shelter-style-baked-chicken",
    name: "Typhoon Shelter Style Baked Chicken",
    cuisine: "Vietnamese",
    time: 40,
    servings: 2,
    need: ["Garlic", "Bread", "Dried chili"],
    optional: ["Salt", "Olive oil"],
    steps: [
      "Heat oven to 200°C. Toss Chicken thighs and vegetables with a little oil, salt, and garlic.",
      "Spread on a tray and roast 20–30 minutes until browned and cooked through.",
      "Finish with soy/honey glaze or herbs if you like; rest 2 minutes before serving.",
    ],
    zh: {
      name: "免炸避風塘烤雞件",
      steps: [
        "焗爐预热 200°C。材料拌油、鹽、蒜。",
        "铺盘焗 20 至 30 分鐘至上色熟透。",
        "可刷生抽蜜糖汁，稍候 2 分鐘再上碟。",
      ],
    },
  },
  {
    id: "home-kai-lan-fried-rice-with-shrimps",
    name: "Kai-Lan Fried Rice with Shrimps",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Cooked rice", "Shrimp", "Onion", "Eggs", "Gai lan", "Spring onion"],
    optional: ["Salt"],
    steps: [
      "Loosen cold cooked rice; beat 2 eggs if eggs are in the dish. Dice other mix-ins small.",
      "Scramble eggs in a hot oiled pan; push aside or remove. Stir-fry aromatics and proteins until cooked.",
      "Add rice and 1–2 tbsp soy sauce; toss on high heat until hot and lightly toasted. Finish with spring onion.",
    ],
    zh: {
      name: "鮮蝦芥蘭炒飯",
      steps: [
        "隔夜飯撥散；如用蛋可先打散。配料切細。",
        "熱鑊炒蛋盛起；爆香蒜薑及蛋白質炒熟。",
        "下飯加 1 至 2 湯匙生抽大火炒香，撒蔥起鑊。",
      ],
    },
  },
  {
    id: "home-shrimp-egg-rice-noodles",
    name: "Shrimp Egg Rice Noodles",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Wide rice noodles", "Shrimp", "Eggs", "Spring onion", "Garlic", "Mozzarella"],
    optional: ["Chicken stock", "Shaoxing wine", "White pepper", "Cornstarch", "Olive oil", "Salt"],
    steps: [
      "Blanch noodles until just tender; drain well. Prep proteins and veg in strips.",
      "Stir-fry Shrimp with garlic until just cooked; add veg and toss briefly.",
      "Add noodles with 1 tbsp soy sauce and 1 tsp dark soy or oyster sauce if using; toss until coated and hot.",
    ],
    zh: {
      name: "滑蛋蝦仁炒河",
      steps: [
        "麵類焯至刚軟瀝乾；肉菜切絲。",
        "爆香蒜後下蛋白質炒至剛熟，再下蔬菜。",
        "下面加 1 湯匙生抽和少許老抽／蠔油炒匀至熱透。",
      ],
    },
  },
  {
    id: "home-cabbage-with-chicken-and-fried-tofu",
    name: "Cabbage with Chicken and Fried Tofu",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Cauliflower", "Chicken breast", "Beans", "Garlic", "Spring onion", "Mozzarella"],
    optional: ["Chicken stock", "Olive oil", "Cornstarch", "White pepper"],
    steps: [
      "Prep Chicken thighs and Tofu plus Cabbage; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add Tofu and Cabbage, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "油豆腐椰菜炒雞絲",
      steps: [
        "準備油豆腐椰菜炒雞絲材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-steamed-egg-white-and-tofu-with-mixed-seafood",
    name: "Steamed Egg White and Tofu with Mixed Seafood",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Silken tofu", "White fish", "Ground pork", "Shrimp", "Eggs", "Spring onion"],
    optional: ["Chicken stock", "Salt", "Shaoxing wine"],
    steps: [
      "Arrange Tofu with Eggs on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "美肌•燉蛋白豆腐",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-steamed-meat-loaf-with-white-bates",
    name: "Steamed Meat Loaf with White Bates",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Ground pork", "Cooked rice", "Spring onion", "Ginger"],
    optional: ["Shaoxing wine", "Cornstarch", "Soy sauce", "White pepper", "Salt"],
    steps: [
      "Arrange Ground pork with White fish on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through (poultry/mince to 74°C / 165°F).",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "白飯魚蒸肉餅",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟（肉類至 74°C / 165°F）。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-egg-whites-with-shrimps",
    name: "Egg Whites with Shrimps",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Eggs", "Milk", "Spring onion"],
    optional: ["Shaoxing wine", "White pepper", "Salt", "Cornstarch"],
    steps: [
      "Prep Shrimp and Eggs; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Shrimp and cook until just cooked.",
      "Add Eggs, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "蛋白炒蝦仁",
      steps: [
        "準備蛋白炒蝦仁材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-steamed-eggs-with-clams-and-clear-noodles",
    name: "Steamed Eggs with Clams and Clear Noodles",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Eggs", "Glass noodles", "Clams", "Mozzarella", "Spring onion"],
    optional: ["Salt", "White pepper"],
    steps: [
      "Arrange Clams with Eggs on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "粉絲蜆蒸水蛋",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-cute-little-chick-bento",
    name: "Cute Little Chick Bento",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Cooked rice", "Ham", "Nori", "Cheddar", "Bell pepper", "Carrots"],
    optional: ["Honey"],
    steps: [
      "Prep Eggs and vegetables; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Eggs and cook until just cooked.",
      "Add vegetables, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "小雞蛋包飯 【親子食堂】",
      steps: [
        "準備小雞蛋包飯 【親子食堂】材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-portuguese-chicken-rice",
    name: "Portuguese Chicken Rice",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Chicken thighs", "Rice", "Potato", "Coconut milk", "Carrots", "Bell pepper", "Onion", "Garlic", "Cheddar", "Cooked rice", "Eggs"],
    optional: ["Turmeric", "Cumin", "White pepper", "Cornstarch", "Chicken stock", "Olive oil", "Salt"],
    steps: [
      "Prep Chicken thighs and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Chicken thighs and cook until cooked through (74°C / 165°F).",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "葡國雞飯",
      steps: [
        "準備葡國雞飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至全熟（74°C / 165°F）。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-steamed-eggplant-with-dried-shrimps",
    name: "Steamed Eggplant with Dried Shrimps",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Eggplant", "Shrimp", "Cooked rice", "Spring onion", "Garlic"],
    optional: ["Sesame oil", "Salt"],
    steps: [
      "Arrange Shrimp with White fish on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "銀魚仔蝦米蒸茄子",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-mushroom-with-beef-over-rice",
    name: "Mushroom with Beef over Rice",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Mozzarella", "Mushroom", "Onion", "Beef steak", "Garlic", "Rice"],
    optional: ["Sesame oil", "Sugar", "Cornstarch", "Chicken stock", "Soy sauce"],
    steps: [
      "Prep Beef steak and Mushroom plus Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Mushroom and Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "鮮菇繪牛肉飯",
      steps: [
        "準備鮮菇繪牛肉飯材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-beef-rice-noodles-sauce",
    name: "Beef Rice Noodles - Sauce",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Wide rice noodles", "Beef steak", "Lettuce", "Garlic", "Mozzarella"],
    optional: ["Chicken stock", "Shaoxing wine", "Soy sauce", "Cornstarch", "Salt", "White pepper"],
    steps: [
      "Prep Beef steak and Cooked rice; cut into bite-size pieces. Mix a quick sauce with 1 tbsp soy sauce, 1 tsp oyster sauce if using, and a splash of water.",
      "Heat a wok or pan with a little oil; stir-fry aromatics (garlic/ginger), then add Beef steak and cook until just cooked.",
      "Add Cooked rice, toss 2–3 minutes until crisp-tender, then pour in the sauce and finish with spring onion.",
    ],
    zh: {
      name: "濕炒牛河",
      steps: [
        "準備濕炒牛河材料：將主要食材切件。用 1 湯匙生抽、1 茶匙蠔油（可選）和少許水調芡。",
        "熱鑊下油爆香蒜薑，下主要蛋白質至剛熟。",
        "下蔬菜快炒 2 至 3 分鐘，倒入芡汁炒匀，可撒蔥花起鑊。",
      ],
    },
  },
  {
    id: "home-fish-maw-cream-corn-soup",
    name: "Fish Maw Cream Corn Soup",
    cuisine: "Cantonese",
    time: 45,
    servings: 3,
    need: ["Butter", "Mozzarella", "Spring onion", "Ginger", "Ham"],
    optional: ["Shaoxing wine", "Chicken stock", "Salt", "Cornstarch"],
    steps: [
      "Blanch White fish briefly if it is meat; rinse. Cut Corn into chunks.",
      "Simmer with ginger and about 1.2–1.5 L water (or stock) 25–35 minutes until flavours come together.",
      "Season with salt and white pepper; add leafy bits in the last 2 minutes if using.",
    ],
    zh: {
      name: "魚肚玉米湯",
      steps: [
        "肉類可先焯水過冷河；蔬菜切件。",
        "加薑片和約 1.2 至 1.5 升水（或湯底）煮 25 至 35 分鐘。",
        "加鹽和白胡椒調味；葉菜最後 2 分鐘才下。",
      ],
    },
  },
  {
    id: "home-seaweed-siu-mais-chinese-new-year-recipe",
    name: "Seaweed Siu Mais",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Rice", "Ground pork", "Spring onion", "Ginger", "Onion", "Nori"],
    optional: ["Soy sauce", "Salt", "Chicken stock", "Olive oil", "Cornstarch"],
    steps: [
      "Arrange Eggs with Tomato on a heatproof plate; scatter ginger and spring onion.",
      "Steam over high heat 10–15 minutes until cooked through.",
      "Drizzle 1 tbsp soy sauce and a little sesame oil; optional hot oil over aromatics before serving.",
    ],
    zh: {
      name: "紫菜燒賣健康年菜蒸蒸日上",
      steps: [
        "材料鋪在碟上，加薑絲蔥絲。",
        "大火蒸 10 至 15 分鐘至熟。",
        "淋 1 湯匙生抽和少許麻油，可潑熱油。",
      ],
    },
  },
  {
    id: "home-pumpkin-stir-fry-rice-noodles",
    name: "Pumpkin Stir Fry Rice Noodles",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Pumpkin", "Rice vermicelli", "Onion", "Shrimp", "Mozzarella"],
    optional: ["Chicken stock", "Salt", "Sugar", "White pepper"],
    steps: [
      "Blanch noodles until just tender; drain well. Prep proteins and veg in strips.",
      "Stir-fry Pumpkin with garlic until just cooked; add veg and toss briefly.",
      "Add noodles with 1 tbsp soy sauce and 1 tsp dark soy or oyster sauce if using; toss until coated and hot.",
    ],
    zh: {
      name: "瘦身•南瓜炒米粉",
      steps: [
        "麵類焯至刚軟瀝乾；肉菜切絲。",
        "爆香蒜後下蛋白質炒至剛熟，再下蔬菜。",
        "下面加 1 湯匙生抽和少許老抽／蠔油炒匀至熱透。",
      ],
    },
  },
  {
    id: "home-shredded-pork-fried-noodles",
    name: "Shredded Pork Fried Noodles",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Bean sprouts", "Dried mushrooms", "Garlic", "Ginger", "Mozzarella"],
    optional: ["Chicken stock", "Shaoxing wine", "White pepper", "Salt", "Sugar", "Cornstarch"],
    steps: [
      "Blanch noodles until just tender; drain well. Prep proteins and veg in strips.",
      "Stir-fry Ground pork with garlic until cooked through (74°C / 165°F); add veg and toss briefly.",
      "Add noodles with 1 tbsp soy sauce and 1 tsp dark soy or oyster sauce if using; toss until coated and hot.",
    ],
    zh: {
      name: "肉絲炒麵",
      steps: [
        "麵類焯至刚軟瀝乾；肉菜切絲。",
        "爆香蒜後下蛋白質炒至全熟（74°C / 165°F），再下蔬菜。",
        "下面加 1 湯匙生抽和少許老抽／蠔油炒匀至熱透。",
      ],
    },
  },
]
