import type { Recipe } from "@/lib/recipes"

/** Extra cookable classics from Made With Lau, Lee Kum Kee HK, and BBC Food. */
export const MORE_EXTRA: Recipe[] = [
  {
    id: "home-chow-mein",
    name: "Chicken chow mein",
    cuisine: "Cantonese",
    time: 30,
    servings: 2,
    need: ["Noodles", "Chicken thighs", "Cabbage"],
    optional: ["Carrots", "Bean sprouts", "Onion", "Oyster sauce", "Soy sauce", "Garlic"],
    steps: [
      "Slice chicken and toss with soy sauce. Shred cabbage; boil or soak noodles until just tender.",
      "Stir-fry chicken until cooked through (74°C / 165°F); remove. Stir-fry cabbage and veg until crisp-tender.",
      "Add noodles with oyster sauce and soy sauce; toss until hot and glossy. Return chicken and bean sprouts.",
    ],
    zh: {
      name: "雞絲炒麵",
      steps: [
        "雞肉切絲加生抽略醃；椰菜切絲，麵煮或浸至軟。",
        "雞絲炒至全熟（74°C）盛起；大火炒椰菜及蔬菜至爽脆。",
        "下面加蠔油生抽炒熱，回雞和芽菜拌勻。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/chow-mein",
    sourceName: "Made With Lau",
  },
  {
    id: "home-singapore-noodles",
    name: "Singapore noodles",
    cuisine: "Hong Kong",
    time: 25,
    servings: 2,
    need: ["Rice vermicelli", "Eggs", "Shrimp"],
    optional: ["Chicken breast", "Bean sprouts", "Onion", "Spring onion", "Soy sauce"],
    steps: [
      "Soak rice vermicelli until soft; drain. Beat eggs; prep shrimp (and chicken if using).",
      "Scramble eggs and set aside. Stir-fry chicken until cooked through if using, then shrimp until opaque and pink.",
      "Add noodles with a pinch of curry powder or soy sauce, toss in veg and eggs until steaming hot.",
    ],
    zh: {
      name: "星洲炒米",
      steps: [
        "米粉浸軟瀝乾；打散蛋；準備蝦（可加雞絲）。",
        "先炒蛋盛起；雞肉炒至全熟，蝦炒至轉色熟透。",
        "下米粉加咖喱粉或生抽，拌入蔬菜和蛋炒熱。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/singapore-noodles",
    sourceName: "Made With Lau",
  },
  {
    id: "home-pan-fried-rice-noodles",
    name: "Pan-fried rice noodles",
    cuisine: "Hong Kong",
    time: 30,
    servings: 2,
    need: ["Rice vermicelli", "Chicken breast"],
    optional: ["Shrimp", "Carrots", "Bean sprouts", "Snow peas", "Oyster sauce", "Garlic", "Ginger"],
    steps: [
      "Soak rice vermicelli; drain well. Slice chicken; prep shrimp and veg.",
      "Pan-fry noodles in a thin oil layer until lightly crisp on spots; set aside. Stir-fry chicken until cooked through (74°C / 165°F), then shrimp until opaque.",
      "Toss veg with oyster sauce; serve the stir-fry over the noodles.",
    ],
    zh: {
      name: "乾炒米粉",
      steps: [
        "米粉浸軟瀝乾；雞肉切片；準備蝦和蔬菜。",
        "少油把米粉煎至微脆盛起。雞片炒至全熟（74°C），蝦炒至熟透。",
        "蔬菜加蠔油快炒，鋪在米粉上。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/pan-fried-rice-noodles",
    sourceName: "Made With Lau",
  },
  {
    id: "home-egg-foo-young",
    name: "Egg foo young",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Eggs", "Bean sprouts", "Shrimp"],
    optional: ["Onion", "Spring onion", "Oyster sauce", "Soy sauce", "Cornstarch"],
    steps: [
      "Beat 4 eggs. Quickly stir-fry shrimp until just opaque; mix with bean sprouts and onion into the eggs.",
      "Shallow-fry spoonfuls of the egg mix until golden and set on both sides.",
      "Optional gravy: simmer oyster sauce, soy sauce, and water thickened with cornstarch; pour over.",
    ],
    zh: {
      name: "芙蓉蛋",
      steps: [
        "打散 4 隻蛋。蝦略炒至轉色，連芽菜洋蔥拌入蛋液。",
        "半煎炸至兩面金黃熟透。",
        "可另煮蠔油生抽芡汁淋上。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/egg-foo-young",
    sourceName: "Made With Lau",
  },
  {
    id: "home-stir-fried-bok-choy",
    name: "Stir-fried bok choy",
    cuisine: "Cantonese",
    time: 12,
    servings: 2,
    need: ["Pak choi", "Garlic"],
    optional: ["Soy sauce", "Sesame oil", "Sugar"],
    steps: [
      "Trim and wash pak choi; separate thick stems from leaves. Slice garlic.",
      "Stir-fry garlic, then stems 30–60 seconds; add leaves and a splash of water.",
      "Season lightly and finish with sesame oil if using. Serve at once.",
    ],
    zh: {
      name: "蒜蓉炒白菜",
      steps: [
        "白菜洗淨，梗葉分開；蒜切蓉。",
        "爆香蒜蓉，先炒梗再下葉，加少許水。",
        "調味，可淋麻油即上碟。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/stir-fried-bok-choy",
    sourceName: "Made With Lau",
  },
  {
    id: "home-orange-chicken",
    name: "Orange chicken",
    cuisine: "Chinese",
    time: 35,
    servings: 2,
    need: ["Chicken breast", "Orange"],
    optional: ["Garlic", "Ginger", "Soy sauce", "Vinegar", "Sugar", "Cornstarch", "Eggs"],
    steps: [
      "Cut chicken into bite-size pieces; toss with a little cornstarch and egg white if using.",
      "Pan-fry until golden and cooked through (74°C / 165°F). Squeeze orange juice; mix with soy, vinegar, sugar.",
      "Simmer sauce with garlic/ginger, thicken with cornstarch slurry, toss chicken until coated.",
    ],
    zh: {
      name: "鮮橙雞柳",
      steps: [
        "雞胸切件，可裹生粉或蛋白。",
        "煎至金黃全熟（74°C）。榨橙汁，加生抽、醋、糖拌勻。",
        "爆香蒜薑，倒入醬汁勾芡，拌勻雞件。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/orange-chicken",
    sourceName: "Made With Lau",
  },
  {
    id: "home-shrimp-broccoli",
    name: "Shrimp and broccoli",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Shrimp", "Broccoli"],
    optional: ["Garlic", "Ginger", "Oyster sauce", "Soy sauce", "Cornstarch"],
    steps: [
      "Cut broccoli into florets; peel shrimp if needed.",
      "Blanch or stir-fry broccoli until bright green. Stir-fry shrimp until opaque and pink throughout.",
      "Toss together with oyster sauce, soy sauce, and a splash of water until glossy.",
    ],
    zh: {
      name: "西蘭花炒蝦仁",
      steps: [
        "西蘭花切小朵；蝦去殼（如需要）。",
        "西蘭花焯或快炒至翠綠；蝦炒至全熟轉色。",
        "加蠔油生抽和少許水炒至上芡。",
      ],
    },
  },
  {
    id: "home-garlic-shrimp",
    name: "Garlic shrimp",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Shrimp", "Garlic"],
    optional: ["Ginger", "Spring onion", "Soy sauce", "Shaoxing wine"],
    steps: [
      "Pat shrimp dry; mince lots of garlic.",
      "Stir-fry garlic (and ginger) briefly, then shrimp until opaque and cooked through.",
      "Splash soy sauce or Shaoxing wine; finish with spring onion.",
    ],
    zh: {
      name: "蒜蓉蝦",
      steps: [
        "蝦抹乾；多量蒜切蓉。",
        "爆香蒜薑，下蝦炒至全熟轉色。",
        "贊酒或生抽，撒蔥花。",
      ],
    },
  },
  {
    id: "home-tofu-shrimp",
    name: "Tofu with shrimp",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Tofu", "Shrimp"],
    optional: ["Garlic", "Spring onion", "Oyster sauce", "Soy sauce"],
    steps: [
      "Cube tofu; pat shrimp dry.",
      "Pan-fry tofu until lightly golden; set aside. Stir-fry shrimp until opaque.",
      "Return tofu with oyster sauce and a little water; simmer gently and finish with spring onion.",
    ],
    zh: {
      name: "蝦仁豆腐",
      steps: [
        "豆腐切丁；蝦抹乾。",
        "豆腐煎至微黃盛起；蝦炒至熟透。",
        "回豆腐加蠔油和水略煮，撒蔥花。",
      ],
    },
  },
  {
    id: "home-west-lake-beef-soup",
    name: "West Lake beef soup",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Ground beef", "Eggs"],
    optional: ["Cornstarch", "Soy sauce", "White pepper", "Spring onion"],
    steps: [
      "Brown ground beef in a pot until cooked through; add 3–4 cups water and simmer 5 minutes.",
      "Thicken lightly with cornstarch slurry. Softly beat 2 eggs and drizzle in while stirring for ribbons.",
      "Season with soy sauce and white pepper; finish with spring onion.",
    ],
    zh: {
      name: "西湖牛肉羹",
      steps: [
        "免治牛肉炒至全熟，加水三至四杯煮 5 分鐘。",
        "生粉水略勾芡；邊攪邊倒入打散雞蛋成蛋花。",
        "生抽白胡椒調味，撒蔥花。",
      ],
    },
  },
  {
    id: "home-hot-sour-soup",
    name: "Hot and sour soup",
    cuisine: "Chinese",
    time: 25,
    servings: 2,
    need: ["Tofu", "Eggs", "Mushroom"],
    optional: ["Vinegar", "Soy sauce", "White pepper", "Cornstarch", "Spring onion", "Carrots"],
    steps: [
      "Cube tofu; slice mushrooms. Bring 4 cups water or stock to a simmer with soy sauce and white pepper.",
      "Add tofu, mushroom, and carrot shreds; simmer 5 minutes. Thicken with cornstarch slurry.",
      "Drizzle beaten egg for ribbons; finish with vinegar to taste and spring onion.",
    ],
    zh: {
      name: "酸辣湯",
      steps: [
        "豆腐切丁，蘑菇切片。水或湯底加生抽白胡椒煮滾。",
        "下豆腐蘑菇紅蘿蔔絲煮 5 分鐘，生粉勾芡。",
        "倒入蛋液成蛋花，加醋調味，撒蔥花。",
      ],
    },
  },
  {
    id: "home-lo-mein",
    name: "Vegetable lo mein",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Noodles", "Cabbage", "Carrots"],
    optional: ["Bean sprouts", "Spring onion", "Soy sauce", "Oyster sauce", "Garlic"],
    steps: [
      "Cook noodles until just tender; drain. Shred cabbage and carrots.",
      "Stir-fry garlic and veg until crisp-tender.",
      "Add noodles with soy and oyster sauce; toss until hot. Finish with bean sprouts.",
    ],
    zh: {
      name: "蔬菜撈麵",
      steps: [
        "麵煮至剛好熟瀝乾；椰菜紅蘿蔔切絲。",
        "爆香蒜蓉炒蔬菜至爽脆。",
        "下面加生抽蠔油炒熱，可加芽菜。",
      ],
    },
  },
  {
    id: "home-chicken-corn-soup",
    name: "Chicken corn soup",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Corn", "Eggs"],
    optional: ["Cornstarch", "Spring onion", "White pepper", "Soy sauce"],
    steps: [
      "Mince or finely dice chicken; simmer in 3 cups water until cooked through (74°C / 165°F).",
      "Add corn and simmer 3 minutes; thicken lightly with cornstarch.",
      "Drizzle beaten egg while stirring; season and finish with spring onion.",
    ],
    zh: {
      name: "雞茸粟米湯",
      steps: [
        "雞肉剁碎，加水三杯煮至全熟（74°C）。",
        "下粟米煮 3 分鐘，生粉略勾芡。",
        "倒入蛋液成蛋花，調味撒蔥花。",
      ],
    },
  },
  {
    id: "home-steamed-pork-patty",
    name: "Steamed pork patty",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Ground pork"],
    optional: ["Soy sauce", "Cornstarch", "Spring onion", "White pepper"],
    steps: [
      "Mix ground pork with soy sauce, cornstarch, and a splash of water until sticky.",
      "Press into a shallow dish; steam over high heat 12–15 minutes until cooked through (74°C / 165°F).",
      "Rest briefly; spoon pan juices over and finish with spring onion.",
    ],
    zh: {
      name: "蒸肉餅",
      steps: [
        "免治豬肉加生抽生粉和少許水拌至起膠。",
        "鋪平深碟，大火蒸 12 至 15 分鐘至全熟（74°C）。",
        "淋原汁，撒蔥花。",
      ],
    },
  },
  {
    id: "home-claypot-style-rice",
    name: "Claypot-style chicken rice",
    cuisine: "Hong Kong",
    time: 40,
    servings: 2,
    need: ["Rice", "Chicken thighs", "Chinese sausage"],
    optional: ["Ginger", "Spring onion", "Soy sauce", "Oyster sauce", "Mushroom"],
    steps: [
      "Rinse rice and start cooking as usual. Slice chicken and sausage; marinate chicken with soy sauce.",
      "When rice is almost done, lay chicken and sausage on top; cover until chicken is cooked through (74°C / 165°F).",
      "Drizzle soy/oyster sauce; rest 5 minutes and stir. Finish with spring onion.",
    ],
    zh: {
      name: "煲仔雞飯風",
      steps: [
        "米洗淨開煮；雞脾切片加生抽醃，臘腸切片。",
        "飯將熟時鋪上雞和臘腸，加蓋煮至雞全熟（74°C）。",
        "淋豉油蠔油，焗 5 分鐘拌勻，撒蔥花。",
      ],
    },
  },
  {
    id: "home-beef-tomato-noodles",
    name: "Tomato beef noodles",
    cuisine: "Hong Kong",
    time: 30,
    servings: 2,
    need: ["Beef steak", "Tomato", "Noodles"],
    optional: ["Onion", "Soy sauce", "Sugar", "Cornstarch", "Spring onion"],
    steps: [
      "Slice beef thin; toss with soy and cornstarch. Cook noodles; set aside.",
      "Stir-fry beef until just cooked; remove. Cook tomato and onion until saucy.",
      "Return beef, season, and serve over noodles with spring onion.",
    ],
    zh: {
      name: "番茄牛肉麵",
      steps: [
        "牛肉切薄片加生抽生粉；麵煮好盛起。",
        "牛肉快炒至熟盛起；番茄洋蔥炒至出汁。",
        "回牛肉調味，鋪在麵上撒蔥花。",
      ],
    },
  },
  {
    id: "home-pork-cabbage",
    name: "Pork and cabbage stir-fry",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Pork chops", "Cabbage"],
    optional: ["Garlic", "Soy sauce", "Chili oil", "Spring onion"],
    steps: [
      "Slice pork thin; shred cabbage.",
      "Stir-fry pork until cooked through (74°C / 165°F); remove. Stir-fry cabbage until wilted.",
      "Return pork with soy sauce; toss. Finish with chili oil or spring onion if you like.",
    ],
    zh: {
      name: "豬肉炒椰菜",
      steps: [
        "豬扒切薄片，椰菜切絲。",
        "豬肉炒至全熟（74°C）盛起；炒椰菜至軟。",
        "回肉加生抽拌勻，可加辣椒油蔥花。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/twice-cooked-pork",
    sourceName: "Made With Lau",
  },
  {
    id: "home-shrimp-noodle-soup",
    name: "Shrimp noodle soup",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Noodles", "Shrimp", "Pak choi"],
    optional: ["Garlic", "Soy sauce", "Sesame oil", "Spring onion", "White pepper"],
    steps: [
      "Boil noodles; blanch pak choi. Warm 3 cups water or stock.",
      "Poach shrimp in the broth until opaque and pink.",
      "Assemble noodles and greens in bowls; ladle broth and shrimp over. Season lightly.",
    ],
    zh: {
      name: "鮮蝦湯麵",
      steps: [
        "煮麵，焯白菜。水或湯底煮熱。",
        "蝦放入湯內煮至全熟轉色。",
        "碗內放麵和菜，淋湯鋪蝦，調味。",
      ],
    },
    sourceUrl: "https://www.madewithlau.com/recipes/wonton-noodle-soup",
    sourceName: "Made With Lau",
  },
  {
    id: "home-honey-garlic-chicken",
    name: "Honey garlic chicken",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Chicken thighs", "Garlic", "Honey"],
    optional: ["Soy sauce", "Vinegar", "Spring onion", "Cornstarch"],
    steps: [
      "Cut chicken into pieces; brown in a pan until cooked through (74°C / 165°F).",
      "Add minced garlic, then honey, soy sauce, and a splash of vinegar or water.",
      "Simmer until glossy; thicken with cornstarch if needed. Finish with spring onion.",
    ],
    zh: {
      name: "蜜糖蒜香雞",
      steps: [
        "雞脾切件煎至全熟（74°C）。",
        "下蒜蓉，加蜜糖生抽和少許醋或水。",
        "煮至稠亮，可勾薄芡，撒蔥花。",
      ],
    },
  },
  {
    id: "home-lemon-chicken",
    name: "Lemon chicken",
    cuisine: "Chinese",
    time: 30,
    servings: 2,
    need: ["Chicken breast", "Lemon"],
    optional: ["Soy sauce", "Sugar", "Cornstarch", "Eggs", "Garlic"],
    steps: [
      "Slice chicken; coat lightly with cornstarch (and egg if using). Pan-fry until cooked through (74°C / 165°F).",
      "Mix lemon juice with a little sugar, soy sauce, and water.",
      "Simmer sauce, thicken lightly, and coat the chicken.",
    ],
    zh: {
      name: "檸檬雞",
      steps: [
        "雞胸切片，可裹生粉煎至全熟（74°C）。",
        "檸檬汁加糖、生抽和水拌勻。",
        "煮醬勾芡，淋在雞上。",
      ],
    },
  },
  {
    id: "home-steamed-tofu-pork",
    name: "Steamed tofu with minced pork",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Tofu", "Ground pork"],
    optional: ["Garlic", "Oyster sauce", "Soy sauce", "Spring onion", "Cornstarch"],
    steps: [
      "Slice tofu into a dish. Mix ground pork with oyster sauce and cornstarch; mound on tofu.",
      "Steam over high heat 10–12 minutes until pork is cooked through (74°C / 165°F).",
      "Drain excess liquid if needed; drizzle soy sauce and spring onion.",
    ],
    zh: {
      name: "蒸肉碎豆腐",
      steps: [
        "豆腐切片鋪碟；免治豬肉加蠔油生粉拌勻鋪面。",
        "大火蒸 10 至 12 分鐘至肉全熟（74°C）。",
        "倒去多餘汁，淋生抽撒蔥花。",
      ],
    },
    sourceUrl: "https://hk.lkk.com/zh-hk/recipes/steamed-tofu-with-minced-pork",
    sourceName: "Lee Kum Kee",
  },
  {
    id: "home-chicken-mushroom-tofu",
    name: "Chicken mushroom tofu",
    cuisine: "Cantonese",
    time: 15,
    servings: 2,
    need: ["Tofu", "Chicken breast", "Mushroom"],
    optional: ["Soy sauce", "Sesame oil", "Spring onion", "Cornstarch"],
    steps: [
      "Cube tofu; mince chicken and mushrooms. Mix chicken-mushroom with soy sauce and cornstarch.",
      "Spread over tofu in a heatproof dish. Steam or microwave covered until chicken is cooked through (74°C / 165°F).",
      "Finish with sesame oil and spring onion.",
    ],
    zh: {
      name: "雙菇雞肉豆腐",
      steps: [
        "豆腐切粒；雞肉蘑菇切碎，加生抽生粉拌勻鋪面。",
        "加蓋蒸或微波至雞全熟（74°C）。",
        "淋麻油撒蔥絲。",
      ],
    },
    sourceUrl: "https://hk.lkk.com/zh-hk/recipes/minced-chicken-and-mushrooms-on-tofu",
    sourceName: "Lee Kum Kee",
  },
  {
    id: "home-omelette-rice",
    name: "Chinese omelette rice",
    cuisine: "Hong Kong",
    time: 25,
    servings: 2,
    need: ["Cooked rice", "Eggs", "Chicken breast"],
    optional: ["Shrimp", "Onion", "Soy sauce", "Oyster sauce", "Spring onion"],
    steps: [
      "Dice chicken (and shrimp); stir-fry with onion until chicken is cooked through (74°C / 165°F).",
      "Toss with rice and soy/oyster sauce until hot; pack into a mound.",
      "Make a thin omelette from beaten eggs; wrap the rice or drape over. Slice to serve.",
    ],
    zh: {
      name: "中式蛋包飯",
      steps: [
        "雞肉（可加蝦）切粒，連洋蔥炒至雞全熟（74°C）。",
        "拌入飯和醬料炒熱，盛成飯團。",
        "蛋液煎成薄皮包裹或覆蓋飯，切開上碟。",
      ],
    },
    sourceUrl: "https://hk.lkk.com/zh-hk/recipes/chinese-omelet-rice",
    sourceName: "Lee Kum Kee",
  },
  {
    id: "home-fu-yung-egg-lkk",
    name: "Ham shrimp omelette",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Eggs", "Ham", "Shrimp"],
    optional: ["Bean sprouts", "Onion", "Oyster sauce", "Spring onion"],
    steps: [
      "Beat eggs with a little oyster sauce. Stir-fry shrimp and ham; mix into eggs with sprouts if using.",
      "Pan-fry until golden and fully set on both sides.",
      "Serve with rice; spring onion on top.",
    ],
    zh: {
      name: "火腿蝦仁芙蓉蛋",
      steps: [
        "蛋加少許蠔油打散；炒香蝦和火腿絲拌入蛋液（可加芽菜）。",
        "煎至兩面金黃熟透。",
        "伴飯，撒蔥花。",
      ],
    },
    sourceUrl: "https://hk.lkk.com/zh-hk/recipes/fried-egg-with-vegetables-ham-and-prawn",
    sourceName: "Lee Kum Kee",
  },
  {
    id: "home-sesame-garlic-chicken-pasta",
    name: "Sesame garlic chicken pasta",
    cuisine: "Western",
    time: 25,
    servings: 1,
    need: ["Pasta", "Chicken breast", "Garlic"],
    optional: ["Ginger", "Sesame oil", "Soy sauce", "Spring onion"],
    steps: [
      "Boil pasta; drain. Slice chicken thin.",
      "Pan-fry chicken until cooked through (74°C / 165°F) with ginger; add lots of garlic in sesame oil.",
      "Toss pasta in; season lightly with soy sauce and spring onion.",
    ],
    zh: {
      name: "麻油蒜蓉雞胸意粉",
      steps: [
        "意粉煮熟瀝乾；雞胸切片。",
        "雞片煎至全熟（74°C），麻油爆香大量蒜蓉。",
        "拌入意粉，少許生抽和蔥花。",
      ],
    },
    sourceUrl: "https://hk.lkk.com/zh-hk/recipes/garlic-chicken-linguine-with-sesame-oil",
    sourceName: "Lee Kum Kee",
  },
  {
    id: "home-beef-snow-peas",
    name: "Beef with snow peas",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Snow peas"],
    optional: ["Garlic", "Ginger", "Oyster sauce", "Soy sauce", "Cornstarch", "Bell pepper"],
    steps: [
      "Slice beef thin; toss with soy and cornstarch. Trim snow peas.",
      "Stir-fry beef until just cooked; remove. Stir-fry snow peas (and pepper) crisp-tender.",
      "Return beef with oyster sauce; toss on high heat.",
    ],
    zh: {
      name: "蜜豆炒牛肉",
      steps: [
        "牛肉切薄片加生抽生粉；蜜豆去絲。",
        "牛肉快炒至熟盛起；蜜豆（可加燈籠椒）大火炒至爽脆。",
        "回牛肉加蠔油炒勻。",
      ],
    },
    sourceUrl: "https://thewoksoflife.com/beef-snow-peas/",
    sourceName: "The Woks of Life",
  },
  {
    id: "home-soy-steamed-fish",
    name: "Soy sauce steamed fish",
    cuisine: "Cantonese",
    time: 20,
    servings: 2,
    need: ["White fish", "Ginger", "Spring onion"],
    optional: ["Soy sauce", "Sesame oil", "Sugar"],
    steps: [
      "Lay fish on a plate over spring onion; tuck ginger on top.",
      "Steam over high heat until the flesh flakes and is opaque (usually 8–12 minutes depending on thickness).",
      "Pour off liquid; top with fresh spring onion, hot oil, and seasoned soy sauce.",
    ],
    zh: {
      name: "豉油清蒸魚",
      steps: [
        "魚底鋪蔥，面放薑片。",
        "大火蒸至肉質不透明可輕鬆拆開（約 8 至 12 分鐘）。",
        "倒去蒸汁，鋪蔥絲，淋熱油和蒸魚豉油。",
      ],
    },
    sourceUrl: "https://hk.lkk.com/zh-hk/recipes/steamed-fish-in-double-fermented-soy-sauce",
    sourceName: "Lee Kum Kee",
  },
  {
    id: "home-braised-tofu-chicken",
    name: "Braised tofu with chicken",
    cuisine: "Cantonese",
    time: 25,
    servings: 2,
    need: ["Tofu", "Chicken breast", "Eggs"],
    optional: ["Ginger", "Oyster sauce", "Soy sauce", "Cornstarch", "Spring onion"],
    steps: [
      "Slice tofu; dust with cornstarch and dip lightly in beaten egg. Pan-fry both sides golden.",
      "Stir-fry chicken pieces until cooked through (74°C / 165°F).",
      "Add tofu back with oyster sauce and a little water; simmer until saucy. Finish with spring onion.",
    ],
    zh: {
      name: "鍋塌豆腐雞柳",
      steps: [
        "豆腐切片拍粉掃蛋液，兩面煎黃。",
        "雞柳炒至全熟（74°C）。",
        "回豆腐加蠔油和水炆至收汁，撒蔥段。",
      ],
    },
    sourceUrl: "https://hk.lkk.com/zh-hk/recipes/braised-fried-tofu-with-chicken-and-shrimp-roe",
    sourceName: "Lee Kum Kee",
  },
  {
    id: "home-garlic-spinach",
    name: "Garlic spinach",
    cuisine: "Chinese",
    time: 8,
    servings: 2,
    need: ["Spinach", "Garlic"],
    optional: ["Soy sauce", "Sesame oil"],
    steps: [
      "Wash spinach; slice garlic.",
      "Stir-fry garlic in a hot oiled pan, then add spinach and toss until just wilted.",
      "Season lightly; sesame oil if you like. Serve at once.",
    ],
    zh: {
      name: "蒜蓉菠菜",
      steps: [
        "菠菜洗淨；蒜切片。",
        "爆香蒜蓉，下菠菜炒至軟。",
        "調味，可淋麻油。",
      ],
    },
  },
  {
    id: "home-oyster-lettuce",
    name: "Oyster sauce lettuce",
    cuisine: "Cantonese",
    time: 8,
    servings: 2,
    need: ["Lettuce", "Oyster sauce", "Garlic"],
    optional: ["Sesame oil", "Sugar"],
    steps: [
      "Separate lettuce leaves; wash and drain well. Slice garlic.",
      "Stir-fry garlic briefly; add lettuce and toss 30–60 seconds until just wilted but still crisp.",
      "Add oyster sauce and toss off heat.",
    ],
    zh: {
      name: "蠔油生菜",
      steps: [
        "生菜拆開洗淨瀝乾；蒜切蓉。",
        "爆香蒜，下生菜快炒半至一分鐘至軟但爽脆。",
        "離火加蠔油拌勻。",
      ],
    },
  },
  {
    id: "home-carrot-egg-stirfry",
    name: "Carrot egg stir-fry",
    cuisine: "Chinese",
    time: 12,
    servings: 2,
    need: ["Carrots", "Eggs"],
    optional: ["Spring onion", "Soy sauce", "Garlic"],
    steps: [
      "Julienne carrots; beat eggs.",
      "Scramble eggs softly and set aside. Stir-fry carrots until tender-crisp.",
      "Return eggs; season and finish with spring onion.",
    ],
    zh: {
      name: "紅蘿蔔炒蛋",
      steps: [
        "紅蘿蔔切絲；打散蛋。",
        "先炒蛋盛起；炒紅蘿蔔至軟脆。",
        "拌回雞蛋調味，撒蔥花。",
      ],
    },
  },
  {
    id: "home-celery-pork",
    name: "Celery and pork stir-fry",
    cuisine: "Chinese",
    time: 18,
    servings: 2,
    need: ["Celery", "Ground pork"],
    optional: ["Garlic", "Soy sauce", "Chili oil"],
    steps: [
      "Slice celery on the bias. Brown ground pork until cooked through (74°C / 165°F).",
      "Add garlic and celery; stir-fry until celery is crisp-tender.",
      "Season with soy sauce (chili oil optional).",
    ],
    zh: {
      name: "西芹炒肉碎",
      steps: [
        "西芹斜切；免治豬肉炒至全熟（74°C）。",
        "下蒜和西芹炒至爽脆。",
        "生抽調味，可加辣椒油。",
      ],
    },
  },
  {
    id: "home-cauliflower-stirfry",
    name: "Garlic cauliflower",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Cauliflower", "Garlic"],
    optional: ["Soy sauce", "Oyster sauce", "Carrots"],
    steps: [
      "Cut cauliflower into small florets. Slice garlic.",
      "Stir-fry garlic, then cauliflower with a splash of water; cover 3–4 minutes until tender-crisp.",
      "Season with soy or oyster sauce.",
    ],
    zh: {
      name: "蒜蓉炒椰菜花",
      steps: [
        "椰菜花切小朵；蒜切片。",
        "爆香蒜，下椰菜花加少許水加蓋 3 至 4 分鐘至軟脆。",
        "生抽或蠔油調味。",
      ],
    },
  },
  {
    id: "home-zucchini-egg",
    name: "Zucchini egg scramble",
    cuisine: "Chinese",
    time: 12,
    servings: 2,
    need: ["Zucchini", "Eggs"],
    optional: ["Garlic", "Soy sauce", "Spring onion"],
    steps: [
      "Slice zucchini into half-moons; beat eggs.",
      "Stir-fry zucchini until just soft; push aside and scramble eggs until set.",
      "Toss together; season and finish with spring onion.",
    ],
    zh: {
      name: "翠玉瓜炒蛋",
      steps: [
        "翠玉瓜切片；打散蛋。",
        "炒軟翠玉瓜，推開炒蛋至熟。",
        "拌勻調味，撒蔥花。",
      ],
    },
  },
  {
    id: "home-sweet-potato-rice",
    name: "Sweet potato rice",
    cuisine: "Chinese",
    time: 35,
    servings: 2,
    need: ["Rice", "Sweet potato"],
    optional: ["Spring onion", "Soy sauce"],
    steps: [
      "Peel and cube sweet potato. Rinse rice; cook rice and sweet potato together with the usual water.",
      "When done, rest 5 minutes and fluff.",
      "Optional: drizzle soy sauce and spring onion.",
    ],
    zh: {
      name: "蕃薯飯",
      steps: [
        "蕃薯去皮切丁，與米同煮。",
        "煮好焗 5 分鐘拌勻。",
        "可淋生抽撒蔥花。",
      ],
    },
  },
  {
    id: "home-tuna-fried-rice",
    name: "Tuna fried rice",
    cuisine: "Hong Kong",
    time: 15,
    servings: 2,
    need: ["Cooked rice", "Canned tuna", "Eggs"],
    optional: ["Spring onion", "Soy sauce", "Onion"],
    steps: [
      "Drain tuna; break up cold rice; beat eggs.",
      "Scramble eggs, add tuna to warm through, then toss with rice until hot.",
      "Season with soy sauce and spring onion.",
    ],
    zh: {
      name: "吞拿魚炒飯",
      steps: [
        "吞拿魚瀝乾；隔夜飯搓散；打散蛋。",
        "先炒蛋，下魚略炒，再下飯炒熱。",
        "生抽蔥花調味。",
      ],
    },
  },
  {
    id: "home-sausage-egg-noodles",
    name: "Sausage egg noodles",
    cuisine: "Hong Kong",
    time: 15,
    servings: 1,
    need: ["Noodles", "Sausages", "Eggs"],
    optional: ["Spring onion", "Soy sauce", "Chili oil"],
    steps: [
      "Cook noodles; slice sausages. Fry sausages until browned and cooked through.",
      "Fry an egg until the white is set.",
      "Toss noodles with soy sauce; top with sausage and egg.",
    ],
    zh: {
      name: "香腸蛋麵",
      steps: [
        "煮麵；香腸切片煎熟。",
        "另煎蛋至蛋白凝固。",
        "麵拌生抽，鋪香腸和蛋。",
      ],
    },
  },
  {
    id: "home-salmon-broccoli-pasta",
    name: "Salmon broccoli pasta",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Pasta", "Salmon", "Broccoli"],
    optional: ["Spring onion", "Lemon", "Olive oil", "Milk"],
    steps: [
      "Boil pasta; add broccoli florets for the last 3 minutes. Drain, saving some water.",
      "Pan-fry salmon chunks in a little oil until opaque and flakes easily (usually 4–6 minutes).",
      "Toss pasta and broccoli with salmon, a splash of pasta water or milk, and lemon if using.",
    ],
    zh: {
      name: "三文魚西蘭花意粉",
      steps: [
        "煮意粉，最後 3 分鐘下西蘭花；瀝乾留少許粉水。",
        "三文魚塊煎至不透明可輕易拆開（約 4 至 6 分鐘）。",
        "拌勻意粉西蘭花，可加粉水或牛奶和檸檬皮。",
      ],
    },
    sourceUrl: "https://www.bbc.co.uk/food/recipes/salmon_broccoli_pasta_39926",
    sourceName: "BBC Food",
  },
  {
    id: "home-cheese-omelette",
    name: "Cheese spinach omelette",
    cuisine: "Western",
    time: 10,
    servings: 1,
    need: ["Eggs", "Cheddar", "Spinach"],
    optional: ["Butter", "Milk", "Onion"],
    steps: [
      "Wilt spinach in a knob of butter; beat 2 eggs.",
      "Pour eggs into a hot buttered pan; cook until almost set, add grated cheddar and spinach.",
      "Fold and cook until the cheese melts and eggs are fully set.",
    ],
    zh: {
      name: "芝士菠菜奄列",
      steps: [
        "牛油炒軟菠菜；打散兩隻蛋。",
        "熱鍋下蛋，將近凝固時加芝士碎和菠菜。",
        "對折，至芝士融化、蛋全熟。",
      ],
    },
    sourceUrl: "https://www.bbc.co.uk/food/recipes/theperfectomelette_86680",
    sourceName: "BBC Food",
  },
  {
    id: "home-tuna-pasta",
    name: "Tuna pasta",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Pasta", "Canned tuna"],
    optional: ["Onion", "Garlic", "Tomato", "Olive oil", "Lemon", "Cheddar"],
    steps: [
      "Boil pasta until al dente; drain, saving water.",
      "Soften onion/garlic in olive oil; stir in drained tuna and tomato if using.",
      "Toss with pasta, loosen with pasta water; lemon or cheddar optional.",
    ],
    zh: {
      name: "吞拿魚意粉",
      steps: [
        "意粉煮至彈牙瀝乾留粉水。",
        "炒軟洋蔥蒜蓉，拌入瀝乾吞拿魚（可加番茄）。",
        "拌粉，用粉水調稀，可加檸檬或芝士。",
      ],
    },
    sourceUrl: "https://www.bbc.co.uk/food/recipes/creamy_tuna_one-pot_19168",
    sourceName: "BBC Food",
  },
  {
    id: "home-jacket-potato-tuna",
    name: "Jacket potato with tuna",
    cuisine: "Western",
    time: 60,
    servings: 1,
    need: ["Potato", "Canned tuna"],
    optional: ["Butter", "Cheddar", "Spring onion", "Mayonnaise", "Lemon"],
    steps: [
      "Prick potato, rub with oil/salt, bake at 200°C until soft inside (45–60 min) or microwave then crisp in a pan/oven.",
      "Fluff the inside with butter.",
      "Mix drained tuna with mayo or lemon; pile into the potato. Cheddar or spring onion optional.",
    ],
    zh: {
      name: "焗薯吞拿魚",
      steps: [
        "薯仔刺孔抹油鹽，200°C 焗至軟心（45 至 60 分鐘），或先微波再焗脆皮。",
        "剖開加牛油拌鬆。",
        "吞拿魚拌蛋黃醬或檸檬填入，可加芝士蔥花。",
      ],
    },
    sourceUrl: "https://www.bbc.co.uk/food/recipes/jacket_potato_with_tuna_30924",
    sourceName: "BBC Food",
  },
  {
    id: "home-chicken-carbonara",
    name: "Chicken bacon pasta",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Pasta", "Chicken breast", "Bacon", "Eggs"],
    optional: ["Cheddar", "Milk", "Olive oil", "Garlic"],
    steps: [
      "Boil pasta; reserve water. Fry bacon until crisp; cook chicken strips until done (74°C / 165°F).",
      "Beat eggs with grated cheddar and a splash of milk.",
      "Off heat, toss hot pasta with egg mix, bacon, and chicken; loosen with pasta water until silky.",
    ],
    zh: {
      name: "雞肉培根意粉",
      steps: [
        "煮意粉留粉水。煎香培根；雞絲炒至全熟（74°C）。",
        "蛋加芝士碎和少許牛奶打散。",
        "離火拌入熱粉、培根和雞，用粉水調至滑稠。",
      ],
    },
    sourceUrl: "https://www.bbc.co.uk/food/recipes/chickencarbonara_90044",
    sourceName: "BBC Food",
  },
  {
    id: "home-mushroom-pasta",
    name: "Creamy mushroom pasta",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Pasta", "Mushroom", "Garlic"],
    optional: ["Milk", "Butter", "Cheddar", "Onion", "Olive oil"],
    steps: [
      "Boil pasta. Slice mushrooms; soften garlic (and onion) in butter/oil.",
      "Cook mushrooms until browned; add a splash of milk and simmer briefly.",
      "Toss with pasta and optional cheddar until coated.",
    ],
    zh: {
      name: "蘑菇忌廉意粉",
      steps: [
        "煮意粉；蘑菇切片，牛油爆香蒜（可加洋蔥）。",
        "炒香蘑菇，加少許牛奶略煮。",
        "拌粉，可加芝士。",
      ],
    },
  },
  {
    id: "home-tomato-soup",
    name: "Tomato soup",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Tomato", "Onion", "Garlic"],
    optional: ["Butter", "Milk", "Sugar", "Bread"],
    steps: [
      "Chop tomatoes and onion. Soften onion and garlic in butter; add tomato and a cup of water.",
      "Simmer 15 minutes until soft; mash or blend until smooth.",
      "Season; splash of milk optional. Serve with bread.",
    ],
    zh: {
      name: "番茄湯",
      steps: [
        "番茄洋蔥切件；牛油炒軟洋蔥蒜，下番茄和一杯水。",
        "煮 15 分鐘至軟，壓蓉或攪打。",
        "調味，可加牛奶，配麵包。",
      ],
    },
  },
  {
    id: "home-chicken-salad",
    name: "Chicken tomato salad",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Chicken breast", "Lettuce", "Tomato"],
    optional: ["Cucumber", "Mayonnaise", "Lemon", "Olive oil"],
    steps: [
      "Cook chicken until done (74°C / 165°F); cool and slice or shred.",
      "Toss lettuce, tomato, and cucumber with olive oil or a little mayo and lemon.",
      "Top with chicken; season.",
    ],
    zh: {
      name: "雞肉番茄沙律",
      steps: [
        "雞胸煮至全熟（74°C），放涼切片。",
        "生菜番茄青瓜拌橄欖油或蛋黃醬檸檬汁。",
        "鋪上雞肉調味。",
      ],
    },
  },
  {
    id: "home-baked-eggs-spinach",
    name: "Baked eggs with spinach",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Eggs", "Spinach"],
    optional: ["Tomato", "Cheddar", "Cream cheese", "Onion", "Olive oil"],
    steps: [
      "Wilt spinach in a little oil; spread in an ovenproof dish with tomato if using.",
      "Make wells and crack in eggs; add cheddar dots.",
      "Bake at 190°C until whites are set (about 10–12 minutes).",
    ],
    zh: {
      name: "焗菠菜蛋",
      steps: [
        "少油炒軟菠菜，鋪焗盤（可加番茄）。",
        "挖穴打入蛋，可加芝士。",
        "190°C 焗至蛋白凝固（約 10 至 12 分鐘）。",
      ],
    },
  },
  {
    id: "home-ham-cheese-toastie",
    name: "Ham cheese toastie",
    cuisine: "Western",
    time: 10,
    servings: 1,
    need: ["Bread", "Ham", "Cheddar"],
    optional: ["Butter", "Mustard", "Tomato"],
    steps: [
      "Butter outside of two bread slices. Layer ham and cheddar (mustard optional) inside.",
      "Toast in a pan or press until bread is golden and cheese melts.",
      "Rest 1 minute; slice.",
    ],
    zh: {
      name: "火腿芝士三明治",
      steps: [
        "麵包外抹牛油，內夾火腿芝士（可加芥末）。",
        "平底鍋或壓烤至兩面金黃、芝士融化。",
        "待 1 分鐘切開。",
      ],
    },
  },
  {
    id: "home-sausage-pasta",
    name: "Sausage tomato pasta",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Pasta", "Sausages", "Tomato"],
    optional: ["Onion", "Garlic", "Olive oil", "Cheddar"],
    steps: [
      "Boil pasta. Slice sausages; brown until cooked through.",
      "Add onion/garlic and chopped tomato; simmer until saucy.",
      "Toss with pasta; cheddar optional.",
    ],
    zh: {
      name: "香腸番茄意粉",
      steps: [
        "煮意粉；香腸切片煎熟。",
        "加洋蔥蒜蓉和番茄煮至出汁。",
        "拌粉，可加芝士。",
      ],
    },
  },
  {
    id: "home-egg-mayo-sandwich",
    name: "Egg mayo sandwich",
    cuisine: "Western",
    time: 15,
    servings: 1,
    need: ["Eggs", "Bread", "Mayonnaise"],
    optional: ["Spring onion", "Lettuce", "Butter"],
    steps: [
      "Hard-boil 2 eggs (whites fully set, about 9–10 minutes); cool and peel.",
      "Mash with mayonnaise and spring onion if using.",
      "Spread on bread with lettuce if you like.",
    ],
    zh: {
      name: "雞蛋沙拉三明治",
      steps: [
        "水煮蛋約 9 至 10 分鐘至全熟，放涼剝殼。",
        "壓蓉拌蛋黃醬（可加蔥花）。",
        "夾入麵包，可加生菜。",
      ],
    },
  },
  {
    id: "home-yogurt-berry-bowl",
    name: "Yogurt berry bowl",
    cuisine: "Western",
    time: 5,
    servings: 1,
    need: ["Yogurt", "Berries"],
    optional: ["Honey", "Banana", "Peanut butter"],
    steps: [
      "Spoon yogurt into a bowl.",
      "Top with berries (and banana slices if using).",
      "Drizzle honey or a little peanut butter.",
    ],
    zh: {
      name: "乳酪雜莓碗",
      steps: [
        "乳酪盛碗。",
        "鋪上雜莓（可加香蕉片）。",
        "淋蜜糖或花生醬。",
      ],
    },
  },
  {
    id: "home-pancakes-simple",
    name: "Simple pancakes",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Flour", "Eggs", "Milk"],
    optional: ["Butter", "Sugar", "Berries", "Jam", "Honey"],
    steps: [
      "Whisk 1 cup flour, 1 egg, and about 1 cup milk into a smooth batter; rest 5 minutes.",
      "Cook spoonfuls in a lightly buttered pan until bubbles form; flip and cook through.",
      "Serve with berries, jam, or honey.",
    ],
    zh: {
      name: "簡易班戟",
      steps: [
        "一杯麵粉、一隻蛋和約一杯牛奶打成順滑麵糊，靜置 5 分鐘。",
        "少油平底鍋倒麵糊，起泡後翻面至熟透。",
        "配雜莓、果醬或蜜糖。",
      ],
    },
  },
  {
    id: "home-grilled-cheese",
    name: "Grilled cheese sandwich",
    cuisine: "Western",
    time: 10,
    servings: 1,
    need: ["Bread", "Cheddar"],
    optional: ["Butter", "Tomato"],
    steps: [
      "Butter outside of bread; fill with cheddar (tomato optional).",
      "Pan-fry both sides until golden and cheese melts.",
      "Rest briefly; cut and serve.",
    ],
    zh: {
      name: "芝士烤三明治",
      steps: [
        "麵包外抹牛油，夾芝士（可加番茄片）。",
        "兩面煎至金黃芝士融化。",
        "稍候切開。",
      ],
    },
  },
  {
    id: "home-chicken-veg-soup",
    name: "Chicken vegetable soup",
    cuisine: "Western",
    time: 35,
    servings: 3,
    need: ["Chicken thighs", "Carrots", "Onion"],
    optional: ["Celery", "Potato", "Garlic", "Spring onion"],
    steps: [
      "Simmer chicken thighs in water 20 minutes until cooked through (74°C / 165°F); remove and shred.",
      "Add chopped carrot, onion, and other veg; simmer until soft.",
      "Return chicken; season. Finish with spring onion.",
    ],
    zh: {
      name: "雞肉蔬菜湯",
      steps: [
        "雞脾加水煮 20 分鐘至全熟（74°C），取出撕絲。",
        "下紅蘿蔔洋蔥等蔬菜煮軟。",
        "回雞肉調味，撒蔥花。",
      ],
    },
  },
  {
    id: "home-salmon-rice-bowl",
    name: "Salmon rice bowl",
    cuisine: "Western",
    time: 20,
    servings: 1,
    need: ["Salmon", "Cooked rice"],
    optional: ["Soy sauce", "Spring onion", "Avocado", "Cucumber", "Sesame oil"],
    steps: [
      "Pan-fry or bake salmon until opaque and flakes (about 4–6 minutes per side depending on thickness).",
      "Warm rice in a bowl; flake salmon over.",
      "Add avocado/cucumber if using; drizzle soy sauce or sesame oil.",
    ],
    zh: {
      name: "三文魚飯碗",
      steps: [
        "三文魚煎或焗至不透明可拆開。",
        "熱飯盛碗，鋪上魚肉。",
        "可加牛油果青瓜，淋生抽或麻油。",
      ],
    },
  },
  {
    id: "home-pork-chop-onion",
    name: "Pan-fried pork chop",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Pork chops", "Onion"],
    optional: ["Garlic", "Soy sauce", "Butter"],
    steps: [
      "Pat pork chops dry; season. Soften sliced onion in the pan; push aside.",
      "Pan-fry chops until cooked through (aim for 71°C / 160°F).",
      "Rest 3 minutes; serve with onions.",
    ],
    zh: {
      name: "洋蔥豬扒",
      steps: [
        "豬扒抹乾調味；先炒軟洋蔥推開。",
        "煎至全熟（建議中心 71°C）。",
        "靜置 3 分鐘，伴洋蔥上碟。",
      ],
    },
  },
  {
    id: "home-shrimp-pasta",
    name: "Garlic shrimp pasta",
    cuisine: "Western",
    time: 20,
    servings: 2,
    need: ["Pasta", "Shrimp", "Garlic"],
    optional: ["Olive oil", "Lemon", "Spring onion", "Chili oil"],
    steps: [
      "Boil pasta. Soften garlic in olive oil; add shrimp and cook until opaque.",
      "Toss with pasta and a splash of pasta water.",
      "Finish with lemon and spring onion.",
    ],
    zh: {
      name: "蒜香蝦意粉",
      steps: [
        "煮意粉；橄欖油爆香蒜蓉，下蝦炒至熟透。",
        "拌粉，加少許粉水。",
        "檸檬和蔥花收尾。",
      ],
    },
  },
  {
    id: "home-bean-tomato-stew",
    name: "Tomato bean stew",
    cuisine: "Western",
    time: 25,
    servings: 2,
    need: ["Beans", "Tomato", "Onion"],
    optional: ["Garlic", "Olive oil", "Spinach", "Bread"],
    steps: [
      "Soften onion and garlic in olive oil; add chopped tomato and drained beans.",
      "Simmer 10–15 minutes until thick; wilt in spinach if using.",
      "Season; serve with bread.",
    ],
    zh: {
      name: "番茄豆炆",
      steps: [
        "橄欖油炒軟洋蔥蒜，下番茄和瀝乾豆子。",
        "煮 10 至 15 分鐘至稠，可加菠菜。",
        "調味，配麵包。",
      ],
    },
  },
  {
    id: "home-corn-egg-scramble",
    name: "Corn egg scramble",
    cuisine: "Chinese",
    time: 10,
    servings: 2,
    need: ["Corn", "Eggs"],
    optional: ["Spring onion", "Soy sauce", "Milk"],
    steps: [
      "Beat eggs; drain canned or use thawed corn.",
      "Scramble eggs softly; add corn and cook until hot and eggs are set.",
      "Season; finish with spring onion.",
    ],
    zh: {
      name: "粟米炒蛋",
      steps: [
        "打散蛋；準備粟米。",
        "炒蛋至將熟，下粟米炒熱至蛋全熟。",
        "調味撒蔥花。",
      ],
    },
  },
  {
    id: "home-cucumber-egg",
    name: "Cucumber egg stir-fry",
    cuisine: "Chinese",
    time: 10,
    servings: 2,
    need: ["Cucumber", "Eggs"],
    optional: ["Garlic", "Soy sauce"],
    steps: [
      "Slice cucumber; beat eggs.",
      "Scramble eggs and set aside. Stir-fry cucumber briefly so it stays crisp.",
      "Return eggs; season lightly.",
    ],
    zh: {
      name: "青瓜炒蛋",
      steps: [
        "青瓜切片；打散蛋。",
        "先炒蛋盛起；青瓜快炒保持爽脆。",
        "拌回雞蛋調味。",
      ],
    },
  },
  {
    id: "home-bell-pepper-beef",
    name: "Bell pepper beef",
    cuisine: "Chinese",
    time: 20,
    servings: 2,
    need: ["Beef steak", "Bell pepper"],
    optional: ["Onion", "Garlic", "Soy sauce", "Oyster sauce", "Cornstarch"],
    steps: [
      "Slice beef thin; toss with soy and cornstarch. Cut peppers into chunks.",
      "Stir-fry beef until just cooked; remove. Stir-fry peppers and onion crisp-tender.",
      "Return beef with oyster sauce; toss on high heat.",
    ],
    zh: {
      name: "彩椒炒牛肉",
      steps: [
        "牛肉切薄片加生抽生粉；燈籠椒切塊。",
        "牛肉快炒至熟盛起；炒椒和洋蔥至爽脆。",
        "回牛肉加蠔油大火炒勻。",
      ],
    },
  },
  {
    id: "home-mushroom-egg-rice",
    name: "Mushroom egg rice",
    cuisine: "Chinese",
    time: 18,
    servings: 2,
    need: ["Cooked rice", "Mushroom", "Eggs"],
    optional: ["Soy sauce", "Garlic", "Spring onion"],
    steps: [
      "Slice mushrooms; beat eggs; loosen rice.",
      "Scramble eggs; stir-fry mushrooms until browned; toss with rice until hot.",
      "Season with soy sauce and spring onion.",
    ],
    zh: {
      name: "蘑菇蛋炒飯",
      steps: [
        "蘑菇切片；打散蛋；隔夜飯搓散。",
        "炒蛋，炒香蘑菇，下飯炒熱。",
        "生抽蔥花調味。",
      ],
    },
  },
  {
    id: "home-spinach-tofu-soup",
    name: "Spinach tofu soup",
    cuisine: "Chinese",
    time: 15,
    servings: 2,
    need: ["Spinach", "Tofu"],
    optional: ["Garlic", "Soy sauce", "Sesame oil", "Eggs"],
    steps: [
      "Cube tofu; wash spinach. Bring 3 cups water to a simmer.",
      "Add tofu 3 minutes; add spinach until wilted.",
      "Optional egg ribbons; season with soy sauce and sesame oil.",
    ],
    zh: {
      name: "菠菜豆腐湯",
      steps: [
        "豆腐切丁；菠菜洗淨。水三杯煮熱。",
        "下豆腐煮 3 分鐘，再下菠菜至軟。",
        "可打蛋花，生抽麻油調味。",
      ],
    },
  },
]

