import type { Recipe } from "@/lib/recipes"

/** Verified direct recipe page URLs (never Google / site search). */
export const RECIPE_SOURCES: Record<string, { url: string; name: string }> = {
  "home-apple-pork-bone-soup": { url: "https://thewoksoflife.com/chinese-salted-pork-bone-soup/", name: "The Woks of Life" },
  "home-avocado-toast": { url: "https://www.bbc.co.uk/food/recipes/smashed_avocado_on_toast_89082", name: "BBC Food" },
  "home-bacon-egg-rice": { url: "https://thewoksoflife.com/bacon-and-egg-fried-rice/", name: "The Woks of Life" },
  "home-bacon-pasta": { url: "https://www.bbc.co.uk/food/recipes/one-pot_bacon_spinach_50776", name: "BBC Food" },
  "home-baked-pork-chop-rice": { url: "https://thewoksoflife.com/baked-pork-chop-rice/", name: "The Woks of Life" },
  "home-banana-oat-pancakes": { url: "https://thewoksoflife.com/banana-oat-pancakes/", name: "The Woks of Life" },
  "home-banh-mi-ish-sandwich": { url: "https://thewoksoflife.com/oven-baked-ribs-char-siu/", name: "The Woks of Life" },
  "home-basil-eggplant": { url: "https://thewoksoflife.com/japanese-eggplant-chicken-thai-basil-stir-fry/", name: "The Woks of Life" },
  "home-beef-broccoli": { url: "https://www.madewithlau.com/recipes/beef-broccoli", name: "Made With Lau" },
  "home-beef-chow-fun": { url: "https://www.madewithlau.com/recipes/beef-chow-fun", name: "Made With Lau" },
  "home-beef-fried-noodles": { url: "https://thewoksoflife.com/braised-beef-noodle-soup/", name: "The Woks of Life" },
  "home-beef-pho-style": { url: "https://thewoksoflife.com/chinese-noodle-soup/", name: "The Woks of Life" },
  "home-beef-snow-peas": { url: "https://hk.lkk.com/zh-hk/recipes/stir-fried-beef-with-honey-pea-and-lily-bulb", name: "Lee Kum Kee" },
  "home-beef-tomato-noodles": { url: "https://www.madewithlau.com/recipes/tomato-beef-pan-fried-noodles", name: "Made With Lau" },
  "home-beef-tomato-rice": { url: "https://www.madewithlau.com/recipes/beef-fried-rice", name: "Made With Lau" },
  "home-bell-pepper-beef": { url: "https://thewoksoflife.com/beef-and-pepper-stir-fry/", name: "The Woks of Life" },
  "home-bitter-melon-beef": { url: "https://thewoksoflife.com/beef-with-bitter-melon/", name: "The Woks of Life" },
  "home-bitter-melon-pork": { url: "https://thewoksoflife.com/bitter-melon-soup-pork-bones/", name: "The Woks of Life" },
  "home-black-bean-beef": { url: "https://thewoksoflife.com/beef-black-bean-sauce/", name: "The Woks of Life" },
  "home-black-bean-ribs": { url: "https://www.madewithlau.com/recipes/steamed-spare-ribs", name: "Made With Lau" },
  "home-black-bean-ribs-claypot": { url: "https://thewoksoflife.com/pork-ribs-black-bean-sauce/", name: "The Woks of Life" },
  "home-braised-egg-rice": { url: "https://www.madewithlau.com/recipes/egg-fried-rice", name: "Made With Lau" },
  "home-braised-tofu-chicken": { url: "https://hk.lkk.com/zh-hk/recipes/braised-fried-tofu-with-chicken-and-shrimp-roe", name: "Lee Kum Kee" },
  "home-braised-tofu-pork": { url: "https://thewoksoflife.com/braised-tofu/", name: "The Woks of Life" },
  "home-braised-tofu-veg": { url: "https://thewoksoflife.com/braised-tofu/", name: "The Woks of Life" },
  "home-broccoli-beef-garlic": { url: "https://www.madewithlau.com/recipes/beef-broccoli", name: "Made With Lau" },
  "home-cabbage-pork-filling": { url: "https://thewoksoflife.com/dumpling-filling-recipes/", name: "The Woks of Life" },
  "home-cantonese-chicken-noodles": { url: "https://thewoksoflife.com/chinese-chicken-noodle-soup/", name: "The Woks of Life" },
  "home-celery-pork": { url: "https://thewoksoflife.com/pork-and-celery-dumplings/", name: "The Woks of Life" },
  "home-celery-pork-bone-soup": { url: "https://thewoksoflife.com/chinese-salted-pork-bone-soup/", name: "The Woks of Life" },
  "home-century-egg-congee": { url: "https://www.madewithlau.com/recipes/century-egg-and-pork-congee", name: "Made With Lau" },
  "home-century-egg-tofu-soup": { url: "https://thewoksoflife.com/tofu-soup/", name: "The Woks of Life" },
  "home-char-siu-home": { url: "https://thewoksoflife.com/oven-baked-ribs-char-siu/", name: "The Woks of Life" },
  "home-cheese-omelette": { url: "https://www.bbc.co.uk/food/recipes/theperfectomelette_86680", name: "BBC Food" },
  "home-chicken-broccoli": { url: "https://thewoksoflife.com/chicken-and-chinese-broccoli/", name: "The Woks of Life" },
  "home-chicken-carbonara": { url: "https://www.bbc.co.uk/food/recipes/chickencarbonara_90044", name: "BBC Food" },
  "home-chicken-corn-soup": { url: "https://www.madewithlau.com/recipes/chicken-corn-soup", name: "Made With Lau" },
  "home-chicken-katsu-pan": { url: "https://thewoksoflife.com/chicken-katsu-curry-rice/", name: "The Woks of Life" },
  "home-chicken-mushroom": { url: "https://www.madewithlau.com/recipes/steamed-chicken-with-mushroom", name: "Made With Lau" },
  "home-chicken-mushroom-tofu": { url: "https://hk.lkk.com/zh-hk/recipes/minced-chicken-and-mushrooms-on-tofu", name: "Lee Kum Kee" },
  "home-chicken-satay-rice": { url: "https://thewoksoflife.com/xo-sauce-fried-rice-chicken/", name: "The Woks of Life" },
  "home-chicken-steak-rice": { url: "https://thewoksoflife.com/xo-sauce-fried-rice-chicken/", name: "The Woks of Life" },
  "home-chicken-tomato-beef-style": { url: "https://thewoksoflife.com/beef-tomato-stir-fry/", name: "The Woks of Life" },
  "home-chickpea-curry": { url: "https://thewoksoflife.com/cashew-chickpea-curry/", name: "The Woks of Life" },
  "home-chili-garlic-eggplant": { url: "https://www.madewithlau.com/recipes/eggplant-with-garlic-sauce", name: "Made With Lau" },
  "home-chili-oil-lettuce": { url: "https://thewoksoflife.com/chili-garlic-sauce/", name: "The Woks of Life" },
  "home-chinese-sausage-rice": { url: "https://thewoksoflife.com/chinese-sausage-fried-rice/", name: "The Woks of Life" },
  "home-chow-mein": { url: "https://www.madewithlau.com/recipes/chow-mein", name: "Made With Lau" },
  "home-clams-black-bean": { url: "https://www.madewithlau.com/recipes/clams-with-black-bean-sauce", name: "Made With Lau" },
  "home-claypot-style-rice": { url: "https://thewoksoflife.com/xo-sauce-fried-rice-chicken/", name: "The Woks of Life" },
  "home-claypot-tofu": { url: "https://www.madewithlau.com/recipes/mushroom-tofu-claypot", name: "Made With Lau" },
  "home-clearout-egg-drop": { url: "https://www.madewithlau.com/recipes/egg-drop-soup", name: "Made With Lau" },
  "home-coconut-pumpkin-soup": { url: "https://thewoksoflife.com/pumpkin-soup-recipe/", name: "The Woks of Life" },
  "home-coconut-shrimp-curry": { url: "https://thewoksoflife.com/coconut-curry-shrimp/", name: "The Woks of Life" },
  "home-cold-sesame-noodles": { url: "https://thewoksoflife.com/cold-sesame-noodles/", name: "The Woks of Life" },
  "home-cold-tofu-soy": { url: "https://thewoksoflife.com/pan-fried-tofu-with-soy-dipping-sauce/", name: "The Woks of Life" },
  "home-congee-fish-slice": { url: "https://thewoksoflife.com/fish-congee/", name: "The Woks of Life" },
  "home-corn-chicken-wing-soup": { url: "https://www.madewithlau.com/recipes/chicken-corn-soup", name: "Made With Lau" },
  "home-creamy-mushroom-chicken": { url: "https://www.madewithlau.com/recipes/steamed-chicken-with-mushroom", name: "Made With Lau" },
  "home-creamy-pumpkin-soup": { url: "https://thewoksoflife.com/pumpkin-soup-recipe/", name: "The Woks of Life" },
  "home-cucumber-miso": { url: "https://thewoksoflife.com/chinese-cucumber-salad/", name: "The Woks of Life" },
  "home-dan-dan-noodles": { url: "https://thewoksoflife.com/dan-dan-noodles/", name: "The Woks of Life" },
  "home-dried-mushroom-chicken-soup": { url: "https://thewoksoflife.com/chinese-chicken-mushroom-soup/", name: "The Woks of Life" },
  "home-dry-fried-green-beans": { url: "https://thewoksoflife.com/sichuan-dry-fried-green-beans/", name: "The Woks of Life" },
  "home-dry-pot-cauliflower": { url: "https://thewoksoflife.com/dry-pot-cauliflower/", name: "The Woks of Life" },
  "home-dumpling-filling-stir": { url: "https://thewoksoflife.com/dumpling-filling-recipes/", name: "The Woks of Life" },
  "home-egg-drop-soup": { url: "https://www.madewithlau.com/recipes/egg-drop-soup", name: "Made With Lau" },
  "home-egg-foo-young": { url: "https://www.madewithlau.com/recipes/egg-foo-young", name: "Made With Lau" },
  "home-egg-fried-rice": { url: "https://www.madewithlau.com/recipes/egg-fried-rice", name: "Made With Lau" },
  "home-egg-white-tomato": { url: "https://thewoksoflife.com/stir-fried-tomato-and-egg/", name: "The Woks of Life" },
  "home-eggplant-mapo-veg": { url: "https://thewoksoflife.com/mapo-eggplant/", name: "The Woks of Life" },
  "home-falafel-bowl": { url: "https://thewoksoflife.com/cashew-chickpea-curry/", name: "The Woks of Life" },
  "home-fermented-tofu-braised-pork": { url: "https://thewoksoflife.com/braised-tofu/", name: "The Woks of Life" },
  "home-fermented-tofu-greens": { url: "https://thewoksoflife.com/water-spinach-garlic-ginger-fermented-tofu/", name: "The Woks of Life" },
  "home-fish-tofu-soup": { url: "https://thewoksoflife.com/easy-fish-tofu-soup/", name: "The Woks of Life" },
  "home-fridge-fried-noodles": { url: "https://www.madewithlau.com/recipes/chow-mein", name: "Made With Lau" },
  "home-fu-yung-egg-lkk": { url: "https://hk.lkk.com/zh-hk/recipes/fried-egg-with-vegetables-ham-and-prawn", name: "Lee Kum Kee" },
  "home-garlic-broccoli": { url: "https://thewoksoflife.com/broccoli-garlic-sauce/", name: "The Woks of Life" },
  "home-garlic-broccoli-tofu": { url: "https://thewoksoflife.com/broccoli-garlic-sauce/", name: "The Woks of Life" },
  "home-garlic-eggplant": { url: "https://www.madewithlau.com/recipes/steamed-chinese-eggplant", name: "Made With Lau" },
  "home-garlic-green-beans": { url: "https://thewoksoflife.com/garlic-green-beans/", name: "The Woks of Life" },
  "home-garlic-lettuce": { url: "https://thewoksoflife.com/cooked-lettuce-with-oyster-sauce-garlic/", name: "The Woks of Life" },
  "home-garlic-pak-choi": { url: "https://www.xiachufang.com/recipe/106509143/", name: "下厨房" },
  "home-garlic-shrimp": { url: "https://www.madewithlau.com/recipes/pan-fried-shrimp-with-garlic", name: "Made With Lau" },
  "home-garlic-spare-ribs": { url: "https://www.madewithlau.com/recipes/steamed-spare-ribs", name: "Made With Lau" },
  "home-garlic-spinach": { url: "https://thewoksoflife.com/water-spinach-garlic-ginger-fermented-tofu/", name: "The Woks of Life" },
  "home-garlic-steamed-shrimp-home": { url: "https://www.madewithlau.com/recipes/steamed-garlic-shrimp", name: "Made With Lau" },
  "home-ginger-chicken": { url: "https://thewoksoflife.com/ginger-chicken/", name: "The Woks of Life" },
  "home-ginger-chicken-clear-soup": { url: "https://thewoksoflife.com/ginger-chicken/", name: "The Woks of Life" },
  "home-ginger-fried-rice": { url: "https://www.madewithlau.com/recipes/ginger-fried-rice", name: "Made With Lau" },
  "home-ginger-scallion-shrimp": { url: "https://thewoksoflife.com/scallion-and-ginger-shrimp/", name: "The Woks of Life" },
  "home-glass-noodle-brisket-soup": { url: "https://thewoksoflife.com/chinese-noodle-soup/", name: "The Woks of Life" },
  "home-glass-noodle-stirfry": { url: "https://thewoksoflife.com/cabbage-and-glass-noodle-stir-fry/", name: "The Woks of Life" },
  "home-green-bean-black-bean": { url: "https://www.madewithlau.com/recipes/chinese-green-beans", name: "Made With Lau" },
  "home-green-bean-pork": { url: "https://thewoksoflife.com/chinese-green-beans-pork/", name: "The Woks of Life" },
  "home-green-curry-chicken": { url: "https://thewoksoflife.com/green-curry-chicken/", name: "The Woks of Life" },
  "home-ham-egg-rice-bowl": { url: "https://www.madewithlau.com/recipes/egg-fried-rice", name: "Made With Lau" },
  "home-herb-tofu-salad": { url: "https://thewoksoflife.com/chinese-tofu-salad/", name: "The Woks of Life" },
  "home-hk-curry-brisket": { url: "https://thewoksoflife.com/beef-curry/", name: "The Woks of Life" },
  "home-hk-curry-chicken": { url: "https://www.madewithlau.com/recipes/curry-chicken", name: "Made With Lau" },
  "home-homestyle-tofu": { url: "https://thewoksoflife.com/home-style-tofu-stir-fry/", name: "The Woks of Life" },
  "home-honey-garlic-chicken": { url: "https://thewoksoflife.com/chicken-garlic-sauce/", name: "The Woks of Life" },
  "home-hot-dry-noodles": { url: "https://thewoksoflife.com/hot-dry-noodles-re-gan-mian/", name: "The Woks of Life" },
  "home-hot-sour-soup": { url: "https://www.madewithlau.com/recipes/hot-sour-soup", name: "Made With Lau" },
  "home-jacket-potato-tuna": { url: "https://www.bbc.co.uk/food/recipes/jacket_potato_with_tuna_30924", name: "BBC Food" },
  "home-japchae-home": { url: "https://thewoksoflife.com/japchae/", name: "The Woks of Life" },
  "home-jianbing-wrap": { url: "https://thewoksoflife.com/avocado-scallion-pancake/", name: "The Woks of Life" },
  "home-kimchi-fried-rice": { url: "https://thewoksoflife.com/beef-kimchi-fried-rice/", name: "The Woks of Life" },
  "home-kimchi-leftover-stew": { url: "https://thewoksoflife.com/kimchi-stew/", name: "The Woks of Life" },
  "home-korean-cucumber-salad": { url: "https://thewoksoflife.com/oi-muchim-korean-cucumber-salad/", name: "The Woks of Life" },
  "home-korean-egg-roll": { url: "https://thewoksoflife.com/egg-roll-in-a-bowl/", name: "The Woks of Life" },
  "home-kung-pao-cauliflower": { url: "https://www.madewithlau.com/recipes/kung-pao-chicken", name: "Made With Lau" },
  "home-kung-pao-chicken": { url: "https://www.madewithlau.com/recipes/kung-pao-chicken", name: "Made With Lau" },
  "home-leftover-beef-fried-rice": { url: "https://www.madewithlau.com/recipes/beef-fried-rice", name: "Made With Lau" },
  "home-leftover-brisket-noodles": { url: "https://thewoksoflife.com/chinese-noodle-soup/", name: "The Woks of Life" },
  "home-leftover-chicken-congee": { url: "https://www.madewithlau.com/recipes/chicken-congee", name: "Made With Lau" },
  "home-leftover-fish-pan": { url: "https://www.madewithlau.com/recipes/pan-fried-fish-cakes", name: "Made With Lau" },
  "home-leftover-fried-rice": { url: "https://www.madewithlau.com/recipes/egg-fried-rice", name: "Made With Lau" },
  "home-leftover-kimchi-pancake": { url: "https://thewoksoflife.com/kimchi-pancake/", name: "The Woks of Life" },
  "home-leftover-pork-fried-rice": { url: "https://www.madewithlau.com/recipes/egg-fried-rice", name: "Made With Lau" },
  "home-leftover-shrimp-fried-rice": { url: "https://thewoksoflife.com/shrimp-fried-rice/", name: "The Woks of Life" },
  "home-leftover-soup-noodle": { url: "https://thewoksoflife.com/chinese-noodle-soup/", name: "The Woks of Life" },
  "home-leftover-steam-rice": { url: "https://thewoksoflife.com/chinese-sausage-fried-rice/", name: "The Woks of Life" },
  "home-leftover-wonton-clear": { url: "https://thewoksoflife.com/wonton-soup-recipe/", name: "The Woks of Life" },
  "home-lemon-chicken": { url: "https://www.madewithlau.com/recipes/lemon-chicken", name: "Made With Lau" },
  "home-lemon-garlic-shrimp-pasta": { url: "https://www.madewithlau.com/recipes/pan-fried-shrimp-with-garlic", name: "Made With Lau" },
  "home-lemon-spare-ribs": { url: "https://www.madewithlau.com/recipes/steamed-spare-ribs", name: "Made With Lau" },
  "home-lemongrass-chicken": { url: "https://thewoksoflife.com/lemongrass-chicken/", name: "The Woks of Life" },
  "home-lo-mein": { url: "https://www.madewithlau.com/recipes/vegetable-lo-mein", name: "Made With Lau" },
  "home-lotus-beef-stir": { url: "https://thewoksoflife.com/lotus-root-recipe-stir-fry/", name: "The Woks of Life" },
  "home-lotus-carrot-stirfry": { url: "https://thewoksoflife.com/lotus-root-recipe-stir-fry/", name: "The Woks of Life" },
  "home-lotus-corn-clear-soup": { url: "https://thewoksoflife.com/lotus-root-recipe-stir-fry/", name: "The Woks of Life" },
  "home-lotus-pork-braise": { url: "https://thewoksoflife.com/lotus-root-recipe-stir-fry/", name: "The Woks of Life" },
  "home-lotus-rib-soup": { url: "https://thewoksoflife.com/lotus-root-recipe-stir-fry/", name: "The Woks of Life" },
  "home-lotus-root-stirfry": { url: "https://thewoksoflife.com/lotus-root-recipe-stir-fry/", name: "The Woks of Life" },
  "home-lu-rou-fan": { url: "https://thewoksoflife.com/lu-rou-fan-taiwanese-braised-pork-rice-bowl/", name: "The Woks of Life" },
  "home-mapo-eggplant": { url: "https://thewoksoflife.com/mapo-eggplant/", name: "The Woks of Life" },
  "home-mapo-tofu": { url: "https://www.madewithlau.com/recipes/mapo-tofu-pork", name: "Made With Lau" },
  "home-mapo-tofu-veg": { url: "https://www.madewithlau.com/recipes/mapo-tofu-pork", name: "Made With Lau" },
  "home-meatball-tomato-pasta": { url: "https://thewoksoflife.com/beef-tomato-stir-fry/", name: "The Woks of Life" },
  "home-miso-pumpkin-braise": { url: "https://thewoksoflife.com/easy-miso-soup/", name: "The Woks of Life" },
  "home-miso-soup": { url: "https://thewoksoflife.com/easy-miso-soup/", name: "The Woks of Life" },
  "home-mushroom-bok-choy": { url: "https://www.madewithlau.com/recipes/bok-choy-recipe", name: "Made With Lau" },
  "home-mushroom-claypot-rice": { url: "https://thewoksoflife.com/mushroom-fried-rice/", name: "The Woks of Life" },
  "home-mushroom-egg-rice": { url: "https://www.madewithlau.com/recipes/egg-fried-rice", name: "Made With Lau" },
  "home-mushroom-risotto": { url: "https://thewoksoflife.com/roast-chicken-wild-mushroom-sticky-rice-risotto/", name: "The Woks of Life" },
  "home-no-seafood-chow-mein": { url: "https://thewoksoflife.com/chicken-chow-mein/", name: "The Woks of Life" },
  "home-nori-tofu-clear-soup": { url: "https://thewoksoflife.com/tofu-soup/", name: "The Woks of Life" },
  "home-omelette-rice": { url: "https://hk.lkk.com/zh-hk/recipes/chinese-omelet-rice", name: "Lee Kum Kee" },
  "home-onion-beef-clear-soup": { url: "https://thewoksoflife.com/beef-onion-stir-fry/", name: "The Woks of Life" },
  "home-orange-chicken": { url: "https://www.madewithlau.com/recipes/orange-chicken", name: "Made With Lau" },
  "home-oyakodon": { url: "https://thewoksoflife.com/oyakodon/", name: "The Woks of Life" },
  "home-oyster-beef": { url: "https://www.madewithlau.com/recipes/beef-oyster-sauce", name: "Made With Lau" },
  "home-oyster-gai-lan": { url: "https://www.xiachufang.com/recipe/100631292/", name: "下厨房" },
  "home-oyster-lettuce": { url: "https://thewoksoflife.com/cooked-lettuce-with-oyster-sauce-garlic/", name: "The Woks of Life" },
  "home-oyster-tofu": { url: "https://hk.lkk.com/zh-hk/recipes/home-style-oyster-sauce-silken-tofu", name: "Lee Kum Kee" },
  "home-pad-thai": { url: "https://thewoksoflife.com/pad-thai/", name: "The Woks of Life" },
  "home-pak-choi-dried-mushroom": { url: "https://thewoksoflife.com/dried-mushrooms/", name: "The Woks of Life" },
  "home-pan-fried-rice-noodles": { url: "https://www.madewithlau.com/recipes/pan-fried-rice-noodles", name: "Made With Lau" },
  "home-pan-radish-cake-style": { url: "https://www.madewithlau.com/recipes/chinese-turnip-cake", name: "Made With Lau" },
  "home-peanut-satay-noodle-bowl": { url: "https://thewoksoflife.com/chinese-noodle-soup/", name: "The Woks of Life" },
  "home-pesto-pasta": { url: "https://thewoksoflife.com/basil-mint-pesto-pasta-tomatoes-strawberries/", name: "The Woks of Life" },
  "home-pho-style-beef-noodles": { url: "https://www.madewithlau.com/recipes/beef-chow-fun", name: "Made With Lau" },
  "home-pineapple-fried-rice": { url: "https://www.madewithlau.com/recipes/pineapple-fried-rice", name: "Made With Lau" },
  "home-pineapple-sweet-sour-veg": { url: "https://thewoksoflife.com/sweet-sour-sauce/", name: "The Woks of Life" },
  "home-pork-cabbage": { url: "https://www.madewithlau.com/recipes/twice-cooked-pork", name: "Made With Lau" },
  "home-pork-chop-noodles": { url: "https://thewoksoflife.com/pork-pan-fried-noodles/", name: "The Woks of Life" },
  "home-pork-chop-onion": { url: "https://thewoksoflife.com/baked-pork-chop-rice/", name: "The Woks of Life" },
  "home-pork-mince-noodles": { url: "https://thewoksoflife.com/pork-pan-fried-noodles/", name: "The Woks of Life" },
  "home-pork-rib-clear-soup": { url: "https://thewoksoflife.com/chinese-watercress-soup-pork/", name: "The Woks of Life" },
  "home-potato-chicken": { url: "https://hk.lkk.com/zh-hk/recipes/oyster-flavoured-braised-chicken-wings-with-potatoes", name: "Lee Kum Kee" },
  "home-potato-spare-ribs": { url: "https://www.madewithlau.com/recipes/steamed-spare-ribs", name: "Made With Lau" },
  "home-pumpkin-spare-ribs": { url: "https://www.madewithlau.com/recipes/steamed-spare-ribs", name: "Made With Lau" },
  "home-red-braised-pork": { url: "https://www.madewithlau.com/recipes/fried-pork-belly", name: "Made With Lau" },
  "home-salmon-broccoli-pasta": { url: "https://www.bbc.co.uk/food/recipes/salmon_broccoli_pasta_39926", name: "BBC Food" },
  "home-salmon-miso-bowl": { url: "https://thewoksoflife.com/easy-miso-soup/", name: "The Woks of Life" },
  "home-salmon-rice-bowl": { url: "https://thewoksoflife.com/salmon-fried-rice/", name: "The Woks of Life" },
  "home-salt-pepper-fish": { url: "https://www.madewithlau.com/recipes/salt-pepper-fried-sole-fish", name: "Made With Lau" },
  "home-salt-pepper-ribs": { url: "https://www.madewithlau.com/recipes/steamed-spare-ribs", name: "Made With Lau" },
  "home-salt-pepper-shrimp": { url: "https://www.madewithlau.com/recipes/salt-pepper-shrimp", name: "Made With Lau" },
  "home-salt-pepper-squid": { url: "https://www.madewithlau.com/recipes/salt-pepper-squid", name: "Made With Lau" },
  "home-salt-pepper-tofu": { url: "https://www.madewithlau.com/recipes/salt-pepper-tofu", name: "Made With Lau" },
  "home-salted-egg-pork-patty": { url: "https://www.madewithlau.com/recipes/steamed-pork-patty", name: "Made With Lau" },
  "home-salted-fish-chicken-fried-rice": { url: "https://www.madewithlau.com/recipes/salted-fish-chicken-fried-rice", name: "Made With Lau" },
  "home-salted-fish-pork-patty": { url: "https://thewoksoflife.com/steamed-pork-salted-fish/", name: "The Woks of Life" },
  "home-san-bei-chicken": { url: "https://thewoksoflife.com/three-cup-chicken-san-bei-ji/", name: "The Woks of Life" },
  "home-satay-beef-noodles": { url: "https://thewoksoflife.com/chinese-noodle-soup/", name: "The Woks of Life" },
  "home-satay-beef-rice": { url: "https://www.madewithlau.com/recipes/beef-fried-rice", name: "Made With Lau" },
  "home-satay-chicken-pan": { url: "https://thewoksoflife.com/chicken-satay-with-peanut-sauce/", name: "The Woks of Life" },
  "home-sausage-sticky-rice": { url: "https://thewoksoflife.com/sticky-rice-with-chinese-sausage/", name: "The Woks of Life" },
  "home-sausage-veg-rice": { url: "https://thewoksoflife.com/chinese-sausage-fried-rice/", name: "The Woks of Life" },
  "home-scallion-pancake": { url: "https://thewoksoflife.com/avocado-scallion-pancake/", name: "The Woks of Life" },
  "home-scrambled-egg-toast": { url: "https://www.bbc.co.uk/food/recipes/scrambledeggandtoast_75736", name: "BBC Food" },
  "home-seaweed-soup": { url: "https://www.madewithlau.com/recipes/seaweed-soup", name: "Made With Lau" },
  "home-sesame-chicken-taiwanese": { url: "https://www.madewithlau.com/recipes/sesame-chicken", name: "Made With Lau" },
  "home-sesame-garlic-chicken-pasta": { url: "https://hk.lkk.com/zh-hk/recipes/garlic-chicken-linguine-with-sesame-oil", name: "Lee Kum Kee" },
  "home-sesame-green-beans": { url: "https://www.madewithlau.com/recipes/chinese-green-beans", name: "Made With Lau" },
  "home-shakshuka": { url: "https://thewoksoflife.com/shakshuka/", name: "The Woks of Life" },
  "home-shoyu-ramen-home": { url: "https://thewoksoflife.com/easy-miso-soup/", name: "The Woks of Life" },
  "home-shrimp-broccoli": { url: "https://thewoksoflife.com/shrimp-and-broccoli/", name: "The Woks of Life" },
  "home-shrimp-lotus-stir": { url: "https://thewoksoflife.com/lotus-root-recipe-stir-fry/", name: "The Woks of Life" },
  "home-shrimp-noodle-soup": { url: "https://www.madewithlau.com/recipes/wonton-noodle-soup", name: "Made With Lau" },
  "home-shrimp-pasta": { url: "https://www.madewithlau.com/recipes/pan-fried-shrimp-with-garlic", name: "Made With Lau" },
  "home-shrimp-taco-wrap": { url: "https://www.madewithlau.com/recipes/pan-fried-shrimp-with-garlic", name: "Made With Lau" },
  "home-shrimp-thai-basil-home": { url: "https://thewoksoflife.com/shrimp-fried-rice-thai-basil/", name: "The Woks of Life" },
  "home-silken-clam-soup": { url: "https://thewoksoflife.com/silken-soft-tofu/", name: "The Woks of Life" },
  "home-singapore-noodles": { url: "https://www.madewithlau.com/recipes/singapore-noodles", name: "Made With Lau" },
  "home-singapore-noodles-no-shrimp": { url: "https://www.madewithlau.com/recipes/singapore-noodles", name: "Made With Lau" },
  "home-smashed-cucumber": { url: "https://www.madewithlau.com/recipes/smashed-cucumber-salad", name: "Made With Lau" },
  "home-soy-braised-wings": { url: "https://www.madewithlau.com/recipes/fried-chicken-wings", name: "Made With Lau" },
  "home-soy-butter-noodles": { url: "https://thewoksoflife.com/soy-sauce-noodles/", name: "The Woks of Life" },
  "home-soy-chicken": { url: "https://www.madewithlau.com/recipes/soy-sauce-chicken", name: "Made With Lau" },
  "home-soy-egg-tofu-braise": { url: "https://thewoksoflife.com/braised-tofu/", name: "The Woks of Life" },
  "home-soy-fried-noodles": { url: "https://thewoksoflife.com/soy-sauce-noodles/", name: "The Woks of Life" },
  "home-soy-garlic-fried-chicken": { url: "https://thewoksoflife.com/soy-garlic-chicken-instant-ramen/", name: "The Woks of Life" },
  "home-soy-sauce-eggs": { url: "https://thewoksoflife.com/eggs-easy-soy-sauce/", name: "The Woks of Life" },
  "home-soy-steamed-fish": { url: "https://hk.lkk.com/zh-hk/recipes/steamed-fish-in-double-fermented-soy-sauce", name: "Lee Kum Kee" },
  "home-spicy-tofu-rice-bowl": { url: "https://www.madewithlau.com/recipes/mapo-tofu-pork", name: "Made With Lau" },
  "home-spinach-tofu-soup": { url: "https://www.madewithlau.com/recipes/spinach-tofu-soup", name: "Made With Lau" },
  "home-squid-ginger-scallion": { url: "https://www.madewithlau.com/recipes/ginger-scallion-sauce", name: "Made With Lau" },
  "home-steamed-beef-patty": { url: "https://www.madewithlau.com/recipes/minced-beef-with-rice", name: "Made With Lau" },
  "home-steamed-chicken-mushroom": { url: "https://thewoksoflife.com/chicken-dumplings-shiitake-mushrooms/", name: "The Woks of Life" },
  "home-steamed-egg-pork": { url: "https://www.madewithlau.com/recipes/steamed-egg-minced-pork", name: "Made With Lau" },
  "home-steamed-egg-shrimp": { url: "https://thewoksoflife.com/shrimp-egg-foo-young/", name: "The Woks of Life" },
  "home-steamed-eggs": { url: "https://www.madewithlau.com/recipes/steamed-egg", name: "Made With Lau" },
  "home-steamed-fish": { url: "https://www.madewithlau.com/recipes/steamed-fish-ginger-scallion", name: "Made With Lau" },
  "home-steamed-fish-tofu": { url: "https://thewoksoflife.com/clay-pot-fish-tofu/", name: "The Woks of Life" },
  "home-steamed-pork-patty": { url: "https://www.madewithlau.com/recipes/steamed-pork-patty", name: "Made With Lau" },
  "home-steamed-tofu-pork": { url: "https://hk.lkk.com/zh-hk/recipes/steamed-tofu-with-minced-pork", name: "Lee Kum Kee" },
  "home-stir-fried-bok-choy": { url: "https://www.madewithlau.com/recipes/stir-fried-bok-choy", name: "Made With Lau" },
  "home-sweet-potato-stirfry": { url: "https://thewoksoflife.com/suan-la-fen-hot-sour-sweet-potato-glass-noodle-soup/", name: "The Woks of Life" },
  "home-sweet-sour-pork": { url: "https://www.madewithlau.com/recipes/sweet-sour-pork", name: "Made With Lau" },
  "home-swiss-chicken-wings": { url: "https://www.madewithlau.com/recipes/fried-chicken-wings", name: "Made With Lau" },
  "home-taiwanese-tomato-egg-rice": { url: "https://www.madewithlau.com/recipes/tomato-and-eggs", name: "Made With Lau" },
  "home-teriyaki-chicken": { url: "https://thewoksoflife.com/mall-chicken-teriyaki/", name: "The Woks of Life" },
  "home-teriyaki-salmon": { url: "https://thewoksoflife.com/salmon-teriyaki-bowls/", name: "The Woks of Life" },
  "home-teriyaki-tofu-bowl": { url: "https://thewoksoflife.com/mall-chicken-teriyaki/", name: "The Woks of Life" },
  "home-thai-basil-chicken": { url: "https://thewoksoflife.com/chicken-and-thai-basil-stir-fry/", name: "The Woks of Life" },
  "home-thai-basil-green-beans": { url: "https://www.madewithlau.com/recipes/chinese-green-beans", name: "Made With Lau" },
  "home-thai-basil-mince-rice": { url: "https://thewoksoflife.com/chicken-and-thai-basil-stir-fry/", name: "The Woks of Life" },
  "home-thai-basil-pork-mince": { url: "https://thewoksoflife.com/thai-basil-pork-belly/", name: "The Woks of Life" },
  "home-thai-cucumber-salad": { url: "https://thewoksoflife.com/chinese-cucumber-salad/", name: "The Woks of Life" },
  "home-thai-green-curry-chicken": { url: "https://thewoksoflife.com/green-curry-chicken/", name: "The Woks of Life" },
  "home-thai-shrimp-stir-fry": { url: "https://thewoksoflife.com/shrimp-fried-rice-thai-basil/", name: "The Woks of Life" },
  "home-tofu-katsu": { url: "https://thewoksoflife.com/chicken-katsu-curry-rice/", name: "The Woks of Life" },
  "home-tofu-scramble-rice": { url: "https://thewoksoflife.com/tofu-fried-rice/", name: "The Woks of Life" },
  "home-tofu-skin-rib-soup": { url: "https://thewoksoflife.com/tofu-skin/", name: "The Woks of Life" },
  "home-tofu-skin-stirfry": { url: "https://thewoksoflife.com/tofu-skin/", name: "The Woks of Life" },
  "home-tofu-skin-veg-stir": { url: "https://thewoksoflife.com/tofu-skin/", name: "The Woks of Life" },
  "home-tofu-teriyaki": { url: "https://thewoksoflife.com/teriyaki-tofu/", name: "The Woks of Life" },
  "home-tom-yum": { url: "https://thewoksoflife.com/tom-yum-soup/", name: "The Woks of Life" },
  "home-tomato-beef": { url: "https://thewoksoflife.com/beef-tomato-stir-fry/", name: "The Woks of Life" },
  "home-tomato-brisket-soup": { url: "https://thewoksoflife.com/beef-tomato-stir-fry/", name: "The Woks of Life" },
  "home-tomato-egg": { url: "https://www.madewithlau.com/recipes/tomato-and-eggs", name: "Made With Lau" },
  "home-tomato-egg-drop-soup": { url: "https://thewoksoflife.com/tomato-egg-drop-soup/", name: "The Woks of Life" },
  "home-tomato-egg-noodles": { url: "https://thewoksoflife.com/stir-fried-tomato-and-egg/", name: "The Woks of Life" },
  "home-tomato-egg-rice": { url: "https://www.madewithlau.com/recipes/egg-fried-rice", name: "Made With Lau" },
  "home-tomato-egg-rice-bowl": { url: "https://www.madewithlau.com/recipes/egg-fried-rice", name: "Made With Lau" },
  "home-tomato-egg-veg-soup": { url: "https://thewoksoflife.com/stir-fried-tomato-and-egg/", name: "The Woks of Life" },
  "home-tomato-pork-chops": { url: "https://www.madewithlau.com/recipes/pan-fried-pork-chops", name: "Made With Lau" },
  "home-tomato-soup": { url: "https://www.madewithlau.com/recipes/tomato-tofu-soup", name: "Made With Lau" },
  "home-tomato-tofu": { url: "https://thewoksoflife.com/tomato-tofu/", name: "The Woks of Life" },
  "home-tomato-tofu-soup": { url: "https://www.madewithlau.com/recipes/tomato-tofu-soup", name: "Made With Lau" },
  "home-tuna-pasta": { url: "https://www.bbc.co.uk/food/recipes/creamy_tuna_one-pot_19168", name: "BBC Food" },
  "home-twice-cooked-pork": { url: "https://www.madewithlau.com/recipes/twice-cooked-pork", name: "Made With Lau" },
  "home-veg-claypot-rice": { url: "https://thewoksoflife.com/vegetable-fried-rice/", name: "The Woks of Life" },
  "home-veg-dan-dan": { url: "https://thewoksoflife.com/dan-dan-noodles/", name: "The Woks of Life" },
  "home-veg-gyudon": { url: "https://thewoksoflife.com/mushroom-fried-rice/", name: "The Woks of Life" },
  "home-veg-hot-sour-soup": { url: "https://thewoksoflife.com/vegetarian-hot-sour-soup/", name: "The Woks of Life" },
  "home-veg-ramen-home": { url: "https://thewoksoflife.com/vegetable-ramen/", name: "The Woks of Life" },
  "home-veg-sweet-sour": { url: "https://thewoksoflife.com/sweet-sour-sauce/", name: "The Woks of Life" },
  "home-vegan-mapo-tofu": { url: "https://thewoksoflife.com/vegan-mapo-tofu/", name: "The Woks of Life" },
  "home-water-spinach-beef": { url: "https://thewoksoflife.com/chinese-water-spinach/", name: "The Woks of Life" },
  "home-water-spinach-chili-garlic": { url: "https://thewoksoflife.com/chili-garlic-sauce/", name: "The Woks of Life" },
  "home-watercress-pork-rib": { url: "https://thewoksoflife.com/chinese-watercress-soup-pork/", name: "The Woks of Life" },
  "home-west-lake-beef-soup": { url: "https://www.madewithlau.com/recipes/west-lake-beef-soup", name: "Made With Lau" },
  "home-white-cut-chicken": { url: "https://www.madewithlau.com/recipes/white-cut-chicken", name: "Made With Lau" },
  "home-winter-melon-chicken-soup": { url: "https://www.madewithlau.com/recipes/winter-melon-seafood-soup", name: "Made With Lau" },
  "home-winter-melon-pork-stir": { url: "https://thewoksoflife.com/winter-melon-soup-pork-ribs/", name: "The Woks of Life" },
  "home-winter-melon-soup": { url: "https://www.madewithlau.com/recipes/winter-melon-seafood-soup", name: "Made With Lau" },
  "home-winter-melon-stirfry": { url: "https://www.madewithlau.com/recipes/winter-melon-seafood-soup", name: "Made With Lau" },
  "home-wonton-noodle-soup": { url: "https://www.madewithlau.com/recipes/wonton-noodle-soup", name: "Made With Lau" },
  "home-wonton-soup": { url: "https://www.madewithlau.com/recipes/wonton-noodle-soup", name: "Made With Lau" },
  "home-yangzhou-fried-rice": { url: "https://www.madewithlau.com/recipes/yangzhou-fried-rice", name: "Made With Lau" },
  "home-yuxiang-eggplant": { url: "https://thewoksoflife.com/fish-fragrant-eggplant-yuxiang-qiezi/", name: "The Woks of Life" },
  "home-yuxiang-shredded-pork": { url: "https://thewoksoflife.com/shredded-pork-stir-fry/", name: "The Woks of Life" },
  "home-zha-jiang-mian": { url: "https://www.madewithlau.com/recipes/zha-jiang-mian", name: "Made With Lau" },
}

/** Merge verified sourceUrl onto a recipe when missing. */
export function withRecipeSource(recipe: Recipe): Recipe {
  if (recipe.sourceUrl) return recipe
  const hit = RECIPE_SOURCES[recipe.id]
  if (!hit) return recipe
  return { ...recipe, sourceUrl: hit.url, sourceName: hit.name }
}
