import type { Recipe } from "@/lib/recipes"

/** Unsplash CDN photo URL (licensed for free use; hotlink these specific IDs). */
const u = (id: string) =>
  `https://images.unsplash.com/photo-${id}?w=800&q=80&auto=format&fit=crop`

/**
 * Stable category photos. Register a better per-id URL in RECIPE_IMAGES when you
 * want a closer match; new home-* recipes fall back via {@link inferRecipeImage}.
 */
export const IMG = {
  rice: u("1512058564366-18510be2db19"),
  egg: u("1525351484163-7529414344d8"),
  soup: u("1547592166-23ac45744acd"),
  veg: u("1540420773420-3366772f4999"),
  chicken: u("1604908176997-125f25cc6f3d"),
  bowl: u("1546069901-ba9599a7e63c"),
  seafood: u("1559339352-11d035aa65de"),
  tofu: u("1626082927389-6cd097cdc6ec"),
  salad: u("1512621776951-a57141f2eefd"),
  fish: u("1467003909585-2f8a72700288"),
  platter: u("1504674900247-0877df9cc836"),
  breakfast: u("1533089860892-a7c6f0a88666"),
  pasta: u("1563379926898-05f4575a45d8"),
  friedRice: u("1603133872878-684f208fb84b"),
  noodles: u("1562967914-608f82629710"),
  stew: u("1574484284002-952d92456975"),
  toast: u("1551218808-94e220e084d2"),
  meat: u("1544025162-d76694265947"),
  potato: u("1518977676601-b53f82aba655"),
} as const

export type ImageCategory = keyof typeof IMG

/**
 * Explicit id → image map for the cookable `home-*` book.
 * Additive only — do not put recipe text here. Wave/growth agents can keep
 * editing more-dishes*; register a photo with one line here (or rely on infer).
 */
export const RECIPE_IMAGES: Record<string, string> = {
  "home-avocado-toast": IMG.toast,
  "home-bacon-egg-rice": IMG.friedRice,
  "home-bacon-pasta": IMG.pasta,
  "home-baked-eggs-spinach": IMG.breakfast,
  "home-bean-sprout-stirfry": IMG.veg,
  "home-bean-tomato-stew": IMG.stew,
  "home-beef-broccoli": IMG.meat,
  "home-beef-snow-peas": IMG.meat,
  "home-beef-tomato-noodles": IMG.noodles,
  "home-bell-pepper-beef": IMG.meat,
  "home-braised-tofu-chicken": IMG.tofu,
  "home-cabbage-stirfry": IMG.veg,
  "home-carrot-egg-stirfry": IMG.egg,
  "home-cauliflower-stirfry": IMG.veg,
  "home-celery-pork": IMG.meat,
  "home-century-egg-congee": IMG.bowl,
  "home-century-egg-tofu": IMG.tofu,
  "home-cheese-omelette": IMG.egg,
  "home-chicken-broccoli": IMG.chicken,
  "home-chicken-carbonara": IMG.pasta,
  "home-chicken-corn-soup": IMG.soup,
  "home-chicken-mushroom": IMG.chicken,
  "home-chicken-mushroom-tofu": IMG.tofu,
  "home-chicken-salad": IMG.salad,
  "home-chicken-veg-soup": IMG.soup,
  "home-chinese-sausage-rice": IMG.friedRice,
  "home-chow-mein": IMG.noodles,
  "home-claypot-style-rice": IMG.rice,
  "home-congee": IMG.bowl,
  "home-corn-egg-scramble": IMG.egg,
  "home-cucumber-egg": IMG.egg,
  "home-egg-drop-soup": IMG.soup,
  "home-egg-foo-young": IMG.egg,
  "home-egg-fried-rice": IMG.friedRice,
  "home-egg-mayo-sandwich": IMG.toast,
  "home-french-toast": IMG.toast,
  "home-fu-yung-egg-lkk": IMG.egg,
  "home-garlic-broccoli": IMG.veg,
  "home-garlic-choi-sum": IMG.veg,
  "home-garlic-eggplant": IMG.veg,
  "home-garlic-pak-choi": IMG.veg,
  "home-garlic-shrimp": IMG.seafood,
  "home-garlic-spinach": IMG.veg,
  "home-ginger-chicken": IMG.chicken,
  "home-ginger-fried-rice": IMG.friedRice,
  "home-grilled-cheese": IMG.toast,
  "home-ham-cheese-toastie": IMG.toast,
  "home-hk-macaroni-soup": IMG.soup,
  "home-honey-garlic-chicken": IMG.chicken,
  "home-hot-sour-soup": IMG.soup,
  "home-instant-noodles-egg": IMG.noodles,
  "home-jacket-potato-tuna": IMG.potato,
  "home-kimchi-fried-rice": IMG.friedRice,
  "home-leftover-fried-rice": IMG.friedRice,
  "home-lemon-chicken": IMG.chicken,
  "home-lo-mein": IMG.noodles,
  "home-luncheon-fried-rice": IMG.friedRice,
  "home-mapo-tofu": IMG.tofu,
  "home-mushroom-egg-rice": IMG.friedRice,
  "home-mushroom-pasta": IMG.pasta,
  "home-omelette-rice": IMG.friedRice,
  "home-orange-chicken": IMG.chicken,
  "home-oyster-gai-lan": IMG.veg,
  "home-oyster-lettuce": IMG.veg,
  "home-oyster-tofu": IMG.tofu,
  "home-pan-fried-rice-noodles": IMG.noodles,
  "home-pancakes-simple": IMG.breakfast,
  "home-pork-cabbage": IMG.meat,
  "home-pork-chop-onion": IMG.meat,
  "home-pork-mince-noodles": IMG.noodles,
  "home-potato-chicken": IMG.chicken,
  "home-potato-stirfry": IMG.veg,
  "home-salmon-broccoli-pasta": IMG.pasta,
  "home-salmon-rice-bowl": IMG.fish,
  "home-salt-pepper-tofu": IMG.tofu,
  "home-sausage-egg-noodles": IMG.noodles,
  "home-sausage-pasta": IMG.pasta,
  "home-scallion-noodles": IMG.noodles,
  "home-scrambled-egg-toast": IMG.toast,
  "home-sesame-garlic-chicken-pasta": IMG.pasta,
  "home-shrimp-broccoli": IMG.seafood,
  "home-shrimp-egg": IMG.seafood,
  "home-shrimp-noodle-soup": IMG.soup,
  "home-shrimp-pasta": IMG.pasta,
  "home-singapore-noodles": IMG.noodles,
  "home-slippery-egg-chicken": IMG.chicken,
  "home-smashed-cucumber": IMG.salad,
  "home-soy-chicken": IMG.chicken,
  "home-soy-steamed-fish": IMG.fish,
  "home-spinach-tofu-soup": IMG.soup,
  "home-steamed-egg-pork": IMG.egg,
  "home-steamed-eggs": IMG.egg,
  "home-steamed-fish": IMG.fish,
  "home-steamed-pork-patty": IMG.meat,
  "home-steamed-tofu-pork": IMG.tofu,
  "home-stir-fried-bok-choy": IMG.veg,
  "home-sweet-potato-rice": IMG.rice,
  "home-tofu-shrimp": IMG.tofu,
  "home-tomato-beef": IMG.meat,
  "home-tomato-egg": IMG.egg,
  "home-tomato-egg-noodles": IMG.noodles,
  "home-tomato-egg-rice": IMG.egg,
  "home-tomato-soup": IMG.soup,
  "home-tomato-tofu": IMG.tofu,
  "home-tomato-tofu-soup": IMG.soup,
  "home-tuna-fried-rice": IMG.friedRice,
  "home-tuna-pasta": IMG.pasta,
  "home-west-lake-beef-soup": IMG.soup,
  "home-yogurt-berry-bowl": IMG.breakfast,
  "home-zucchini-egg": IMG.egg,
  "home-baked-pork-chop-rice": IMG.meat,
  "home-baked-seafood-rice": IMG.fish,
  "home-beef-choi-sum": IMG.meat,
  "home-beef-chow-fun": IMG.meat,
  "home-beef-fried-noodles": IMG.noodles,
  "home-beef-tomato-rice": IMG.meat,
  "home-bibimbap": IMG.egg,
  "home-black-bean-beef": IMG.meat,
  "home-black-bean-ribs": IMG.meat,
  "home-braised-egg-rice": IMG.egg,
  "home-braised-tofu-pork": IMG.tofu,
  "home-braised-tofu-veg": IMG.tofu,
  "home-broccoli-beef-garlic": IMG.meat,
  "home-bulgogi-beef": IMG.meat,
  "home-cabbage-pork-filling": IMG.meat,
  "home-cantonese-chicken-noodles": IMG.soup,
  "home-celery-tofu": IMG.tofu,
  "home-century-egg-tofu-soup": IMG.tofu,
  "home-char-siu-home": IMG.meat,
  "home-chawanmushi-egg": IMG.egg,
  "home-chicken-katsu-pan": IMG.chicken,
  "home-chicken-steak-rice": IMG.chicken,
  "home-chili-fried-tofu": IMG.tofu,
  "home-chili-garlic-eggplant": IMG.veg,
  "home-chili-oil-lettuce": IMG.salad,
  "home-chili-oil-noodles": IMG.noodles,
  "home-chili-oil-wonton": IMG.meat,
  "home-chongqing-noodles": IMG.noodles,
  "home-clearout-egg-drop": IMG.soup,
  "home-cold-chili-noodles": IMG.noodles,
  "home-cold-sesame-noodles": IMG.noodles,
  "home-cold-tofu-soy": IMG.tofu,
  "home-condensed-milk-toast": IMG.toast,
  "home-corn-butter-rice": IMG.rice,
  "home-corned-beef-macaroni": IMG.noodles,
  "home-creamed-corn-soup": IMG.soup,
  "home-cumin-beef": IMG.meat,
  "home-dan-dan-noodles": IMG.noodles,
  "home-doenjang-jjigae": IMG.tofu,
  "home-dry-fried-green-beans": IMG.meat,
  "home-dry-pot-cauliflower": IMG.meat,
  "home-egg-tofu-stew": IMG.tofu,
  "home-eggplant-mince": IMG.veg,
  "home-eggplant-pork-claypot": IMG.veg,
  "home-fermented-tofu-greens": IMG.tofu,
  "home-fridge-fried-noodles": IMG.noodles,
  "home-garlic-cucumber-spicy": IMG.salad,
  "home-garlic-green-beans": IMG.platter,
  "home-garlic-lettuce": IMG.salad,
  "home-garlic-snow-peas": IMG.platter,
  "home-ginger-choi-sum": IMG.veg,
  "home-glass-noodle-stirfry": IMG.noodles,
  "home-gyudon": IMG.noodles,
  "home-ham-macaroni-soup": IMG.soup,
  "home-hk-borscht": IMG.soup,
  "home-hk-curry-brisket": IMG.meat,
  "home-hk-curry-chicken": IMG.chicken,
  "home-hk-egg-sandwich": IMG.toast,
  "home-hk-spaghetti": IMG.noodles,
  "home-homestyle-tofu": IMG.tofu,
  "home-hot-dry-noodles": IMG.noodles,
  "home-hotwater-noodle-bowl": IMG.soup,
  "home-japanese-curry-rice": IMG.chicken,
  "home-kimchi-jjigae": IMG.tofu,
  "home-kimchi-leftover-stew": IMG.soup,
  "home-kongnamul-muchim": IMG.platter,
  "home-korean-cucumber-salad": IMG.salad,
  "home-korean-egg-roll": IMG.egg,
  "home-kung-pao-chicken": IMG.chicken,
  "home-laziji-chicken": IMG.chicken,
  "home-leftover-chicken-congee": IMG.bowl,
  "home-leftover-noodle-toss": IMG.noodles,
  "home-leftover-steam-rice": IMG.veg,
  "home-leftover-wrap": IMG.veg,
  "home-lotus-rib-soup": IMG.soup,
  "home-luncheon-egg-noodles": IMG.noodles,
  "home-mapo-eggplant": IMG.veg,
  "home-mapo-tofu-veg": IMG.tofu,
  "home-miso-soup": IMG.tofu,
  "home-mushroom-bok-choy": IMG.veg,
  "home-mushroom-claypot-rice": IMG.chicken,
  "home-nasu-dengaku": IMG.veg,
  "home-nikujaga": IMG.meat,
  "home-oyakodon": IMG.chicken,
  "home-oyster-choi-sum": IMG.veg,
  "home-pineapple-chicken": IMG.chicken,
  "home-pork-chop-noodles": IMG.noodles,
  "home-pork-mince-rice-bowl": IMG.meat,
  "home-potato-spare-ribs": IMG.meat,
  "home-salmon-ochazuke": IMG.fish,
  "home-salt-pepper-mushrooms": IMG.platter,
  "home-salted-egg-pork-patty": IMG.meat,
  "home-salted-fish-chicken-fried-rice": IMG.friedRice,
  "home-satay-beef-noodles": IMG.soup,
  "home-satay-beef-rice": IMG.meat,
  "home-sausage-veg-rice": IMG.meat,
  "home-seafood-fried-rice": IMG.friedRice,
  "home-seaweed-soup": IMG.soup,
  "home-shogayaki": IMG.meat,
  "home-shrimp-wonton": IMG.seafood,
  "home-shuizhu-mild": IMG.tofu,
  "home-sour-cabbage-pork": IMG.meat,
  "home-soy-butter-noodles": IMG.noodles,
  "home-soy-fried-noodles": IMG.noodles,
  "home-soy-garlic-fried-chicken": IMG.chicken,
  "home-soy-greens-rice": IMG.veg,
  "home-spicy-pork-bulgogi": IMG.meat,
  "home-spinach-egg-drop": IMG.egg,
  "home-spinach-gomaae": IMG.veg,
  "home-steamed-chicken-mushroom": IMG.chicken,
  "home-steamed-fish-fillets": IMG.fish,
  "home-sundubu-jjigae": IMG.tofu,
  "home-sweet-sour-pork": IMG.meat,
  "home-swiss-chicken-wings": IMG.chicken,
  "home-tamago-gohan": IMG.chicken,
  "home-tamago-sando": IMG.toast,
  "home-teriyaki-chicken": IMG.chicken,
  "home-teriyaki-salmon": IMG.fish,
  "home-tofu-egg-scramble": IMG.tofu,
  "home-tofu-miso-stew": IMG.tofu,
  "home-tofu-skin-stirfry": IMG.tofu,
  "home-tomato-cabbage": IMG.veg,
  "home-tomato-egg-drop-soup": IMG.soup,
  "home-tomato-egg-rice-bowl": IMG.egg,
  "home-tomato-potato-stew": IMG.soup,
  "home-tomato-soup-macaroni": IMG.soup,
  "home-tteokbokki": IMG.veg,
  "home-tuna-mayo-onigiri": IMG.fish,
  "home-tuna-rice-ball": IMG.fish,
  "home-twice-cooked-pork": IMG.meat,
  "home-udon-soy-broth": IMG.soup,
  "home-white-cut-chicken": IMG.chicken,
  "home-winter-melon-soup": IMG.soup,
  "home-wonton-noodle-soup": IMG.soup,
  "home-wonton-soup": IMG.soup,
  "home-yakisoba": IMG.noodles,
  "home-yangzhou-fried-rice": IMG.friedRice,
  "home-yuxiang-eggplant": IMG.veg,
  "home-yuxiang-shredded-pork": IMG.fish,
  "home-zha-jiang-mian": IMG.noodles,
}

/** Keyword → category for unmapped / newly added home recipes (500+ scale). */
const INFER_RULES: { re: RegExp; key: ImageCategory }[] = [
  { re: /eggplant|aubergine/, key: "veg" },
  { re: /tofu|mapo|豆腐/, key: "tofu" },
  { re: /congee|porridge|粥/, key: "bowl" },
  { re: /soup|stew|broth|汤|湯/, key: "soup" },
  { re: /noodle|mein|pasta|macaroni|udon|ramen|麵|面/, key: "noodles" },
  { re: /fried.?rice|炒飯|炒饭/, key: "friedRice" },
  { re: /toast|sandwich|toastie/, key: "toast" },
  { re: /pancake|yogurt|granola|breakfast/, key: "breakfast" },
  { re: /salad|cucumber|生菜/, key: "salad" },
  { re: /fish|salmon|鳕|魚|鱼/, key: "fish" },
  { re: /shrimp|prawn|scallop|海鮮|海鲜/, key: "seafood" },
  { re: /chicken|雞|鸡/, key: "chicken" },
  { re: /beef|pork|bacon|sausage|ham|肉|豬|牛/, key: "meat" },
  { re: /potato|jacket/, key: "potato" },
  { re: /egg|omelette|煎蛋|蒸蛋/, key: "egg" },
  { re: /broccoli|cabbage|spinach|lettuce|choi|bok|gai.?lan|greens|vegetable|菜/, key: "veg" },
  { re: /rice|飯|饭/, key: "rice" },
]

/** Infer a category photo from dish name / id / ingredients. */
export function inferRecipeImage(recipe: Pick<Recipe, "id" | "name" | "need" | "zh">): string {
  const hay = [recipe.id, recipe.name, recipe.zh?.name ?? "", ...(recipe.need ?? [])]
    .join(" ")
    .toLowerCase()
  for (const { re, key } of INFER_RULES) {
    if (re.test(hay)) return IMG[key]
  }
  return IMG.platter
}

/** Resolve the display image for a recipe (inline → map → infer). */
export function recipeImage(recipe: Recipe): string {
  if (recipe.image?.startsWith("https://") || recipe.image?.startsWith("/")) {
    return recipe.image
  }
  return RECIPE_IMAGES[recipe.id] ?? inferRecipeImage(recipe)
}

/** Merge a stored/inferred photo onto a recipe without clobbering inline fields. */
export function enrichRecipe(recipe: Recipe): Recipe {
  if (recipe.image) return recipe
  const image = RECIPE_IMAGES[recipe.id] ?? (recipe.id.startsWith("home-") ? inferRecipeImage(recipe) : undefined)
  if (!image) return recipe
  return { ...recipe, image }
}

export function hasRecipeImage(recipe: Recipe): boolean {
  return Boolean(recipe.image || RECIPE_IMAGES[recipe.id] || recipe.id.startsWith("home-"))
}
