export type IngredientCategory =
  | "protein"
  | "veg"
  | "carb"
  | "dairy"
  | "sauce"
  | "spice"
  | "pantry"
  | "other"

/** Canonical fridge/pantry ingredient registry. Dishes must reference `name` only. */
export type ShelfFood = {
  /** Stable kebab-case id — never rename casually; `name` is the display/canonical key for recipes. */
  id: string
  name: string
  /** EN + ZH aliases matching HK supermarket / wet-market packaging where possible. */
  aliases: string[]
  category: IngredientCategory
  location: "fridge" | "freezer" | "pantry"
  days: number
  /** Pantry staple — prefer recipe `optional`, not a core cook material. */
  staple?: boolean
}

export const SHELF: ShelfFood[] = [
  {
    id: "milk",
    name: "Milk",
    aliases: [
      "fresh milk",
      "whole milk",
      "skim milk",
      "2% milk",
      "牛奶",
      "鮮奶",
      "鲜奶",
      "全脂牛奶",
    ],
    category: "dairy",
    location: "fridge",
    days: 7,
  },
  {
    id: "uht-milk-opened",
    name: "UHT Milk (opened)",
    aliases: [
      "uht",
      "long life milk",
      "保久乳",
      "UHT牛奶",
      "長壽奶",
    ],
    category: "dairy",
    location: "fridge",
    days: 5,
  },
  {
    id: "yogurt",
    name: "Yogurt",
    aliases: [
      "yoghurt",
      "greek yogurt",
      "乳酪",
      "酸奶",
      "希腊乳酪",
      "Greek yogurt",
    ],
    category: "dairy",
    location: "fridge",
    days: 14,
  },
  {
    id: "butter",
    name: "Butter",
    aliases: [
      "牛油",
      "黃油",
      "黄油",
      "奶油",
    ],
    category: "dairy",
    location: "fridge",
    days: 60,
  },
  {
    id: "cheddar",
    name: "Cheddar",
    aliases: [
      "hard cheese",
      "cheese",
      "車打芝士",
      "芝士",
      "奶酪",
    ],
    category: "dairy",
    location: "fridge",
    days: 21,
  },
  {
    id: "mozzarella",
    name: "Mozzarella",
    aliases: [
      "fresh mozzarella",
      "莫札瑞拉",
      "马苏里拉",
      "水牛芝士",
    ],
    category: "dairy",
    location: "fridge",
    days: 7,
  },
  {
    id: "cream-cheese",
    name: "Cream cheese",
    aliases: [
      "奶油芝士",
      "乳脂芝士",
    ],
    category: "dairy",
    location: "fridge",
    days: 14,
  },
  {
    id: "sour-cream",
    name: "Sour cream",
    aliases: [
      "酸忌廉",
      "酸奶油",
    ],
    category: "dairy",
    location: "fridge",
    days: 14,
  },
  {
    id: "eggs",
    name: "Eggs",
    aliases: [
      "egg",
      "fresh eggs",
      "fried egg",
      "soft boiled egg",
      "蛋",
      "雞蛋",
      "鸡蛋",
      "鮮雞蛋",
      "鲜鸡蛋",
      "非籠養雞蛋",
    ],
    category: "dairy",
    location: "fridge",
    days: 28,
  },
  {
    id: "tofu",
    name: "Tofu",
    aliases: [
      "bean curd",
      "firm tofu",
      "silken tofu",
      "豆腐",
      "硬豆腐",
      "板豆腐",
    ],
    category: "protein",
    location: "fridge",
    days: 5,
  },
  {
    id: "chicken-breast",
    name: "Chicken breast",
    aliases: [
      "chicken",
      "raw chicken",
      "雞胸",
      "鸡胸",
      "雞胸肉",
      "鸡肉",
    ],
    category: "protein",
    location: "fridge",
    days: 2,
  },
  {
    id: "chicken-thighs",
    name: "Chicken thighs",
    aliases: [
      "chicken leg",
      "雞髀",
      "鸡腿",
      "雞腿",
    ],
    category: "protein",
    location: "fridge",
    days: 2,
  },
  {
    id: "ground-beef",
    name: "Ground beef",
    aliases: [
      "minced beef",
      "beef mince",
      "牛絞肉",
      "免治牛肉",
      "牛肉碎",
    ],
    category: "protein",
    location: "fridge",
    days: 2,
  },
  {
    id: "beef-steak",
    name: "Beef steak",
    aliases: [
      "steak",
      "beef",
      "牛扒",
      "牛排",
      "牛肉",
    ],
    category: "protein",
    location: "fridge",
    days: 4,
  },
  {
    id: "pork-chops",
    name: "Pork chops",
    aliases: [
      "pork",
      "pork loin",
      "豬扒",
      "猪扒",
      "豬排",
    ],
    category: "protein",
    location: "fridge",
    days: 4,
  },
  {
    id: "bacon",
    name: "Bacon",
    aliases: [
      "煙肉",
      "烟肉",
      "培根",
    ],
    category: "protein",
    location: "fridge",
    days: 7,
  },
  {
    id: "ham",
    name: "Ham",
    aliases: [
      "sliced ham",
      "火腿",
      "火腿片",
    ],
    category: "protein",
    location: "fridge",
    days: 5,
  },
  {
    id: "sausages",
    name: "Sausages",
    aliases: [
      "sausage",
      "hot dog",
      "香腸",
      "香肠",
      "肉腸",
    ],
    category: "protein",
    location: "fridge",
    days: 3,
  },
  {
    id: "salmon",
    name: "Salmon",
    aliases: [
      "fish",
      "raw salmon",
      "三文魚",
      "三文鱼",
      "鮭魚",
    ],
    category: "protein",
    location: "fridge",
    days: 2,
  },
  {
    id: "white-fish",
    name: "White fish",
    aliases: [
      "cod",
      "cod fillet",
      "seabass",
      "sea bass",
      "snapper",
      "白魚",
      "白鱼",
      "鱸魚",
      "鲈鱼",
    ],
    category: "protein",
    location: "fridge",
    days: 2,
  },
  {
    id: "shrimp",
    name: "Shrimp",
    aliases: [
      "prawns",
      "prawn",
      "蝦",
      "虾",
      "蝦仁",
      "大蝦",
    ],
    category: "protein",
    location: "fridge",
    days: 2,
  },
  {
    id: "cooked-leftovers",
    name: "Cooked leftovers",
    aliases: [
      "leftovers",
      "leftover",
      "takeaway",
      "剩菜",
      "隔夜菜",
      "剩餸",
      "熟食",
    ],
    category: "carb",
    location: "fridge",
    days: 3,
  },
  {
    id: "lettuce",
    name: "Lettuce",
    aliases: [
      "romaine",
      "iceberg",
      "leafy greens",
      "生菜",
      "玻璃生菜",
    ],
    category: "veg",
    location: "fridge",
    days: 7,
  },
  {
    id: "spinach",
    name: "Spinach",
    aliases: [
      "baby spinach",
      "菠菜",
      "莧菜",
    ],
    category: "veg",
    location: "fridge",
    days: 5,
  },
  {
    id: "pak-choi",
    name: "Pak choi",
    aliases: [
      "bok choy",
      "bok choi",
      "shanghai greens",
      "白菜仔",
      "小白菜",
    ],
    category: "veg",
    location: "fridge",
    days: 5,
  },
  {
    id: "choi-sum",
    name: "Choi sum",
    aliases: [
      "choy sum",
      "cai xin",
      "菜心",
      "菜芯",
      "choy sum vegetable",
    ],
    category: "veg",
    location: "fridge",
    days: 4,
  },
  {
    id: "gai-lan",
    name: "Gai lan",
    aliases: [
      "chinese broccoli",
      "kai lan",
      "芥蘭",
      "芥兰",
      "Chinese broccoli",
    ],
    category: "veg",
    location: "fridge",
    days: 5,
  },
  {
    id: "broccoli",
    name: "Broccoli",
    aliases: [
      "西蘭花",
      "西兰花",
      "綠花椰菜",
    ],
    category: "veg",
    location: "fridge",
    days: 5,
  },
  {
    id: "cauliflower",
    name: "Cauliflower",
    aliases: [
      "椰菜花",
      "花椰菜",
    ],
    category: "veg",
    location: "fridge",
    days: 7,
  },
  {
    id: "cabbage",
    name: "Cabbage",
    aliases: [
      "napa cabbage",
      "wong bak",
      "chinese cabbage",
      "椰菜",
      "高麗菜",
      "捲心菜",
    ],
    category: "veg",
    location: "fridge",
    days: 12,
  },
  {
    id: "carrots",
    name: "Carrots",
    aliases: [
      "carrot",
      "紅蘿蔔",
      "红萝卜",
      "甘筍",
      "甘笋",
      "胡蘿蔔",
    ],
    category: "veg",
    location: "fridge",
    days: 21,
  },
  {
    id: "celery",
    name: "Celery",
    aliases: [
      "西芹",
      "芹菜",
    ],
    category: "veg",
    location: "fridge",
    days: 14,
  },
  {
    id: "cucumber",
    name: "Cucumber",
    aliases: [
      "青瓜",
      "黃瓜",
      "黄瓜",
    ],
    category: "veg",
    location: "fridge",
    days: 6,
  },
  {
    id: "tomato",
    name: "Tomato",
    aliases: [
      "tomatoes",
      "番茄",
      "蕃茄",
      "西红柿",
    ],
    category: "veg",
    location: "fridge",
    days: 7,
  },
  {
    id: "bell-pepper",
    name: "Bell pepper",
    aliases: [
      "capsicum",
      "red pepper",
      "green pepper",
      "灯笼椒",
      "燈籠椒",
      "青椒",
      "彩椒",
      "甜椒",
    ],
    category: "veg",
    location: "fridge",
    days: 8,
  },
  {
    id: "onion",
    name: "Onion",
    aliases: [
      "onions",
      "yellow onion",
      "洋蔥",
      "洋葱",
    ],
    category: "veg",
    location: "pantry",
    days: 30,
    staple: true,
  },
  {
    id: "spring-onion",
    name: "Spring onion",
    aliases: [
      "green onion",
      "scallion",
      "green onions",
      "蔥",
      "葱",
      "青蔥",
      "青葱",
      "蔥花",
    ],
    category: "veg",
    location: "fridge",
    days: 7,
    staple: true,
  },
  {
    id: "garlic",
    name: "Garlic",
    aliases: [
      "garlic clove",
      "garlic cloves",
      "蒜",
      "蒜頭",
      "蒜头",
      "蒜蓉",
      "大蒜",
    ],
    category: "veg",
    location: "pantry",
    days: 30,
    staple: true,
  },
  {
    id: "ginger",
    name: "Ginger",
    aliases: [
      "薑",
      "姜",
      "薑片",
      "薑蓉",
    ],
    category: "veg",
    location: "fridge",
    days: 21,
    staple: true,
  },
  {
    id: "potato",
    name: "Potato",
    aliases: [
      "potatoes",
      "薯仔",
      "土豆",
      "馬鈴薯",
    ],
    category: "veg",
    location: "pantry",
    days: 21,
  },
  {
    id: "sweet-potato",
    name: "Sweet potato",
    aliases: [
      "番薯",
      "地瓜",
    ],
    category: "veg",
    location: "pantry",
    days: 21,
  },
  {
    id: "mushroom",
    name: "Mushroom",
    aliases: [
      "mushrooms",
      "shiitake",
      "button mushroom",
      "蘑菇",
      "鮮菇",
      "洋菇",
    ],
    category: "veg",
    location: "fridge",
    days: 5,
  },
  {
    id: "corn",
    name: "Corn",
    aliases: [
      "corn on the cob",
      "sweet corn",
      "粟米",
      "玉米",
    ],
    category: "veg",
    location: "fridge",
    days: 3,
  },
  {
    id: "eggplant",
    name: "Eggplant",
    aliases: [
      "aubergine",
      "茄子",
      "矮瓜",
    ],
    category: "veg",
    location: "fridge",
    days: 5,
  },
  {
    id: "zucchini",
    name: "Zucchini",
    aliases: [
      "courgette",
      "翠玉瓜",
      "節瓜",
      "zucchini",
    ],
    category: "veg",
    location: "fridge",
    days: 5,
  },
  {
    id: "apple",
    name: "Apple",
    aliases: [
      "apples",
      "蘋果",
      "苹果",
    ],
    category: "other",
    location: "fridge",
    days: 21,
  },
  {
    id: "banana",
    name: "Banana",
    aliases: [
      "bananas",
      "香蕉",
    ],
    category: "other",
    location: "pantry",
    days: 5,
  },
  {
    id: "orange",
    name: "Orange",
    aliases: [
      "oranges",
      "citrus",
      "橙",
      "橘子",
    ],
    category: "other",
    location: "fridge",
    days: 14,
  },
  {
    id: "lemon",
    name: "Lemon",
    aliases: [
      "lemons",
      "lemon juice",
      "檸檬汁",
      "檸檬",
      "柠檬",
    ],
    category: "other",
    location: "fridge",
    days: 21,
  },
  {
    id: "berries",
    name: "Berries",
    aliases: [
      "strawberry",
      "blueberry",
      "raspberry",
      "strawberries",
      "莓",
      "藍莓",
      "草莓",
      "雜莓",
    ],
    category: "other",
    location: "fridge",
    days: 4,
  },
  {
    id: "grapes",
    name: "Grapes",
    aliases: [
      "提子",
      "葡萄",
    ],
    category: "other",
    location: "fridge",
    days: 7,
  },
  {
    id: "avocado",
    name: "Avocado",
    aliases: [
      "ripe avocado",
      "hass avocado",
      "牛油果",
      "鳄梨",
      "鱷梨",
      "avocado Hass",
      "Hass avocado",
    ],
    category: "other",
    location: "pantry",
    days: 4,
  },
  {
    id: "mango",
    name: "Mango",
    aliases: [
      "芒果",
    ],
    category: "other",
    location: "pantry",
    days: 5,
  },
  {
    id: "rice",
    name: "Rice",
    aliases: [
      "uncooked rice",
      "jasmine rice",
      "米",
      "香米",
      "茉莉香米",
      "珍珠米",
      "泰國香米",
    ],
    category: "carb",
    location: "pantry",
    days: 365,
  },
  {
    id: "cooked-rice",
    name: "Cooked rice",
    aliases: [
      "leftover rice",
      "day old rice",
      "cold rice",
      "白饭",
      "白飯",
      "冷饭",
      "冷飯",
      "剩飯",
      "隔夜飯",
    ],
    category: "carb",
    location: "fridge",
    days: 3,
  },
  {
    id: "noodles",
    name: "Noodles",
    aliases: [
      "egg noodles",
      "ramen",
      "udon",
      "rice noodles",
      "gong zai mein",
      "麵",
      "面",
      "蛋麵",
      "生麵",
    ],
    category: "carb",
    location: "pantry",
    days: 180,
  },
  {
    id: "pasta",
    name: "Pasta",
    aliases: [
      "spaghetti",
      "意粉",
      "意大利粉",
      "通心粉",
    ],
    category: "carb",
    location: "pantry",
    days: 365,
  },
  {
    id: "bread",
    name: "Bread",
    aliases: [
      "loaf",
      "toast",
      "sourdough",
      "sourdough toast",
      "toast bread",
      "切片麵包",
      "酸種",
      "麵包",
      "面包",
      "多士",
    ],
    category: "carb",
    location: "pantry",
    days: 5,
  },
  {
    id: "tortilla",
    name: "Tortilla",
    aliases: [
      "wrap",
      "墨西哥餅",
      "玉米餅",
    ],
    category: "carb",
    location: "pantry",
    days: 10,
  },
  {
    id: "soy-sauce",
    name: "Soy sauce",
    aliases: [
      "light soy sauce",
      "dark soy sauce",
      "regular soy sauce",
      "生抽",
      "老抽",
      "酱油",
      "醬油",
      "豉油",
      "金標生抽",
      "淡豉油",
      "light soy",
      "dark soy",
    ],
    category: "sauce",
    location: "pantry",
    days: 365,
    staple: true,
  },
  {
    id: "oyster-sauce",
    name: "Oyster sauce",
    aliases: [
      "蠔油",
      "蚝油",
      "舊庄特級蠔油",
      "鮮蠔油",
    ],
    category: "sauce",
    location: "fridge",
    days: 180,
    staple: true,
  },
  {
    id: "hoisin-sauce",
    name: "Hoisin sauce",
    aliases: [
      "海鮮醬",
      "海鲜酱",
      "柱侯醬",
    ],
    category: "sauce",
    location: "fridge",
    days: 180,
  },
  {
    id: "chili-oil",
    name: "Chili oil",
    aliases: [
      "chilli oil",
      "chili crisp",
      "辣椒油",
      "辣油",
      "紅油",
    ],
    category: "sauce",
    location: "pantry",
    days: 180,
    staple: true,
  },
  {
    id: "ketchup",
    name: "Ketchup",
    aliases: [
      "茄汁",
      "番茄醬",
      "番茄酱",
    ],
    category: "sauce",
    location: "fridge",
    days: 180,
  },
  {
    id: "mayonnaise",
    name: "Mayonnaise",
    aliases: [
      "mayo",
      "蛋黃醬",
      "蛋黄酱",
      "美乃滋",
    ],
    category: "sauce",
    location: "fridge",
    days: 60,
  },
  {
    id: "mustard",
    name: "Mustard",
    aliases: [
      "芥末",
      "芥末醬",
    ],
    category: "sauce",
    location: "fridge",
    days: 180,
  },
  {
    id: "olive-oil",
    name: "Olive oil",
    aliases: [
      "extra virgin olive oil",
      "evoo",
      "EVOO",
      "virgin olive oil",
      "特級初榨橄欖油",
      "橄欖油",
      "橄榄油",
    ],
    category: "sauce",
    location: "pantry",
    days: 365,
    staple: true,
  },
  {
    id: "sesame-oil",
    name: "Sesame oil",
    aliases: [
      "麻油",
      "香油",
      "芝麻油",
    ],
    category: "sauce",
    location: "pantry",
    days: 180,
    staple: true,
  },
  {
    id: "vinegar",
    name: "Vinegar",
    aliases: [
      "rice vinegar",
      "black vinegar",
      "醋",
      "米醋",
      "香醋",
      "陳醋",
      "浙醋",
    ],
    category: "sauce",
    location: "pantry",
    days: 365,
    staple: true,
  },
  {
    id: "kimchi",
    name: "Kimchi",
    aliases: [
      "泡菜",
      "韓式泡菜",
    ],
    category: "sauce",
    location: "fridge",
    days: 30,
  },
  {
    id: "pickles",
    name: "Pickles",
    aliases: [
      "pickled vegetables",
    ],
    category: "sauce",
    location: "fridge",
    days: 60,
  },
  {
    id: "orange-juice",
    name: "Orange juice",
    aliases: [
      "juice",
      "橙汁",
    ],
    category: "other",
    location: "fridge",
    days: 7,
  },
  {
    id: "tofu-pudding",
    name: "Tofu pudding",
    aliases: [
      "douhua",
      "豆腐花",
      "豆花",
    ],
    category: "dairy",
    location: "fridge",
    days: 3,
  },
  {
    id: "luncheon-meat",
    name: "Luncheon meat",
    aliases: [
      "spam",
      "canned ham",
      "午餐肉",
      "餐肉",
      "Spam",
      "SPAM",
    ],
    category: "protein",
    location: "fridge",
    days: 5,
  },
  {
    id: "canned-tuna",
    name: "Canned tuna",
    aliases: [
      "tuna",
      "罐頭吞拿魚",
      "吞拿魚",
    ],
    category: "protein",
    location: "pantry",
    days: 365,
  },
  {
    id: "beans",
    name: "Beans",
    aliases: [
      "canned beans",
      "black beans",
      "chickpeas",
      "豆",
      "焗豆",
      "豆子",
      "baked beans",
      "罐豆",
    ],
    category: "pantry",
    location: "pantry",
    days: 365,
  },
  {
    id: "coconut-milk",
    name: "Coconut milk",
    aliases: [
      "椰奶",
      "椰漿",
      "椰浆",
    ],
    category: "pantry",
    location: "pantry",
    days: 365,
  },
  {
    id: "peanut-butter",
    name: "Peanut butter",
    aliases: [
      "花生醬",
      "花生酱",
    ],
    category: "sauce",
    location: "pantry",
    days: 180,
  },
  {
    id: "jam",
    name: "Jam",
    aliases: [
      "jelly",
      "果醬",
      "果酱",
    ],
    category: "sauce",
    location: "fridge",
    days: 90,
  },
  {
    id: "honey",
    name: "Honey",
    aliases: [
      "蜜糖",
      "蜂蜜",
    ],
    category: "sauce",
    location: "pantry",
    days: 730,
    staple: true,
  },
  {
    id: "flour",
    name: "Flour",
    aliases: [
      "麵粉",
      "面粉",
      "中筋麵粉",
    ],
    category: "carb",
    location: "pantry",
    days: 180,
    staple: true,
  },
  {
    id: "sugar",
    name: "Sugar",
    aliases: [
      "糖",
      "白糖",
      "冰糖",
      "砂糖",
    ],
    category: "spice",
    location: "pantry",
    days: 730,
    staple: true,
  },
  {
    id: "salt",
    name: "Salt",
    aliases: [
      "sea salt",
      "kosher salt",
      "table salt",
      "海鹽",
      "鹽",
      "盐",
    ],
    category: "spice",
    location: "pantry",
    days: 1825,
    staple: true,
  },
  {
    id: "ground-pork",
    name: "Ground pork",
    aliases: [
      "minced pork",
      "pork mince",
      "免治豬肉",
      "豬絞肉",
      "猪绞肉",
      "免治猪肉",
      "豬肉碎",
      "猪肉碎",
      "絞肉",
    ],
    category: "protein",
    location: "fridge",
    days: 2,
  },
  {
    id: "century-egg",
    name: "Century egg",
    aliases: [
      "preserved egg",
      "pidan",
      "皮蛋",
      "松花蛋",
    ],
    category: "protein",
    location: "fridge",
    days: 30,
  },
  {
    id: "bean-sprouts",
    name: "Bean sprouts",
    aliases: [
      "sprouts",
      "豆芽",
      "芽菜",
      "綠豆芽",
    ],
    category: "veg",
    location: "fridge",
    days: 3,
  },
  {
    id: "rice-vermicelli",
    name: "Rice vermicelli",
    aliases: [
      "rice noodles",
      "bee hoon",
      "米粉",
      "米線",
    ],
    category: "carb",
    location: "pantry",
    days: 365,
  },
  {
    id: "chinese-sausage",
    name: "Chinese sausage",
    aliases: [
      "lap cheong",
      "腊肠",
      "臘腸",
      "風腸",
    ],
    category: "protein",
    location: "fridge",
    days: 30,
  },
  {
    id: "cornstarch",
    name: "Cornstarch",
    aliases: [
      "corn flour",
      "corn starch",
      "potato starch",
      "tapioca starch",
      "生粉",
      "淀粉",
      "澱粉",
      "太白粉",
      "玉米粉",
    ],
    category: "spice",
    location: "pantry",
    days: 730,
    staple: true,
  },
  {
    id: "shaoxing-wine",
    name: "Shaoxing wine",
    aliases: [
      "chinese cooking wine",
      "rice wine",
      "料酒",
      "黃酒",
      "绍兴酒",
      "紹興酒",
      "花雕",
    ],
    category: "sauce",
    location: "pantry",
    days: 730,
    staple: true,
  },
  {
    id: "white-pepper",
    name: "White pepper",
    aliases: [
      "pepper",
      "ground white pepper",
      "black pepper",
      "ground black pepper",
      "fresh black pepper",
      "胡椒",
      "白胡椒",
      "黑胡椒",
      "胡椒粉",
    ],
    category: "spice",
    location: "pantry",
    days: 730,
    staple: true,
  },
  {
    id: "silken-tofu",
    name: "Silken tofu",
    aliases: [
      "soft tofu",
      "嫩豆腐",
      "滑豆腐",
      "軟豆腐",
    ],
    category: "protein",
    location: "fridge",
    days: 5,
  },
  {
    id: "snow-peas",
    name: "Snow peas",
    aliases: [
      "mangetout",
      "荷蘭豆",
      "荷兰豆",
      "甜豆",
    ],
    category: "veg",
    location: "fridge",
    days: 5,
  },
  {
    id: "water-spinach",
    name: "Water spinach",
    aliases: [
      "ong choy",
      "tong cai",
      "通菜",
      "空心菜",
      "蕹菜",
    ],
    category: "veg",
    location: "fridge",
    days: 3,
  },
  {
    id: "green-beans",
    name: "Green beans",
    aliases: [
      "string beans",
      "long beans",
      "四季豆",
      "豆角",
      "敏豆",
    ],
    category: "veg",
    location: "fridge",
    days: 5,
  },
  {
    id: "winter-melon",
    name: "Winter melon",
    aliases: [
      "dong gua",
      "冬瓜",
    ],
    category: "veg",
    location: "fridge",
    days: 7,
  },
  {
    id: "lotus-root",
    name: "Lotus root",
    aliases: [
      "renkon",
      "藕",
      "蓮藕",
      "莲藕",
    ],
    category: "veg",
    location: "fridge",
    days: 5,
  },
  {
    id: "pineapple",
    name: "Pineapple",
    aliases: [
      "菠蘿",
      "凤梨",
      "鳳梨",
      "菠萝",
    ],
    category: "other",
    location: "fridge",
    days: 5,
  },
  {
    id: "condensed-milk",
    name: "Condensed milk",
    aliases: [
      "sweetened condensed milk",
      "煉奶",
      "炼奶",
      "淡奶",
    ],
    category: "dairy",
    location: "pantry",
    days: 180,
  },
  {
    id: "instant-noodles",
    name: "Instant noodles",
    aliases: [
      "ramen pack",
      "公仔麵",
      "方便麵",
      "杯麵",
      "公仔面",
      "公仔即食麵",
      "出前一丁",
      "即食麵",
      "即食面",
      "doll noodles",
    ],
    category: "carb",
    location: "pantry",
    days: 365,
  },
  {
    id: "curry-powder",
    name: "Curry powder",
    aliases: [
      "curry paste",
      "咖哩粉",
      "咖喱粉",
    ],
    category: "spice",
    location: "pantry",
    days: 365,
  },
  {
    id: "fermented-tofu",
    name: "Fermented tofu",
    aliases: [
      "fu yu",
      "腐乳",
      "fermented bean curd",
      "南乳",
    ],
    category: "sauce",
    location: "fridge",
    days: 180,
  },
  {
    id: "fermented-black-beans",
    name: "Fermented black beans",
    aliases: [
      "douchi",
      "豆豉",
      "black bean sauce",
    ],
    category: "sauce",
    location: "pantry",
    days: 365,
  },
  {
    id: "miso",
    name: "Miso",
    aliases: [
      "miso paste",
      "味噌",
      "味噌醬",
    ],
    category: "sauce",
    location: "fridge",
    days: 180,
  },
  {
    id: "nori",
    name: "Nori",
    aliases: [
      "seaweed sheets",
      "紫菜",
      "海苔",
    ],
    category: "pantry",
    location: "pantry",
    days: 365,
  },
  {
    id: "rice-cakes",
    name: "Rice cakes",
    aliases: [
      "tteok",
      "年糕",
      "粿條",
    ],
    category: "carb",
    location: "fridge",
    days: 14,
  },
  {
    id: "udon",
    name: "Udon",
    aliases: [
      "udon noodles",
      "烏冬",
      "乌冬",
      "烏龍麵",
    ],
    category: "carb",
    location: "pantry",
    days: 365,
  },
  {
    id: "pumpkin",
    name: "Pumpkin",
    aliases: [
      "kabocha",
      "南瓜",
    ],
    category: "veg",
    location: "pantry",
    days: 14,
  },
  {
    id: "bitter-melon",
    name: "Bitter melon",
    aliases: [
      "bitter gourd",
      "涼瓜",
      "苦瓜",
    ],
    category: "veg",
    location: "fridge",
    days: 5,
  },
  {
    id: "tofu-skin",
    name: "Tofu skin",
    aliases: [
      "yuba",
      "bean curd sheet",
      "豆腐皮",
      "腐竹",
    ],
    category: "protein",
    location: "fridge",
    days: 7,
  },
  {
    id: "corned-beef",
    name: "Corned beef",
    aliases: [
      "salted beef",
      "鹹牛肉",
      "咸牛肉",
    ],
    category: "protein",
    location: "pantry",
    days: 365,
  },
  {
    id: "spare-ribs",
    name: "Spare ribs",
    aliases: [
      "pork ribs",
      "排骨",
      "豬排骨",
    ],
    category: "protein",
    location: "fridge",
    days: 2,
  },
  {
    id: "chicken-wings",
    name: "Chicken wings",
    aliases: [
      "wings",
      "雞翼",
      "鸡翼",
      "雞翅膀",
    ],
    category: "protein",
    location: "fridge",
    days: 2,
  },
  {
    id: "glass-noodles",
    name: "Glass noodles",
    aliases: [
      "cellophane noodles",
      "mung bean noodles",
      "粉絲",
      "冬粉",
      "粉條",
    ],
    category: "carb",
    location: "pantry",
    days: 365,
  },
  {
    id: "wonton-wrappers",
    name: "Wonton wrappers",
    aliases: [
      "dumpling wrappers",
      "雲吞皮",
      "云吞皮",
      "餛飩皮",
    ],
    category: "carb",
    location: "fridge",
    days: 7,
  },
  {
    id: "thai-basil",
    name: "Thai basil",
    aliases: [
      "holy basil",
      "金不換",
      "羅勒",
      "九層塔",
    ],
    category: "veg",
    location: "fridge",
    days: 4,
  },
  {
    id: "lemongrass",
    name: "Lemongrass",
    aliases: [
      "檸檬草",
      "香茅",
    ],
    category: "veg",
    location: "fridge",
    days: 10,
  },
  {
    id: "doenjang",
    name: "Doenjang",
    aliases: [
      "korean soybean paste",
      "大醬",
      "大酱",
      "된장",
    ],
    category: "sauce",
    location: "fridge",
    days: 180,
  },
  {
    id: "gochujang",
    name: "Gochujang",
    aliases: [
      "korean chili paste",
      "辣椒醬",
      "辣醬",
      "韓式辣椒醬",
    ],
    category: "sauce",
    location: "fridge",
    days: 180,
  },
  {
    id: "sesame-seeds",
    name: "Sesame seeds",
    aliases: [
      "白芝麻",
      "芝麻",
      "炒芝麻",
    ],
    category: "spice",
    location: "pantry",
    days: 365,
    staple: true,
  },
  {
    id: "peanuts",
    name: "Peanuts",
    aliases: [
      "花生",
      "炸花生",
    ],
    category: "spice",
    location: "pantry",
    days: 180,
  },
  {
    id: "dried-mushrooms",
    name: "Dried mushrooms",
    aliases: [
      "shiitake",
      "冬菇",
      "香菇",
      "乾冬菇",
    ],
    category: "pantry",
    location: "pantry",
    days: 365,
  },
  {
    id: "oats",
    name: "Oats",
    aliases: [
      "oatmeal",
      "燕麥",
      "燕麦",
      "即食燕麥",
    ],
    category: "carb",
    location: "pantry",
    days: 365,
  },
  {
    id: "satay-sauce",
    name: "Satay sauce",
    aliases: [
      "沙爹醬",
      "satay",
      "沙茶醬",
    ],
    category: "sauce",
    location: "pantry",
    days: 180,
  },
  {
    id: "beef-brisket",
    name: "Beef brisket",
    aliases: [
      "brisket",
      "牛腩",
    ],
    category: "protein",
    location: "fridge",
    days: 3,
  },
  {
    id: "squid",
    name: "Squid",
    aliases: [
      "calamari",
      "魷魚",
      "鱿鱼",
      "墨魚",
    ],
    category: "protein",
    location: "fridge",
    days: 2,
  },
  {
    id: "clams",
    name: "Clams",
    aliases: [
      "蜆",
      "蛤",
      "蚬",
      "花甲",
    ],
    category: "protein",
    location: "fridge",
    days: 1,
  },
  {
    id: "cooking-oil",
    name: "Cooking oil",
    aliases: [
      "oil",
      "vegetable oil",
      "neutral oil",
      "canola oil",
      "peanut oil",
      "corn oil",
      "食用油",
      "菜油",
      "花生油",
      "玉米油",
      "芥花油",
    ],
    category: "sauce",
    location: "pantry",
    days: 365,
    staple: true,
  },
  {
    id: "cilantro",
    name: "Cilantro",
    aliases: [
      "coriander",
      "fresh cilantro",
      "fresh coriander",
      "香菜",
      "芫荽",
      "coriander leaves",
      "fresh coriander leaves",
    ],
    category: "veg",
    location: "fridge",
    days: 5,
  },
  {
    id: "shallot",
    name: "Shallot",
    aliases: [
      "shallots",
      "red shallot",
      "乾蔥",
      "红葱头",
      "紅蔥頭",
      "干葱",
    ],
    category: "veg",
    location: "pantry",
    days: 21,
  },
  {
    id: "baking-soda",
    name: "Baking soda",
    aliases: [
      "bicarbonate of soda",
      "baking powder",
      "苏打粉",
      "蘇打粉",
      "泡打粉",
      "小蘇打",
    ],
    category: "spice",
    location: "pantry",
    days: 730,
    staple: true,
  },
  {
    id: "five-spice-powder",
    name: "Five-spice powder",
    aliases: [
      "five spice",
      "五香粉",
    ],
    category: "spice",
    location: "pantry",
    days: 730,
    staple: true,
  },
  {
    id: "doubanjiang",
    name: "Doubanjiang",
    aliases: [
      "spicy bean sauce",
      "chili bean sauce",
      "broad bean paste",
      "豆瓣酱",
      "豆瓣醬",
      "郫县豆瓣",
      "郫縣豆瓣",
    ],
    category: "sauce",
    location: "fridge",
    days: 365,
  },
  {
    id: "sichuan-peppercorns",
    name: "Sichuan peppercorns",
    aliases: [
      "sichuan pepper",
      "szechuan peppercorns",
      "花椒",
      "花椒粒",
      "川椒",
    ],
    category: "spice",
    location: "pantry",
    days: 730,
  },
  {
    id: "dried-chili",
    name: "Dried chili",
    aliases: [
      "dried chilies",
      "dried chilli",
      "red chilies",
      "dried red chilies",
      "thai bird chili",
      "bird's eye chili",
      "干辣椒",
      "乾辣椒",
      "辣椒",
      "chili flakes",
      "chilli flakes",
      "dried chilli flakes",
      "red pepper flakes",
      "辣椒碎",
      "辣椒粉",
    ],
    category: "spice",
    location: "pantry",
    days: 730,
  },
  {
    id: "chicken-stock",
    name: "Chicken stock",
    aliases: [
      "chicken broth",
      "chicken bouillon",
      "chicken bouillon powder",
      "stock",
      "broth",
      "鸡汤",
      "雞湯",
      "鸡粉",
      "雞粉",
      "高湯",
      "清雞湯",
    ],
    category: "pantry",
    location: "pantry",
    days: 365,
    staple: true,
  },
  {
    id: "water-chestnuts",
    name: "Water chestnuts",
    aliases: [
      "water chestnut",
      "马蹄",
      "馬蹄",
      "荸薺",
    ],
    category: "veg",
    location: "fridge",
    days: 7,
  },
  {
    id: "pickled-mustard",
    name: "Pickled mustard",
    aliases: [
      "sui mi ya cai",
      "ya cai",
      "preserved mustard",
      "碎米芽菜",
      "芽菜",
      "榨菜",
      "梅菜",
    ],
    category: "sauce",
    location: "fridge",
    days: 180,
  },
  {
    id: "lime",
    name: "Lime",
    aliases: [
      "limes",
      "lime juice",
      "青檸",
      "青柠",
      "萊姆",
      "莱姆",
      "lime wedge",
    ],
    category: "other",
    location: "fridge",
    days: 21,
  },
]

export const SHELF_BY_ID: ReadonlyMap<string, ShelfFood> = new Map(SHELF.map((f) => [f.id, f]))
export const SHELF_BY_NAME: ReadonlyMap<string, ShelfFood> = new Map(SHELF.map((f) => [f.name, f]))
export const SHELF_NAMES: ReadonlySet<string> = new Set(SHELF.map((f) => f.name))

export function isRegistryName(name: string): boolean {
  return SHELF_NAMES.has(name)
}

export function isStapleIngredient(name: string): boolean {
  return SHELF_BY_NAME.get(name)?.staple === true
}

export function requireRegistryName(name: string): string {
  if (!SHELF_NAMES.has(name)) {
    throw new Error(`Ingredient "${name}" is not in the shelf registry`)
  }
  return name
}
