export const ZH_FOOD: Record<string, string> = {
  Milk: "牛奶",
  "UHT Milk (opened)": "開封保久乳",
  Yogurt: "乳酪",
  Butter: "牛油",
  Cheddar: "車打芝士",
  Mozzarella: "莫札瑞拉",
  "Cream cheese": "奶油芝士",
  "Sour cream": "酸忌廉",
  Eggs: "雞蛋",
  Tofu: "豆腐",
  "Chicken breast": "雞胸",
  "Chicken thighs": "雞髀",
  "Ground beef": "免治牛肉",
  "Beef steak": "牛扒",
  "Pork chops": "豬扒",
  Bacon: "煙肉",
  Ham: "火腿",
  Sausages: "香腸",
  Salmon: "三文魚",
  "White fish": "白魚",
  Shrimp: "蝦",
  "Cooked leftovers": "熟食剩餸",
  Lettuce: "生菜",
  Spinach: "菠菜",
  "Pak choi": "白菜仔",
  "Choi sum": "菜心",
  "Gai lan": "芥蘭",
  Broccoli: "西蘭花",
  Cauliflower: "椰菜花",
  Cabbage: "椰菜",
  Carrots: "紅蘿蔔",
  Celery: "西芹",
  Cucumber: "青瓜",
  Tomato: "番茄",
  "Bell pepper": "燈籠椒",
  Onion: "洋蔥",
  "Spring onion": "蔥",
  Garlic: "蒜頭",
  Ginger: "薑",
  Potato: "薯仔",
  "Sweet potato": "番薯",
  Mushroom: "蘑菇",
  Corn: "粟米",
  Eggplant: "茄子",
  Zucchini: "翠玉瓜",
  Apple: "蘋果",
  Banana: "香蕉",
  Orange: "橙",
  Lemon: "檸檬",
  Berries: "莓",
  Grapes: "提子",
  Avocado: "牛油果",
  Mango: "芒果",
  Rice: "米",
  "Cooked rice": "白飯",
  Noodles: "麵",
  Pasta: "意粉",
  Bread: "麵包",
  Tortilla: "墨西哥餅",
  "Soy sauce": "豉油",
  "Oyster sauce": "蠔油",
  "Hoisin sauce": "海鮮醬",
  "Chili oil": "辣椒油",
  Ketchup: "茄汁",
  Mayonnaise: "蛋黃醬",
  Mustard: "芥末",
  "Olive oil": "橄欖油",
  "Sesame oil": "麻油",
  Vinegar: "醋",
  Kimchi: "泡菜",
  Pickles: "酸菜",
  "Orange juice": "橙汁",
  "Tofu pudding": "豆腐花",
  "Luncheon meat": "午餐肉",
  "Canned tuna": "罐頭吞拿魚",
  Beans: "豆",
  "Coconut milk": "椰奶",
  "Peanut butter": "花生醬",
  Jam: "果醬",
  Honey: "蜜糖",
  Flour: "麵粉",
  Sugar: "糖",
  Salt: "鹽",
}

export const ZH_CUISINE: Record<string, string> = {
  All: "全部",
  Cantonese: "粵菜",
  "Hong Kong": "港式",
  Chinese: "中菜",
  Western: "西式",
  Sichuan: "川菜",
  Japanese: "日式",
  Asian: "亞洲",
  Korean: "韓式",
  Breakfast: "早餐",
  Italian: "意式",
}

export const ZH_RECIPE: Record<string, { name: string; steps: string[] }> = {
  "tomato-eggs": {
    name: "番茄炒蛋",
    steps: ["雞蛋加少許鹽打散。", "番茄切角。", "熱油炒蛋至剛熟，盛起。", "炒番茄至出汁，加少許糖和鹽。", "倒回雞蛋，快手拌勻，撒蔥花。"],
  },
  "garlic-choi-sum": {
    name: "蒜蓉菜心",
    steps: ["菜心在鹽水裡焯 45–60 秒。", "瀝乾。", "油爆蒜蓉，加蠔油和少許水。", "將汁淋在菜上。"],
  },
  "pak-choi-oyster": {
    name: "蠔油白菜仔",
    steps: ["白菜仔對半切開，洗淨。", "爆香蒜頭，下白菜仔和少許水，加蓋煮約 2 分鐘。", "加蠔油調味。"],
  },
  "steamed-fish": {
    name: "薑蔥蒸魚",
    steps: ["魚放碟上，鋪薑絲。", "蒸 8–12 分鐘，視乎厚度。", "放上蔥絲。燒熱油和豉油，淋上。"],
  },
  "soy-chicken": {
    name: "簡易豉油雞",
    steps: ["雞件煎至上色。", "加豉油、薑、少許糖，水浸到一半。", "加蓋煮 20–25 分鐘，至熟透並收汁。"],
  },
  "egg-fried-rice": {
    name: "蛋炒飯",
    steps: ["先炒蛋，盛起。", "冷飯下鍋炒散。", "加入其他配料和豉油，再拌回雞蛋和蔥花。"],
  },
  congee: {
    name: "白粥",
    steps: ["米洗淨，加大量水煮 40–50 分鐘，間中攪動。", "最後 10 分鐘加薑片和肉或魚。", "調味，撒蔥花。"],
  },
  "mapo-tofu": {
    name: "平日麻婆豆腐",
    steps: ["豆腐切粒，鹽水略焯。", "爆香蒜薑，有免治牛肉就一起炒香。", "加辣椒油、豉油和少許水，煮豆腐約 3 分鐘。", "略收汁，撒蔥花。"],
  },
  "stirfry-beef-onion": {
    name: "洋蔥炒牛肉",
    steps: ["牛肉逆紋切片，加少許豉油拌勻。", "大火快炒牛肉，盛起。", "洋蔥炒至邊緣焦黃，倒回牛肉，加豉油。"],
  },
  "garlic-broccoli": {
    name: "蒜蓉西蘭花",
    steps: ["西蘭花切小朵，焯水約 1 分鐘。", "爆香蒜頭，下西蘭花，加蠔油或豉油。"],
  },
  "tomato-pasta": {
    name: "番茄意粉",
    steps: ["意粉在鹽水裡煮熟。", "爆香蒜（和洋蔥），下番茄碎，煮約 8 分鐘。", "拌意粉，可加少許芝士。"],
  },
  omelette: {
    name: "清冰箱奄列",
    steps: ["雞蛋加鹽打散。", "先炒剩菜或火腿。", "倒入蛋液，加芝士，剛凝固就對折。"],
  },
  "chicken-rice-bowl": {
    name: "薑汁雞肉飯",
    steps: ["雞胸切片，用豉油和薑醃一醃。", "煎至熟透。", "配白飯、青瓜和蔥。"],
  },
  "salmon-soy": {
    name: "豉油香煎三文魚",
    steps: ["三文魚抹乾，皮向下煎約 4 分鐘。", "翻面，加豉油和薑，再煮約 3 分鐘。", "配白飯。"],
  },
  "shrimp-eggs": {
    name: "滑蛋蝦仁",
    steps: ["蝦抹乾，調味。", "蛋炒至嫩滑，盛起。", "蝦快炒，再拌回雞蛋和蔥。"],
  },
  "miso-ish-soup": {
    name: "豆腐薑湯",
    steps: ["薑片加水煮約 5 分鐘。", "下豆腐和蘑菇，再煮約 4 分鐘。", "加豉油，再放菜和蔥。"],
  },
  "veggie-stirfry": {
    name: "雜菜炒",
    steps: ["蔬菜切成差不多大小。", "先炒較硬的，再下葉菜。", "用豉油或蠔油調味。"],
  },
  "banana-yogurt": {
    name: "香蕉乳酪碗",
    steps: ["香蕉切片，放在乳酪上。", "有莓、蜜糖或花生醬就加上。"],
  },
  "grilled-cheese": {
    name: "芝士多士",
    steps: ["麵包塗牛油，夾芝士（和番茄）。", "煎至兩面金黃、芝士融化。"],
  },
  "tuna-pasta": {
    name: "吞拿魚意粉",
    steps: ["煮意粉。", "爆香洋蔥和蒜，下瀝乾吞拿魚和檸檬。", "拌勻意粉。"],
  },
  "potato-egg": {
    name: "脆薯仔配蛋",
    steps: ["薯仔切粒，煎至脆。", "推到一旁，炒蛋或煎蛋。", "拌勻，調味。"],
  },
  "kimchi-fried-rice": {
    name: "泡菜炒飯",
    steps: ["泡菜切碎炒香。", "下飯，加少許泡菜汁。", "上面放一隻煎蛋。"],
  },
  "spam-eggs-rice": {
    name: "午餐肉煎蛋飯",
    steps: ["午餐肉煎至兩面上色。", "煎一隻蛋，配熱飯和豉油。"],
  },
  "avocado-toast": {
    name: "牛油果多士",
    steps: ["多士烤香。牛油果加鹽和檸檬壓成茸。", "有蛋就煎一隻放上面。"],
  },
  "mushroom-garlic": {
    name: "蒜香蘑菇",
    steps: ["蘑菇用大火煎，不要太擠。", "加蒜和牛油或油，快炒約 1 分鐘。"],
  },
  "cabbage-stirfry": {
    name: "清炒椰菜",
    steps: ["椰菜切片。", "爆香蒜，大火下椰菜。", "加豉油和少許醋。"],
  },
  "carrot-ginger-soup": {
    name: "紅蘿蔔薑湯",
    steps: ["炒香洋蔥，下紅蘿蔔和薑。", "加水，煮約 20 分鐘。", "打茸，太稠可加牛奶。"],
  },
  "lettuce-wrap-idea": {
    name: "生菜雞肉包",
    steps: ["雞胸切碎，加蒜炒熟。", "加豉油，舀進生菜葉。"],
  },
}
